# -*- coding: utf-8 -*-
"""10 quiz thématiques — chacun avec question, 4 réponses, index correct, explication."""

QUIZZES = [
    {
        "id": "fondamentaux-histoire", "icon": "📜", "color": "gris",
        "title": "Fondamentaux & Histoire",
        "desc": "Des origines philosophiques aux grandes écoles de pensée.",
        "difficulty": "Facile",
        "questions": [
            {"q": "Qui a fondé le premier laboratoire de psychologie expérimentale en 1879 ?",
             "a": ["Sigmund Freud", "Wilhelm Wundt", "William James", "Ivan Pavlov"], "correct": 1,
             "explain": "Wilhelm Wundt fonde à Leipzig en 1879 le premier laboratoire consacré à l'étude expérimentale de l'esprit."},
            {"q": "Quel courant affirme que seul le comportement observable doit être étudié scientifiquement ?",
             "a": ["Le structuralisme", "La psychanalyse", "Le behaviorisme", "L'humanisme"], "correct": 2,
             "explain": "Le behaviorisme (Watson, Skinner) rejette l'introspection au profit de l'étude du comportement observable."},
            {"q": "Quel livre de Freud, publié en 1900, fonde la psychanalyse ?",
             "a": ["Totem et Tabou", "L'interprétation des rêves", "Le Moi et le Ça", "Cinq leçons sur la psychanalyse"], "correct": 1,
             "explain": "L'interprétation des rêves (1900) est le texte fondateur de la psychanalyse freudienne."},
            {"q": "Qui a inventé le premier test d'intelligence utilisable, en 1905 ?",
             "a": ["Jean Piaget", "Alfred Binet", "Howard Gardner", "Théodule Ribot"], "correct": 1,
             "explain": "Alfred Binet, avec Théodore Simon, crée en 1905 la première échelle métrique de l'intelligence."},
            {"q": "Qu'est-ce que la « révolution cognitive » des années 1950-60 ?",
             "a": ["Le retour à l'étude des processus mentaux via le modèle du traitement de l'information",
                   "L'invention de l'IRM cérébrale", "La fin de la psychanalyse", "La création du DSM"], "correct": 0,
             "explain": "Portée par l'essor de l'informatique, elle réintroduit l'étude des processus mentaux internes avec une nouvelle rigueur scientifique."},
            {"q": "D'où vient le mot « psychologie » ?", "a": ["Du latin", "Du grec ancien (âme + étude)", "De l'arabe", "De l'allemand"], "correct": 1,
             "explain": "Du grec psukhê (âme, esprit) et logos (étude, discours)."},
            {"q": "Quelle école pense que l'humain a un potentiel inné de croissance et d'épanouissement ?",
             "a": ["Le behaviorisme", "Le structuralisme", "L'humanisme", "Le fonctionnalisme"], "correct": 2,
             "explain": "L'humanisme (Rogers, Maslow) met l'accent sur le potentiel de croissance et l'épanouissement personnel."},
            {"q": "Théodule Ribot a étudié les maladies de...", "a": ["la peau", "la mémoire et de la volonté", "les os", "la vision"], "correct": 1,
             "explain": "Ribot a analysé les maladies de la mémoire, de la volonté et de la personnalité pour éclairer leur fonctionnement normal."},
        ],
    },
    {
        "id": "cognitive", "icon": "💭", "color": "vert",
        "title": "Psychologie Cognitive",
        "desc": "Perception, mémoire, attention et biais de raisonnement.",
        "difficulty": "Moyen",
        "questions": [
            {"q": "Selon la loi de Miller, combien d'éléments la mémoire à court terme retient-elle en moyenne ?",
             "a": ["3 ± 1", "7 ± 2", "12 ± 3", "20 ± 5"], "correct": 1, "explain": "Miller (1956) a estimé cette capacité à 7 ± 2 éléments."},
            {"q": "Que démontre l'expérience du « gorille invisible » ?",
             "a": ["Que la mémoire est infinie", "Que l'attention sélective peut nous rendre aveugles à un événement inattendu",
                   "Que les gorilles sont intelligents", "Que la perception est toujours fidèle"], "correct": 1,
             "explain": "Concentrés sur une tâche, de nombreux observateurs ne remarquent pas un événement pourtant très visible."},
            {"q": "Qu'a démontré Elizabeth Loftus sur la mémoire des témoins ?",
             "a": ["Qu'elle est parfaitement fiable", "Qu'elle peut être altérée par des informations reçues après les faits",
                   "Qu'elle s'améliore avec le stress", "Qu'elle ne concerne que les enfants"], "correct": 1,
             "explain": "La mémoire est reconstructive et suggestible : une information reçue après l'événement peut la modifier."},
            {"q": "Qu'est-ce que l'heuristique de disponibilité ?",
             "a": ["Juger la fréquence d'un événement selon la facilité à s'en souvenir", "Toujours choisir l'option la moins chère",
                   "Une technique de mémorisation", "Un trouble de l'attention"], "correct": 0,
             "explain": "On surestime la fréquence des événements dont des exemples nous viennent facilement à l'esprit (ex. peur de l'avion)."},
            {"q": "Le biais de confirmation consiste à...", "a": ["chercher activement des informations qui contredisent ses croyances",
             "privilégier les informations qui confirment ce que l'on croit déjà", "ne jamais se tromper", "oublier rapidement"], "correct": 1,
             "explain": "On a tendance à privilégier, mémoriser et rechercher les informations qui confirment nos croyances préexistantes."},
            {"q": "Quel système de mémoire retient l'information moins d'une seconde ?", "a": ["La mémoire sensorielle", "La mémoire à long terme",
             "La mémoire de travail", "La mémoire procédurale"], "correct": 0, "explain": "La mémoire sensorielle retient une trace brute très brève (moins d'une seconde) avant tri de l'attention."},
            {"q": "L'effet d'ancrage désigne...", "a": ["l'oubli progressif d'un souvenir", "l'influence disproportionnée de la première information reçue sur le jugement final",
             "la peur de perdre ses souvenirs", "un trouble de la perception visuelle"], "correct": 1,
             "explain": "La première donnée reçue (même arbitraire) influence fortement les estimations et jugements qui suivent."},
        ],
    },
    {
        "id": "sociale", "icon": "👥", "color": "or",
        "title": "Psychologie Sociale",
        "desc": "Conformité, obéissance, foules et influence de groupe.",
        "difficulty": "Moyen",
        "questions": [
            {"q": "Dans l'expérience de Milgram, quel pourcentage de participants a obéi jusqu'au bout ?",
             "a": ["5 %", "35 %", "65 %", "95 %"], "correct": 2, "explain": "65 % des participants ont administré ce qu'ils croyaient être des chocs potentiellement mortels."},
            {"q": "Que teste l'expérience d'Asch sur la conformité ?",
             "a": ["La mémoire des lignes", "Si les gens se conforment à une réponse fausse donnée par un groupe",
                   "La vitesse de réaction", "L'intelligence spatiale"], "correct": 1,
             "explain": "Asch montre que la pression du groupe peut faire donner une réponse fausse que l'on sait pourtant erronée."},
            {"q": "Qu'est-ce que la diffusion de responsabilité ?",
             "a": ["Plus il y a de témoins, plus chacun intervient", "Plus il y a de témoins, moins chacun se sent responsable d'agir",
                   "La responsabilité juridique d'un groupe", "Une théorie de la mémoire"], "correct": 1,
             "explain": "Découverte après le meurtre de Kitty Genovese : la présence de nombreux témoins réduit le sentiment de responsabilité individuelle."},
            {"q": "Selon Gustave Le Bon, que se passe-t-il dans une foule ?",
             "a": ["L'individu garde tout son sens critique", "L'individu perd son sens critique au profit d'une « âme collective » émotionnelle",
                   "Rien ne change psychologiquement", "La foule devient plus rationnelle"], "correct": 1,
             "explain": "Le Bon (1895) postule que la foule induit une perte de responsabilité individuelle et une contagion émotionnelle — thèse à nuancer scientifiquement."},
            {"q": "Selon Durkheim, le suicide anomique est lié à...", "a": ["un excès d'intégration sociale", "une dérégulation sociale brutale (crise économique, changement rapide)",
             "un manque total de conscience", "la génétique uniquement"], "correct": 1,
             "explain": "Le suicide anomique survient quand les normes sociales régulatrices s'effondrent brutalement (ex. crise économique)."},
            {"q": "Quelle est la différence entre préjugé et discrimination ?",
             "a": ["Aucune, ce sont des synonymes", "Le préjugé est une attitude, la discrimination est un comportement",
                   "Le préjugé est un comportement, la discrimination une attitude", "Le préjugé concerne les animaux uniquement"], "correct": 1,
             "explain": "Le préjugé est une attitude négative (émotionnelle) ; la discrimination est l'action défavorable qui peut en découler."},
        ],
    },
    {
        "id": "developpement-personnalite", "icon": "🌱", "color": "vert",
        "title": "Développement & Personnalité",
        "desc": "De l'enfance à l'âge adulte : attachement, stades et traits.",
        "difficulty": "Moyen",
        "questions": [
            {"q": "Quel est le stade de Piaget concernant les enfants de 0 à 2 ans ?",
             "a": ["Opératoire formel", "Sensorimoteur", "Préopératoire", "Opératoire concret"], "correct": 1,
             "explain": "Le stade sensorimoteur (0-2 ans) se caractérise par la découverte du monde via les sens et l'action."},
            {"q": "Quel style d'attachement est le plus fréquent chez l'enfant ?",
             "a": ["Évitant", "Désorganisé", "Sûr", "Anxieux-ambivalent"], "correct": 2,
             "explain": "L'attachement sûr concerne environ 65 % des enfants dans les études d'Ainsworth."},
            {"q": "Quelle crise psychosociale d'Erikson caractérise l'adolescence ?",
             "a": ["Confiance vs méfiance", "Identité vs confusion des rôles", "Intimité vs isolement", "Intégrité vs désespoir"], "correct": 1,
             "explain": "L'adolescence est marquée par la construction de l'identité, face au risque de confusion des rôles."},
            {"q": "Que signifie l'acronyme OCEAN (Big Five) ?",
             "a": ["Ouverture, Conscienciosité, Extraversion, Agréabilité, Névrosisme", "Optimisme, Calme, Énergie, Ambition, Neutralité",
                   "Observation, Cognition, Émotion, Attention, Notion", "Aucune de ces réponses"], "correct": 0,
             "explain": "Le modèle des Big Five décrit la personnalité selon ces 5 grands traits."},
            {"q": "Qu'est-ce que la zone proximale de développement de Vygotsky ?",
             "a": ["La zone du cerveau liée à la mémoire", "L'écart entre ce qu'un enfant sait faire seul et avec l'aide d'autrui",
                   "Une région géographique", "Un stade de Piaget"], "correct": 1,
             "explain": "Elle désigne ce qu'un enfant peut réaliser avec l'aide d'un adulte ou d'un pair plus avancé, au-delà de ses capacités seules."},
            {"q": "À quel âge la théorie de l'esprit apparaît-elle généralement chez l'enfant ?",
             "a": ["Dès la naissance", "Vers 4 ans", "Vers 12 ans", "À l'âge adulte seulement"], "correct": 1,
             "explain": "Le test des fausses croyances (Sally-Anne) montre que cette capacité émerge généralement vers 4 ans."},
        ],
    },
    {
        "id": "emotions-motivation", "icon": "❤️", "color": "rose",
        "title": "Émotions & Motivation",
        "desc": "Théories de l'émotion, universalité et motivation intrinsèque.",
        "difficulty": "Moyen",
        "questions": [
            {"q": "Que dit la théorie de James-Lange sur l'émotion ?",
             "a": ["L'émotion précède toujours la réaction corporelle", "L'émotion résulte de la perception des changements corporels",
                   "Emotion et réaction corporelle sont indépendantes", "Les émotions sont uniquement culturelles"], "correct": 1,
             "explain": "Selon James-Lange, c'est la perception de nos réactions corporelles qui génère l'émotion ressentie."},
            {"q": "Selon Darwin, les expressions émotionnelles de base sont...",
             "a": ["Purement culturelles", "Innées et universelles", "Absentes chez les animaux", "Apprises après 10 ans"], "correct": 1,
             "explain": "Darwin soutient que ces expressions sont héritées de l'évolution et partagées entre cultures et espèces."},
            {"q": "Quelles sont les 6 émotions de base identifiées par Paul Ekman ?",
             "a": ["Joie, tristesse, colère, peur, dégoût, surprise", "Amour, haine, jalousie, fierté, honte, culpabilité",
                   "Calme, excitation, ennui, curiosité, nostalgie, espoir", "Aucune réponse correcte"], "correct": 0,
             "explain": "Ces 6 émotions sont reconnues dans toutes les cultures étudiées par Ekman."},
            {"q": "Quels sont les 3 besoins de la théorie de l'autodétermination (Deci & Ryan) ?",
             "a": ["Argent, statut, pouvoir", "Autonomie, compétence, relation sociale", "Sécurité, nourriture, sommeil", "Vitesse, force, agilité"], "correct": 1,
             "explain": "Ces 3 besoins psychologiques fondamentaux nourrissent la motivation intrinsèque."},
            {"q": "Quelle stratégie de régulation émotionnelle est associée à un meilleur bien-être à long terme ?",
             "a": ["La suppression émotionnelle", "Le recadrage cognitif", "L'évitement total", "Le déni"], "correct": 1,
             "explain": "Réinterpréter la situation (recadrage cognitif) est plus efficace et moins coûteux cognitivement que la suppression."},
        ],
    },
    {
        "id": "neurosciences", "icon": "🧠", "color": "vert",
        "title": "Neurosciences",
        "desc": "Cerveau, neurotransmetteurs et plasticité cérébrale.",
        "difficulty": "Difficile",
        "questions": [
            {"q": "Quel lobe cérébral gère principalement la planification et le contrôle des impulsions ?",
             "a": ["Le lobe occipital", "Le lobe temporal", "Le lobe frontal", "Le lobe pariétal"], "correct": 2,
             "explain": "Le lobe frontal est associé à la planification, la décision et le contrôle des impulsions."},
            {"q": "Quel neurotransmetteur est principalement lié à la motivation et à la récompense ?",
             "a": ["Le GABA", "La dopamine", "L'acétylcholine", "L'histamine"], "correct": 1,
             "explain": "La dopamine est au cœur des circuits de motivation et de récompense (et de l'addiction)."},
            {"q": "Quelle structure cérébrale est essentielle à la formation des souvenirs ?",
             "a": ["Le cervelet", "L'hippocampe", "Le thalamus", "Le bulbe olfactif"], "correct": 1,
             "explain": "L'hippocampe joue un rôle central dans la consolidation des souvenirs à long terme."},
            {"q": "Qu'est-ce que la neuroplasticité ?",
             "a": ["La rigidité du cerveau après 25 ans", "La capacité du cerveau à créer de nouvelles connexions tout au long de la vie",
                   "Une maladie neurologique", "La taille du cerveau"], "correct": 1,
             "explain": "Le cerveau reste capable de se réorganiser en fonction de l'expérience, à tout âge."},
            {"q": "Quelle technique de neuroimagerie offre la meilleure résolution temporelle ?",
             "a": ["L'IRMf", "Le TEP (scanner)", "L'EEG", "L'échographie"], "correct": 2,
             "explain": "L'EEG mesure l'activité électrique en temps quasi réel, avec une excellente résolution temporelle (mais spatiale limitée)."},
            {"q": "Charcot a fondé la neurologie clinique moderne principalement à...",
             "a": ["l'université de Leipzig", "la Salpêtrière (Paris)", "Vienne", "Londres"], "correct": 1,
             "explain": "Charcot a observé méthodiquement ses patients à l'hôpital de la Salpêtrière, à Paris."},
        ],
    },
    {
        "id": "psychopathologie", "icon": "🩺", "color": "rose",
        "title": "Psychopathologie",
        "desc": "Troubles mentaux, histoire clinique et regard non stigmatisant.",
        "difficulty": "Difficile",
        "questions": [
            {"q": "Qu'énonce la loi de régression de Ribot ?",
             "a": ["Les souvenirs récents disparaissent après les anciens", "Les souvenirs récents et complexes disparaissent avant les anciens et automatiques",
                   "Tous les souvenirs disparaissent en même temps", "La mémoire ne se dégrade jamais"], "correct": 1,
             "explain": "Dans l'amnésie, les acquisitions les plus récentes sont les plus fragiles ; les habitudes anciennes résistent le plus longtemps."},
            {"q": "Qu'est-ce que l'automatisme psychologique selon Pierre Janet ?",
             "a": ["Un réflexe musculaire", "Des comportements/pensées échappant au contrôle conscient, fonctionnant de façon dissociée",
                   "Une forme d'intelligence artificielle", "Une technique de méditation"], "correct": 1,
             "explain": "Janet décrit des processus psychiques qui se déroulent hors du contrôle volontaire — précurseur des troubles dissociatifs."},
            {"q": "Quelle est la triade cognitive de Beck dans la dépression ?",
             "a": ["Vision négative de soi, du monde, de l'avenir", "Colère, tristesse, peur", "Passé, présent, futur", "Corps, esprit, âme"], "correct": 0,
             "explain": "Beck identifie ces trois cibles de pensées négatives caractéristiques de la dépression."},
            {"q": "Le modèle bio-psycho-social explique les troubles mentaux par...",
             "a": ["La génétique uniquement", "L'interaction de facteurs biologiques, psychologiques et sociaux", "Le hasard", "La faiblesse de caractère"], "correct": 1,
             "explain": "Ce modèle intégratif est aujourd'hui la référence pour comprendre l'origine multifactorielle des troubles mentaux."},
            {"q": "Quelle proportion de la population mondiale vit avec un trouble mental, selon l'OMS ?",
             "a": ["1 sur 50", "1 sur 8", "1 sur 2", "1 sur 1000"], "correct": 1, "explain": "Environ 1 personne sur 8 dans le monde vit avec un trouble mental, la dépression et l'anxiété étant les plus fréquents."},
            {"q": "Que signifie TOC ?", "a": ["Trouble obsessionnel-compulsif", "Trouble oppositionnel chronique", "Test d'observation cognitive", "Trouble de l'organisation cérébrale"], "correct": 0,
             "explain": "Le TOC associe pensées intrusives (obsessions) et rituels répétitifs (compulsions)."},
        ],
    },
    {
        "id": "therapies", "icon": "🛋️", "color": "or",
        "title": "Thérapies & Interventions",
        "desc": "Psychanalyse, TCC, approche humaniste et thérapies récentes.",
        "difficulty": "Moyen",
        "questions": [
            {"q": "Que signifie le modèle ABC en thérapie cognitivo-comportementale ?",
             "a": ["Attitude, Bonheur, Croyance", "Activating event, Belief, Consequence", "Analyse, Bilan, Correction", "Aucune réponse correcte"], "correct": 1,
             "explain": "Événement déclencheur, croyance/pensée automatique, puis conséquence émotionnelle et comportementale."},
            {"q": "Quelles sont les 3 attitudes clés du thérapeute selon Carl Rogers ?",
             "a": ["Autorité, distance, neutralité", "Empathie, congruence, regard positif inconditionnel", "Silence, jugement, conseil", "Fermeté, rigueur, discipline"], "correct": 1,
             "explain": "Ces 3 attitudes définissent la thérapie centrée sur la personne de Rogers."},
            {"q": "L'EMDR est une thérapie particulièrement recommandée pour...",
             "a": ["Le rhume", "Le trouble de stress post-traumatique", "La myopie", "Le diabète"], "correct": 1,
             "explain": "L'EMDR (mouvements oculaires) aide à retraiter les souvenirs traumatiques du PTSD."},
            {"q": "La thérapie systémique considère comme unité de soin...",
             "a": ["Uniquement l'individu", "La famille comme un système", "Le quartier", "L'entreprise"], "correct": 1,
             "explain": "Elle analyse les comportements comme ayant une fonction dans l'équilibre familial global."},
            {"q": "Quel est le principe central de l'ACT (thérapie d'acceptation et d'engagement) ?",
             "a": ["Supprimer toute émotion négative", "Accepter les pensées/émotions difficiles et se recentrer sur ses valeurs",
                   "Éviter systématiquement les situations difficiles", "Analyser les rêves"], "correct": 1,
             "explain": "L'ACT invite à accepter l'expérience intérieure difficile plutôt qu'à lutter contre elle, en agissant selon ses valeurs."},
        ],
    },
    {
        "id": "vie-quotidienne", "icon": "🌤️", "color": "or",
        "title": "Bien-être, Travail & Éducation",
        "desc": "Psychologie positive, motivation professionnelle et apprentissage.",
        "difficulty": "Facile",
        "questions": [
            {"q": "Que signifie l'acronyme PERMA du modèle de bien-être de Seligman ?",
             "a": ["Positive emotions, Engagement, Relationships, Meaning, Accomplishment", "Paix, Énergie, Repos, Motivation, Ambition",
                   "Peur, Espoir, Rage, Malaise, Anxiété", "Aucune réponse correcte"], "correct": 0,
             "explain": "Ce sont les 5 piliers du bien-être durable selon la psychologie positive."},
            {"q": "Quelles conditions sont nécessaires pour atteindre l'état de flow ?",
             "a": ["Une tâche très facile", "Un équilibre entre défi et compétence, avec objectifs clairs et feedback",
                   "L'absence totale d'objectif", "Un environnement bruyant"], "correct": 1,
             "explain": "Csikszentmihalyi montre que le flow émerge quand le défi correspond exactement au niveau de compétence."},
            {"q": "Que distingue la théorie des deux facteurs de Herzberg au travail ?",
             "a": ["Les facteurs d'hygiène (insatisfaction) et les facteurs de motivation réels", "Le salaire et les vacances uniquement",
                   "Les employés et les managers", "Le matin et le soir"], "correct": 0,
             "explain": "L'absence de facteurs d'hygiène démotive, mais leur présence ne motive pas vraiment — seuls les facteurs de motivation (reconnaissance, accomplissement) engagent durablement."},
            {"q": "Qu'est-ce que le testing effect en pédagogie ?",
             "a": ["Se tester activement mémorise mieux que relire passivement", "Les tests sont inutiles", "Il faut éviter de se tromper à tout prix",
                   "Relire 10 fois est la meilleure méthode"], "correct": 0,
             "explain": "Le rappel actif (se tester) renforce durablement la mémorisation, plus efficacement que la relecture passive."},
            {"q": "Quelles sont les 3 dimensions du burn-out selon Maslach ?",
             "a": ["Fatigue, faim, soif", "Épuisement émotionnel, dépersonnalisation, perte d'accomplissement", "Colère, tristesse, peur", "Argent, temps, énergie"], "correct": 1,
             "explain": "Ces 3 dimensions caractérisent l'épuisement professionnel."},
        ],
    },
    {
        "id": "legale-comparee", "icon": "⚖️", "color": "gris",
        "title": "Psychologie Légale & Comparée",
        "desc": "Criminologie, témoignage judiciaire et cognition animale.",
        "difficulty": "Moyen",
        "questions": [
            {"q": "La théorie du « criminel-né » de Lombroso est aujourd'hui...",
             "a": ["Validée scientifiquement", "Totalement réfutée et considérée comme dangereuse", "Utilisée dans tous les tribunaux", "Ignorée par manque d'intérêt historique"], "correct": 1,
             "explain": "Cette théorie basée sur des traits physiques est aujourd'hui rejetée par la science et a nourri des dérives eugénistes."},
            {"q": "Le témoignage oculaire est-il toujours fiable devant un tribunal ?",
             "a": ["Oui, à 100 %", "Non, il est influençable par le stress, la présence d'une arme, le délai...", "Seulement pour les enfants", "Seulement la nuit"], "correct": 1,
             "explain": "La recherche montre que la mémoire des témoins est reconstructive et peut être altérée par de nombreux facteurs."},
            {"q": "Le profilage criminel est-il une science exacte ?",
             "a": ["Oui, infaillible", "Non, les profileurs ne sont pas plus précis que des policiers expérimentés sans formation spécifique", "Oui, mais seulement aux USA", "Il n'existe pas"], "correct": 1,
             "explain": "Les études contrôlées montrent que le profilage reste un outil d'aide à l'enquête, pas une preuve scientifique fiable."},
            {"q": "Qu'est-ce que l'empreinte (imprinting) découverte par Konrad Lorenz ?",
             "a": ["Une trace génétique", "L'attachement immédiat d'un oisillon à la première figure mobile perçue", "Une technique de dressage", "Un réflexe digestif"], "correct": 1,
             "explain": "Ce phénomène a fortement influencé les théories de l'attachement humain (Bowlby)."},
            {"q": "Quel animal a démontré une fabrication d'outils en plusieurs étapes ?",
             "a": ["Le chat domestique", "Le corbeau calédonien", "Le poisson rouge", "L'escargot"], "correct": 1,
             "explain": "Les corbeaux calédoniens résolvent des problèmes complexes en fabriquant des outils à plusieurs étapes."},
        ],
    },
]
