# -*- coding: utf-8 -*-
"""Dictionnaire biographique des grandes figures de la psychologie."""

# (id, nom, dates, pays, courant, apport, bio, citation, oeuvres)
AUTEURS = [
    ("wundt", "Wilhelm Wundt", "1832-1920", "Allemagne", "Structuralisme / psychologie expérimentale",
     "Fonde en 1879 à Leipzig le premier laboratoire de psychologie expérimentale.",
     "Médecin et physiologiste, Wundt veut faire de la psychologie une science de laboratoire, distincte de la philosophie. Il mesure les temps de réaction, étudie la sensation et l'attention par introspection contrôlée. Son laboratoire forme des centaines d'étudiants venus du monde entier, qui essaimeront ensuite aux États-Unis, en Russie et en France. Il distingue la psychologie expérimentale, réservée aux processus élémentaires, de la Völkerpsychologie (psychologie des peuples), consacrée au langage, aux mythes et aux coutumes.",
     "« La psychologie doit étudier l'expérience immédiate. »",
     "Principes de psychologie physiologique (1874)"),

    ("james", "William James", "1842-1910", "États-Unis", "Fonctionnalisme / pragmatisme",
     "Auteur du premier grand traité de psychologie américain et théoricien de la conscience comme flux.",
     "Formé à la médecine, James refuse de réduire l'esprit à des éléments statiques : la conscience est un courant continu (stream of consciousness) qui sert l'adaptation de l'organisme. Il propose avec Carl Lange une théorie contre-intuitive de l'émotion (nous avons peur parce que nous fuyons), développe la notion de self, d'habitude et de volonté, et fonde le pragmatisme en philosophie. Son style littéraire a fait de ses Principles un classique lu bien au-delà de la discipline.",
     "« Le plus grand découverte de ma génération est qu'un être humain peut changer sa vie en changeant son état d'esprit. »",
     "Principes de psychologie (1890), Les Formes multiples de l'expérience religieuse (1902)"),

    ("freud", "Sigmund Freud", "1856-1939", "Autriche", "Psychanalyse",
     "Invente la psychanalyse : inconscient, refoulement, transfert, interprétation des rêves.",
     "Neurologue viennois, Freud part de l'hystérie et de l'hypnose (avec Charcot puis Breuer) pour élaborer une méthode fondée sur l'association libre. Il propose une architecture de l'appareil psychique (conscient/préconscient/inconscient, puis ça/moi/surmoi), une théorie du développement psychosexuel et une théorie des mécanismes de défense. Contesté scientifiquement, son influence sur la clinique, la culture, la littérature et le langage courant reste immense.",
     "« Le rêve est la voie royale qui mène à l'inconscient. »",
     "L'Interprétation des rêves (1900), Trois essais sur la théorie sexuelle (1905), Le Moi et le Ça (1923)"),

    ("jung", "Carl Gustav Jung", "1875-1961", "Suisse", "Psychologie analytique",
     "Introduit l'inconscient collectif, les archétypes et les types psychologiques.",
     "D'abord disciple et « dauphin » désigné de Freud, Jung rompt avec lui en 1913 sur la question de la libido et de la religion. Il postule un inconscient collectif peuplé d'archétypes (l'ombre, l'anima, le vieux sage), développe le processus d'individuation et distingue introversion et extraversion — distinction reprise ensuite par toute la psychologie de la personnalité. Ses travaux sur les symboles, l'alchimie et la synchronicité l'éloignent de la science expérimentale mais nourrissent l'art et l'anthropologie.",
     "« Celui qui regarde à l'extérieur rêve ; celui qui regarde à l'intérieur s'éveille. »",
     "Métamorphoses de l'âme et ses symboles (1912), Types psychologiques (1921)"),

    ("adler", "Alfred Adler", "1870-1937", "Autriche", "Psychologie individuelle",
     "Théoricien du sentiment d'infériorité et de la compensation.",
     "Membre puis dissident du cercle freudien, Adler place au centre non la sexualité mais la volonté de puissance et le sentiment d'infériorité que chacun cherche à compenser. Il insiste sur le rang dans la fratrie, le style de vie et le « sentiment social » (Gemeinschaftsgefühl) comme critère de santé psychique. Praticien engagé, il crée des centres de guidance éducative à Vienne et influence durablement l'éducation et le coaching.",
     "« Être un être humain, c'est se sentir inférieur. »",
     "Le Tempérament nerveux (1912), Connaissance de l'homme (1927)"),

    ("pavlov", "Ivan Pavlov", "1849-1936", "Russie", "Réflexologie",
     "Découvre le conditionnement classique ; prix Nobel de médecine 1904.",
     "Physiologiste spécialiste de la digestion, Pavlov remarque que ses chiens salivent avant même de recevoir la nourriture. Il consacre le reste de sa carrière à l'étude systématique de ces « réflexes conditionnels », établissant les lois d'acquisition, d'extinction, de généralisation et de discrimination. Son travail fournit un modèle objectif de l'apprentissage, sans recours à l'introspection, et fonde une part importante des thérapies comportementales.",
     "« Les faits sont l'air du savant. »",
     "Les Réflexes conditionnels (1927)"),

    ("watson", "John B. Watson", "1878-1958", "États-Unis", "Behaviorisme",
     "Fondateur du behaviorisme : la psychologie doit étudier le comportement observable.",
     "Dans son manifeste de 1913, Watson exclut la conscience du champ scientifique : seul compte le lien stimulus-réponse, mesurable et reproductible. Il démontre avec le petit Albert qu'une peur peut être conditionnée, et affirme pouvoir façonner n'importe quel enfant en n'importe quel professionnel. Exclu de l'université après un scandale privé, il fait carrière dans la publicité, où il applique ses principes avec succès.",
     "« Donnez-moi une douzaine d'enfants sains… et je garantis d'en faire n'importe quel type de spécialiste. »",
     "La psychologie telle que le behavioriste la voit (1913)"),

    ("skinner", "B. F. Skinner", "1904-1990", "États-Unis", "Behaviorisme radical",
     "Formalise le conditionnement opérant et les programmes de renforcement.",
     "Skinner déplace l'attention du stimulus vers les conséquences : un comportement suivi d'un renforcement se répète. Il invente la « boîte de Skinner », les machines à enseigner, et analyse le langage comme comportement verbal. Son behaviorisme radical ne nie pas l'existence des états internes mais refuse d'en faire des causes. Ses écrits utopiques (Walden Two) et sa critique du concept de liberté ont suscité de vives polémiques.",
     "« L'éducation est ce qui survit quand ce qui a été appris a été oublié. »",
     "Le Comportement des organismes (1938), Par-delà la liberté et la dignité (1971)"),

    ("piaget", "Jean Piaget", "1896-1980", "Suisse", "Constructivisme",
     "Décrit les stades du développement de l'intelligence chez l'enfant.",
     "Biologiste de formation, Piaget étudie comment la connaissance se construit par l'interaction entre l'enfant et son milieu, via les mécanismes d'assimilation et d'accommodation. Il décrit quatre stades (sensori-moteur, préopératoire, opératoire concret, opératoire formel) et invente la méthode clinique d'interrogatoire de l'enfant. Fondateur de l'épistémologie génétique, il a influencé toutes les pédagogies actives du XXe siècle.",
     "« L'intelligence, ce n'est pas ce que l'on sait mais ce que l'on fait quand on ne sait pas. »",
     "La Naissance de l'intelligence chez l'enfant (1936), La Psychologie de l'enfant (1966)"),

    ("vygotski", "Lev Vygotski", "1896-1934", "URSS", "Socio-constructivisme",
     "Théoricien de la zone proximale de développement et du rôle du langage.",
     "Mort à 37 ans de la tuberculose, Vygotski laisse une œuvre qui ne sera diffusée en Occident qu'à partir des années 1960. Il soutient que le développement va du social vers l'individuel : l'enfant intériorise des outils culturels, au premier rang desquels le langage. La « zone proximale de développement » désigne l'écart entre ce que l'enfant fait seul et ce qu'il réussit avec l'aide d'un adulte — ce qui définit la zone où l'enseignement est efficace.",
     "« Ce que l'enfant sait faire aujourd'hui avec l'aide d'autrui, il saura le faire seul demain. »",
     "Pensée et langage (1934)"),

    ("bowlby", "John Bowlby", "1907-1990", "Royaume-Uni", "Théorie de l'attachement",
     "Démontre que le lien affectif précoce est un besoin primaire.",
     "Psychiatre et psychanalyste, Bowlby s'appuie sur l'éthologie pour affirmer que le bébé humain dispose d'un système comportemental d'attachement sélectionné par l'évolution : pleurer, s'agripper, suivre. La séparation prolongée d'avec la figure d'attachement provoque protestation, désespoir puis détachement. Son rapport à l'OMS (1951) a transformé les pratiques des pouponnières et des hôpitaux pédiatriques dans le monde entier.",
     "« Le berceau de la sécurité, c'est une base sûre d'où explorer le monde. »",
     "Attachement et perte, 3 volumes (1969-1980)"),

    ("ainsworth", "Mary Ainsworth", "1913-1999", "Canada/États-Unis", "Théorie de l'attachement",
     "Crée la « situation étrange » et la typologie des styles d'attachement.",
     "Après un travail de terrain en Ouganda puis à Baltimore, Ainsworth met au point un protocole de laboratoire permettant de classer la qualité du lien enfant-parent. Elle décrit l'attachement sûr, évitant et ambivalent (le désorganisé sera ajouté plus tard par Main et Solomon), et montre que la sensibilité du parent aux signaux du bébé prédit la sécurité du lien.",
     "« La sensibilité maternelle est la clé de la sécurité de l'enfant. »",
     "Patterns of Attachment (1978)"),

    ("rogers", "Carl Rogers", "1902-1987", "États-Unis", "Approche humaniste",
     "Fonde la thérapie centrée sur la personne.",
     "Rogers renverse la relation thérapeutique traditionnelle : ce n'est pas l'expert qui interprète, c'est la personne qui trouve ses propres réponses si trois conditions sont réunies — empathie, considération positive inconditionnelle et congruence du thérapeute. Il est le premier à enregistrer et analyser des séances réelles pour évaluer l'efficacité thérapeutique, ouvrant la voie à la recherche en psychothérapie.",
     "« Le curieux paradoxe, c'est que je ne peux changer que le jour où je m'accepte tel que je suis. »",
     "Le Développement de la personne (1961)"),

    ("maslow", "Abraham Maslow", "1908-1970", "États-Unis", "Psychologie humaniste",
     "Propose la hiérarchie des besoins et le concept d'accomplissement de soi.",
     "Lassé d'une psychologie centrée sur la pathologie, Maslow étudie les personnes qu'il juge exceptionnellement accomplies (Einstein, Lincoln) et décrit une progression des besoins, des plus physiologiques aux plus existentiels. Il décrit aussi les « expériences paroxystiques » (peak experiences) et fonde la psychologie transpersonnelle à la fin de sa vie.",
     "« Ce qu'un homme peut être, il doit l'être. »",
     "Motivation et personnalité (1954)"),

    ("beck", "Aaron T. Beck", "1921-2021", "États-Unis", "Thérapie cognitive",
     "Crée la thérapie cognitive de la dépression et ses échelles de mesure.",
     "Psychiatre formé à la psychanalyse, Beck constate que ses patients déprimés produisent spontanément des pensées automatiques négatives portant sur eux-mêmes, le monde et l'avenir (la « triade cognitive »). Il élabore une thérapie brève, structurée et évaluable, dont l'efficacité est mesurée dès les années 1970. L'Inventaire de dépression de Beck reste l'un des instruments les plus utilisés au monde.",
     "« Il n'y a pas de pensée si absurde qu'elle ne mérite d'être examinée. »",
     "Cognitive Therapy of Depression (1979)"),

    ("ellis", "Albert Ellis", "1913-2007", "États-Unis", "Thérapie rationnelle-émotive",
     "Précurseur des TCC avec le modèle ABC des croyances irrationnelles.",
     "Dès 1955, Ellis affirme que ce ne sont pas les événements (A) qui provoquent les conséquences émotionnelles (C) mais les croyances (B) que nous entretenons à leur sujet. Il traque les exigences absolutistes (« je dois absolument réussir ») et les remplace par des préférences réalistes, dans un style de confrontation directe très personnel.",
     "« Les gens ne sont pas perturbés par les choses, mais par l'opinion qu'ils en ont. »",
     "Reason and Emotion in Psychotherapy (1962)"),

    ("kahneman", "Daniel Kahneman", "1934-2024", "Israël/États-Unis", "Économie comportementale",
     "Met au jour les heuristiques et biais du jugement ; Nobel d'économie 2002.",
     "Avec Amos Tversky, Kahneman démontre expérimentalement que nos jugements en situation d'incertitude reposent sur des raccourcis (disponibilité, représentativité, ancrage) qui produisent des erreurs systématiques. Leur théorie des perspectives (prospect theory) montre que les pertes pèsent environ deux fois plus lourd que les gains équivalents. Il popularise la distinction entre système 1 (rapide, intuitif) et système 2 (lent, analytique).",
     "« Rien dans la vie n'a autant d'importance que vous le pensez pendant que vous y pensez. »",
     "Système 1 / Système 2 : les deux vitesses de la pensée (2011)"),

    ("tversky", "Amos Tversky", "1937-1996", "Israël", "Psychologie du jugement",
     "Co-auteur des travaux fondateurs sur les heuristiques et la théorie des perspectives.",
     "Mathématicien de formation, Tversky apporte la rigueur formelle aux intuitions expérimentales du duo qu'il forme avec Kahneman. Il travaille sur la similarité, la mesure du risque et le cadrage des décisions. Mort prématurément, il n'a pu recevoir le Nobel attribué en 2002 à son collaborateur, qui a publiquement souligné que le prix récompensait un travail commun.",
     "« Il est plus facile de prédire ce que les gens feront de mal que ce qu'ils feront de bien. »",
     "Judgment under Uncertainty (1974, avec Kahneman)"),

    ("bandura", "Albert Bandura", "1925-2021", "Canada/États-Unis", "Théorie sociale cognitive",
     "Théoricien de l'apprentissage par observation et du sentiment d'efficacité personnelle.",
     "Bandura montre avec la poupée Bobo qu'un comportement peut s'acquérir sans renforcement direct, par simple observation d'un modèle. Il développe ensuite le concept d'auto-efficacité (self-efficacy) : la croyance en sa capacité à réussir une tâche prédit l'effort, la persévérance et la performance. Son modèle du « déterminisme réciproque » articule personne, comportement et environnement.",
     "« Les gens qui se croient capables d'agir sur les événements affrontent plus volontiers les difficultés. »",
     "L'Apprentissage social (1977), Auto-efficacité (1997)"),

    ("seligman", "Martin Seligman", "1942-", "États-Unis", "Psychologie positive",
     "Passe de l'impuissance apprise à la science du fonctionnement optimal.",
     "Après avoir décrit l'impuissance apprise comme modèle de la dépression, Seligman opère un virage en 1998, année de sa présidence de l'American Psychological Association : il propose d'étudier aussi ce qui rend la vie digne d'être vécue. Il élabore le modèle PERMA (émotions positives, engagement, relations, sens, accomplissement) et la classification des forces de caractère, avec des programmes appliqués à l'école et à l'armée.",
     "« L'optimisme s'apprend, comme n'importe quelle compétence. »",
     "Apprendre l'optimisme (1991), S'épanouir (2011)"),

    ("csikszentmihalyi", "Mihaly Csikszentmihalyi", "1934-2021", "Hongrie/États-Unis", "Psychologie positive",
     "Théoricien de l'état de flow.",
     "En étudiant peintres, alpinistes, chirurgiens et joueurs d'échecs, il isole un état d'absorption totale dans l'activité, où le temps semble disparaître. Le flow apparaît quand le défi rencontre exactement le niveau de compétence, avec des objectifs clairs et un retour immédiat. Ce modèle irrigue aujourd'hui le design de jeux, la pédagogie et le management.",
     "« Les meilleurs moments surviennent quand le corps ou l'esprit est poussé à ses limites dans un effort volontaire. »",
     "Vivre : la psychologie du bonheur (1990)"),

    ("gardner", "Howard Gardner", "1943-", "États-Unis", "Intelligences multiples",
     "Conteste l'intelligence unique et propose huit formes d'intelligence.",
     "Gardner soutient que l'intelligence n'est pas une aptitude générale mais un ensemble de capacités relativement indépendantes : linguistique, logico-mathématique, spatiale, musicale, corporelle-kinesthésique, interpersonnelle, intrapersonnelle et naturaliste. Sa théorie a eu un immense succès pédagogique, malgré des critiques scientifiques sur l'absence de validation psychométrique.",
     "« La question n'est pas : es-tu intelligent ? mais : comment es-tu intelligent ? »",
     "Les Formes de l'intelligence (1983)"),

    ("goleman", "Daniel Goleman", "1946-", "États-Unis", "Intelligence émotionnelle",
     "Popularise l'intelligence émotionnelle auprès du grand public et des entreprises.",
     "Journaliste scientifique et docteur en psychologie, Goleman synthétise en 1995 les travaux de Salovey et Mayer et affirme que la conscience de soi, la gestion des émotions, la motivation, l'empathie et les compétences sociales prédisent la réussite autant, sinon plus, que le QI. Son livre déclenche une vague mondiale de formations en entreprise.",
     "« Dans un sens très réel, nous avons deux esprits : l'un qui pense, l'autre qui ressent. »",
     "L'Intelligence émotionnelle (1995)"),

    ("ekman", "Paul Ekman", "1934-", "États-Unis", "Psychologie des émotions",
     "Établit l'universalité de certaines expressions faciales et code les micro-expressions.",
     "Ekman étudie des populations isolées de Papouasie-Nouvelle-Guinée et retrouve la reconnaissance des mêmes émotions de base (joie, tristesse, colère, peur, dégoût, surprise). Il élabore le FACS (Facial Action Coding System), qui décompose l'expression en 44 unités musculaires, utilisé aujourd'hui en animation et en recherche. Ses applications à la détection du mensonge restent scientifiquement fragiles.",
     "« Le visage est un système de signaux multiples. »",
     "Emotions Revealed (2003)"),

    ("damasio", "Antonio Damasio", "1944-", "Portugal/États-Unis", "Neurosciences affectives",
     "Montre que l'émotion est indispensable à la décision rationnelle.",
     "À partir de patients dont le cortex préfrontal ventromédian est lésé, Damasio observe une intelligence préservée mais des décisions de vie catastrophiques. Il formule l'hypothèse des « marqueurs somatiques » : les états corporels associés à nos expériences passées balisent nos choix. Il réfute ainsi l'opposition classique entre raison et émotion.",
     "« Nous ne sommes pas des machines à penser qui ressentent, mais des machines à ressentir qui pensent. »",
     "L'Erreur de Descartes (1994), Le Sentiment même de soi (1999)"),

    ("sperry", "Roger Sperry", "1913-1994", "États-Unis", "Neuropsychologie",
     "Prix Nobel 1981 pour ses travaux sur la spécialisation hémisphérique.",
     "En étudiant des patients épileptiques dont le corps calleux a été sectionné, Sperry démontre que chaque hémisphère peut traiter l'information de façon autonome, avec des compétences distinctes : langage et analyse à gauche, traitement spatial et global à droite. Ses travaux précisent l'organisation fonctionnelle du cerveau tout en étant souvent caricaturés dans la vulgarisation.",
     "« Chaque hémisphère possède sa propre chaîne de souvenirs et d'apprentissages. »",
     "Travaux sur le cerveau divisé (1960-1970)"),

    ("milgram", "Stanley Milgram", "1933-1984", "États-Unis", "Psychologie sociale",
     "Étudie l'obéissance destructrice et le « petit monde ».",
     "Élève d'Asch, Milgram cherche à comprendre comment des individus ordinaires ont pu participer aux crimes nazis. Ses expériences d'obéissance, menées à Yale, restent parmi les plus discutées de la discipline. Il est aussi l'auteur de l'expérience du « petit monde » qui a popularisé l'idée des six degrés de séparation, et de travaux sur la vie urbaine et la « familiarité de l'inconnu ».",
     "« Ce n'est pas la colère mais le sens du devoir qui conduit à la destruction. »",
     "Soumission à l'autorité (1974)"),

    ("asch", "Solomon Asch", "1907-1996", "Pologne/États-Unis", "Psychologie sociale",
     "Démontre expérimentalement la force du conformisme.",
     "Asch pense d'abord démontrer la résistance de l'individu au groupe ; ses résultats montrent l'inverse et deviennent un classique. Il travaille aussi sur la formation des impressions et montre l'effet de primauté : les premiers traits mentionnés colorent l'interprétation des suivants (« intelligent, travailleur, impulsif » vs l'ordre inverse).",
     "« Le fait que des personnes intelligentes appellent blanc ce qui est noir est un sujet de préoccupation. »",
     "Social Psychology (1952)"),

    ("festinger", "Leon Festinger", "1919-1989", "États-Unis", "Psychologie sociale",
     "Théoricien de la dissonance cognitive et de la comparaison sociale.",
     "Festinger postule que l'incohérence entre nos croyances et nos actes produit une tension désagréable que nous cherchons à réduire — souvent en modifiant la croyance plutôt que l'acte. Il étudie aussi comment nous nous évaluons en nous comparant à autrui, mécanisme devenu central pour comprendre l'effet des réseaux sociaux sur l'estime de soi. Son étude infiltrée d'une secte millénariste (L'Échec d'une prophétie) est un modèle du genre.",
     "« Dites à un homme convaincu qu'il a tort, et il ne fera que s'accrocher davantage. »",
     "A Theory of Cognitive Dissonance (1957)"),

    ("lewin", "Kurt Lewin", "1890-1947", "Allemagne/États-Unis", "Dynamique des groupes",
     "Fondateur de la psychologie sociale expérimentale et de la recherche-action.",
     "Lewin formule que le comportement est fonction de la personne et de son environnement (B = f(P, E)), introduit la notion de « champ psychologique » et étudie les styles de leadership (autoritaire, démocratique, laisser-faire). Il invente la recherche-action, qui associe production de connaissances et transformation du terrain, et le modèle du changement en trois temps : décristallisation, déplacement, recristallisation.",
     "« Rien n'est plus pratique qu'une bonne théorie. »",
     "Field Theory in Social Science (1951)"),

    ("allport", "Gordon Allport", "1897-1967", "États-Unis", "Psychologie de la personnalité",
     "Fonde l'approche des traits et analyse la nature des préjugés.",
     "Allport recense 18 000 mots du dictionnaire décrivant la personnalité et propose une hiérarchie de traits cardinaux, centraux et secondaires. Il défend une psychologie de l'individu concret plutôt que des lois moyennes. Son ouvrage sur la nature du préjugé formule l'hypothèse du contact : le contact intergroupe réduit les préjugés sous quatre conditions (statut égal, but commun, coopération, soutien institutionnel).",
     "« La personnalité est une organisation dynamique. »",
     "The Nature of Prejudice (1954)"),

    ("cattell", "Raymond Cattell", "1905-1998", "Royaume-Uni/États-Unis", "Psychométrie",
     "Distingue intelligence fluide et cristallisée, crée le 16PF.",
     "Pionnier de l'analyse factorielle appliquée à la personnalité, Cattell isole 16 facteurs primaires et construit le questionnaire 16PF. Il distingue l'intelligence fluide (capacité de raisonnement abstrait, qui décline avec l'âge) et l'intelligence cristallisée (connaissances accumulées, qui se maintient ou progresse). Certaines de ses positions eugénistes tardives ont durablement terni sa réputation.",
     "« La personnalité est ce qui permet de prédire ce qu'une personne fera dans une situation donnée. »",
     "The Scientific Analysis of Personality (1965)"),

    ("eysenck", "Hans Eysenck", "1916-1997", "Allemagne/Royaume-Uni", "Psychologie différentielle",
     "Propose un modèle biologique de la personnalité en trois dimensions.",
     "Eysenck ramène la personnalité à trois grandes dimensions (extraversion, névrosisme, psychotisme) qu'il relie à des différences d'activation corticale et de réactivité du système nerveux autonome. Critique virulent de l'efficacité de la psychanalyse, il contribue à l'essor des thérapies comportementales. Une large partie de ses publications tardives a été rétractée pour données non fiables.",
     "« Les théories doivent être testables, sinon elles ne sont pas scientifiques. »",
     "Dimensions of Personality (1947)"),

    ("binet", "Alfred Binet", "1857-1911", "France", "Psychométrie",
     "Crée avec Théodore Simon la première échelle d'intelligence.",
     "Chargé par le ministère français de l'Instruction publique d'identifier les élèves nécessitant un soutien, Binet conçoit en 1905 une série d'épreuves étalonnées par âge. Il insiste sur le caractère modifiable de l'intelligence et sur l'« orthopédie mentale » — un entraînement des fonctions cognitives. Il dirige aussi le laboratoire de psychologie physiologique de la Sorbonne et travaille sur la suggestibilité et le témoignage.",
     "« Quelques philosophes semblent avoir donné leur appui à ce verdict brutal que l'intelligence d'un individu est une quantité fixe. Nous devons protester. »",
     "Les Idées modernes sur les enfants (1909)"),

    ("janet", "Pierre Janet", "1859-1947", "France", "Psychologie clinique",
     "Théoricien de la dissociation et de l'automatisme psychologique.",
     "Contemporain et rival de Freud, Janet décrit l'« automatisme psychologique » et la dissociation des fonctions mentales sous l'effet d'un abaissement du niveau d'énergie psychique. Sa notion d'« idée fixe subconsciente » anticipe une partie des théories du trauma. Redécouvert à partir des années 1980, il est aujourd'hui considéré comme un précurseur majeur de la psychotraumatologie moderne.",
     "« Le traumatisme est une idée fixe qui reste vivante. »",
     "L'Automatisme psychologique (1889), Les Névroses (1909)"),

    ("charcot", "Jean-Martin Charcot", "1825-1893", "France", "Neurologie / hystérie",
     "Maître de la Salpêtrière, il légitime l'étude clinique de l'hystérie.",
     "Charcot fait de l'hôpital de la Salpêtrière un centre mondial de la neurologie. Ses « leçons du mardi », où il présente des patientes hystériques sous hypnose, attirent Freud, Janet, Babinski et Gilles de la Tourette. Il soutient que l'hystérie est une affection neurologique authentique, obéissant à des lois, et non une simulation — thèse décisive pour la reconnaissance des troubles psychiques.",
     "« La théorie c'est bon, mais ça n'empêche pas d'exister. »",
     "Leçons sur les maladies du système nerveux (1872-1887)"),

    ("ribot", "Théodule Ribot", "1839-1916", "France", "Psychologie expérimentale française",
     "Fondateur de la psychologie scientifique en France.",
     "Ribot crée la Revue philosophique, occupe la première chaire de psychologie expérimentale au Collège de France et impose la méthode pathologique : étudier les fonctions normales à travers leurs dysfonctionnements. Sa « loi de régression » stipule que la destruction de la mémoire suit l'ordre inverse de son acquisition — du plus récent au plus ancien, du complexe au simple.",
     "« La mémoire est une fonction générale de l'organisme. »",
     "Les Maladies de la mémoire (1881), La Psychologie des sentiments (1896)"),

    ("wallon", "Henri Wallon", "1879-1962", "France", "Psychologie du développement",
     "Décrit le développement de l'enfant à travers l'émotion et le corps.",
     "Médecin, psychologue et homme politique, Wallon insiste sur le rôle des émotions et de la motricité dans la construction de la personnalité, là où Piaget privilégie la logique. Il décrit le « stade du miroir » avant Lacan et une succession de stades alternant orientation vers soi et vers autrui. Le plan Langevin-Wallon (1947) reste une référence de la pensée éducative française.",
     "« L'enfant ne peut vivre que par les autres. »",
     "Les Origines du caractère chez l'enfant (1934)"),

    ("lacan", "Jacques Lacan", "1901-1981", "France", "Psychanalyse structurale",
     "Propose un « retour à Freud » relu à travers la linguistique.",
     "Lacan articule l'inconscient au langage (« l'inconscient est structuré comme un langage ») et distingue trois registres : le réel, le symbolique et l'imaginaire. Il élabore le stade du miroir comme moment de constitution du moi et introduit l'« objet petit a » comme cause du désir. Sa pratique des séances à durée variable provoque son exclusion de l'association internationale et la fondation de son école.",
     "« Le désir de l'homme est le désir de l'Autre. »",
     "Écrits (1966), Séminaires (1953-1979)"),

    ("dolto", "Françoise Dolto", "1908-1988", "France", "Psychanalyse de l'enfant",
     "Pionnière de l'écoute de l'enfant comme sujet à part entière.",
     "Pédiatre et psychanalyste, Dolto affirme que le bébé est un être de langage qui comprend ce qu'on lui dit, bien avant de parler. Elle introduit la notion d'« image inconsciente du corps », crée la Maison verte, lieu d'accueil parents-enfants, et rend la psychanalyse accessible par des émissions de radio très écoutées. Ses positions sur certaines questions cliniques restent discutées.",
     "« Tout est langage. »",
     "Psychanalyse et pédiatrie (1939), La Cause des enfants (1985)"),

    ("durkheim", "Émile Durkheim", "1858-1917", "France", "Sociologie / psychologie sociale",
     "Fonde la sociologie et éclaire les déterminants sociaux du suicide.",
     "Durkheim démontre statistiquement que le suicide, acte apparemment le plus intime, varie selon le degré d'intégration et de régulation sociale. Il distingue les suicides égoïste, altruiste, anomique et fataliste. Sa notion de « fait social » et son travail sur l'anomie irriguent la psychologie sociale, la santé publique et la compréhension du mal-être contemporain.",
     "« Traiter les faits sociaux comme des choses. »",
     "Le Suicide (1897), Les Règles de la méthode sociologique (1895)"),

    ("lebon", "Gustave Le Bon", "1841-1931", "France", "Psychologie des foules",
     "Premier théoricien du comportement collectif.",
     "Le Bon décrit la foule comme une entité dotée d'une âme collective, où l'individu perd son sens critique, devient suggestible et contagieux émotionnellement. Son livre a connu une influence considérable, y compris auprès de dirigeants autoritaires qui y ont cherché des recettes de manipulation. Les théories modernes de l'identité sociale ont largement nuancé sa vision d'une foule irrationnelle et uniforme.",
     "« Dans la foule, l'individu descend plusieurs degrés sur l'échelle de la civilisation. »",
     "Psychologie des foules (1895)"),

    ("loftus", "Elizabeth Loftus", "1944-", "États-Unis", "Psychologie de la mémoire",
     "Démontre la malléabilité des souvenirs et l'implantation de faux souvenirs.",
     "Loftus montre que la façon de poser une question modifie durablement le souvenir d'un témoin et qu'il est possible d'implanter des souvenirs entiers d'événements jamais vécus. Ses travaux ont transformé les procédures judiciaires et l'ont conduite à témoigner dans des centaines de procès, ce qui lui a valu une notoriété autant qu'une hostilité importante.",
     "« La mémoire ressemble moins à un enregistrement qu'à une page Wikipédia que chacun peut modifier. »",
     "Eyewitness Testimony (1979), The Myth of Repressed Memory (1994)"),

    ("baddeley", "Alan Baddeley", "1934-", "Royaume-Uni", "Psychologie cognitive",
     "Modélise la mémoire de travail.",
     "Avec Graham Hitch, Baddeley remplace la notion passive de « mémoire à court terme » par un système actif à plusieurs composantes : la boucle phonologique (matériel verbal), le calepin visuo-spatial (images), l'administrateur central (contrôle attentionnel) et, plus tard, le buffer épisodique. Ce modèle reste le cadre dominant pour comprendre l'attention, la lecture et les apprentissages scolaires.",
     "« La mémoire de travail est l'atelier de la pensée. »",
     "Working Memory (1986)"),

    ("tulving", "Endel Tulving", "1927-2023", "Estonie/Canada", "Psychologie de la mémoire",
     "Distingue mémoire épisodique et mémoire sémantique.",
     "Tulving montre que se souvenir d'un événement personnellement vécu (mémoire épisodique, associée à un « voyage mental dans le temps ») relève d'un système différent de celui qui stocke les connaissances générales (mémoire sémantique). Il formule aussi le principe de spécificité d'encodage : on se souvient mieux dans un contexte proche de celui de l'apprentissage.",
     "« Se souvenir, c'est voyager mentalement dans le temps. »",
     "Elements of Episodic Memory (1983)"),

    ("chomsky", "Noam Chomsky", "1928-", "États-Unis", "Psycholinguistique",
     "Sa critique de Skinner ouvre la révolution cognitive.",
     "Linguiste, Chomsky soutient que la structure du langage ne peut s'expliquer par le seul conditionnement : les enfants produisent des phrases jamais entendues et acquièrent une grammaire complexe malgré la « pauvreté du stimulus ». Il postule une grammaire universelle innée. Sa recension dévastatrice de Verbal Behavior (1959) est souvent citée comme l'acte de décès du behaviorisme dominant.",
     "« Le langage n'est pas un comportement, c'est une connaissance. »",
     "Structures syntaxiques (1957)"),

    ("miller-g", "George A. Miller", "1920-2012", "États-Unis", "Psychologie cognitive",
     "Cofondateur de la révolution cognitive et auteur du « nombre magique ».",
     "Miller applique la théorie de l'information à la psychologie et montre les limites du canal de traitement humain. Il cofonde avec Jerome Bruner le Center for Cognitive Studies de Harvard en 1960, moment souvent retenu comme la naissance institutionnelle des sciences cognitives. Il dirige aussi la création de WordNet, base de données lexicale toujours utilisée en traitement automatique du langage.",
     "« La psychologie est la science de la vie mentale. »",
     "The Magical Number Seven (1956)"),

    ("bruner", "Jerome Bruner", "1915-2016", "États-Unis", "Psychologie cognitive et culturelle",
     "Théoricien de l'apprentissage par découverte et de l'étayage.",
     "Bruner introduit la notion d'étayage (scaffolding) : l'adulte soutient l'enfant sur la partie de la tâche qu'il ne maîtrise pas encore, puis retire progressivement son aide. Il propose l'idée de « curriculum en spirale » et, dans sa seconde carrière, défend une psychologie culturelle centrée sur le récit comme mode fondamental d'organisation de l'expérience.",
     "« On peut enseigner n'importe quoi à n'importe qui, à condition de le faire honnêtement. »",
     "Le Développement de l'enfant : savoir faire, savoir dire (1983)"),

    ("gibson", "James J. Gibson", "1904-1979", "États-Unis", "Psychologie écologique",
     "Fonde l'approche écologique de la perception et le concept d'affordance.",
     "Gibson refuse l'idée que la perception résulte d'un traitement d'indices pauvres : l'environnement offre directement une information riche et structurée, et l'organisme perçoit des « affordances », c'est-à-dire des possibilités d'action (une chaise « offre » de s'asseoir). Ses idées ont profondément marqué le design d'interfaces et la robotique.",
     "« Nous percevons pour agir et nous agissons pour percevoir. »",
     "The Ecological Approach to Visual Perception (1979)"),

    ("hebb", "Donald Hebb", "1904-1985", "Canada", "Neuropsychologie",
     "Formule la règle d'apprentissage synaptique qui porte son nom.",
     "Hebb propose en 1949 que lorsque deux neurones s'activent simultanément de manière répétée, l'efficacité de leur connexion augmente — principe résumé par la formule « des neurones qui s'activent ensemble se lient ensemble ». Cette intuition anticipe la potentialisation à long terme découverte vingt ans plus tard et fonde les réseaux de neurones artificiels.",
     "« Les cellules qui s'activent ensemble se connectent ensemble. »",
     "The Organization of Behavior (1949)"),

    ("kabat-zinn", "Jon Kabat-Zinn", "1944-", "États-Unis", "Mindfulness",
     "Adapte la méditation de pleine conscience à la médecine occidentale.",
     "Biologiste moléculaire pratiquant le zen, Kabat-Zinn crée en 1979 le programme MBSR (Mindfulness-Based Stress Reduction) à l'hôpital du Massachusetts, destiné à des patients atteints de douleurs chroniques. En dépouillant la pratique de son cadre religieux, il permet son évaluation scientifique ; la MBCT qui en dérive figure aujourd'hui dans les recommandations de prévention de la rechute dépressive.",
     "« La pleine conscience, c'est porter attention, intentionnellement, au moment présent, sans jugement. »",
     "Au cœur de la tourmente, la pleine conscience (1990)"),

    ("linehan", "Marsha Linehan", "1943-", "États-Unis", "Thérapie comportementale dialectique",
     "Crée la TCD pour le trouble de la personnalité borderline.",
     "Linehan conçoit une thérapie qui articule acceptation radicale et changement, combinant entraînement aux compétences (régulation émotionnelle, tolérance à la détresse, efficacité interpersonnelle, pleine conscience), thérapie individuelle et soutien téléphonique. La TCD est le premier traitement dont l'efficacité a été démontrée sur les conduites suicidaires répétées. Elle a révélé en 2011 avoir elle-même souffert de ce trouble.",
     "« Les patients font de leur mieux, et ils doivent faire mieux. »",
     "Cognitive-Behavioral Treatment of Borderline Personality Disorder (1993)"),

    ("dweck", "Carol Dweck", "1946-", "États-Unis", "Psychologie de la motivation",
     "Distingue état d'esprit fixe et état d'esprit de développement.",
     "Dweck montre que les élèves qui croient l'intelligence malléable (growth mindset) persistent davantage face à l'échec que ceux qui la pensent innée et fixe. Ses travaux ont inspiré d'immenses programmes scolaires, même si les réplications récentes indiquent des effets réels mais modestes, surtout bénéfiques pour les élèves en difficulté.",
     "« Le pas-encore est plus puissant que l'échec. »",
     "Changer d'état d'esprit (2006)"),

    ("bronfenbrenner", "Urie Bronfenbrenner", "1917-2005", "Russie/États-Unis", "Psychologie écologique du développement",
     "Modélise le développement comme emboîtement de systèmes.",
     "Bronfenbrenner décrit l'enfant au centre de cercles concentriques : microsystème (famille, école), mésosystème (liens entre ces milieux), exosystème (travail des parents, politiques locales), macrosystème (culture, lois) et chronosystème (le temps, les transitions). Ce cadre structure aujourd'hui l'évaluation en protection de l'enfance et les politiques publiques ; il est aussi le co-fondateur du programme Head Start.",
     "« Chaque enfant a besoin d'au moins un adulte qui soit follement fou de lui. »",
     "The Ecology of Human Development (1979)"),

    ("zimbardo", "Philip Zimbardo", "1933-2024", "États-Unis", "Psychologie sociale",
     "Auteur de l'expérience de la prison de Stanford et de l'« effet Lucifer ».",
     "Zimbardo consacre sa carrière à démontrer le pouvoir des situations sur le comportement individuel. Après Stanford, il travaille sur la timidité, la perspective temporelle, puis lance le Heroic Imagination Project, qui forme à résister aux pressions situationnelles. Ses conclusions sur Stanford ont été sévèrement contestées à partir de 2018.",
     "« Les pommes ne sont pas pourries : c'est souvent le tonneau qui l'est. »",
     "L'Effet Lucifer (2007)"),

    ("bion", "Wilfred Bion", "1897-1979", "Royaume-Uni", "Psychanalyse des groupes",
     "Théoricien du fonctionnement inconscient des groupes.",
     "Psychiatre militaire, Bion observe que tout groupe oscille entre un « groupe de travail » orienté vers la tâche et des « hypothèses de base » inconscientes (dépendance, attaque-fuite, couplage) qui le détournent de son objectif. Il développe aussi les concepts de fonction alpha et de contenant-contenu, qui décrivent comment un psychisme transforme l'expérience brute en pensée.",
     "« Le groupe est plus que la somme de ses membres, il a une vie mentale propre. »",
     "Recherches sur les petits groupes (1961)"),

    ("winnicott", "Donald Winnicott", "1896-1971", "Royaume-Uni", "Psychanalyse de l'enfant",
     "Invente l'objet transitionnel et la « mère suffisamment bonne ».",
     "Pédiatre ayant examiné des dizaines de milliers d'enfants, Winnicott décrit le doudou comme un « objet transitionnel » situé entre le moi et le monde, essentiel à la construction de l'autonomie. Il insiste sur le fait que la perfection parentale n'est pas souhaitable : c'est la défaillance progressive et supportable de la mère qui permet à l'enfant de développer ses propres ressources.",
     "« Un bébé seul, ça n'existe pas. »",
     "Jeu et réalité (1971)"),

    ("klein", "Melanie Klein", "1882-1960", "Autriche/Royaume-Uni", "Psychanalyse kleinienne",
     "Explore le monde interne très précoce du nourrisson.",
     "Klein développe la technique du jeu pour analyser de très jeunes enfants et décrit deux positions fondamentales : la position schizo-paranoïde (le monde est clivé en bon et mauvais) et la position dépressive (reconnaissance de l'ambivalence et émergence de la réparation). Ses débats avec Anna Freud ont structuré deux courants durables de la psychanalyse de l'enfant.",
     "« L'amour et la haine visent le même objet dès l'origine. »",
     "Essais de psychanalyse (1948)"),

    ("frankl", "Viktor Frankl", "1905-1997", "Autriche", "Logothérapie",
     "Fonde une psychothérapie centrée sur la quête de sens.",
     "Psychiatre viennois déporté à Auschwitz, Frankl observe que ceux qui conservaient un « pourquoi » résistaient mieux à l'extrême. Il fonde la logothérapie, troisième école viennoise après Freud et Adler, qui postule que la volonté de sens est la motivation première de l'être humain. Son témoignage, écrit en neuf jours, s'est vendu à plus de 16 millions d'exemplaires.",
     "« Celui qui a un pourquoi qui lui tient lieu de but peut supporter tous les comment. »",
     "Découvrir un sens à sa vie (1946)"),

    ("rorschach", "Hermann Rorschach", "1884-1922", "Suisse", "Psychologie projective",
     "Crée le test des taches d'encre.",
     "Rorschach met au point une série de dix planches symétriques et ambiguës, en faisant l'hypothèse que la manière de les interpréter révèle l'organisation de la personnalité. Mort à 37 ans, un an après la publication de son ouvrage, il n'a pas vu le succès planétaire de son test. Le système d'Exner (1974) a tenté d'en standardiser la cotation, sans dissiper les critiques sur sa validité.",
     "« Ce n'est pas ce que l'on voit qui compte, mais comment on le voit. »",
     "Psychodiagnostic (1921)"),

    ("lorenz", "Konrad Lorenz", "1903-1989", "Autriche", "Éthologie",
     "Découvre l'empreinte ; prix Nobel de médecine 1973.",
     "Lorenz montre que les oisons suivent le premier objet mouvant qu'ils voient après l'éclosion — lui-même en l'occurrence — pendant une période sensible très brève. Ce phénomène d'empreinte inspire directement la théorie de l'attachement de Bowlby et le concept de période critique du développement. Son passé politique sous le régime nazi reste une tache majeure sur son héritage.",
     "« L'observation patiente précède toute théorie valable. »",
     "L'Agression, une histoire naturelle du mal (1963)"),

    ("triplett", "Norman Triplett", "1861-1931", "États-Unis", "Psychologie sociale",
     "Auteur de la première expérience de psychologie sociale.",
     "En 1898, Triplett remarque que les cyclistes sont plus rapides en peloton que seuls contre la montre. Il reproduit l'effet en laboratoire avec des enfants enroulant une ligne de canne à pêche, seuls ou en présence d'autres. C'est l'acte de naissance de l'étude expérimentale de la facilitation sociale, approfondie plus tard par Zajonc.",
     "« La présence d'un concurrent libère une énergie latente. »",
     "The Dynamogenic Factors in Pacemaking and Competition (1898)"),

    ("hall", "G. Stanley Hall", "1844-1924", "États-Unis", "Psychologie du développement",
     "Premier docteur en psychologie américain, invente le concept d'adolescence.",
     "Élève de James et de Wundt, Hall fonde le premier laboratoire de psychologie américain, la première revue de la discipline et l'American Psychological Association, qu'il préside. Son ouvrage de 1904 impose la notion d'adolescence comme période distincte de « tempête et de stress ». C'est lui qui invite Freud aux États-Unis en 1909, favorisant la diffusion de la psychanalyse outre-Atlantique.",
     "« L'adolescence est une nouvelle naissance. »",
     "Adolescence (1904)"),

    ("calkins", "Mary Whiton Calkins", "1863-1930", "États-Unis", "Psychologie de la mémoire",
     "Première femme présidente de l'APA, pionnière de l'étude des associations.",
     "Calkins invente la technique des paires associées, encore utilisée en recherche sur la mémoire, et développe une psychologie du self. Harvard lui a refusé le doctorat qu'elle avait pourtant entièrement mérité, en raison de son sexe ; elle est néanmoins élue présidente de l'American Psychological Association en 1905, puis de l'American Philosophical Association.",
     "« Le moi est le fait central de la psychologie. »",
     "An Introduction to Psychology (1901)"),

    ("washburn", "Margaret Floy Washburn", "1871-1939", "États-Unis", "Psychologie comparée",
     "Première femme docteure en psychologie aux États-Unis.",
     "Washburn soutient sa thèse sous la direction de Titchener en 1894 et consacre sa carrière à la vie mentale des animaux, dans un contexte où le behaviorisme naissant refuse d'aborder cette question. Elle défend une théorie motrice de la conscience et devient la deuxième femme présidente de l'APA en 1921.",
     "« Nous ne pouvons pas connaître directement l'esprit animal, mais nous pouvons l'inférer rigoureusement. »",
     "The Animal Mind (1908)"),

    ("clark", "Kenneth & Mamie Clark", "1914-2005 / 1917-1983", "États-Unis", "Psychologie sociale",
     "Leurs études sur les poupées ont pesé sur la fin de la ségrégation scolaire.",
     "Les Clark demandent à des enfants afro-américains de choisir entre des poupées noires et blanches et d'indiquer laquelle est « gentille » ou « jolie ». Les résultats mettent en évidence l'intériorisation précoce du stigmate racial. Leur témoignage est cité dans l'arrêt Brown v. Board of Education (1954) qui déclare la ségrégation scolaire inconstitutionnelle aux États-Unis.",
     "« La ségrégation inflige des dommages psychologiques mesurables aux enfants. »",
     "Racial Identification and Preference in Negro Children (1947)"),

    ("kohlberg", "Lawrence Kohlberg", "1927-1987", "États-Unis", "Développement moral",
     "Décrit six stades du raisonnement moral.",
     "Prolongeant Piaget, Kohlberg soumet à ses participants des dilemmes moraux (dont le célèbre dilemme de Heinz : faut-il voler un médicament pour sauver sa femme ?) et analyse non la réponse mais sa justification. Il en tire trois niveaux — préconventionnel, conventionnel, postconventionnel — subdivisés en six stades. Carol Gilligan lui a reproché de valoriser une éthique de justice masculine au détriment d'une éthique du care.",
     "« Ce n'est pas la réponse qui compte, mais le raisonnement. »",
     "Essais sur le développement moral (1981)"),

    ("gilligan", "Carol Gilligan", "1936-", "États-Unis", "Psychologie du genre et de la morale",
     "Formule l'éthique du care face au modèle de la justice.",
     "Élève puis critique de Kohlberg, Gilligan montre que les femmes de ses études raisonnent souvent en termes de responsabilité, de relation et de soin plutôt que de droits abstraits — ce que les échelles de Kohlberg cotaient comme un stade inférieur. Son livre relance à la fois la psychologie du genre et la philosophie morale contemporaine.",
     "« Une voix différente n'est pas une voix inférieure. »",
     "Une voix différente (1982)"),

    ("sacks", "Oliver Sacks", "1933-2015", "Royaume-Uni/États-Unis", "Neurologie narrative",
     "Redonne au récit clinique une place centrale.",
     "Sacks raconte des cas neurologiques extraordinaires — agnosie visuelle, syndrome de Tourette, amnésie profonde, autisme — en restituant l'expérience subjective des patients plutôt qu'en les réduisant à une lésion. Son travail sur l'« éveil » temporaire de patients post-encéphalitiques grâce à la L-dopa a été porté à l'écran. Il a réconcilié un large public avec la neurologie.",
     "« Les maladies ont un visage humain. »",
     "L'Homme qui prenait sa femme pour un chapeau (1985), L'Éveil (1973)"),

    ("hofstede", "Geert Hofstede", "1928-2020", "Pays-Bas", "Psychologie interculturelle",
     "Établit les dimensions de comparaison des cultures nationales.",
     "À partir d'une enquête menée auprès de plus de 100 000 employés d'IBM dans 50 pays, Hofstede dégage des dimensions permettant de comparer les cultures : distance hiérarchique, individualisme/collectivisme, masculinité/féminité, évitement de l'incertitude, orientation à long terme et indulgence. Son modèle domine le management interculturel, malgré des critiques sur l'assimilation d'une nation à une culture homogène.",
     "« La culture est la programmation mentale collective. »",
     "Culture's Consequences (1980)"),

    ("triandis", "Harry Triandis", "1926-2019", "Grèce/États-Unis", "Psychologie interculturelle",
     "Approfondit l'opposition individualisme / collectivisme.",
     "Triandis affine le modèle en distinguant les formes horizontales et verticales de l'individualisme et du collectivisme, et montre comment la culture façonne la conception même du soi (indépendant vs interdépendant). Il documente les conséquences de ces différences sur la communication, la négociation et l'attribution causale.",
     "« La plupart des théories psychologiques ont été construites sur 5 % de l'humanité. »",
     "Individualism and Collectivism (1995)"),

    ("henrich", "Joseph Henrich", "1968-", "États-Unis", "Psychologie évolutionniste et culturelle",
     "Dénonce le biais WEIRD de la recherche en psychologie.",
     "Henrich et ses collègues montrent en 2010 que l'écrasante majorité des participants aux études publiées proviennent de sociétés occidentales, éduquées, industrialisées, riches et démocratiques (WEIRD) — soit une population statistiquement atypique de l'humanité, y compris sur des tâches perceptives élémentaires. Ce constat a déclenché un vaste mouvement de diversification des échantillons.",
     "« Les sujets les plus étudiés de la psychologie sont les moins représentatifs de l'espèce. »",
     "The WEIRDest People in the World (2020)"),
]
