# -*- coding: utf-8 -*-
"""16 quiz supplémentaires : nouvelles catégories, références et examen final."""

QUIZZES_PLUS = [
    {
        "id": "interculturelle", "icon": "🌍", "color": "or",
        "title": "Psychologie Interculturelle",
        "desc": "Universel, culturel, et le fameux biais WEIRD.",
        "difficulty": "Moyen",
        "questions": [
            {"q": "Que signifie l'acronyme WEIRD ?",
             "a": ["Western, Educated, Industrialized, Rich, Democratic", "World Expert In Research Data",
                   "Wide Ethnographic International Research Database", "Western European Individualistic Research Design"], "correct": 0,
             "explain": "Ces sociétés représentent environ 12 % de l'humanité mais fournissent la quasi-totalité des participants aux études publiées."},
            {"q": "Quelle stratégie d'acculturation est associée au meilleur bien-être ?",
             "a": ["L'assimilation", "La séparation", "L'intégration", "La marginalisation"], "correct": 2,
             "explain": "Conserver sa culture d'origine tout en adoptant celle du pays d'accueil est la stratégie la plus protectrice selon Berry."},
            {"q": "Qu'est-ce qu'un soi interdépendant ?",
             "a": ["Un soi défini par ses attributs personnels", "Un soi défini par ses relations et ses rôles",
                   "Un soi instable", "Un soi pathologique"], "correct": 1,
             "explain": "Markus et Kitayama ont montré que la conception du soi varie culturellement, avec des conséquences sur l'émotion, la motivation et la perception."},
            {"q": "Quelle dimension de Hofstede mesure le besoin de règles explicites ?",
             "a": ["La distance hiérarchique", "L'évitement de l'incertitude", "L'indulgence", "L'orientation à long terme"], "correct": 1,
             "explain": "Un évitement élevé de l'incertitude correspond à une faible tolérance à l'ambiguïté et à un fort besoin de cadres formels."},
            {"q": "Qu'est-ce qu'une culture à contexte fort selon Edward Hall ?",
             "a": ["Une culture où tout doit être explicite", "Une culture où le sens passe par l'implicite et la relation",
                   "Une culture très hiérarchisée", "Une culture individualiste"], "correct": 1,
             "explain": "Dans ces cultures, le non-dit, la relation et le non-verbal portent une large part du message."},
            {"q": "Que désigne un « idiome culturel de détresse » ?",
             "a": ["Un trouble propre à une seule langue", "Une manière culturellement façonnée d'exprimer une souffrance psychique",
                   "Une erreur de traduction diagnostique", "Un dialecte médical"], "correct": 1,
             "explain": "Par exemple, la dépression s'exprime souvent par des plaintes somatiques dans plusieurs cultures d'Asie du Sud-Est."},
            {"q": "Pourquoi l'illusion de Müller-Lyer trompe-t-elle moins certaines populations ?",
             "a": ["Leur vision est meilleure", "Elles ont grandi dans un environnement moins marqué par les angles droits",
                   "Elles connaissent l'illusion", "Elles ont un cerveau différent"], "correct": 1,
             "explain": "Même la perception élémentaire porte la marque de l'environnement construit dans lequel on grandit."},
            {"q": "Que peut-on faire pour utiliser un test psychométrique dans une autre culture ?",
             "a": ["Le traduire mot à mot", "Procéder à une validation transculturelle complète",
                   "Adapter seulement les consignes", "Utiliser le même étalonnage"], "correct": 1,
             "explain": "La traduction ne suffit jamais : il faut revérifier la structure, la validité et l'étalonnage dans la nouvelle population."},
        ],
    },
    {
        "id": "langage", "icon": "🗣️", "color": "vert",
        "title": "Psycholinguistique & Langage",
        "desc": "Acquisition, cerveau du langage, lecture et bilinguisme.",
        "difficulty": "Moyen",
        "questions": [
            {"q": "Que révèle l'erreur « il a prendu » chez un enfant de 3 ans ?",
             "a": ["Un retard de langage", "Qu'il applique une règle grammaticale productive",
                   "Qu'il imite mal les adultes", "Un trouble articulatoire"], "correct": 1,
             "explain": "Cette surgénéralisation prouve que l'enfant a extrait une règle au lieu de mémoriser des formes entendues."},
            {"q": "Quelle aphasie produit un discours fluide mais vide de sens ?",
             "a": ["L'aphasie de Broca", "L'aphasie de Wernicke", "L'aphasie de conduction", "L'aphasie globale"], "correct": 1,
             "explain": "L'atteinte de l'aire de Wernicke altère la compréhension ; le débit reste normal voire logorrhéique."},
            {"q": "Qu'est-ce que l'argument de la pauvreté du stimulus ?",
             "a": ["Les enfants entendent trop de langage", "La parole entendue est insuffisante pour expliquer la grammaire acquise",
                   "Les enfants manquent de vocabulaire", "Le babillage est trop pauvre"], "correct": 1,
             "explain": "C'est l'argument central de Chomsky contre l'explication purement behavioriste du langage."},
            {"q": "Qu'est-ce que le recyclage neuronal ?",
             "a": ["La régénération des neurones", "La réutilisation d'un circuit évolué pour une compétence culturelle récente",
                   "Le sommeil réparateur", "Le remplacement des synapses"], "correct": 1,
             "explain": "La lecture, trop récente pour avoir été sélectionnée, réutilise une région spécialisée dans la reconnaissance des formes visuelles."},
            {"q": "Quel déficit explique l'essentiel des dyslexies ?",
             "a": ["Un déficit visuel", "Un déficit de traitement phonologique", "Un déficit attentionnel", "Un manque d'entraînement"], "correct": 1,
             "explain": "La difficulté porte sur la manipulation des unités sonores de la langue, pas sur la vision ni sur l'intelligence."},
            {"q": "Le bilinguisme précoce provoque-t-il un retard durable ?",
             "a": ["Oui, systématiquement", "Non : le vocabulaire total est équivalent ou supérieur",
                   "Oui, jusqu'à 10 ans", "Seulement chez les garçons"], "correct": 1,
             "explain": "Le vocabulaire par langue peut être un peu plus réduit, mais le total ne l'est pas, et l'alternance de codes est un signe de maîtrise."},
            {"q": "Que dit la version faible de l'hypothèse Sapir-Whorf ?",
             "a": ["La langue détermine entièrement la pensée", "La langue oriente l'attention et facilite certains traitements",
                   "La langue n'a aucun effet", "La pensée précède toujours la langue"], "correct": 1,
             "explain": "Seule cette version est soutenue par les données : les locuteurs du russe discriminent plus vite deux nuances de bleu qu'ils nomment différemment."},
            {"q": "À quel âge un bébé cesse-t-il de distinguer les phonèmes absents de sa langue ?",
             "a": ["Vers 3 mois", "Vers 12 mois", "Vers 3 ans", "Jamais"], "correct": 1,
             "explain": "Cette spécialisation perceptive s'opère au cours de la première année : c'est une optimisation, pas une perte."},
        ],
    },
    {
        "id": "psychometrie", "icon": "📏", "color": "gris",
        "title": "Psychométrie & Mesure",
        "desc": "QI, validité, effet Flynn et tests douteux.",
        "difficulty": "Moyen",
        "questions": [
            {"q": "Quelle différence entre fidélité et validité ?",
             "a": ["Aucune", "La fidélité est la stabilité, la validité le fait de mesurer ce qu'on prétend",
                   "La validité est la stabilité", "La fidélité concerne les participants"], "correct": 1,
             "explain": "Un pèse-personne affichant toujours 10 kg de trop est parfaitement fidèle mais totalement invalide."},
            {"q": "Quelle proportion de la population se situe entre 85 et 115 de QI ?",
             "a": ["50 %", "68 %", "95 %", "99 %"], "correct": 1,
             "explain": "Un écart-type de part et d'autre de la moyenne couvre environ 68 % d'une distribution normale."},
            {"q": "Qu'est-ce que l'effet Flynn ?",
             "a": ["La baisse du QI avec l'âge", "La hausse des scores bruts au fil des générations",
                   "L'effet du sommeil sur le QI", "Un biais de l'examinateur"], "correct": 1,
             "explain": "Environ 3 points par décennie au XXe siècle : trop rapide pour être génétique, l'effet s'inverse depuis peu dans certains pays."},
            {"q": "Pourquoi le MBTI est-il critiqué scientifiquement ?",
             "a": ["Il est trop long", "Fidélité test-retest médiocre et dichotomies artificielles",
                   "Il est trop récent", "Il n'existe qu'en anglais"], "correct": 1,
             "explain": "Jusqu'à la moitié des personnes changent de type en quelques semaines, et les traits psychologiques sont continus, non dichotomiques."},
            {"q": "Que vaut une corrélation de 0,30 en psychologie ?",
             "a": ["Un effet nul", "Un effet modéré, fréquent dans la discipline", "Une preuve de causalité", "Un effet très fort"], "correct": 1,
             "explain": "0,10 est faible, 0,30 modéré, 0,50 fort — et aucune corrélation n'établit une causalité."},
            {"q": "Qu'est-ce que l'effet Barnum ?",
             "a": ["Accepter comme personnelle une description vague valable pour tous", "Un biais de l'examinateur",
                   "Un effet de l'ordre des questions", "Une erreur de cotation"], "correct": 0,
             "explain": "C'est le ressort des horoscopes et de nombreux tests de personnalité non validés."},
            {"q": "Que distingue Cattell dans l'intelligence ?",
             "a": ["Verbal et non verbal", "Fluide et cristallisée", "Concrète et abstraite", "Innée et acquise"], "correct": 1,
             "explain": "L'intelligence fluide décline avec l'âge, la cristallisée se maintient ou progresse."},
            {"q": "Que pensait Binet de la fixité de l'intelligence ?",
             "a": ["Il la jugeait innée et immuable", "Il protestait contre cette idée",
                   "Il n'en parlait pas", "Il pensait qu'elle diminuait avec l'âge"], "correct": 1,
             "explain": "Binet défendait l'« orthopédie mentale » ; l'interprétation héréditariste de ses tests est un détournement de son travail."},
        ],
    },
    {
        "id": "sport", "icon": "🏃", "color": "or",
        "title": "Psychologie du Sport",
        "desc": "Motivation, pression, imagerie mentale et objectifs.",
        "difficulty": "Facile",
        "questions": [
            {"q": "Quels sont les trois besoins de la théorie de l'autodétermination ?",
             "a": ["Sécurité, plaisir, argent", "Autonomie, compétence, affiliation",
                   "Force, endurance, technique", "Discipline, sommeil, nutrition"], "correct": 1,
             "explain": "Deci et Ryan : ces trois besoins doivent être satisfaits pour qu'une motivation de qualité se maintienne."},
            {"q": "Qu'est-ce que l'effet de surjustification ?",
             "a": ["Trop d'entraînement nuit", "Récompenser une activité appréciée réduit la motivation intrinsèque",
                   "Justifier ses échecs améliore la performance", "Trop d'objectifs paralysent"], "correct": 1,
             "explain": "L'activité devient un moyen d'obtenir la récompense au lieu d'être une fin en soi."},
            {"q": "Pourquoi rate-t-on souvent au moment décisif (choking) ?",
             "a": ["Par manque d'entraînement", "Parce que le contrôle conscient reprend la main sur un geste automatisé",
                   "Par fatigue musculaire", "Par manque de motivation"], "correct": 1,
             "explain": "La self-focus theory de Beilock : surveiller consciemment un geste surappris le désorganise."},
            {"q": "Quel type d'objectif faut-il privilégier en compétition ?",
             "a": ["De résultat", "De performance", "De processus", "Aucun"], "correct": 2,
             "explain": "Les objectifs de processus sont entièrement sous contrôle, donc bien moins anxiogènes."},
            {"q": "Que dit la loi de Yerkes-Dodson ?",
             "a": ["Plus on est activé, mieux c'est", "La performance suit un U inversé selon l'activation",
                   "L'anxiété est toujours nuisible", "La performance est linéaire avec l'effort"], "correct": 1,
             "explain": "Il existe un niveau d'activation optimal, variable selon la tâche et selon l'individu."},
            {"q": "Que recommande le modèle PETTLEP pour l'imagerie mentale ?",
             "a": ["Imaginer très vite", "Imaginer en temps réel, en contexte et avec l'émotion",
                   "Imaginer uniquement des victoires", "Imaginer en vue extérieure"], "correct": 1,
             "explain": "Plus l'imagerie est proche des conditions réelles, plus elle transfère à la performance."},
            {"q": "Quel effet a l'écriture des inquiétudes avant une épreuve ?",
             "a": ["Elle aggrave l'anxiété", "Elle améliore la performance, surtout chez les plus anxieux",
                   "Elle n'a aucun effet", "Elle allonge le temps de réaction"], "correct": 1,
             "explain": "Dix minutes d'écriture libèrent la mémoire de travail occupée par les ruminations."},
            {"q": "Comment interpréter au mieux les sensations physiques avant une épreuve ?",
             "a": ["Comme du stress à supprimer", "Comme de l'excitation mobilisatrice",
                   "Comme un signe de mauvaise préparation", "Comme une maladie"], "correct": 1,
             "explain": "La réévaluation de l'activation en excitation améliore réellement la performance dans les études expérimentales."},
        ],
    },
    {
        "id": "consommation", "icon": "🛒", "color": "rose",
        "title": "Psychologie de la Consommation",
        "desc": "Influence, nudges, dark patterns et parades.",
        "difficulty": "Facile",
        "questions": [
            {"q": "Lequel ne fait PAS partie des principes de Cialdini ?",
             "a": ["Réciprocité", "Rareté", "Répétition mécanique", "Preuve sociale"], "correct": 2,
             "explain": "Les six principes sont réciprocité, engagement, preuve sociale, sympathie, autorité et rareté — auxquels s'ajoute l'unité."},
            {"q": "Pourquoi l'option par défaut est-elle si puissante ?",
             "a": ["Elle est obligatoire", "Elle exploite l'inertie et se lit comme une recommandation implicite",
                   "Elle est toujours la moins chère", "Elle est plus visible"], "correct": 1,
             "explain": "Le passage de l'opt-in à l'opt-out fait passer les taux de consentement au don d'organes de moins de 20 % à plus de 90 %."},
            {"q": "Qu'est-ce que le confirmshaming ?",
             "a": ["Confirmer une commande deux fois", "Formuler le refus de façon culpabilisante",
                   "Demander un avis après achat", "Un message de confirmation trompeur"], "correct": 1,
             "explain": "« Non merci, je préfère payer plein tarif » est un exemple typique de ce dark pattern."},
            {"q": "Qu'est-ce que l'effet leurre ?",
             "a": ["Une publicité mensongère", "Une troisième option peu attractive qui oriente vers une option ciblée",
                   "Un prix barré", "Un faux compte à rebours"], "correct": 1,
             "explain": "Le leurre rend l'option visée artificiellement supérieure par comparaison."},
            {"q": "Que montre l'expérience des confitures d'Iyengar ?",
             "a": ["Plus de choix, plus de ventes", "24 variétés attirent plus mais vendent dix fois moins que 6",
                   "Le choix n'a aucun effet", "Les clients préfèrent le sucré"], "correct": 1,
             "explain": "C'est l'illustration classique du paradoxe du choix : trop d'options paralysent la décision."},
            {"q": "Pourquoi payer sans espèces augmente-t-il les dépenses ?",
             "a": ["C'est plus rapide", "La « douleur de payer » est réduite", "Les prix sont plus bas", "Les cartes offrent des réductions"], "correct": 1,
             "explain": "Le paiement dématérialisé atténue le signal négatif associé à la sortie d'argent."},
            {"q": "Quelle parade neutralise le mieux l'urgence artificielle ?",
             "a": ["Acheter tout de suite", "La règle des 24 heures", "Comparer les prix barrés", "Demander un avis en magasin"], "correct": 1,
             "explain": "Différer la décision fait disparaître à la fois l'urgence fabriquée et l'émotion du moment."},
            {"q": "Que dit la recherche sur le neuromarketing ?",
             "a": ["Il a identifié un bouton d'achat cérébral", "Ses résultats réels restent limités",
                   "Il remplace les études de marché", "Il lit les pensées des clients"], "correct": 1,
             "explain": "L'imagerie prédit légèrement mieux les ventes agrégées que les déclarations, sans plus."},
        ],
    },
    {
        "id": "numerique", "icon": "📱", "color": "vert",
        "title": "Psychologie du Numérique",
        "desc": "Attention, réseaux sociaux, désinformation.",
        "difficulty": "Moyen",
        "questions": [
            {"q": "Quel programme de renforcement les fils d'actualité exploitent-ils ?",
             "a": ["Renforcement continu", "Ratio variable", "Intervalle fixe", "Punition positive"], "correct": 1,
             "explain": "C'est le programme le plus résistant à l'extinction, identifié par Skinner — et celui des machines à sous."},
            {"q": "Quelle distinction compte plus que le temps d'écran ?",
             "a": ["Le type d'appareil", "L'usage passif contre l'usage actif", "L'heure de la journée", "La marque du téléphone"], "correct": 1,
             "explain": "Faire défiler et comparer est associé à une baisse d'humeur ; échanger réellement avec des proches ne l'est pas."},
            {"q": "Quelle est l'ampleur de la corrélation entre temps d'écran global et bien-être ?",
             "a": ["Très forte", "Faible, comparable à des variables anodines", "Nulle", "Positive et forte"], "correct": 1,
             "explain": "Autour de r = -0,05 dans les grandes analyses : ni « poison générationnel », ni absence totale d'effet."},
            {"q": "Qu'est-ce que l'effet de vérité illusoire ?",
             "a": ["Croire ce qu'on voit", "Une affirmation répétée paraît plus vraie",
                   "Les images sont plus crédibles que les textes", "Les experts sont toujours crus"], "correct": 1,
             "explain": "L'effet fonctionne même lorsqu'on avait initialement jugé l'affirmation fausse."},
            {"q": "Pourquoi les fausses informations se diffusent-elles plus vite ?",
             "a": ["Elles sont mieux écrites", "Elles sont plus nouvelles et suscitent surprise et dégoût",
                   "Elles sont diffusées par des robots uniquement", "Elles sont plus courtes"], "correct": 1,
             "explain": "L'étude du MIT sur 126 000 rumeurs pointe la nouveauté et la charge émotionnelle, pas seulement les robots."},
            {"q": "Qu'est-ce que le prebunking ?",
             "a": ["Démentir après coup", "Exposer les techniques de manipulation avant l'exposition",
                   "Bloquer les comptes suspects", "Vérifier ses sources"], "correct": 1,
             "explain": "Le principe est celui d'un vaccin : reconnaître la technique immunise contre son effet."},
            {"q": "Quel facteur aggrave spécifiquement le cyberharcèlement ?",
             "a": ["La lenteur des réseaux", "L'absence de frein empathique, l'agresseur ne voyant pas la détresse",
                   "Le coût des abonnements", "La qualité des images"], "correct": 1,
             "explain": "S'y ajoutent la continuité 24 h/24, l'audience illimitée et la permanence des traces."},
            {"q": "Quelle stratégie d'hygiène numérique est la plus efficace ?",
             "a": ["Compter sur sa volonté", "Modifier son environnement (notifications, écran d'accueil, frictions)",
                   "Supprimer tous ses comptes", "Utiliser un minuteur mental"], "correct": 1,
             "explain": "Agir sur l'environnement est bien plus fiable que la maîtrise de soi face à des interfaces conçues pour capter l'attention."},
        ],
    },
    {
        "id": "evolutionniste", "icon": "🧬", "color": "or",
        "title": "Psychologie Évolutionniste",
        "desc": "Adaptations, décalage évolutif et critiques.",
        "difficulty": "Moyen",
        "questions": [
            {"q": "Qu'est-ce que le décalage évolutif (mismatch) ?",
             "a": ["Une erreur génétique", "L'inadéquation entre mécanismes ancestraux et environnement moderne",
                   "Un retard de développement", "Une mutation récente"], "correct": 1,
             "explain": "Notre attirance pour le sucre était adaptative en pénurie ; elle devient problématique en abondance."},
            {"q": "Que dit la théorie de la gestion des erreurs ?",
             "a": ["Il faut éviter toute erreur", "Quand les coûts des deux erreurs diffèrent, un biais est sélectionné",
                   "Les erreurs sont aléatoires", "L'erreur est toujours coûteuse"], "correct": 1,
             "explain": "Prendre un bâton pour un serpent coûte un sursaut ; l'inverse peut coûter la vie."},
            {"q": "Qu'est-ce que le sophisme naturaliste ?",
             "a": ["Confondre nature et culture", "Déduire ce qui doit être de ce qui est",
                   "Nier l'évolution", "Surestimer la génétique"], "correct": 1,
             "explain": "Expliquer l'origine évolutive d'un comportement ne le justifie en aucune façon."},
            {"q": "Quelle est la critique de Gould et Lewontin ?",
             "a": ["L'évolution n'existe pas", "Tous les traits ne sont pas des adaptations : certains sont des sous-produits",
                   "La sélection est trop lente", "Les gènes ne comptent pas"], "correct": 1,
             "explain": "Leur métaphore des spandrels met en garde contre l'adaptationnisme systématique."},
            {"q": "Que montre la tâche de sélection de Wason en version sociale ?",
             "a": ["Les gens sont illogiques", "La performance grimpe quand le problème porte sur une règle sociale",
                   "La logique est innée", "Le contexte ne change rien"], "correct": 1,
             "explain": "De moins de 25 % à plus de 75 % de réussite : Cosmides y voit un module de détection des tricheurs."},
            {"q": "Que désigne le nombre de Dunbar ?",
             "a": ["Le nombre de neurones", "Environ 150 relations sociales stables",
                   "Le nombre d'émotions de base", "La taille d'une tribu préhistorique maximale"], "correct": 1,
             "explain": "Il correspond à la taille observée de nombreux groupes humains stables, des villages néolithiques aux unités militaires."},
            {"q": "Quelle distinction Geary applique-t-il à l'éducation ?",
             "a": ["Facile et difficile", "Biologiquement primaire et secondaire", "Oral et écrit", "Théorique et pratique"], "correct": 1,
             "explain": "Parler s'acquiert spontanément ; lire et calculer exigent un enseignement explicite et beaucoup d'effort."},
            {"q": "Pourquoi les phobies portent-elles plus souvent sur les serpents que sur les prises électriques ?",
             "a": ["Les serpents sont plus visibles", "Il existe une préparation biologique à certaines peurs",
                   "Les prises sont récentes et inoffensives", "C'est un effet culturel uniquement"], "correct": 1,
             "explain": "Seligman parle de peurs « préparées » : nos ancêtres ont été sélectionnés face à ces dangers, pas face à l'électricité."},
        ],
    },
    {
        "id": "vieillissement", "icon": "🌿", "color": "gris",
        "title": "Vieillissement & Gérontopsychologie",
        "desc": "Ce qui décline, ce qui progresse, et comment protéger.",
        "difficulty": "Moyen",
        "questions": [
            {"q": "Quelle capacité progresse avec l'âge ?",
             "a": ["La vitesse de traitement", "L'intelligence cristallisée et la régulation émotionnelle",
                   "La mémoire de travail", "L'attention divisée"], "correct": 1,
             "explain": "Vocabulaire, connaissances et gestion des émotions s'améliorent, tandis que la vitesse et la mémoire épisodique déclinent."},
            {"q": "Qu'est-ce que la réserve cognitive ?",
             "a": ["Un stock de neurones inutilisés", "Un capital de connexions et de stratégies retardant les symptômes",
                   "La mémoire à long terme", "Une zone du cortex"], "correct": 1,
             "explain": "À lésions égales, une réserve élevée retarde l'apparition clinique des troubles."},
            {"q": "Quel facteur modifiable de démence est souvent négligé ?",
             "a": ["La couleur des yeux", "La surdité non appareillée", "Le groupe sanguin", "La taille"], "correct": 1,
             "explain": "C'est l'un des facteurs de risque les plus importants à l'âge moyen selon la commission du Lancet."},
            {"q": "Que dit la théorie de la sélectivité socio-émotionnelle ?",
             "a": ["Les personnes âgées deviennent asociales", "Quand l'horizon perçu se raccourcit, on privilégie le sens et les relations proches",
                   "Le bien-être décline linéairement", "Les émotions s'émoussent"], "correct": 1,
             "explain": "Carstensen a montré que ce n'est pas l'âge qui compte mais l'horizon temporel perçu."},
            {"q": "Quel signe distingue un oubli normal d'un signal d'alerte ?",
             "a": ["La fréquence seule", "Dans le normal, la personne se plaint elle-même et les indices l'aident",
                   "L'heure de la journée", "Le type d'objet oublié"], "correct": 1,
             "explain": "Dans le pathologique, c'est souvent l'entourage qui s'inquiète, et les indices ne permettent pas de retrouver l'information."},
            {"q": "Quelle est la forme de la courbe du bien-être sur la vie entière ?",
             "a": ["Décroissante", "En U : minimum vers 45-55 ans puis remontée", "Croissante", "Plate"], "correct": 1,
             "explain": "Le bien-être remonte au grand âge malgré les pertes de santé, ce qui a longtemps surpris les chercheurs."},
            {"q": "Que sait-on des jeux d'entraînement cérébral ?",
             "a": ["Ils préviennent la démence", "Ils améliorent surtout la performance aux jeux entraînés",
                   "Ils augmentent le QI", "Ils remplacent l'activité physique"], "correct": 1,
             "explain": "Le transfert vers d'autres tâches est quasi nul ; l'activité physique reste le facteur le mieux établi."},
            {"q": "Qu'est-ce que l'elderspeak ?",
             "a": ["Un dialecte régional", "Un langage infantilisant adressé aux personnes âgées",
                   "Une thérapie du langage", "Une technique de mémoire"], "correct": 1,
             "explain": "Voix aiguë, diminutifs et « on » collectif dégradent l'estime de soi et augmentent la résistance aux soins."},
        ],
    },
    {
        "id": "environnementale", "icon": "🌱", "color": "vert",
        "title": "Psychologie Environnementale",
        "desc": "Lieux de vie, nature et éco-anxiété.",
        "difficulty": "Facile",
        "questions": [
            {"q": "Que montre l'étude d'Ulrich de 1984 ?",
             "a": ["La musique accélère la guérison", "Une vue sur des arbres raccourcit l'hospitalisation",
                   "Les chambres individuelles sont préférables", "La lumière artificielle suffit"], "correct": 1,
             "explain": "Les patients avec vue sur la végétation sortaient en moyenne un jour plus tôt et recevaient moins d'antalgiques."},
            {"q": "Que dit la théorie de la restauration de l'attention ?",
             "a": ["La nature fatigue l'attention", "La nature sollicite une attention involontaire douce, permettant la récupération",
                   "Seul le sommeil restaure l'attention", "L'attention ne se restaure pas"], "correct": 1,
             "explain": "Kaplan : l'attention dirigée, épuisée par les tâches urbaines, récupère dans les environnements naturels."},
            {"q": "Quel message change le plus efficacement un comportement écologique ?",
             "a": ["Un message culpabilisant", "La norme descriptive : la majorité de vos voisins le fait",
                   "Une menace de sanction", "Un rappel du réchauffement global"], "correct": 1,
             "explain": "Les campagnes hôtelières sur les serviettes en fournissent la démonstration classique."},
            {"q": "L'éco-anxiété est-elle un trouble mental ?",
             "a": ["Oui, dans le DSM-5", "Non : c'est une réponse proportionnée à une menace réelle",
                   "Oui, dans la CIM-11", "Seulement chez les adolescents"], "correct": 1,
             "explain": "Elle n'appelle un accompagnement que lorsqu'elle devient paralysante et durablement invalidante."},
            {"q": "Qu'est-ce que l'effet rebond ?",
             "a": ["Le retour d'une habitude abandonnée", "L'absorption des gains d'efficacité par une hausse de consommation",
                   "Un effet de mode écologique", "Le rejet des normes environnementales"], "correct": 1,
             "explain": "Un appareil deux fois plus économe peut être utilisé deux fois plus longtemps."},
            {"q": "Qu'est-ce qui pèse le plus dans le vécu de la densité ?",
             "a": ["Le nombre de personnes au m²", "Le sentiment de contrôle sur ses interactions",
                   "La hauteur sous plafond", "La température"], "correct": 1,
             "explain": "Un espace dense mais modulable est mieux vécu qu'un espace ouvert sans possibilité de repli."},
            {"q": "Qu'a montré l'étude harvardienne sur les bureaux paysagers ?",
             "a": ["Une hausse des échanges en face-à-face", "Une baisse de 70 % des interactions directes",
                   "Aucune différence", "Une hausse de la créativité"], "correct": 1,
             "explain": "Les échanges se déplacent vers l'écrit — l'inverse de l'objectif affiché de ces aménagements."},
            {"q": "Quel seuil hebdomadaire de contact avec la nature est associé au bien-être ?",
             "a": ["30 minutes", "Environ 120 minutes cumulables", "5 heures", "Un week-end complet"], "correct": 1,
             "explain": "Le cumul compte davantage que la répartition : deux heures par semaine, en une ou plusieurs fois."},
        ],
    },
    {
        "id": "politique", "icon": "🗳️", "color": "rose",
        "title": "Psychologie Politique & Croyances",
        "desc": "Polarisation, complotisme et esprit critique.",
        "difficulty": "Difficile",
        "questions": [
            {"q": "Qu'est-ce que la polarisation affective ?",
             "a": ["L'écart entre programmes politiques", "L'hostilité croissante envers le camp adverse",
                   "L'abstention électorale", "La radicalisation idéologique"], "correct": 1,
             "explain": "C'est le phénomène le plus marqué : les positions bougent peu, l'hostilité interpersonnelle beaucoup."},
            {"q": "Quels besoins alimentent les croyances complotistes ?",
             "a": ["Financiers, sociaux, politiques", "Épistémique, existentiel et social",
                   "Affectif, moral, religieux", "Cognitif uniquement"], "correct": 1,
             "explain": "Comprendre, retrouver du contrôle, et se valoriser en détenant un savoir caché."},
            {"q": "Qu'est-ce que le biais de proportionnalité ?",
             "a": ["Évaluer les proportions d'un dessin", "Exiger qu'un grand événement ait une grande cause",
                   "Comparer deux groupes de tailles différentes", "Surestimer les petites minorités"], "correct": 1,
             "explain": "Il rend difficile d'accepter qu'un individu isolé ait pu provoquer un événement historique majeur."},
            {"q": "Que dit la métaphore de l'éléphant et du cornac (Haidt) ?",
             "a": ["La raison guide les émotions", "L'intuition décide et la raison justifie après coup",
                   "Les émotions sont irrationnelles", "Le groupe décide pour l'individu"], "correct": 1,
             "explain": "C'est pourquoi de bons arguments convainquent rarement une personne engagée dans un camp."},
            {"q": "Quelle méthode produit des changements d'attitude durables ?",
             "a": ["La confrontation argumentée", "Le deep canvassing : conversation longue et non jugeante",
                   "Le partage de statistiques", "La moquerie publique"], "correct": 1,
             "explain": "Des essais randomisés ont montré des effets persistant plusieurs mois sur des sujets très clivants."},
            {"q": "Que sait-on du « retour de flamme » après une correction factuelle ?",
             "a": ["Il est systématique", "Il est en réalité rare : corriger reste utile",
                   "Il concerne uniquement les réseaux sociaux", "Il n'a jamais été étudié"], "correct": 1,
             "explain": "À condition de fournir une explication alternative complète, et pas seulement un démenti."},
            {"q": "Qu'est-ce que l'illusion de profondeur explicative ?",
             "a": ["Croire comprendre un mécanisme jusqu'à devoir l'expliquer", "Surestimer la profondeur d'un texte",
                   "Confondre corrélation et causalité", "Croire les experts sur parole"], "correct": 0,
             "explain": "Demander « comment cela fonctionne-t-il concrètement ? » modère spontanément les positions — demander « pourquoi ? » ne le fait pas."},
            {"q": "Qu'est-ce que le rasoir de Hitchens ?",
             "a": ["Une technique de débat agressive", "Ce qui est affirmé sans preuve peut être rejeté sans preuve",
                   "Un principe de parcimonie biologique", "Une règle de politesse argumentative"], "correct": 1,
             "explain": "La charge de la preuve incombe à celui qui affirme, pas à celui qui doute."},
        ],
    },
    {
        "id": "science-psychologique", "icon": "🔬", "color": "vert",
        "title": "Science psychologique du cerveau",
        "desc": "Tests, techniques, cave des mythes, et ce qu'on peut vraiment en faire.",
        "difficulty": "Difficile",
        "questions": [
            {"q": "Que montre le cas de Leborgne (« Tan ») en 1861 ?",
             "a": ["Que tout le cerveau sert au langage", "Qu'une lésion frontale gauche peut détruire l'articulation de la parole",
                   "Que la phrénologie avait raison", "Que l'IRM existait déjà"], "correct": 1,
             "explain": "Broca relie une lésion localisée à un déficit précis : acte de naissance de la localisation moderne."},
            {"q": "Pourquoi l'IRMf ne photographie-t-elle pas la pensée ?",
             "a": ["Parce que les aimants sont trop faibles", "Elle mesure un signal BOLD décalé, corrélé à l'activité, pas les neurones eux-mêmes",
                   "Parce qu'elle n'est pas encore assez colorée", "Parce qu'elle ne marche que sur l'animal"], "correct": 1,
             "explain": "Le BOLD suit l'oxygène du sang avec plusieurs secondes de retard. Corrélation, pas lecture d'esprit."},
            {"q": "Quelle leçon principale tire-t-on du patient H.M. ?",
             "a": ["Toute mémoire passe par l'hippocampe", "La mémoire procédurale peut progresser sans souvenirs déclaratifs nouveaux",
                   "On n'utilise que 10 % du cerveau", "L'amnésie est toujours réversible"], "correct": 1,
             "explain": "Il s'améliorait au dessin en miroir sans se souvenir d'avoir pratiqué : plusieurs systèmes de mémoire."},
            {"q": "Qu'est-ce que l'homoncule de Penfield ?",
             "a": ["Un test de personnalité", "La carte corticale du corps, déformée selon la finesse sensorielle ou motrice",
                   "Un mythe sans base", "Un dessin de phrénologie"], "correct": 1,
             "explain": "Mains et lèvres occupent une surface énorme ; le tronc, très peu."},
            {"q": "Quel neuromythe le split-brain a-t-il surtout nourri ?",
             "a": ["Les 10 % du cerveau", "Cerveau gauche rationnel / cerveau droit créatif",
                   "Les styles d'apprentissage", "L'effet Mozart"], "correct": 1,
             "explain": "Sperry a montré des spécialisations ; les magazines en ont fait deux personnalités. Les hémisphères coopèrent."},
            {"q": "Que mesure principalement un EEG ?",
             "a": ["Le débit sanguin", "L'activité électrique du scalp, avec une excellente résolution temporelle",
                   "Les gènes exprimés", "La myéline"], "correct": 1,
             "explain": "Berger 1929. Idéal pour le sommeil et les potentiels évoqués ; faible pour localiser précisément."},
            {"q": "Que montre le Iowa Gambling Task ?",
             "a": ["Que la logique suffit toujours", "Que sans marqueurs corporels, on évite moins bien les choix toxiques",
                   "Que les émotions empêchent de décider", "Que le hasard n'existe pas"], "correct": 1,
             "explain": "Damasio et Bechara : l'émotion participe à la décision, elle ne s'y oppose pas."},
            {"q": "Parmi ces projets, lesquels offrent de vraies données de cerveaux à explorer ?",
             "a": ["Un test de QI en ligne payant", "Human Connectome, OpenNeuro, Allen Brain Map, BigBrain",
                   "Un casque grand public de « boost »", "Une application de styles d'apprentissage"], "correct": 1,
             "explain": "Ce sont des projets complets, ouverts, cités dans la zone de découverte."},
        ],
    },
    {
        "id": "experiences-celebres", "icon": "🔬", "color": "vert",
        "title": "Les grandes expériences",
        "desc": "Milgram, Asch, Pavlov, Loftus… reconnaîtras-tu les protocoles ?",
        "difficulty": "Moyen",
        "questions": [
            {"q": "Dans l'expérience de Milgram, quelle proportion va jusqu'à 450 volts ?",
             "a": ["12 %", "35 %", "65 %", "95 %"], "correct": 2,
             "explain": "Deux tiers des participants, malgré un stress visible et intense."},
            {"q": "Que montre l'expérience du gorille invisible ?",
             "a": ["Une illusion d'optique", "La cécité attentionnelle liée à l'attention sélective",
                   "Un trouble de la vision", "Un effet de fatigue"], "correct": 1,
             "explain": "Environ la moitié des participants concentrés sur les passes ne voient pas le gorille traverser la scène."},
            {"q": "Qu'a démontré Elizabeth Loftus avec les vidéos d'accident ?",
             "a": ["Les témoins mentent souvent", "Le verbe employé dans la question modifie le souvenir",
                   "La mémoire est infaillible", "Les vidéos améliorent le rappel"], "correct": 1,
             "explain": "« Fracassées » produit des vitesses estimées plus élevées et fait apparaître un verre brisé inexistant."},
            {"q": "Que révèlent les singes de Harlow ?",
             "a": ["Le besoin de nourriture prime", "Le besoin de réconfort tactile prime sur l'alimentation",
                   "Les singes n'ont pas d'attachement", "L'imitation est innée"], "correct": 1,
             "explain": "Les petits passaient leur temps agrippés à la mère en tissu, allant à la mère métallique uniquement pour se nourrir."},
            {"q": "Quelle est la principale critique de la prison de Stanford ?",
             "a": ["L'échantillon trop grand", "Consignes explicites aux gardiens et absence de groupe contrôle",
                   "La durée trop longue", "Le manque de financement"], "correct": 1,
             "explain": "S'y ajoute la sélection de volontaires prédisposés : c'est une démonstration, pas une preuve expérimentale."},
            {"q": "Que montre le patient H.M. ?",
             "a": ["Que la mémoire est unique", "Que mémoire procédurale et déclarative sont dissociables",
                   "Que l'hippocampe est inutile", "Que l'amnésie est réversible"], "correct": 1,
             "explain": "Il progressait au dessin en miroir sans jamais se souvenir de s'être entraîné."},
            {"q": "Qu'a montré Asch avec ses trois lignes ?",
             "a": ["Un trouble visuel fréquent", "Que 75 % des participants se conforment au moins une fois",
                   "Que le groupe améliore le jugement", "Que la perception est infaillible"], "correct": 1,
             "explain": "Un seul allié dissident suffit pourtant à faire chuter massivement la conformité."},
            {"q": "Que révèle l'expérience des groupes minimaux de Tajfel ?",
             "a": ["Les conflits viennent de la compétition pour les ressources", "Un critère trivial suffit à créer une discrimination intergroupe",
                   "Les groupes coopèrent spontanément", "L'identité sociale n'existe pas"], "correct": 1,
             "explain": "Les participants maximisent l'écart en faveur de leur groupe, quitte à réduire son gain absolu."},
            {"q": "Que dit la réplication moderne du test du marshmallow ?",
             "a": ["L'effet est encore plus fort", "L'effet est bien plus faible et lié au milieu socio-économique",
                   "Le test est invalide", "Les enfants trichent"], "correct": 1,
             "explain": "La fiabilité perçue de l'adulte et les conditions de vie expliquent une grande partie du résultat initial."},
            {"q": "Quelle expérience a montré l'effet placebo en chirurgie ?",
             "a": ["Celle de Beecher", "Celle de Moseley sur l'arthrose du genou", "Celle de Rosenhan", "Celle de Hofling"], "correct": 1,
             "explain": "Chirurgie simulée et chirurgie réelle ont produit la même réduction de douleur sur deux ans."},
        ],
    },
    {
        "id": "biais-cognitifs", "icon": "🎯", "color": "or",
        "title": "Reconnaître les biais cognitifs",
        "desc": "Situations concrètes : quel biais est à l'œuvre ?",
        "difficulty": "Moyen",
        "questions": [
            {"q": "Vous ne lisez que les avis confirmant votre choix de voiture. Quel biais ?",
             "a": ["Ancrage", "Confirmation", "Halo", "Récence"], "correct": 1,
             "explain": "Le biais de confirmation nous fait chercher et retenir ce qui soutient nos croyances."},
            {"q": "Un prix barré de 200 € fait paraître 120 € avantageux. Quel biais ?",
             "a": ["Ancrage", "Rareté", "Réciprocité", "Cadrage"], "correct": 0,
             "explain": "Le premier chiffre rencontré sert de référence pour toutes les évaluations suivantes."},
            {"q": "Vous finissez un film ennuyeux parce que vous avez payé la place. Quel biais ?",
             "a": ["Statu quo", "Coûts irrécupérables", "Dotation", "Optimisme"], "correct": 1,
             "explain": "Seuls les coûts et bénéfices futurs devraient compter : le passé est dépensé quoi qu'il arrive."},
            {"q": "Après un crash aérien médiatisé, vous surestimez le risque de l'avion. Quel biais ?",
             "a": ["Représentativité", "Disponibilité", "Négativité", "Halo"], "correct": 1,
             "explain": "La facilité avec laquelle un exemple vient à l'esprit est confondue avec sa fréquence réelle."},
            {"q": "Une personne séduisante vous paraît aussi plus compétente. Quel biais ?",
             "a": ["Halo", "Contraste", "Primauté", "Autorité"], "correct": 0,
             "explain": "Une caractéristique saillante colore l'évaluation de toutes les autres qualités."},
            {"q": "Vous étudiez uniquement les habitudes des entrepreneurs à succès. Quel biais ?",
             "a": ["Sélection", "Survivants", "Confirmation", "Optimisme"], "correct": 1,
             "explain": "Ceux qui avaient les mêmes habitudes et ont échoué sont absents de l'échantillon."},
            {"q": "Après dix rouges à la roulette, vous pariez sur le noir « qui doit tomber ». Quel biais ?",
             "a": ["Illusion de contrôle", "Sophisme du joueur", "Ancrage", "Représentativité"], "correct": 1,
             "explain": "Les tirages indépendants n'ont pas de mémoire : la probabilité reste identique."},
            {"q": "Un pilote félicité fait moins bien au vol suivant : l'instructeur conclut que les éloges nuisent. Quel phénomène ?",
             "a": ["Effet Pygmalion", "Régression vers la moyenne", "Effet Golem", "Menace du stéréotype"], "correct": 1,
             "explain": "Après une performance extrême, la suivante est statistiquement plus proche de la moyenne."},
            {"q": "Vous reconnaissez les biais des autres bien mieux que les vôtres. Quel biais ?",
             "a": ["Angle mort", "Faux consensus", "Auto-complaisance", "Dunning-Kruger"], "correct": 0,
             "explain": "Le biais de l'angle mort est particulièrement traître : il protège tous les autres."},
            {"q": "Un horoscope vous décrit avec une précision troublante. Quel effet ?",
             "a": ["Halo", "Barnum", "Placebo", "Ancrage"], "correct": 1,
             "explain": "Les descriptions vagues et flatteuses s'appliquent à presque tout le monde."},
        ],
    },
    {
        "id": "grands-auteurs", "icon": "👤", "color": "rose",
        "title": "Les grandes figures",
        "desc": "Qui a fait quoi ? Associe auteurs et contributions.",
        "difficulty": "Moyen",
        "questions": [
            {"q": "Qui a formulé la zone proximale de développement ?",
             "a": ["Piaget", "Vygotski", "Bruner", "Wallon"], "correct": 1,
             "explain": "Vygotski désigne ainsi l'écart entre ce que l'enfant réussit seul et avec l'aide d'un adulte."},
            {"q": "Qui a créé la thérapie comportementale dialectique ?",
             "a": ["Aaron Beck", "Marsha Linehan", "Albert Ellis", "Jon Kabat-Zinn"], "correct": 1,
             "explain": "La TCD est le premier traitement validé sur les conduites suicidaires répétées du trouble borderline."},
            {"q": "Qui a montré que l'émotion est nécessaire à la décision rationnelle ?",
             "a": ["Paul Ekman", "Antonio Damasio", "Daniel Goleman", "Joseph LeDoux"], "correct": 1,
             "explain": "Ses patients au cortex ventromédian lésé conservaient leur intelligence mais prenaient des décisions catastrophiques."},
            {"q": "Qui a théorisé le sentiment d'efficacité personnelle ?",
             "a": ["Albert Bandura", "Martin Seligman", "Carol Dweck", "Edward Deci"], "correct": 0,
             "explain": "Bandura a également démontré l'apprentissage par observation avec la poupée Bobo."},
            {"q": "Qui a introduit l'objet transitionnel et la mère « suffisamment bonne » ?",
             "a": ["Melanie Klein", "Donald Winnicott", "Anna Freud", "Françoise Dolto"], "correct": 1,
             "explain": "Winnicott, pédiatre, a montré que la défaillance progressive et supportable du parent construit l'autonomie."},
            {"q": "Qui a dénoncé le biais WEIRD de la recherche en psychologie ?",
             "a": ["Geert Hofstede", "Joseph Henrich", "Harry Triandis", "Shinobu Kitayama"], "correct": 1,
             "explain": "Son article de 2010 a déclenché un vaste mouvement de diversification des échantillons."},
            {"q": "Qui a distingué mémoire épisodique et mémoire sémantique ?",
             "a": ["Alan Baddeley", "Endel Tulving", "George Miller", "Brenda Milner"], "correct": 1,
             "explain": "Tulving décrit la mémoire épisodique comme un « voyage mental dans le temps »."},
            {"q": "Qui a fondé la sociologie et étudié les déterminants sociaux du suicide ?",
             "a": ["Gustave Le Bon", "Émile Durkheim", "Gabriel Tarde", "Pierre Janet"], "correct": 1,
             "explain": "Durkheim distingue les suicides égoïste, altruiste, anomique et fataliste."},
            {"q": "Qui a créé la logothérapie après avoir survécu aux camps ?",
             "a": ["Bruno Bettelheim", "Viktor Frankl", "Alfred Adler", "Carl Rogers"], "correct": 1,
             "explain": "Frankl postule que la volonté de sens est la motivation première de l'être humain."},
            {"q": "Qui a décrit la loi de régression de la mémoire ?",
             "a": ["Pierre Janet", "Théodule Ribot", "Jean-Martin Charcot", "Hippolyte Taine"], "correct": 1,
             "explain": "La destruction de la mémoire suit l'ordre inverse de son acquisition : du récent vers l'ancien."},
        ],
    },
    {
        "id": "troubles-reconnaitre", "icon": "🩺", "color": "rose",
        "title": "Comprendre les troubles",
        "desc": "Repères cliniques essentiels — sans valeur diagnostique.",
        "difficulty": "Difficile",
        "questions": [
            {"q": "Quel traitement est la référence pour le TOC ?",
             "a": ["La relaxation", "L'exposition avec prévention de la réponse", "L'hypnose", "La psychanalyse"], "correct": 1,
             "explain": "Affronter le déclencheur sans réaliser le rituel est le cœur du traitement validé."},
            {"q": "Quel trouble présente la mortalité la plus élevée en psychiatrie ?",
             "a": ["La schizophrénie", "L'anorexie mentale", "Le trouble bipolaire", "La dépression"], "correct": 1,
             "explain": "Entre 5 et 10 % de mortalité à long terme, par complications somatiques et par suicide."},
            {"q": "La schizophrénie correspond-elle à un dédoublement de la personnalité ?",
             "a": ["Oui", "Non : c'est un contresens issu de l'étymologie", "Parfois", "Seulement dans les formes sévères"], "correct": 1,
             "explain": "Elle associe hallucinations, idées délirantes et désorganisation ; le trouble dissociatif de l'identité est une entité distincte."},
            {"q": "Quel modèle explique le trouble borderline selon Linehan ?",
             "a": ["Purement génétique", "Biosocial : vulnérabilité émotionnelle et environnement invalidant",
                   "Purement traumatique", "Purement éducatif"], "correct": 1,
             "explain": "La combinaison des deux facteurs, et non l'un ou l'autre isolément, explique le tableau."},
            {"q": "Le TDAH est-il un déficit d'attention au sens strict ?",
             "a": ["Oui, toujours", "Non : c'est un trouble de la régulation de l'attention",
                   "Oui, uniquement chez l'enfant", "Non, c'est un trouble moteur"], "correct": 1,
             "explain": "L'hyperfocus sur une activité intéressante coexiste avec l'impossibilité de se mobiliser sur une tâche ennuyeuse."},
            {"q": "Que faut-il faire avant tout travail psychothérapeutique profond dans l'anorexie ?",
             "a": ["Explorer l'enfance", "Renutrir : la dénutrition produit elle-même des symptômes psychiques",
                   "Prescrire un antidépresseur", "Isoler la personne"], "correct": 1,
             "explain": "Rigidité, obsessions alimentaires et repli sont en partie des conséquences directes de la dénutrition."},
            {"q": "Quel traitement est recommandé en première intention pour l'insomnie chronique ?",
             "a": ["Les benzodiazépines", "La TCC de l'insomnie", "La mélatonine", "Le repos prolongé au lit"], "correct": 1,
             "explain": "La TCC-I est supérieure aux hypnotiques à long terme, et recommandée avant tout médicament."},
            {"q": "Parler du suicide avec une personne en souffrance augmente-t-il le risque ?",
             "a": ["Oui, nettement", "Non : cela soulage le plus souvent et ouvre la discussion",
                   "Seulement chez les adolescents", "Uniquement sans professionnel"], "correct": 1,
             "explain": "C'est l'idée reçue la plus dangereuse en prévention. En France : 3114, 24 h/24."},
            {"q": "Qu'est-ce qui distingue le baby blues de la dépression du post-partum ?",
             "a": ["L'intensité seule", "La durée : le baby blues est transitoire, quelques jours",
                   "Le sexe du bébé", "Le mode d'accouchement"], "correct": 1,
             "explain": "Le baby blues touche 50 à 80 % des accouchées et se résout spontanément ; la dépression dure et nécessite un traitement."},
            {"q": "Le burn-out est-il un diagnostic psychiatrique ?",
             "a": ["Oui, dans le DSM-5", "Non : c'est un phénomène lié au contexte professionnel (CIM-11)",
                   "Oui, depuis 2019", "Seulement en France"], "correct": 1,
             "explain": "Cette distinction est importante : elle renvoie à l'organisation du travail, pas à une fragilité individuelle."},
        ],
    },
    {
        "id": "chronologie-quiz", "icon": "🕰️", "color": "gris",
        "title": "Chronologie de la psychologie",
        "desc": "Situe les grandes dates de la discipline.",
        "difficulty": "Facile",
        "questions": [
            {"q": "En quelle année naît la psychologie scientifique ?",
             "a": ["1859", "1879", "1900", "1913"], "correct": 1,
             "explain": "Wundt fonde le laboratoire de Leipzig en 1879."},
            {"q": "Quel événement marque 1900 en psychologie ?",
             "a": ["La création de l'APA", "L'Interprétation des rêves de Freud", "Le premier test de QI", "La découverte du conditionnement"], "correct": 1,
             "explain": "L'ouvrage fondateur de la psychanalyse paraît à la toute fin de 1899, daté 1900."},
            {"q": "Que se passe-t-il en 1956 ?",
             "a": ["Le manifeste behavioriste", "Le nombre magique sept et le lancement de la révolution cognitive",
                   "La création du DSM-III", "La découverte des neurones miroirs"], "correct": 1,
             "explain": "L'article de Miller est l'un des textes fondateurs des sciences cognitives."},
            {"q": "Qu'apporte le DSM-III en 1980 ?",
             "a": ["Le retrait de l'homosexualité", "Des critères diagnostiques opérationnels et athéoriques",
                   "La reconnaissance du burn-out", "La disparition des troubles anxieux"], "correct": 1,
             "explain": "L'objectif était la fidélité diagnostique : que deux cliniciens posent le même diagnostic."},
            {"q": "Quelle année marque la crise de la réplication ?",
             "a": ["2005", "2010", "2015", "2020"], "correct": 2,
             "explain": "Le Reproducibility Project publie ses résultats en 2015 : 36 % de réplications réussies."},
            {"q": "Quand l'homosexualité a-t-elle été retirée du DSM ?",
             "a": ["1952", "1973", "1990", "2013"], "correct": 1,
             "explain": "L'OMS ne suivra qu'en 1990 pour la CIM."},
            {"q": "Que reconnaît la CIM-11 en 2018 ?",
             "a": ["Le TSPT complexe et le trouble du jeu vidéo", "La dépression saisonnière",
                   "L'hyperphagie boulimique", "Le trouble borderline"], "correct": 0,
             "explain": "Deux entités longtemps débattues y font leur entrée officielle."},
            {"q": "Qui libère les aliénés de leurs chaînes en 1793 ?",
             "a": ["Charcot", "Pinel", "Esquirol", "Janet"], "correct": 1,
             "explain": "Philippe Pinel à Bicêtre : acte fondateur du « traitement moral »."},
        ],
    },
    {
        "id": "examen-final", "icon": "🎓", "color": "vert",
        "title": "Examen final — toutes catégories",
        "desc": "20 questions transversales pour valider l'ensemble du parcours.",
        "difficulty": "Difficile",
        "questions": [
            {"q": "Quelle méthode permet seule d'établir une causalité ?",
             "a": ["L'observation naturaliste", "L'expérimentation randomisée", "L'étude de cas", "L'enquête"], "correct": 1,
             "explain": "Seule la randomisation neutralise les variables confondues."},
            {"q": "Quel est le meilleur prédicteur du résultat d'une psychothérapie ?",
             "a": ["La technique employée", "L'alliance thérapeutique", "La durée du suivi", "Le diplôme du thérapeute"], "correct": 1,
             "explain": "Les écarts entre praticiens d'une même approche dépassent les écarts entre approches."},
            {"q": "Quelle technique d'apprentissage est la plus efficace ?",
             "a": ["Relire ses notes", "Surligner", "Se tester (rappel actif)", "Recopier le cours"], "correct": 2,
             "explain": "Le testing effect est l'un des résultats les plus robustes de la psychologie cognitive."},
            {"q": "Que code réellement la dopamine ?",
             "a": ["Le plaisir", "L'erreur de prédiction de récompense", "La douleur", "La mémoire"], "correct": 1,
             "explain": "Elle signale l'écart entre ce qui était attendu et ce qui survient, ce qui explique le désir sans plaisir de l'addiction."},
            {"q": "Quelle dimension du Big Five prédit le mieux la réussite professionnelle ?",
             "a": ["Extraversion", "Ouverture", "Conscienciosité", "Agréabilité"], "correct": 2,
             "explain": "Elle prédit aussi la santé et la longévité."},
            {"q": "Quelle est la trajectoire la plus fréquente après un événement traumatique ?",
             "a": ["Le TSPT chronique", "La résilience", "La dépression durable", "La dissociation"], "correct": 1,
             "explain": "Environ deux tiers des personnes retrouvent leur fonctionnement antérieur (Bonanno)."},
            {"q": "Quel facteur réduit le plus la stigmatisation des troubles psychiques ?",
             "a": ["Les campagnes d'information", "Le contact direct avec des personnes concernées",
                   "Les explications biologiques", "Les documentaires"], "correct": 1,
             "explain": "Les messages purement biologiques augmentent même la perception de dangerosité."},
            {"q": "Que dit la théorie de l'autodétermination ?",
             "a": ["Les récompenses motivent toujours", "Trois besoins doivent être satisfaits : autonomie, compétence, affiliation",
                   "La motivation est innée", "Seul l'objectif compte"], "correct": 1,
             "explain": "La qualité de la motivation compte plus que sa quantité."},
            {"q": "Quelle est la capacité réelle de la mémoire de travail selon les estimations modernes ?",
             "a": ["7 ± 2 éléments", "Environ 4 unités", "12 éléments", "Illimitée"], "correct": 1,
             "explain": "Cowan a révisé à la baisse l'estimation classique de Miller."},
            {"q": "Qu'est-ce que l'effet de cadrage ?",
             "a": ["L'influence de l'environnement visuel", "La formulation en gains ou en pertes modifie le choix",
                   "L'effet du cadre professionnel", "Un biais de mémoire"], "correct": 1,
             "explain": "« 90 % de survie » et « 10 % de mortalité » ne produisent pas les mêmes décisions."},
            {"q": "Que montre la courbe de l'oubli d'Ebbinghaus ?",
             "a": ["L'oubli est linéaire", "L'oubli est très rapide au début puis se stabilise",
                   "On n'oublie jamais vraiment", "L'oubli dépend de l'âge"], "correct": 1,
             "explain": "Chaque révision espacée aplatit la courbe et prolonge la rétention."},
            {"q": "Quelle condition n'est PAS requise par l'hypothèse du contact d'Allport ?",
             "a": ["Statut égal", "Objectifs communs", "Compétition stimulante", "Soutien institutionnel"], "correct": 2,
             "explain": "C'est au contraire la coopération, et non la compétition, qui est nécessaire."},
            {"q": "Qu'est-ce que la réserve cognitive ?",
             "a": ["Un stock de neurones", "Un capital de connexions retardant l'expression des symptômes",
                   "La mémoire à long terme", "Une zone du cortex frontal"], "correct": 1,
             "explain": "Elle se construit par l'éducation, la complexité du travail et l'activité sociale."},
            {"q": "Quel modèle explique le changement de comportement en santé ?",
             "a": ["PERMA", "COM-B", "PETTLEP", "OCEAN"], "correct": 1,
             "explain": "Capacité, Opportunité et Motivation doivent être réunies simultanément."},
            {"q": "Que signifie le biais WEIRD ?",
             "a": ["Un biais de mesure", "La surreprésentation de populations occidentales atypiques",
                   "Un effet de l'expérimentateur", "Une erreur de traduction"], "correct": 1,
             "explain": "Ces populations représentent environ 12 % de l'humanité et sont atypiques sur de nombreuses tâches."},
            {"q": "Quelle affirmation sur les styles d'apprentissage est correcte ?",
             "a": ["Il faut enseigner selon le style dominant", "L'hypothèse d'appariement a été invalidée",
                   "Ils sont fixés génétiquement", "Ils déterminent la réussite"], "correct": 1,
             "explain": "Varier les modalités bénéficie à tous ; enfermer un élève dans un canal n'apporte rien."},
            {"q": "Quel est le principal facteur de maintien d'une phobie ?",
             "a": ["La génétique", "L'évitement, qui empêche la réévaluation", "L'intelligence", "Le stress au travail"], "correct": 1,
             "explain": "C'est pourquoi l'exposition graduée est le traitement de référence."},
            {"q": "Que mesure l'IRM fonctionnelle ?",
             "a": ["L'activité électrique des neurones", "Le signal BOLD, indirect et retardé",
                   "Le métabolisme du glucose", "Le volume de matière grise"], "correct": 1,
             "explain": "C'est une mesure hémodynamique indirecte, à faible résolution temporelle."},
            {"q": "Quelle affirmation sur le stress est exacte ?",
             "a": ["Tout stress est nocif", "Le stress aigu est adaptatif, c'est la chronicité qui nuit",
                   "Le stress provoque le cancer", "Le stress n'a pas d'effet physiologique"], "correct": 1,
             "explain": "La manière d'interpréter le stress modifie aussi ses effets physiologiques."},
            {"q": "Quelle est la meilleure définition de l'esprit critique ?",
             "a": ["Douter de tout", "Calibrer son doute sur la qualité des preuves",
                   "Refuser l'autorité", "Chercher toujours la contradiction"], "correct": 1,
             "explain": "Le doute généralisé mène au relativisme, et paradoxalement au complotisme."},
        ],
    },
]
