# -*- coding: utf-8 -*-
"""Zone de découverte — images libres, planches d'expériences, projets ouverts.

Les fichiers locaux sont téléchargés depuis Wikimedia Commons (voir
`download_commons.py`). Chaque entrée cite le nom Commons et la licence.
"""

# (fichier local, titre Commons, licence, titre FR, légende, liens internes)
# liens : chemins relatifs à 07-ebook-final/
GALLERIE = [
    ("phrenologie.jpg", "PhrenologyPix.jpg", "Domaine public",
     "Planche de phrénologie",
     "Gall promettait de lire le caractère dans les bosses. Faux de bout en bout — et pourtant l'idée qu'une fonction a une place a survécu.",
     [("categories/27-science-psychologique.html", "Science psychologique"),
      ("references/mythes.html", "Mythes")]),
    ("portrait-broca.jpg", "Paul Broca 2.jpg", "Domaine public",
     "Paul Broca (1824-1880)",
     "En 1861, l'autopsie de Leborgne relie une lésion frontale gauche à la perte de la parole articulée.",
     [("references/experiences.html#broca-tan", "Tan / Broca"),
      ("categories/18-langage.html", "Langage")]),
    ("portrait-wernicke.jpg", "Carl Wernicke.png", "Domaine public",
     "Carl Wernicke (1848-1905)",
     "L'aphasie fluide et vide de sens : l'autre pôle du réseau du langage.",
     [("references/experiences.html#wernicke-aphasie", "Aphasie de Wernicke")]),
    ("phineas-gage.jpg", "Phineas Gage Cased Daguerreotype WilgusPhoto2008-12-19 Unretouched Color.jpg", "CC BY-SA 3.0",
     "Phineas Gage",
     "La barre à mine, le lobe frontal, et une personnalité trop souvent romancée ensuite.",
     [("references/experiences.html#phineas-gage", "Gage"),
      ("references/cas.html", "Cas")]),
    ("homonculus-sensoriel.jpg", "1421 Sensory Homunculus.jpg", "CC BY 3.0",
     "Homoncule sensoriel de Penfield",
     "Le corps selon le cortex : mains et lèvres démesurées, tronc minuscule.",
     [("references/experiences.html#penfield-homoncule", "Penfield"),
      ("categories/08-neurosciences.html", "Neurosciences")]),
    ("aires-brodmann.png", "Brodmann areas 3D.png", "Domaine public",
     "Aires de Brodmann (1909)",
     "52 territoires selon les couches cellulaires — un siècle avant l'IRM, des frontières encore utiles.",
     [("categories/08-neurosciences.html", "Neurosciences")]),
    ("hippocampe.png", "Gray739-emphasizing-hippocampus.png", "Domaine public",
     "Hippocampe (Gray)",
     "Sans lui, plus de souvenirs déclaratifs nouveaux : la leçon de H.M.",
     [("references/experiences.html#patient-hm", "H.M.")]),
    ("corps-calleux.png", "Corpus callosum.png", "CC BY-SA 2.1 jp",
     "Corps calleux",
     "Deux cents millions de fibres. Les sectionner a révélé le split-brain — et nourri un mythe.",
     [("references/experiences.html#split-brain", "Cerveau divisé")]),
    ("cerveau-lobes-fr.svg", "Cerebrum lobes-FR.svg", "CC BY-SA 3.0",
     "Les quatre lobes",
     "Frontal, pariétal, temporal, occipital : une carte utile, jamais une prison.",
     [("categories/08-neurosciences.html", "Lobes")]),
    ("neurone-complet-fr.svg", "Complete neuron cell diagram fr.svg", "Domaine public",
     "Le neurone, légendé",
     "Dendrites, axone, synapse : l'unité que Cajal a imposée contre Golgi.",
     [("categories/08-neurosciences.html", "Neurone")]),
    ("synapse-chimique.jpg", "Chemical synapse schema cropped.jpg", "Domaine public",
     "Synapse chimique",
     "Là où le courant devient molécule — et où agissent presque tous les psychotropes.",
     [("categories/08-neurosciences.html", "Synapse")]),
    ("systeme-limbique.png", "Blausen 0614 LimbicSystem.png", "CC BY 3.0",
     "Système limbique",
     "Amygdale, hippocampe, hypothalamus. Le « cerveau émotionnel séparé » est un mythe : ces structures décident aussi.",
     [("categories/07-emotions.html", "Émotions")]),
    ("golgi-pyramidal.jpg", "GolgiStainedPyramidalCell.jpg", "Domaine public",
     "Cellule pyramidale (coloration de Golgi)",
     "La méthode qui a rendu visibles les arbres neuronaux — et permis les planches de Cajal.",
     [("categories/27-science-psychologique.html", "Science psychologique")]),
    ("cajal-hippocampe.jpg", "CajalHippocampus.jpeg", "Domaine public",
     "Hippocampe dessiné par Cajal",
     "Une planche d'observation plus précise que beaucoup de schémas modernes.",
     [("references/experiences.html#patient-hm", "Mémoire")]),
    ("portrait-cajal.jpg", "Santiago Ramón y Cajal (1852-1934) portrait (restored).jpg", "Domaine public",
     "Santiago Ramón y Cajal",
     "Nobel 1906. La doctrine du neurone, et des milliers de dessins encore enseignés.",
     [("categories/27-science-psychologique.html", "Cajal")]),
    ("portrait-golgi.jpg", "Camillo Golgi.jpg", "Domaine public",
     "Camillo Golgi",
     "Inventeur de la coloration au chrome-argent. Il voyait un réseau continu : l'erreur féconde.",
     [("categories/27-science-psychologique.html", "Golgi")]),
    ("portrait-penfield.jpg", "Wilder Penfield.jpg", "Domaine public",
     "Wilder Penfield",
     "Montréal, patient éveillé, stimulation corticale : la carte du corps et parfois un souvenir.",
     [("references/experiences.html#penfield-homoncule", "Homoncule")]),
    ("portrait-berger.jpg", "Hans Berger 1938.jpg", "Domaine public",
     "Hans Berger",
     "Premier EEG humain. D'abord moqué, puis devenu l'outil quotidien du sommeil et de l'épilepsie.",
     [("references/experiences.html#berger-eeg", "EEG")]),
    ("eeg-1020.jpg", "International 10-20 system for EEG-MCN.png", "CC BY-SA 3.0",
     "Système 10-20 de l'EEG",
     "Où poser les électrodes pour que les laboratoires se parlent. Technique, pas esthétique.",
     [("references/experiences.html#berger-eeg", "Berger")]),
    ("irm-sagittal.jpg", "MRI brain sagittal section.jpg", "CC BY-SA 3.0",
     "IRM sagittale du cerveau",
     "Une coupe réelle, pas un schéma. Corps calleux, cervelet, tronc : tout y est visible.",
     [("categories/08-neurosciences.html", "Imagerie")]),
    ("irm-axial.jpg", "MRI Brain ADC Axial (1).jpg", "CC BY-SA 4.0",
     "IRM axiale",
     "Le regard du radiologue : substance grise, substance blanche, ventricules.",
     [("decouverte.html#techniques", "Techniques")]),
    ("dti-fibres.jpg", "DTI-sagittal-fibers.jpg", "CC BY 3.0",
     "Tractographie (DTI)",
     "Les faisceaux de substance blanche reconstruits par la diffusion de l'eau. Base du connectome.",
     [("decouverte.html#projets", "Projets ouverts")]),
    ("tms-bobine.jpg", "Transcranial magnetic stimulation.jpg", "CC BY-SA 3.0",
     "Stimulation magnétique transcrânienne",
     "Une bobine, un champ, une région perturbée quelques millisecondes. De la causalité, enfin.",
     [("references/experiences.html#tms-pascual", "TMS")]),
    ("vesale-cerveau.jpg", "The entire human brain and cerebellum, by Vesalius. Wellcome L0003677.jpg", "Domaine public",
     "Vésale, De humani corporis fabrica (1543)",
     "Ouvrir un crâne et le dessiner sans les dogmes de Galien. La première planche moderne.",
     [("categories/02-histoire.html", "Histoire")]),
    ("gray-base.jpg", "Gray718.png", "Domaine public",
     "Base du cerveau (Gray)",
     "Planche pédagogique du Gray's Anatomy : nerfs crâniens, tronc, cervelet.",
     [("categories/08-neurosciences.html", "Anatomie")]),
    ("gray-ventricules.jpg", "Gray734.png", "Domaine public",
     "Ventricules (Gray)",
     "Les cavités du liquide cérébrospinal. Longtemps explorées par des techniques aujourd'hui abandonnées.",
     [("decouverte.html#cache", "Cave")]),
    ("leborgne-cerveau.jpg", "Cerveau de Louis Victor Leborgne dit Tantan 1.jpg", "CC BY-SA 4.0",
     "Cerveau de Leborgne",
     "La pièce à conviction de Broca. Une lésion, une syllabe, une science.",
     [("references/experiences.html#broca-tan", "Tan")]),
    ("portrait-charcot.jpg", "Charcot Jean-Martin Gallica Nadar.jpg", "Domaine public",
     "Jean-Martin Charcot",
     "La Salpêtrière : observer pour localiser. Source directe de la neurologie clinique.",
     [("categories/09-psychopathologie.html", "Clinique")]),
    ("portrait-wundt.jpg", "Dora Arnd-Raschid - Portrait Wilhelm Wundt, 1898.png", "Domaine public",
     "Wilhelm Wundt",
     "1879, Leipzig : le premier laboratoire. Mesurer le temps de l'esprit.",
     [("categories/02-histoire.html", "Histoire")]),
    ("portrait-fechner.jpg", "Gustav Fechner.jpg", "Domaine public",
     "Gustav Fechner",
     "La sensation comme logarithme du stimulus. La psychologie quantitative commence ici.",
     [("categories/01-fondamentaux.html", "Méthode")]),
    ("portrait-helmholtz.jpg", "Hermann von Helmholtz.jpg", "Domaine public",
     "Hermann von Helmholtz",
     "La vitesse de l'influx n'est pas infinie. Le temps de réaction devient une donnée.",
     [("categories/27-science-psychologique.html", "Mesure")]),
    ("portrait-pavlov.jpg", "Françoise Foliot - Portrait du professeur Pavlov.jpg", "CC BY-SA 4.0",
     "Ivan Pavlov",
     "La fistule, le métronome, la salive : un réflexe mesuré devient une théorie de l'apprentissage.",
     [("references/experiences.html#chiens-pavlov", "Pavlov")]),
    ("conditionnement-pavlov.svg", "Pavlov's dog conditioning.svg", "CC BY-SA 4.0",
     "Schéma du conditionnement",
     "Stimulus neutre, stimulus inconditionnel, réponse. La planche la plus copiée de la psychologie.",
     [("categories/03-cognitive.html", "Cognitive")]),
    ("courbe-oubli-ebbinghaus.svg", "ForgettingCurve.svg", "Domaine public",
     "Courbe de l'oubli",
     "Ce que l'on perd en vingt-quatre heures, et pourquoi l'espacement bat le bachotage.",
     [("references/experiences.html#ebbinghaus-oubli", "Ebbinghaus"),
      ("apprendre.html", "Apprendre")]),
    ("neurone.svg", "Neuron Hand-tuned.svg", "CC BY-SA 3.0",
     "Structure d'un neurone",
     "Le schéma de cours, à relier aux planches de Cajal : deux langages, un même objet.",
     [("categories/08-neurosciences.html", "Neurone")]),
    ("cerveau-humain.svg", "Brain-diagram-pink-6289600.svg", "CC0",
     "Coupe du cerveau",
     "Une silhouette pour se repérer avant d'ouvrir les vraies IRM.",
     [("categories/08-neurosciences.html", "Cerveau")]),
    ("portrait-darwin.jpg", "Charles Robert Darwin by John Collier.jpg", "Domaine public",
     "Charles Darwin",
     "L'expression des émotions : photographies, questionnaires, continuité avec l'animal.",
     [("references/experiences.html#darwin-emotions-exp", "Darwin"),
      ("categories/07-emotions.html", "Émotions")]),
    ("rorschach-planche-1.jpg", "Normalized Rorschach blot 01.jpg", "Domaine public",
     "Planche I de Rorschach",
     "Un test projectif célèbre, aujourd'hui très critiqué pour sa validité. À voir comme objet historique.",
     [("references/tests.html", "Tests"),
      ("categories/19-psychometrie.html", "Psychométrie")]),
    ("boite-skinner.png", "Skinner box scheme 01.png", "CC BY-SA 3.0",
     "Boîte de Skinner",
     "Le levier, la boulette, le programme de renforcement. Et plus tard, le défilement infini.",
     [("references/experiences.html#boite-skinner", "Skinner")]),
    ("illusion-muller-lyer.svg", "Müller-Lyer illusion.svg", "CC BY-SA 3.0",
     "Illusion de Müller-Lyer",
     "Savoir que les segments sont égaux ne les fait pas voir égaux. La perception n'écoute pas le cours.",
     [("laboratoire.html", "Laboratoire"),
      ("categories/03-cognitive.html", "Cognitive")]),
    ("triangle-kanizsa.svg", "Kanizsa triangle.svg", "CC BY-SA 3.0",
     "Triangle de Kanizsa",
     "Un triangle qui n'existe pas : le cerveau complète. C'est déjà une théorie de la prédiction.",
     [("categories/03-cognitive.html", "Gestalt")]),
    ("vase-rubin.svg", "Cup or faces paradox.svg", "CC BY-SA 3.0",
     "Vase de Rubin",
     "On ne peut pas voir les deux à la fois. Figure et fond : une décision, pas une copie.",
     [("categories/03-cognitive.html", "Perception")]),
    ("cube-necker.svg", "Necker cube.svg", "CC BY-SA 3.0",
     "Cube de Necker",
     "Deux interprétations pour le même encre. La conscience bascule, le dessin ne bouge pas.",
     [("categories/03-cognitive.html", "Ambiguïté")]),
    ("portrait-james.jpg", "William James self-portrait.jpg", "Domaine public",
     "William James",
     "La conscience comme courant. Lire le Précis après avoir vu les planches change le texte.",
     [("references/auteurs.html#james", "James")]),
    ("portrait-pinel.jpg", "Philippe Pinel.jpg", "Domaine public",
     "Philippe Pinel",
     "Délier les aliénés : un geste politique autant que médical, aux racines de la clinique.",
     [("categories/09-psychopathologie.html", "Histoire clinique")]),
    ("cajal-cortex.png", "Cajal cortex drawings.png", "Domaine public",
     "Cortex dessiné par Cajal",
     "Couches, pyramides, arbustes : la planche d'un observateur qui a gagné contre le réseau continu.",
     [("categories/27-science-psychologique.html", "Doctrine du neurone")]),
    ("premier-eeg.png", "1st-eeg.png", "Domaine public",
     "L'un des premiers tracés EEG",
     "Des ondes, enfin visibles. Berger a ouvert une fenêtre temporelle que l'IRM n'égalera jamais.",
     [("references/experiences.html#berger-eeg", "Berger")]),
    ("broca-wernicke.jpg", "1605 Brocas and Wernickes Areas-02.jpg", "CC BY 4.0",
     "Aires de Broca et de Wernicke",
     "Deux pôles, un réseau. À relier aux aphasies et à la fiche Langage.",
     [("references/experiences.html#broca-tan", "Broca"),
      ("categories/18-langage.html", "Langage")]),
    ("eeg-enregistrement.jpg", "EEG recording.jpg", "CC BY-SA 4.0",
     "Enregistrement EEG",
     "Le scalp, les électrodes, le tracé. Technique quotidienne, pas lecture de pensées.",
     [("references/experiences.html#berger-eeg", "EEG")]),
]

# Planches visuelles d'expériences : (id, fig, titre, annee, protocole court, resultat, href, image)
PLANCHES_EXPERIENCES = [
    ("broca-tan", "I", "La syllabe de Leborgne", "1861",
     "Un patient ne dit plus que « tan ». Broca attend l'autopsie et ouvre le frontal gauche.",
     "Une lésion localisée, une fonction perdue : la parole articulée a une adresse.",
     "references/experiences.html#broca-tan", "leborgne-cerveau.jpg"),
    ("penfield-homoncule", "II", "Le corps redessiné", "1937-1957",
     "Patient éveillé, cortex exposé, faible courant. On note quel doigt, quelle lèvre bouge ou picote.",
     "L'homoncule : la carte n'est pas à l'échelle du corps, elle est à l'échelle de la précision.",
     "references/experiences.html#penfield-homoncule", "homonculus-sensoriel.jpg"),
    ("berger-eeg", "III", "Le premier tracé", "1924-1929",
     "Berger pose des électrodes sur le scalp de son fils, puis de patients. Il cherche une « énergie psychique ».",
     "Des ondes régulières (alpha) apparaissent, disparaissent à l'ouverture des yeux. L'EEG est né.",
     "references/experiences.html#berger-eeg", "eeg-1020.jpg"),
    ("patient-hm", "IV", "Deux mémoires", "1953-1957",
     "On retire les hippocampes pour une épilepsie. Milner fait dessiner une étoile en miroir, jour après jour.",
     "H.M. s'améliore sans se souvenir d'avoir pratiqué. La mémoire procédurale ne passe pas par l'hippocampe.",
     "references/experiences.html#patient-hm", "hippocampe.png"),
    ("split-brain", "V", "Deux regards", "1960s",
     "Image à gauche ou à droite seulement, après section du corps calleux. On demande de nommer, ou de désigner.",
     "L'hémisphère gauche parle ; le droit agit. Puis le patient invente une raison cohérente.",
     "references/experiences.html#split-brain", "corps-calleux.png"),
    ("hubel-wiesel-colonnes", "VI", "Une barre, un neurone", "1959-1962",
     "Microélectrode dans le cortex visuel d'un chat. On projette des barres d'orientations différentes.",
     "Chaque cellule a une orientation préférée. Le monde visuel est déjà une statistique, pas une photo.",
     "references/experiences.html#hubel-wiesel-colonnes", "irm-sagittal.jpg"),
    ("libet-intention", "VII", "Le doigt en retard", "1983",
     "Le participant note l'heure d'une horloge tournante au moment où il « décide » de fléchir le poignet. L'EEG tourne.",
     "Le potentiel de préparation précède le moment conscient. Le moi n'est pas le premier informé.",
     "references/experiences.html#libet-intention", "eeg-1020.jpg"),
    ("blindsight", "VIII", "Voir sans voir", "1974",
     "Un patient avec lésion occipitale dit ne rien voir dans une partie du champ. On lui demande de deviner, ou de pointer.",
     "Il pointe mieux que le hasard. Une voie visuelle a survécu à la conscience.",
     "references/experiences.html#blindsight", "cerveau-lobes-fr.svg"),
    ("damasio-iowa-gambling", "IX", "Le jeu de Iowa", "1994",
     "Quatre paquets de cartes, gains et pertes cachés. On mesure aussi la conductance de la peau.",
     "Les sujets sains évitent les paquets toxiques avant de pouvoir l'expliquer. Les lésions frontales, non.",
     "references/experiences.html#damasio-iowa-gambling", "systeme-limbique.png"),
    ("rubber-hand", "X", "La main étrangère", "1998",
     "Une main en caoutchouc est caressée en même temps que la main cachée. On demande ensuite où est « ma » main.",
     "Le cerveau adopte le leurre. Le schéma corporel est une hypothèse, pas une donnée.",
     "references/experiences.html#rubber-hand", "homonculus-sensoriel.jpg"),
    ("fritsch-hitzig", "XI", "La patte qui part", "1870",
     "Faible courant sur le cortex d'un chien anesthésié. On observe le mouvement controlatéral.",
     "Le cortex moteur existe. La stimulation électrique devient un instrument, pas une curiosité.",
     "references/experiences.html#fritsch-hitzig", "aires-brodmann.png"),
    ("kandel-aplysia", "XII", "La limace qui apprend", "1960s-2000",
     "On touche le siphon d'une aplysie, on mesure le réflexe de retrait, on répète, on associe un choc.",
     "L'apprentissage change le nombre et la force des synapses. Nobel 2000. La mémoire a une biologie.",
     "references/experiences.html#kandel-aplysia", "synapse-chimique.jpg"),
]

TECHNIQUES = [
    ("EEG", "Électricité du scalp",
     "Résolution temporelle excellente, spatiale faible. Sommeil, épilepsie, P300, N400, MMN.",
     "references/experiences.html#berger-eeg"),
    ("MEG", "Champs magnétiques",
     "Meilleure localisation que l'EEG. Rare, coûteux, complémentaire.",
     "categories/08-neurosciences.html"),
    ("PET", "Traceur radioactif",
     "Métabolisme et récepteurs (dopamine, amyloïde). Plus moléculaire que l'IRMf.",
     "categories/08-neurosciences.html"),
    ("IRMf", "Signal BOLD",
     "Corrélation hémodynamique, délai de 4-6 s. Ne photographie pas une pensée.",
     "categories/08-neurosciences.html"),
    ("DTI", "Diffusion de l'eau",
     "Faisceaux de substance blanche. Cartographie du connectome structurel.",
     "decouverte.html#projets"),
    ("TMS", "Impulsion magnétique",
     "Perturbe ou facilite une région. Valeur causale, usage clinique encadré.",
     "references/experiences.html#tms-pascual"),
    ("tDCS", "Courant faible",
     "Facilitation diffuse, effets modestes. Beaucoup de marketing, peu de miracles.",
     "categories/27-science-psychologique.html"),
    ("DBS", "Électrodes implantées",
     "Parkinson, quelques indications. Travaux fondateurs de Benabid à Grenoble.",
     "references/experiences.html#dbs-benabid"),
    ("Cellule unique", "Microélectrode",
     "Hubel & Wiesel, cellules de lieu, cellules de grille. La résolution ultime, sur l'animal surtout.",
     "references/experiences.html#hubel-wiesel-colonnes"),
    ("Optogénétique", "Lumière + opsines",
     "Allumer une population précise chez l'animal. Pas un casque de salon.",
     "references/experiences.html#optogenetique"),
    ("Wada", "Anesthésie d'un hémisphère",
     "Savoir où habite le langage avant une chirurgie. Un test brutal et précieux.",
     "references/experiences.html#wada-test"),
    ("Lésion / neuropsycho.", "Dissociation",
     "Quand A survit et B disparaît, A et B ne sont pas le même système. Gage, H.M., Tan.",
     "references/cas.html"),
]

PROJETS = [
    ("Human Connectome Project",
     "https://www.humanconnectome.org",
     "Carte structurelle et fonctionnelle de cerveaux sains (≈ 1 200 jeunes adultes, puis lifespan). IRM 3T/7T, MEG, comportement. Logiciel libre Connectome Workbench.",
     "Van Essen, Ugurbil — NIH Blueprint"),
    ("OpenNeuro",
     "https://openneuro.org",
     "Entrepôt public de jeux de données IRM, EEG, MEG, PET, au format BIDS. On peut ouvrir, télécharger, réanalyser.",
     "Poldrack et al."),
    ("Allen Brain Map",
     "https://portal.brain-map.org",
     "Atlas d'expression génique, types cellulaires, cerveau humain et souris. Données et visualiseurs ouverts.",
     "Allen Institute for Brain Science"),
    ("BigBrain / EBRAINS",
     "https://bigbrainproject.org",
     "Un cerveau post-mortem coupé à 20 µm, un téraoctet, cartes cytoarchitectoniques. Licence ouverte. Viewer siibra.",
     "Amunts, Evans — Science 2013"),
    ("Julich Brain Atlas",
     "https://julich-brain-atlas.de",
     "Atlas probabiliste 3D des aires corticales, plus de territoires que Brodmann, branché sur EBRAINS.",
     "Amunts 2020, Science"),
    ("NeuroVault",
     "https://neurovault.org",
     "Cartes statistiques non seuillées d'IRM et de TEP, visualisables, citables, réutilisables pour méta-analyses.",
     "Gorgolewski et al."),
    ("Neurosynth",
     "https://neurosynth.org",
     "Méta-analyse automatique de milliers d'articles d'IRMf. Taper « amygdala » ou « working memory » et voir le consensus.",
     "Yarkoni et al."),
    ("EBRAINS",
     "https://www.ebrains.eu",
     "Infrastructure européenne héritée du Human Brain Project : atlas, modèles, données, outils d'analyse.",
     "Human Brain Project → EBRAINS"),
    ("BALSA / ConnectomeDB",
     "https://balsa.wustl.edu",
     "Visualisations et données du HCP déjà prétraitées. Pour explorer sans reconstruire toute la chaîne.",
     "Washington University"),
    ("The Brain Initiative (NIH)",
     "https://braininitiative.nih.gov",
     "Programme américain de technologies pour observer et perturber les circuits. Appels, outils, données associées.",
     "NIH"),
    ("Neuroimaging Tools & Resources",
     "https://www.nitrc.org",
     "Catalogue d'outils libres : FSL, FreeSurfer, SPM communautaires, pipelines de prétraitement.",
     "NITRC"),
    ("Cognitive Atlas",
     "https://www.cognitiveatlas.org",
     "Ontologie des fonctions cognitives, reliée aux tâches et aux cartes. Pour ne plus mélanger les mots.",
     "Poldrack / Bilder"),
]

CACHE = [
    ("La phrénologie comme science",
     "On vendait des bustes, des cabinets, des expertises judiciaires. Il n'y avait aucune corrélation fiable entre une bosse et un trait. Ce qui reste : l'idée de localisation, reprise ensuite par Broca avec une méthode inverse — partir du déficit, pas du crâne.",
     "phrenologie.jpg", "categories/27-science-psychologique.html"),
    ("Les 10 % du cerveau",
     "Aucune mesure de métabolisme, aucune lésion, aucune IRMf ne soutient ce chiffre. Un AVC de quelques millimètres suffit à tout changer. Le mythe vend des livres et des films ; il n'explique rien.",
     "irm-sagittal.jpg", "references/mythes.html"),
    ("Gauche rationnel / droit créatif",
     "Sperry a montré des spécialisations. Les magazines ont conclu à deux personnalités. En cerveau intact, les hémisphères coopèrent en permanence via le corps calleux.",
     "corps-calleux.png", "references/experiences.html#split-brain"),
    ("La lobotomie comme progrès",
     "Des dizaines de milliers de personnes opérées au XXe siècle, souvent sans consentement éclairé. Présentée comme une modernité. C'est une page à connaître, pas un modèle à réhabiliter.",
     "portrait-charcot.jpg", "references/debats.html"),
    ("Gage le monstre",
     "Les récits tardifs ont noirci Gage. Il a travaillé ensuite, s'est en partie réadapté. La leçon sur le frontal reste ; le roman, non.",
     "phineas-gage.jpg", "references/experiences.html#phineas-gage"),
    ("Lashley : « la mémoire est partout »",
     "Après des lésions corticales chez le rat, Lashley conclut à l'équiponentialité. Trop extrême. Vrai : une fonction complexe n'est pas un point. Faux : tout est interchangeable.",
     "aires-brodmann.png", "references/experiences.html#lashley-masse"),
    ("Pneumoencéphalographie",
     "On remplaçait le liquide cérébrospinal par de l'air pour voir les ventricules à la radio. Douloureux, dangereux, abandonné dès l'arrivée du scanner. Une technique réelle, aujourd'hui cachée des manuels grand public.",
     "gray-ventricules.jpg", "decouverte.html#techniques"),
    ("Styles d'apprentissage",
     "Se dire « visuel » ou « auditif » ne prédit pas la meilleure méthode. Le double codage aide tout le monde. Le test préalable et l'espacement aussi.",
     "courbe-oubli-ebbinghaus.svg", "apprendre.html"),
]

SOURCES = [
    ("Human Connectome Project", "https://www.humanconnectome.org",
     "Données, publications et logiciel de visualisation du connectome humain."),
    ("OpenNeuro", "https://openneuro.org",
     "Jeux de données BIDS publics (IRM, EEG, MEG, PET)."),
    ("Allen Brain Map", "https://portal.brain-map.org",
     "Atlas cellulaires et d'expression génique."),
    ("BigBrain", "https://bigbrainproject.org",
     "Volume histologique 20 µm, Amunts et al., Science 2013."),
    ("EBRAINS", "https://www.ebrains.eu",
     "Atlas de Jülich, outils et données européennes."),
    ("NeuroVault", "https://neurovault.org",
     "Cartes statistiques d'imagerie partageables."),
    ("Neurosynth", "https://neurosynth.org",
     "Méta-analyses automatiques d'IRMf."),
    ("Wikimedia Commons", "https://commons.wikimedia.org",
     "Toutes les images de cette page : domaine public, CC0, CC BY ou CC BY-SA."),
    ("Gallica — BnF", "https://gallica.bnf.fr",
     "Charcot, fonds patrimonial de neurologie et de psychologie."),
    ("Internet Archive", "https://archive.org",
     "Ouvrages du domaine public lus dans le lecteur du site."),
    ("PubMed / PMC", "https://pubmed.ncbi.nlm.nih.gov",
     "Pour vérifier un résultat d'imagerie ou une réplication."),
    ("Stanford Encyclopedia of Philosophy — Neuroscience",
     "https://plato.stanford.edu/entries/neuroscience/",
     "Synthèses philosophiques sourcées sur l'esprit et le cerveau."),
]
