# -*- coding: utf-8 -*-
"""Quiz du lycée à la L1 et socle des quatre branches."""

QUIZZES_LYCEE = [
    {
        "id": "lycee-orientation", "icon": "🎓", "color": "or",
        "title": "Du lycée à la L1",
        "desc": "Spécialités du bac, licence, titre de psychologue.",
        "difficulty": "Facile",
        "questions": [
            {"q": "Où s'adresser au lycée pour l'orientation vers la psychologie ?",
             "a": ["Uniquement le proviseur", "Le CIO et les psychologues de l'Éducation nationale", "Uniquement Parcoursup le jour J", "Un forum en ligne"], "correct": 1,
             "explain": "Les PsyEN du CIO accompagnent les élèves et les familles tout au long de l'année."},
            {"q": "La psychologie est-elle une spécialité du bac ?",
             "a": ["Oui, depuis 2021", "Oui, en option facultative", "Non : on prépare la L1 via SES, HLP, SVT, maths, philo…", "Uniquement en STI2D"], "correct": 2,
             "explain": "Aucune spécialité « psychologie » n'existe au bac. On construit le socle avec SES, HLP, SVT, maths, philo et le Grand oral."},
            {"q": "Quelle combinaison est cohérente pour viser une L1 de psychologie ?",
             "a": ["Uniquement NSI + SI", "SES + HLP, ou SES + SVT, ou maths + SVT", "Uniquement théâtre + LCA", "Abandonner toutes les sciences"], "correct": 1,
             "explain": "Parcoursup n'exige pas une doublette unique, mais les stats et la biologie de L1 punissent l'absence de raisonnement scientifique."},
            {"q": "À quoi sert un CIO ?",
             "a": ["Uniquement à noter les élèves", "À informer et conseiller sur l'orientation, avec des PsyEN", "À remplacer la licence", "À diagnostiquer"], "correct": 1,
             "explain": "Le CIO accueille élèves et familles ; les psychologues de l'Éducation nationale interviennent aussi dans les établissements."},
            {"q": "La L1 de psychologie contient surtout…",
             "a": ["Uniquement des stages cliniques", "Clinique, sociale, développement, cognitive, plus méthodes, stats et psychobiologie", "Uniquement de la psychanalyse", "Un titre de psychologue au bout d'un an"], "correct": 1,
             "explain": "C'est un socle général. Beaucoup abandonnent en découvrant statistiques et biologie."},
            {"q": "Quand obtient-on le titre de psychologue en France ?",
             "a": ["Après le bac", "Après la licence", "Après un master de psychologie avec stage et mémoire", "Après un week-end de formation"], "correct": 2,
             "explain": "Le titre est protégé (loi de 1985). La licence seule n'autorise pas l'exercice."},
            {"q": "Pourquoi les mathématiques restent-elles utiles sans être « la » spécialité obligatoire ?",
             "a": ["Pour calculer le loyer à Lyon", "Parce que la L1 exige des statistiques descriptives puis inférentielles", "Elles ne servent à rien en psycho", "Uniquement pour le QI"], "correct": 1,
             "explain": "Moyenne, écart-type, corrélation, puis tests : c'est le premier choc de septembre."},
            {"q": "Un Grand oral « psychologie » réussi consiste à…",
             "a": ["Raconter sa vie", "Présenter une étude (protocole, résultat, limite) et tenir l'échange", "Diagnostiquer le jury", "Réciter Freud sans source"], "correct": 1,
             "explain": "Le jury évalue la clarté, les sources et la capacité à répondre — exactement le geste de L1."},
        ],
    },
    {
        "id": "clinique-l1", "icon": "🩺", "color": "rose",
        "title": "Clinique — niveau lycée / L1",
        "desc": "Cadre, modèles, titres, éthique : sans aucun diagnostic.",
        "difficulty": "Moyen",
        "questions": [
            {"q": "La psychologie clinique étudie principalement…",
             "a": ["Les scores de QI en entreprise", "La souffrance et les ressources d'une personne concrète", "Les marchés financiers", "Les réflexes du chien de Pavlov uniquement"], "correct": 1,
             "explain": "L'unité d'analyse est le sujet dans son histoire et son contexte, pas une moyenne de groupe."},
            {"q": "Quelle différence est exacte ?",
             "a": ["Psychologue et psychiatre, c'est le même métier", "Le psychiatre est médecin et peut prescrire ; le psychologue a un bac+5 de psychologie", "Le coach a le même titre protégé", "Le PsyEN n'est pas psychologue"], "correct": 1,
             "explain": "Titres distincts, formations distinctes. Le PsyEN est psychologue de l'Éducation nationale, recruté sur concours."},
            {"q": "L'alliance thérapeutique, c'est…",
             "a": ["Devenir ami sur les réseaux", "L'accord sur les buts, les tâches et le lien de confiance", "Un médicament", "Un test projectif"], "correct": 1,
             "explain": "C'est le prédicteur le plus robuste du changement, toutes approches confondues."},
            {"q": "Quel geste est éthique pour un lycéen face à un camarade en détresse ?",
             "a": ["Lui coller une étiquette de trouble", "Écouter, ne pas rester seul, orienter vers un adulte et les numéros d'aide", "Publier son histoire", "Improviser une « thérapie » de cour de récré"], "correct": 1,
             "explain": "Écouter n'est pas soigner. 3114, 15, infirmière, PsyEN, CMP : voilà l'orientation juste."},
            {"q": "Parmi ces approches, laquelle insiste sur les pensées automatiques ?",
             "a": ["La thérapie systémique", "La thérapie cognitive de Beck", "La phrénologie", "Le structuralisme de Wundt"], "correct": 1,
             "explain": "Beck décrit pensées automatiques, distorsions et schémas — base des TCC."},
            {"q": "Un questionnaire de site a-t-il une valeur diagnostique ?",
             "a": ["Oui s'il a plus de 20 items", "Non : le diagnostic appartient à un professionnel dans un cadre", "Oui s'il est partagé sur Discord", "Oui pour le TDAH uniquement"], "correct": 1,
             "explain": "Psyclopédia le répète : pédagogie seulement. S'étiqueter via un quiz est une erreur."},
            {"q": "Le secret professionnel sert à…",
             "a": ["Protéger l'institution d'un scandale", "Rendre possible une parole sans qu'elle circule", "Cacher les notes aux parents dans tous les cas", "Remplacer la loi"], "correct": 1,
             "explain": "Sans confidentialité, pas de cadre clinique. Des exceptions légales existent (danger grave)."},
            {"q": "Que montrent surtout les « facteurs communs » ?",
             "a": ["Que seule la psychanalyse marche", "Que la technique explique une part limitée du résultat", "Que les médicaments sont inutiles", "Que le diagnostic suffit à guérir"], "correct": 1,
             "explain": "Alliance, espoir, engagement du patient pèsent souvent autant que l'école affichée."},
        ],
    },
    {
        "id": "branches-l1", "icon": "🧭", "color": "vert",
        "title": "Quatre branches — savoir les distinguer",
        "desc": "Clinique, sociale, développement, cognitive : objets et méthodes.",
        "difficulty": "Moyen",
        "questions": [
            {"q": "Quelle branche pose surtout la question « comment le groupe oriente-t-il mon acte ? »",
             "a": ["Clinique", "Sociale", "Développement", "Cognitive"], "correct": 1,
             "explain": "La sociale relie individu et situation sociale : normes, influence, identités."},
            {"q": "Stroop, empan et temps de réaction sont des outils typiques de la…",
             "a": ["Clinique uniquement", "Psychologie cognitive", "Sociologie", "Psychanalyse"], "correct": 1,
             "explain": "On y mesure erreurs et latences pour inférer des processus (attention, interférence)."},
            {"q": "Piaget, Vygotski et Bowlby appartiennent d'abord à la…",
             "a": ["Psychologie du développement", "Psychologie du travail", "Psychométrie des adultes", "Neuroscience des réseaux"], "correct": 0,
             "explain": "Stades, ZPD, attachement : trio incontournable du développement."},
            {"q": "L'entretien clinique se distingue de l'expérience sociale parce qu'il…",
             "a": ["Manipule toujours une variable indépendante", "Cherche à comprendre un sujet singulier dans un cadre", "Produit forcément un graphique", "Interdit toute hypothèse"], "correct": 1,
             "explain": "La clinique priorise le cas ; la sociale priorise souvent l'effet moyen d'une manipulation."},
            {"q": "Une étude qui compare des 8 ans, des 14 ans et des 20 ans le même jour est…",
             "a": ["Longitudinale", "Transversale", "Un essai randomisé", "Une méta-analyse"], "correct": 1,
             "explain": "Transversale : économique, mais elle mélange âge et génération (cohorte)."},
            {"q": "« 65 % chez Milgram » illustre d'abord…",
             "a": ["Un trouble de la personnalité", "L'obéissance à une autorité dans un dispositif donné", "La mémoire de travail", "L'attachement désorganisé"], "correct": 1,
             "explain": "Le chiffre dépend du protocole ; il ne diagnostique personne."},
            {"q": "La zone proximale de développement, c'est…",
             "a": ["La distance à l'école", "L'écart entre seul et avec étayage", "Un stade piagétien de plus", "Une aire cérébrale"], "correct": 1,
             "explain": "Vygotski : ce qui est possible aujourd'hui avec une aide le sera seul demain."},
            {"q": "Loftus a montré que la mémoire…",
             "a": ["Est une vidéo fidèle", "Peut être altérée par une information reçue après les faits", "Disparaît après 20 ans", "Ne concerne que les enfants"], "correct": 1,
             "explain": "Mémoire reconstructive et suggestible — pont cognitif vers le droit et les témoins."},
        ],
    },
]
