# -*- coding: utf-8 -*-
"""Répertoire clinique des troubles psychiques (vulgarisation, sans valeur diagnostique)."""

# (id, nom, famille, prevalence, signes, comprendre, traitements)
TROUBLES = [
    ("depression", "Épisode dépressif caractérisé", "Troubles de l'humeur", "≈ 5 % des adultes sur un an",
     ["Humeur triste la majeure partie de la journée, presque tous les jours",
      "Perte d'intérêt ou de plaisir (anhédonie)",
      "Troubles du sommeil et de l'appétit, fatigue intense",
      "Sentiment de culpabilité ou de dévalorisation, ralentissement",
      "Pensées de mort ou idées suicidaires"],
     "Le diagnostic demande au moins cinq symptômes présents pendant au moins deux semaines, avec un retentissement net sur le fonctionnement. Ce n'est ni une faiblesse de caractère ni une tristesse ordinaire : on observe des modifications du fonctionnement des circuits fronto-limbiques, de l'axe du stress et du sommeil. Les modèles actuels combinent vulnérabilité biologique, événements de vie et schémas cognitifs négatifs (triade de Beck).",
     "TCC et thérapie interpersonnelle en première intention pour les formes légères à modérées ; antidépresseurs (ISRS) pour les formes modérées à sévères, souvent en association ; activation comportementale, activité physique régulière, régularisation du sommeil ; MBCT pour prévenir les rechutes ; stimulation magnétique transcrânienne ou électroconvulsivothérapie dans les formes résistantes."),

    ("bipolaire", "Trouble bipolaire", "Troubles de l'humeur", "≈ 1 à 2 % de la population",
     ["Épisodes maniaques ou hypomaniaques : euphorie ou irritabilité, énergie débordante",
      "Diminution du besoin de sommeil sans fatigue",
      "Accélération de la pensée, logorrhée, distractibilité",
      "Conduites à risque (dépenses, sexualité, projets démesurés)",
      "Alternance avec des épisodes dépressifs souvent plus longs"],
     "On distingue le type I (au moins un épisode maniaque franc) du type II (hypomanie et dépressions récurrentes). Le délai moyen entre les premiers symptômes et le diagnostic dépasse souvent plusieurs années, car c'est la phase dépressive qui amène à consulter. L'héritabilité est l'une des plus élevées en psychiatrie.",
     "Thymorégulateurs (lithium, valproate, lamotrigine) au long cours ; psychoéducation du patient et de l'entourage, très efficace sur les rechutes ; régularité des rythmes veille-sommeil (thérapie des rythmes sociaux) ; repérage précoce des signes annonciateurs par un plan de crise écrit."),

    ("tag", "Trouble anxieux généralisé", "Troubles anxieux", "≈ 3 à 6 % sur la vie entière",
     ["Inquiétude excessive et difficile à contrôler, la plupart du temps, depuis 6 mois au moins",
      "Tension musculaire, agitation, fatigue",
      "Difficultés de concentration, irritabilité",
      "Troubles du sommeil, en particulier à l'endormissement",
      "Anticipation catastrophique sur de multiples domaines"],
     "L'inquiétude fonctionne comme un évitement mental : ruminer sur l'avenir donne l'illusion de contrôler, tout en empêchant le traitement émotionnel réel. Les personnes concernées ont souvent des « métacroyances » positives sur leur inquiétude (« m'inquiéter me prépare ») qui la maintiennent.",
     "TCC avec travail sur l'intolérance à l'incertitude et exposition aux scénarios redoutés ; thérapie métacognitive ; relaxation appliquée et cohérence cardiaque ; ISRS/IRSNA si le retentissement est important ; limitation de la caféine et régularisation du sommeil."),

    ("panique", "Trouble panique", "Troubles anxieux", "≈ 2 à 3 % sur un an",
     ["Attaques de panique brutales : palpitations, souffle court, vertiges, sueurs",
      "Sensation de mort imminente ou de devenir fou",
      "Peur persistante d'une nouvelle attaque (anxiété anticipatoire)",
      "Évitement progressif des lieux associés",
      "Consultations répétées aux urgences"],
     "L'attaque de panique est une réaction d'alarme physiologique normale déclenchée à tort. Le cercle vicieux vient de l'interprétation catastrophique des sensations corporelles : une palpitation est lue comme un infarctus, ce qui augmente l'angoisse, donc les sensations. Comprendre ce mécanisme est déjà thérapeutique.",
     "TCC avec exposition intéroceptive (reproduire volontairement les sensations : hyperventilation contrôlée, tourner sur soi) ; restructuration des interprétations catastrophiques ; exposition graduée aux situations évitées ; ISRS si nécessaire. C'est l'un des troubles où la TCC obtient les meilleurs résultats."),

    ("phobie-sociale", "Anxiété sociale", "Troubles anxieux", "≈ 7 à 12 % sur la vie entière",
     ["Peur intense du jugement d'autrui dans les situations sociales ou de performance",
      "Crainte de rougir, trembler, transpirer, avoir « l'esprit vide »",
      "Évitement ou endurance au prix d'une souffrance majeure",
      "Auto-observation intense pendant l'interaction",
      "Rumination post-événement (« autopsie sociale »)"],
     "La personne se voit comme un objet exposé au regard d'autrui et détourne ses ressources attentionnelles vers elle-même, ce qui dégrade réellement sa performance sociale et confirme sa crainte. Le trouble débute souvent à l'adolescence et reste longtemps non traité.",
     "TCC en groupe, particulièrement adaptée ; exposition progressive avec abandon des comportements de sécurité ; entraînement à l'attention externe ; jeux de rôle et vidéo-feedback (voir qu'on paraît moins anxieux qu'on ne le ressent) ; ISRS dans les formes sévères."),

    ("phobie-specifique", "Phobie spécifique", "Troubles anxieux", "≈ 7 à 9 % sur un an",
     ["Peur intense et disproportionnée d'un objet ou d'une situation précise",
      "Réaction immédiate d'anxiété à l'exposition",
      "Évitement actif ou endurance avec détresse",
      "Reconnaissance du caractère excessif de la peur",
      "Retentissement sur les activités quotidiennes"],
     "Les phobies se classent en types : animal, environnement naturel, sang-injection (avec réaction vagale et risque de malaise), situationnel (avion, ascenseur). Elles peuvent naître d'un conditionnement, d'un apprentissage vicariant ou d'une transmission d'information, et se maintiennent par l'évitement qui empêche toute réévaluation.",
     "Exposition graduée, in vivo ou en réalité virtuelle : c'est le traitement de référence, avec 80 à 90 % d'amélioration, parfois en une seule séance prolongée ; technique de tension appliquée pour la phobie du sang ; l'EMDR est parfois utilisée lorsqu'un traumatisme initial est identifié."),

    ("toc", "Trouble obsessionnel-compulsif", "TOC et apparentés", "≈ 2 % de la population",
     ["Obsessions : pensées, images ou impulsions intrusives et angoissantes",
      "Compulsions : rituels mentaux ou comportementaux pour neutraliser l'angoisse",
      "Perte de temps considérable (souvent plus d'une heure par jour)",
      "Conscience, au moins partielle, du caractère excessif",
      "Thèmes fréquents : contamination, vérification, symétrie, pensées agressives ou sexuelles taboues"],
     "Presque tout le monde a des pensées intrusives bizarres ; ce qui fait le TOC, c'est l'interprétation qu'on en donne (« penser cela signifie que je pourrais le faire ») et le rituel qui soulage à court terme mais renforce le cycle à long terme. Les circuits cortico-striato-thalamo-corticaux sont impliqués.",
     "Exposition avec prévention de la réponse (EPR) : affronter le déclencheur sans réaliser le rituel — traitement de référence ; thérapie cognitive sur la fusion pensée-action et la responsabilité excessive ; ISRS à posologie élevée ; stimulation cérébrale profonde dans des cas résistants exceptionnels."),

    ("tspt", "Trouble de stress post-traumatique", "Troubles liés au trauma", "≈ 4 à 8 % sur la vie entière",
     ["Reviviscences : flashbacks, cauchemars, intrusions sensorielles",
      "Évitement des rappels du traumatisme",
      "Altérations négatives des cognitions et de l'humeur",
      "Hypervigilance, sursauts, troubles du sommeil et de la concentration",
      "Symptômes présents plus d'un mois après l'événement"],
     "Le souvenir traumatique est mal intégré : stocké sous forme sensorielle brute, il n'est pas situé dans le passé, si bien qu'il se rejoue au présent. On observe une hyperactivité de l'amygdale et un contrôle préfrontal insuffisant. Tous les exposés ne développent pas un TSPT : le soutien social post-événement est un facteur protecteur majeur.",
     "TCC centrée sur le trauma avec exposition prolongée ; EMDR (recommandée par l'OMS) ; thérapie du traitement cognitif ; ISRS en appoint ; le débriefing psychologique immédiat systématique est déconseillé, car potentiellement délétère."),

    ("tspt-complexe", "TSPT complexe", "Troubles liés au trauma", "Reconnu par la CIM-11 (2018)",
     ["Tous les symptômes du TSPT",
      "Dysrégulation émotionnelle sévère et durable",
      "Croyances négatives persistantes sur soi (honte, culpabilité, sentiment d'être abîmé)",
      "Difficultés majeures et durables dans les relations",
      "Souvent : dissociation, somatisations"],
     "Il fait suite à des traumatismes répétés, prolongés et sous emprise, souvent dans l'enfance (maltraitance, inceste) ou dans un contexte de captivité ou de violences conjugales. La personnalité s'est construite autour de la survie, ce qui rend le tableau plus global qu'un TSPT simple.",
     "Traitement séquencé en trois phases : stabilisation et compétences de régulation, puis travail sur les souvenirs traumatiques, puis réintégration relationnelle ; TCD, thérapie des schémas, ICV, EMDR adaptée ; la durée est plus longue et l'alliance thérapeutique est le facteur pronostique principal."),

    ("schizophrenie", "Schizophrénie", "Troubles psychotiques", "≈ 0,7 % de la population mondiale",
     ["Symptômes positifs : hallucinations (souvent auditives), idées délirantes",
      "Symptômes négatifs : retrait, émoussement affectif, perte d'initiative",
      "Désorganisation de la pensée et du discours",
      "Troubles cognitifs (attention, mémoire de travail, fonctions exécutives)",
      "Début typique entre 15 et 30 ans"],
     "Ce n'est pas un « dédoublement de la personnalité » : ce contresens vient de l'étymologie. Le modèle dominant est celui de la vulnérabilité-stress : une vulnérabilité neurodéveloppementale rencontre des facteurs environnementaux (cannabis précoce, migration, traumatismes, urbanicité). Le pronostic est très variable : une part importante des personnes connaît une rémission durable.",
     "Antipsychotiques (traitement de fond indispensable) ; remédiation cognitive ; TCC des hallucinations et des idées délirantes ; psychoéducation familiale, qui réduit fortement les rechutes ; réhabilitation psychosociale et soutien à l'emploi ; intervention précoce dès le premier épisode, déterminante pour le pronostic."),

    ("tdah", "TDAH", "Troubles neurodéveloppementaux", "≈ 5 % des enfants, 2,5 % des adultes",
     ["Inattention : distractibilité, oublis, difficulté à finir les tâches",
      "Hyperactivité : agitation motrice, difficulté à rester assis",
      "Impulsivité : interruptions, réponses précipitées, décisions rapides",
      "Symptômes présents avant 12 ans et dans au moins deux contextes",
      "Chez l'adulte : procrastination, désorganisation, instabilité professionnelle"],
     "Le trouble concerne moins l'attention elle-même que sa régulation : une personne avec TDAH peut être hyperconcentrée sur ce qui l'intéresse (hyperfocus) et incapable de se mobiliser sur une tâche ennuyeuse. Les circuits dopaminergiques préfrontaux et le contrôle exécutif sont impliqués. L'héritabilité est estimée autour de 75 %.",
     "Psychostimulants (méthylphénidate) efficaces chez environ 70 % des patients ; TCC adaptée aux fonctions exécutives ; aménagements scolaires et professionnels (temps majoré, environnement épuré, consignes écrites) ; guidance parentale ; structuration externe (agendas, minuteurs, découpage des tâches)."),

    ("tsa", "Trouble du spectre de l'autisme", "Troubles neurodéveloppementaux", "≈ 1 % de la population",
     ["Particularités de la communication et des interactions sociales réciproques",
      "Intérêts restreints et intenses, routines, ritualisation",
      "Particularités sensorielles (hyper- ou hyposensibilité)",
      "Manifestations présentes dès la petite enfance",
      "Grande hétérogénéité, avec ou sans déficience intellectuelle ou trouble du langage"],
     "La notion de spectre remplace les anciennes catégories (dont le syndrome d'Asperger). Le modèle du « double problème d'empathie » suggère que l'incompréhension est réciproque entre personnes autistes et non autistes, plutôt qu'un déficit unilatéral. Le sous-diagnostic des filles et des femmes, qui masquent souvent leurs difficultés (camouflage), est massif.",
     "Interventions développementales précoces et structurées ; orthophonie, psychomotricité, ergothérapie ; aménagements sensoriels et environnementaux ; soutien à l'autodétermination plutôt que normalisation à tout prix ; accompagnement des comorbidités fréquentes (anxiété, TDAH, épilepsie)."),

    ("dys", "Troubles spécifiques des apprentissages", "Troubles neurodéveloppementaux", "≈ 5 à 8 % des enfants",
     ["Dyslexie : déchiffrage lent et coûteux, confusions de lettres",
      "Dysorthographie : orthographe durablement déficitaire",
      "Dyscalculie : difficulté avec le sens du nombre et le calcul",
      "Dysgraphie : écriture lente, illisible, douloureuse",
      "Dyspraxie / TDC : maladresse, difficulté de coordination motrice"],
     "Ces troubles sont durables, spécifiques et sans lien avec l'intelligence globale ni avec un défaut d'enseignement. La dyslexie s'explique principalement par un déficit de traitement phonologique. Le diagnostic repose sur un bilan pluridisciplinaire comparant les performances aux normes d'âge.",
     "Rééducation spécialisée (orthophonie, ergothérapie, orthoptie selon le cas) ; outils de compensation numériques (synthèse vocale, correcteurs, ordinateur) ; aménagements scolaires et aux examens (PAP, PPS, tiers-temps) ; soutien de l'estime de soi, souvent très touchée."),

    ("anorexie", "Anorexie mentale", "Troubles des conduites alimentaires", "≈ 0,9 % des femmes, 0,3 % des hommes",
     ["Restriction alimentaire conduisant à un poids significativement bas",
      "Peur intense de prendre du poids malgré la maigreur",
      "Altération de la perception de son corps",
      "Aménorrhée fréquente, hypothermie, bradycardie",
      "Hyperactivité physique, contrôle rigide, déni de la gravité"],
     "L'anorexie mentale présente la mortalité la plus élevée de tous les troubles psychiatriques (5 à 10 % à long terme). La dénutrition produit elle-même des symptômes psychologiques (rigidité, obsessions alimentaires, repli), ce qui rend la renutrition indispensable avant tout travail psychothérapeutique profond.",
     "Prise en charge pluridisciplinaire (médecin, diététicien, psychologue) ; thérapie familiale de type Maudsley, traitement de référence chez l'adolescent ; TCC-E pour les adultes ; hospitalisation si critères de gravité somatique ; surveillance du syndrome de renutrition inappropriée."),

    ("boulimie", "Boulimie nerveuse", "Troubles des conduites alimentaires", "≈ 1 à 1,5 % de la population",
     ["Crises de consommation massive avec sentiment de perte de contrôle",
      "Comportements compensatoires (vomissements, laxatifs, jeûne, sport excessif)",
      "Poids souvent normal, d'où un trouble longtemps invisible",
      "Honte, secret, estime de soi centrée sur le poids et la silhouette",
      "Complications : érosion dentaire, troubles ioniques, œsophagite"],
     "Le cycle restriction → crise → compensation → culpabilité → restriction est auto-entretenu : c'est la restriction elle-même qui prépare la crise suivante, sur un plan physiologique autant que psychologique. Le trouble reste souvent caché pendant des années.",
     "TCC-E (protocole de Fairburn), traitement de référence ; régularisation alimentaire structurée (trois repas et deux collations) avant tout travail cognitif ; thérapie interpersonnelle ; fluoxétine à posologie élevée ; groupes de soutien."),

    ("hyperphagie", "Hyperphagie boulimique", "Troubles des conduites alimentaires", "≈ 2 à 3 %, TCA le plus fréquent",
     ["Crises de consommation massive sans comportement compensatoire",
      "Manger très vite, jusqu'à l'inconfort, sans faim physique",
      "Manger seul par honte, détresse marquée après la crise",
      "Souvent associée à un surpoids ou une obésité",
      "Au moins une crise par semaine pendant trois mois"],
     "Longtemps confondu avec un simple manque de volonté, ce trouble a été reconnu comme entité à part entière dans le DSM-5 (2013). Les crises jouent fréquemment un rôle de régulation émotionnelle : elles apaisent momentanément une détresse que la personne ne parvient pas à traiter autrement.",
     "TCC et thérapie comportementale dialectique adaptée ; travail sur la régulation émotionnelle et l'alimentation intuitive ; les régimes restrictifs sont contre-productifs ; lisdexamfétamine dans certains pays ; prise en charge de la souffrance liée à la stigmatisation du poids."),

    ("borderline", "Trouble de la personnalité borderline", "Troubles de la personnalité", "≈ 1,5 % de la population",
     ["Instabilité intense des relations, de l'image de soi et des émotions",
      "Efforts désespérés pour éviter l'abandon réel ou imaginé",
      "Impulsivité potentiellement dommageable (dépenses, substances, sexualité, conduite)",
      "Gestes auto-agressifs ou suicidaires répétés",
      "Sentiment chronique de vide, colères intenses, épisodes dissociatifs"],
     "Le modèle biosociale de Linehan combine une vulnérabilité émotionnelle constitutionnelle (réactions plus rapides, plus intenses, retour au calme plus lent) et un environnement invalidant qui a appris à la personne à ne pas faire confiance à son vécu. Les traumatismes précoces sont très fréquents, sans être systématiques. Le pronostic à long terme est bien meilleur qu'on ne l'a longtemps cru.",
     "Thérapie comportementale dialectique (TCD), traitement le mieux validé ; thérapie basée sur la mentalisation ; thérapie des schémas ; approche centrée sur le transfert ; pas de traitement médicamenteux spécifique, mais traitement des comorbidités ; cadre clair et continuité des soins essentiels."),

    ("narcissique", "Trouble de la personnalité narcissique", "Troubles de la personnalité", "≈ 1 % de la population",
     ["Sentiment grandiose d'importance, besoin d'admiration",
      "Fantasmes de succès, de pouvoir ou de beauté illimités",
      "Sentiment d'avoir droit à un traitement de faveur",
      "Empathie limitée, exploitation des relations",
      "Vulnérabilité extrême à la critique, avec réactions de rage ou d'effondrement"],
     "On distingue une forme grandiose (visible, dominante) et une forme vulnérable (hypersensible, repliée, envieuse), qui coexistent souvent chez la même personne. Derrière la grandiosité se trouve fréquemment une estime de soi instable, entièrement dépendante du regard extérieur. Le terme est massivement galvaudé dans le langage courant : un comportement égocentrique n'est pas un trouble de la personnalité.",
     "Psychothérapie au long cours (thérapie des schémas, approche centrée sur le transfert) ; la demande de soin vient généralement d'une dépression, d'une rupture ou d'un échec professionnel ; l'alliance thérapeutique est fragile et nécessite un travail spécifique sur les ruptures de lien."),

    ("evitante", "Trouble de la personnalité évitante", "Troubles de la personnalité", "≈ 2 % de la population",
     ["Évitement des activités sociales par peur de la critique ou du rejet",
      "Réticence à s'engager sans certitude d'être apprécié",
      "Sentiment d'incompétence et d'infériorité",
      "Retenue dans les relations intimes par peur du ridicule",
      "Désir profond de relations, contrairement à la personnalité schizoïde"],
     "Très proche de l'anxiété sociale généralisée, ce trouble s'en distingue par son caractère plus précoce, plus envahissant et plus identitaire : ce n'est pas seulement la situation sociale qui est redoutée, c'est un sentiment global d'inadéquation. La souffrance principale vient du décalage entre le désir de lien et l'évitement.",
     "TCC avec exposition sociale progressive ; thérapie des schémas (schémas d'imperfection et d'exclusion) ; travail sur l'affirmation de soi ; thérapie de groupe, particulièrement indiquée ; les progrès sont réels mais demandent du temps."),

    ("insomnie", "Insomnie chronique", "Troubles du sommeil", "≈ 10 % des adultes en forme chronique",
     ["Difficulté d'endormissement, réveils nocturnes ou réveil trop précoce",
      "Au moins trois nuits par semaine depuis plus de trois mois",
      "Retentissement diurne : fatigue, irritabilité, difficultés de concentration",
      "Anxiété de performance vis-à-vis du sommeil",
      "Temps passé au lit augmenté, efficacité du sommeil dégradée"],
     "L'insomnie devient chronique quand les stratégies d'adaptation (se coucher plus tôt, rester au lit, siestes, alcool) dégradent la pression de sommeil et associent le lit à l'éveil anxieux. Le modèle 3P décrit des facteurs prédisposants, précipitants et de perpétuation — ce sont ces derniers qu'on traite.",
     "TCC-I, recommandée en première intention avant tout médicament : restriction du temps passé au lit, contrôle du stimulus, restructuration cognitive, hygiène du sommeil ; efficacité supérieure aux hypnotiques à long terme ; les benzodiazépines ne sont indiquées que sur de très courtes durées."),

    ("addiction", "Troubles de l'usage de substances", "Addictions", "≈ 5 à 10 % selon les substances",
     ["Perte de contrôle sur la consommation, envie irrépressible (craving)",
      "Poursuite malgré les conséquences négatives évidentes",
      "Tolérance (besoin d'augmenter les doses) et sevrage",
      "Temps considérable consacré à obtenir et consommer",
      "Abandon progressif d'autres activités"],
     "L'addiction détourne le circuit de la récompense : la dopamine signale non plus le plaisir mais le désir (wanting), qui persiste alors même que le plaisir (liking) a disparu. Les facteurs sociaux et traumatiques sont déterminants — l'expérience du « Rat Park » a montré que des rats vivant dans un environnement riche consomment beaucoup moins.",
     "Entretien motivationnel (approche empathique, non confrontante) ; TCC de prévention de la rechute ; traitements de substitution pour les opiacés ; réduction des risques ; groupes d'entraide ; traitement des comorbidités psychiatriques, très fréquentes."),

    ("addiction-comportementale", "Addictions comportementales", "Addictions", "Jeu d'argent ≈ 1 %, jeu vidéo ≈ 1 à 3 %",
     ["Préoccupation permanente pour l'activité",
      "Perte de contrôle malgré les tentatives d'arrêt",
      "Poursuite malgré les conséquences (dettes, échec scolaire, conflits)",
      "Irritabilité en cas d'impossibilité de pratiquer",
      "Mensonges sur l'ampleur réelle de la pratique"],
     "Seuls le jeu d'argent pathologique et le trouble du jeu vidéo sont officiellement reconnus comme troubles. Les mécanismes de renforcement à ratio variable — les mêmes que la boîte de Skinner — sont délibérément intégrés dans la conception des machines à sous, des loot boxes et de certaines applications. La frontière entre passion intense et addiction passe par le retentissement fonctionnel, non par le temps passé.",
     "TCC spécialisée, avec travail sur les distorsions cognitives (illusion de contrôle, croyance au « coup à venir ») ; entretien motivationnel ; interdiction volontaire de jeu ; accompagnement budgétaire et familial ; régulation du design persuasif au niveau des politiques publiques."),

    ("deuil-prolonge", "Trouble du deuil prolongé", "Troubles liés au stress", "≈ 7 à 10 % des personnes endeuillées",
     ["Nostalgie intense et persistante du défunt au-delà de 6 à 12 mois",
      "Préoccupation envahissante par le disparu",
      "Difficulté à accepter la mort, sentiment d'irréalité",
      "Sentiment qu'une partie de soi est morte, perte de sens",
      "Retentissement marqué sur la vie quotidienne"],
     "Il ne s'agit pas de « mal faire son deuil » ni de pathologiser la tristesse : ce diagnostic, introduit récemment, identifie une minorité de personnes chez qui le processus reste bloqué et qui bénéficient d'un accompagnement spécifique. Les décès brutaux, violents ou d'un enfant augmentent nettement le risque.",
     "Thérapie du deuil compliqué (Shear) : récit répété de la mort, travail sur les évitements, réengagement dans des objectifs personnels ; groupes de pairs endeuillés ; traitement d'un éventuel TSPT associé ; les antidépresseurs ne traitent pas le deuil en tant que tel."),

    ("somatique", "Trouble à symptomatologie somatique", "Troubles somatoformes", "≈ 5 à 7 % de la population",
     ["Symptômes physiques réels et pénibles (douleur, fatigue, troubles digestifs)",
      "Pensées disproportionnées sur la gravité des symptômes",
      "Anxiété élevée concernant la santé",
      "Temps et énergie excessifs consacrés à la santé",
      "Persistance au-delà de six mois"],
     "Le point clé, souvent mal compris : les symptômes sont authentiques, ils ne sont ni simulés ni « dans la tête ». Le diagnostic ne repose pas sur l'absence d'explication médicale mais sur la présence d'une détresse et de préoccupations excessives. Les allers-retours entre spécialistes et les examens répétés entretiennent l'anxiété.",
     "Consultation régulière programmée avec un médecin unique (plutôt qu'à la demande) ; validation explicite de la réalité des symptômes ; TCC ; activité physique adaptée et progressive ; travail sur l'attention portée aux sensations corporelles."),

    ("dissociatif", "Troubles dissociatifs", "Troubles dissociatifs", "≈ 1 à 2 % pour l'ensemble du spectre",
     ["Dépersonnalisation : sentiment d'être étranger à soi, comme un observateur",
      "Déréalisation : le monde paraît irréel, flou, artificiel",
      "Amnésie dissociative portant sur des périodes autobiographiques",
      "Dans le trouble dissociatif de l'identité : états d'identité distincts",
      "Discontinuités du sens de soi et de l'agentivité"],
     "La dissociation est un mécanisme de survie : face à une expérience intolérable et inévitable, le psychisme se déconnecte. Elle existe sous des formes bénignes et courantes (« route hypnotique ») et devient pathologique lorsqu'elle est massive et involontaire. Le trouble dissociatif de l'identité, très rare, est presque toujours lié à des traumatismes précoces sévères et reste débattu.",
     "Traitement séquencé en trois phases comme pour le TSPT complexe ; priorité à la stabilisation et aux techniques d'ancrage sensoriel ; psychoéducation sur la dissociation ; éviter tout travail traumatique prématuré, qui peut aggraver le tableau."),

    ("burnout", "Épuisement professionnel (burn-out)", "Santé au travail", "≈ 5 à 10 % des actifs selon les études",
     ["Épuisement émotionnel profond, non réparé par le repos",
      "Cynisme et distance vis-à-vis du travail (dépersonnalisation)",
      "Sentiment de perte d'efficacité professionnelle",
      "Troubles du sommeil, irritabilité, symptômes somatiques",
      "Installation progressive, souvent chez des personnes très investies"],
     "Le burn-out n'est pas un diagnostic psychiatrique mais un phénomène lié au contexte professionnel (CIM-11). Le modèle de Karasek montre que la combinaison forte demande / faible latitude décisionnelle / faible soutien social est la plus délétère. C'est l'organisation du travail, davantage que la fragilité individuelle, qui est en cause.",
     "Arrêt de travail lorsque nécessaire, mais insuffisant seul ; psychothérapie de soutien et TCC ; travail sur les limites et les valeurs professionnelles ; retour progressif et aménagé ; interventions organisationnelles (charge, autonomie, reconnaissance), les seules efficaces durablement."),

    ("tdi-phobie-scolaire", "Refus scolaire anxieux", "Troubles de l'enfant et de l'adolescent", "≈ 1 à 5 % des élèves",
     ["Impossibilité de se rendre à l'école malgré le désir d'y aller",
      "Symptômes somatiques le matin (maux de ventre, nausées) disparaissant le week-end",
      "Angoisse majeure à l'approche de l'établissement",
      "Absence de comportement délinquant (contrairement à l'école buissonnière)",
      "Retentissement scolaire et social rapide"],
     "Le terme ancien de « phobie scolaire » est trompeur : il s'agit rarement d'une phobie de l'école en tant que telle, mais d'un faisceau de causes possibles — anxiété de séparation, anxiété sociale, harcèlement, dépression, troubles des apprentissages non diagnostiqués. Le repérage rapide est déterminant car chaque semaine d'absence rend le retour plus difficile.",
     "Évaluation des causes sous-jacentes avant tout ; retour scolaire progressif et planifié avec l'établissement ; TCC avec exposition graduée ; travail avec les parents sur l'accompagnement ; traitement du harcèlement s'il est en cause ; scolarité aménagée temporaire, jamais définitive."),

    ("anxiete-separation", "Anxiété de séparation", "Troubles de l'enfant et de l'adolescent", "≈ 4 % des enfants",
     ["Détresse excessive lors de la séparation d'avec les figures d'attachement",
      "Crainte persistante qu'il leur arrive malheur",
      "Refus de dormir seul ou hors du domicile",
      "Cauchemars à thème de séparation",
      "Plaintes somatiques lors des séparations"],
     "Une certaine anxiété de séparation est normale entre 8 mois et 3 ans. Elle devient un trouble lorsqu'elle persiste au-delà, qu'elle est disproportionnée et qu'elle entrave la vie quotidienne. Elle peut aussi apparaître chez l'adulte, notamment après une perte.",
     "TCC adaptée à l'enfant avec exposition graduée aux séparations ; guidance parentale pour éviter le renforcement involontaire de l'évitement ; rituels de séparation clairs et brefs ; thérapie familiale si l'anxiété parentale entretient le trouble."),

    ("hypocondrie", "Crainte excessive d'avoir une maladie", "Troubles somatoformes", "≈ 1 à 5 % des consultants",
     ["Préoccupation persistante d'être ou de devenir gravement malade",
      "Symptômes somatiques absents ou très légers",
      "Vérifications corporelles répétées ou, à l'inverse, évitement des soins",
      "Recherche d'informations médicales compulsive (cybercondrie)",
      "Réassurance médicale n'apaisant que très brièvement"],
     "Le mécanisme central est l'hypervigilance corporelle : plus on scrute son corps, plus on détecte de sensations banales, qui sont ensuite interprétées comme des signes de maladie. La réassurance fonctionne comme une compulsion : elle soulage quelques heures puis renforce le besoin de vérifier.",
     "TCC avec prévention de la réassurance et des vérifications ; travail sur l'attention corporelle ; exposition aux informations médicales anxiogènes ; consultation médicale programmée à intervalle fixe plutôt qu'en urgence ; ISRS dans les formes sévères."),

    ("saisonnier", "Trouble affectif saisonnier", "Troubles de l'humeur", "≈ 1 à 3 %, davantage aux hautes latitudes",
     ["Épisodes dépressifs récurrents à la même période de l'année (automne-hiver)",
      "Hypersomnie et augmentation de l'appétit (envie de sucres lents)",
      "Prise de poids hivernale, fatigue marquée",
      "Rémission au printemps",
      "Au moins deux années consécutives de ce schéma"],
     "La réduction de lumière décale l'horloge circadienne et modifie la sécrétion de mélatonine et la disponibilité de la sérotonine. Le profil symptomatique est atypique : au lieu de l'insomnie et de la perte d'appétit de la dépression classique, on observe une hypersomnie et une hyperphagie.",
     "Luminothérapie : 10 000 lux, 30 minutes le matin, efficacité démontrée en une à deux semaines ; TCC adaptée au trouble saisonnier, avec des effets plus durables ; activité extérieure matinale ; ISRS dans les formes résistantes ; simulateur d'aube."),

    ("post-partum", "Dépression du post-partum", "Périnatalité", "≈ 10 à 15 % des accouchées",
     ["Tristesse, pleurs, irritabilité persistant au-delà de deux semaines",
      "Difficulté à établir le lien avec le bébé, culpabilité intense",
      "Troubles du sommeil non expliqués par les réveils du bébé",
      "Anxiété majeure concernant l'enfant, pensées intrusives",
      "Peut aussi toucher le partenaire (≈ 5 à 10 %)"],
     "À distinguer du baby blues, transitoire et très fréquent (50 à 80 %), qui dure quelques jours après l'accouchement. La dépression du post-partum est durable et nécessite un traitement. Elle est massivement sous-déclarée du fait de la honte : la norme sociale du bonheur maternel rend l'aveu difficile.",
     "Dépistage systématique (échelle EPDS) ; psychothérapie interpersonnelle ou TCC ; antidépresseurs compatibles avec l'allaitement ; soutien concret sur le sommeil et les tâches ; unités mère-bébé dans les formes sévères ; en France, entretien postnatal précoce remboursé."),

    ("troubles-sexuels", "Dysfonctions sexuelles", "Sexologie", "≈ 30 à 40 % à un moment de la vie",
     ["Baisse du désir sexuel provoquant une souffrance",
      "Troubles de l'excitation ou de l'érection",
      "Troubles de l'orgasme (anorgasmie, éjaculation précoce)",
      "Douleurs lors des rapports (vaginisme, dyspareunie)",
      "Évitement progressif de l'intimité"],
     "Le facteur d'entretien principal est souvent l'anxiété de performance et l'auto-observation pendant l'acte (le « spectatoring » décrit par Masters et Johnson), qui bloque la réponse sexuelle. Il est essentiel d'écarter d'abord les causes médicales et médicamenteuses.",
     "Bilan médical préalable ; thérapie sexofonctionnelle et exercices de focalisation sensorielle ; TCC sur les croyances et l'anxiété de performance ; thérapie de couple lorsque la dimension relationnelle domine ; rééducation périnéale pour le vaginisme ; traitements médicamenteux selon l'indication."),

    ("jeu-video", "Trouble du jeu vidéo", "Addictions", "≈ 1 à 3 % des joueurs",
     ["Perte de contrôle sur la durée et la fréquence des sessions",
      "Priorité croissante donnée au jeu sur les autres activités",
      "Poursuite malgré les conséquences négatives",
      "Retentissement scolaire, professionnel ou familial marqué",
      "Évolution sur au moins 12 mois"],
     "Reconnu par la CIM-11 en 2019, ce diagnostic reste débattu : la grande majorité des joueurs intensifs ne sont pas dépendants. Ce n'est pas le temps de jeu qui définit le trouble mais le retentissement fonctionnel et la perte de contrôle. Le jeu est souvent une conséquence — une stratégie d'adaptation face à l'anxiété sociale, à la dépression ou au harcèlement — autant qu'une cause.",
     "Évaluation des troubles sous-jacents, prioritaire ; TCC avec réintroduction progressive d'autres sources de satisfaction ; travail familial sur le cadre plutôt que la confiscation brutale ; entretien motivationnel ; hygiène du sommeil."),

    ("dysmorphophobie", "Obsession d'une dysmorphie corporelle", "TOC et apparentés", "≈ 2 % de la population",
     ["Préoccupation intense concernant un défaut physique imperceptible ou minime",
      "Comportements répétitifs : miroir, camouflage, comparaison",
      "Souffrance et évitement social importants",
      "Recours répétés à la chirurgie esthétique, sans satisfaction durable",
      "Risque suicidaire élevé"],
     "Il ne s'agit pas de coquetterie : la souffrance est comparable à celle d'un TOC sévère. Les zones les plus fréquemment concernées sont la peau, le nez et les cheveux. La chirurgie esthétique aggrave généralement le trouble, le foyer de préoccupation se déplaçant vers une autre zone.",
     "TCC spécifique avec exposition et prévention de la réponse (limiter miroir et camouflage) ; ISRS à posologie élevée ; refus argumenté des interventions esthétiques ; travail sur l'attention perceptive globale plutôt que détaillée."),

    ("trichotillomanie", "Trichotillomanie et dermatillomanie", "TOC et apparentés", "≈ 1 à 2 % de la population",
     ["Arrachage répété de cheveux ou de poils, ou grattage de la peau",
      "Tentatives répétées et infructueuses de diminuer le comportement",
      "Tension avant le geste, soulagement pendant",
      "Lésions visibles, honte et dissimulation",
      "Geste souvent automatique, en état d'absorption"],
     "Ces comportements répétitifs centrés sur le corps ne sont pas des automutilations au sens du geste suicidaire : la fonction est régulatrice, souvent apaisante ou stimulante. Ils apparaissent fréquemment à l'adolescence et sont durablement cachés.",
     "Renversement d'habitude (habit reversal training) : conscience du geste, réponse motrice concurrente, soutien social — traitement de référence ; thérapie d'acceptation et d'engagement ; barrières physiques temporaires ; N-acétylcystéine, avec des résultats encourageants."),

    ("ptsd-vicariant", "Traumatisme vicariant et fatigue de compassion", "Santé au travail", "Fréquent chez les métiers d'aide",
     ["Symptômes de stress post-traumatique sans exposition directe",
      "Images intrusives issues des récits des personnes accompagnées",
      "Modification de la vision du monde : perte de confiance, hypervigilance",
      "Épuisement émotionnel et distance protectrice",
      "Culpabilité de ne pas en faire assez"],
     "Concerne les soignants, travailleurs sociaux, magistrats, journalistes, modérateurs de contenus, interprètes et bénévoles exposés de façon répétée à la souffrance d'autrui. Ce n'est pas un défaut de professionnalisme, mais une conséquence attendue d'une exposition répétée sans espace de traitement.",
     "Supervision et analyse de pratique régulières ; limitation de la charge de cas exposés ; formation aux limites professionnelles ; travail sur les ressources personnelles ; psychothérapie individuelle si symptômes installés ; responsabilité organisationnelle centrale."),
]
