# -*- coding: utf-8 -*-
"""Lexique anglais-français de la psychologie.

La quasi-totalité de la littérature scientifique est publiée en anglais. Ce
lexique donne l'équivalent français usuel et signale les faux amis, qui sont la
première cause de contresens en traduction.
"""

# (anglais, francais, domaine, note)
LEXIQUE_EN = [
    ("Ability", "Aptitude, capacité", "Général", "« Habileté » convient pour une compétence acquise, « aptitude » pour un potentiel."),
    ("Accuracy", "Exactitude", "Méthodes", "Distincte de la précision (<em>precision</em>), qui désigne la reproductibilité."),
    ("Achievement", "Réussite, performance scolaire", "Éducation", "<em>Achievement test</em> : test de connaissances acquises, opposé à <em>aptitude test</em>."),
    ("Acquiescence bias", "Biais d'acquiescement", "Mesure", "Tendance à répondre « oui » quel que soit l'item ; se contre par des items inversés."),
    ("Adjustment", "Adaptation, ajustement", "Clinique", "Faux ami : ne pas traduire par « ajustement » quand il s'agit d'adaptation psychosociale."),
    ("Affect", "Affect, tonalité émotionnelle", "Émotions", "En anglais, terme générique couvrant émotions et humeurs ; en français, plus technique."),
    ("Agency", "Capacité d'agir, agentivité", "Social", "Aucune traduction parfaite : « pouvoir d'agir » est souvent le plus juste."),
    ("Agreeableness", "Agréabilité", "Personnalité", "Dimension du Big Five ; « amabilité » ou « caractère agréable » selon les traductions."),
    ("Amygdala", "Amygdale", "Neurosciences", "Attention : rien à voir avec les amygdales de la gorge (<em>tonsils</em>)."),
    ("Anchoring", "Ancrage", "Décision", "Biais d'ancrage : la première valeur entendue oriente l'estimation finale."),
    ("Antecedent", "Antécédent, situation déclenchante", "Comportement", "Le A du modèle ABC en analyse fonctionnelle."),
    ("Anxiety", "Anxiété", "Clinique", "L'anglais ne distingue pas systématiquement anxiété (diffuse) et peur (objet précis)."),
    ("Appraisal", "Évaluation cognitive", "Émotions", "Terme central du modèle de Lazarus ; ne pas traduire par « appréciation »."),
    ("Arousal", "Activation, éveil physiologique", "Émotions", "Faux ami majeur : ne signifie pas « excitation sexuelle » hors contexte explicite."),
    ("Assessment", "Évaluation, bilan", "Clinique", "<em>Psychological assessment</em> : bilan psychologique complet, pas un simple test."),
    ("Attachment", "Attachement", "Développement", "<em>Secure / insecure attachment</em> : attachement sécure / insécure."),
    ("Attainment", "Niveau atteint, acquis", "Éducation", "<em>Educational attainment</em> : niveau d'études atteint."),
    ("Attention deficit", "Déficit de l'attention", "Neurodéveloppement", "TDAH en français, ADHD en anglais."),
    ("Attitude", "Attitude", "Social", "Disposition évaluative envers un objet ; ne pas confondre avec le comportement."),
    ("Attrition", "Attrition, perdus de vue", "Méthodes", "Abandons en cours d'étude longitudinale ; menace majeure pour la validité."),
    ("Availability heuristic", "Heuristique de disponibilité", "Décision", "Juger la fréquence d'un événement à la facilité avec laquelle un exemple vient à l'esprit."),
    ("Awareness", "Conscience, prise de conscience", "Cognition", "Plus proche de « se rendre compte » que de « conscience » au sens philosophique."),
    ("Baseline", "Ligne de base, mesure initiale", "Méthodes", "Niveau observé avant toute intervention."),
    ("Behaviour / Behavior", "Comportement, conduite", "Général", "Orthographe britannique / américaine."),
    ("Belief", "Croyance", "Cognition", "Sans connotation religieuse : désigne toute représentation tenue pour vraie."),
    ("Bias", "Biais", "Méthodes", "Erreur systématique, à distinguer de l'erreur aléatoire (bruit, <em>noise</em>)."),
    ("Binge eating", "Hyperphagie boulimique", "Clinique", "Crises de consommation alimentaire sans conduite compensatoire."),
    ("Blinding", "Insu, aveugle", "Méthodes", "<em>Double-blind</em> : double aveugle, ou « en double insu »."),
    ("Bottom-up", "Ascendant, guidé par les données", "Cognition", "Traitement piloté par le stimulus, opposé au traitement descendant."),
    ("Bullying", "Harcèlement (entre pairs)", "Éducation", "<em>Workplace bullying</em> : harcèlement moral au travail."),
    ("Burnout", "Épuisement professionnel", "Travail", "Trois dimensions : épuisement, cynisme, perte d'accomplissement."),
    ("Caregiver", "Aidant, figure de soin", "Développement", "Couvre le parent, le professionnel ou l'aidant familial selon le contexte."),
    ("Ceiling effect", "Effet plafond", "Mesure", "Tâche trop facile : tout le monde réussit, l'instrument ne discrimine plus."),
    ("Chunking", "Regroupement en unités", "Mémoire", "Souvent laissé en anglais ; « empaquetage » se rencontre aussi."),
    ("Cognition", "Cognition", "Cognition", "L'ensemble des processus de traitement de l'information."),
    ("Compliance", "Observance, soumission", "Santé / Social", "Faux ami : en santé, observance du traitement ; en social, soumission à une demande."),
    ("Conditioning", "Conditionnement", "Apprentissage", "<em>Classical</em> : classique ou répondant ; <em>operant</em> : opérant."),
    ("Confidence interval", "Intervalle de confiance", "Statistiques", "Plage de valeurs plausibles pour le paramètre estimé."),
    ("Confound", "Variable confondue", "Méthodes", "Le verbe <em>to confound</em> signifie « rendre inextricables deux effets »."),
    ("Conscientiousness", "Conscienciosité", "Personnalité", "Dimension du Big Five ; rien à voir avec la conscience (<em>consciousness</em>)."),
    ("Consciousness", "Conscience (phénoménale)", "Cognition", "À ne pas confondre avec <em>conscience</em> anglais, qui signifie « conscience morale »."),
    ("Construct", "Construit", "Mesure", "Concept théorique non observable directement (l'anxiété, l'intelligence)."),
    ("Coping", "Stratégies d'ajustement, faire face", "Stress", "Souvent conservé tel quel ; « composer avec » rend bien l'idée."),
    ("Craving", "Envie impérieuse, appétence", "Addiction", "Terme technique généralement conservé en français."),
    ("Cross-sectional", "Transversal", "Méthodes", "S'oppose à <em>longitudinal</em>."),
    ("Cue", "Indice, signal", "Apprentissage", "<em>Retrieval cue</em> : indice de récupération en mémoire."),
    ("Debriefing", "Débriefing", "Éthique", "Information délivrée après coup lorsqu'il y a eu tromperie."),
    ("Decay", "Estompage, effacement", "Mémoire", "Théorie de l'oubli par simple passage du temps."),
    ("Delay discounting", "Dévalorisation temporelle", "Décision", "Perte de valeur d'une récompense à mesure qu'elle s'éloigne dans le temps."),
    ("Demand characteristics", "Caractéristiques de la demande", "Méthodes", "Indices par lesquels le participant devine l'hypothèse testée."),
    ("Depletion", "Épuisement (des ressources)", "Motivation", "<em>Ego depletion</em> : épuisement du moi — concept largement remis en cause."),
    ("Deprivation", "Privation, carence", "Développement", "<em>Sleep deprivation</em> : privation de sommeil."),
    ("Disclosure", "Divulgation, dévoilement", "Clinique", "<em>Self-disclosure</em> : dévoilement de soi dans la relation."),
    ("Discounting", "Dévalorisation", "Décision", "Réduction subjective de la valeur d'une récompense différée ou incertaine."),
    ("Disorder", "Trouble", "Clinique", "Traduire par « trouble », jamais par « désordre »."),
    ("Distress", "Détresse, souffrance", "Clinique", "Faux ami : ne pas traduire par « stress », qui est plus large."),
    ("Drive", "Pulsion, poussée motivationnelle", "Motivation", "Dans la tradition béhavioriste, tension interne orientée vers la réduction d'un besoin."),
    ("Dual process", "Double processus", "Cognition", "Modèles opposant traitement automatique et traitement contrôlé."),
    ("Effect size", "Taille d'effet", "Statistiques", "Information la plus importante d'un résultat, souvent la plus discrète."),
    ("Efficacy vs effectiveness", "Efficacité théorique / efficacité en pratique", "Santé", "Distinction majeure : en essai contrôlé versus en conditions réelles."),
    ("Embodiment", "Incarnation, cognition incarnée", "Cognition", "Idée que la cognition s'appuie sur le corps et ses interactions."),
    ("Emotion regulation", "Régulation émotionnelle", "Émotions", "Ensemble des stratégies modulant l'intensité ou la durée d'une émotion."),
    ("Empathy", "Empathie", "Social", "Distinguer empathie cognitive (comprendre) et affective (ressentir avec)."),
    ("Encoding", "Encodage", "Mémoire", "Première étape du traitement mnésique, avant stockage et récupération."),
    ("Endorsement", "Approbation, adhésion à un item", "Mesure", "<em>Item endorsement</em> : proportion de participants approuvant un item."),
    ("Engagement", "Engagement", "Travail / Éducation", "État positif d'implication, opposé au désengagement et au burnout."),
    ("Executive function", "Fonctions exécutives", "Cognition", "Inhibition, flexibilité, mise à jour en mémoire de travail, planification."),
    ("Expectancy", "Attente, expectation", "Motivation", "<em>Expectancy-value theory</em> : théorie attente-valeur."),
    ("Exposure", "Exposition", "Thérapies", "Technique centrale du traitement des phobies et du TSPT."),
    ("Extinction", "Extinction", "Apprentissage", "Diminution d'une réponse quand l'association cesse d'être renforcée."),
    ("Eyewitness testimony", "Témoignage oculaire", "Légale", "Champ marqué par les travaux de Loftus sur la malléabilité du souvenir."),
    ("Fading", "Estompage de l'aide", "Éducation", "Retrait progressif de l'étayage à mesure que l'autonomie grandit."),
    ("Feedback", "Retour d'information, rétroaction", "Éducation", "« Rétroaction » est la traduction technique, « retour » l'usage courant."),
    ("Fidelity", "Fidélité de mise en œuvre", "Méthodes", "Degré auquel une intervention a été appliquée comme prévu."),
    ("Flashbulb memory", "Souvenir-flash", "Mémoire", "Souvenir très vivace d'un événement marquant — vivacité n'est pas exactitude."),
    ("Floor effect", "Effet plancher", "Mesure", "Tâche trop difficile : personne ne réussit, l'instrument ne discrimine plus."),
    ("Fluid intelligence", "Intelligence fluide", "Intelligence", "Capacité à raisonner sur du matériel nouveau, opposée à l'intelligence cristallisée."),
    ("Framing effect", "Effet de cadrage", "Décision", "La formulation d'un choix (gain ou perte) modifie la décision."),
    ("Gaslighting", "Manipulation par le doute induit", "Social", "Terme issu d'une pièce de théâtre, entré dans l'usage clinique et courant."),
    ("Goal setting", "Fixation d'objectifs", "Travail", "Théorie de Locke et Latham : objectifs spécifiques et ambitieux."),
    ("Grit", "Persévérance et passion durables", "Motivation", "Concept d'Angela Duckworth, très critiqué pour son recouvrement avec la conscienciosité."),
    ("Grooming", "Manipulation prédatrice", "Légale", "Stratégie progressive de mise en confiance d'un mineur par un agresseur."),
    ("Habituation", "Habituation", "Apprentissage", "Diminution de la réponse à un stimulus répété et sans conséquence."),
    ("Hardiness", "Endurance psychologique", "Stress", "Engagement, contrôle, défi — proche mais distinct de la résilience."),
    ("Heuristic", "Heuristique", "Décision", "Raccourci mental efficace mais faillible dans certaines situations."),
    ("Hindsight bias", "Biais rétrospectif", "Décision", "« Je le savais depuis le début » — reconstruction après coup."),
    ("Hoarding", "Accumulation compulsive", "Clinique", "Trouble à part entière depuis le DSM-5, distinct du TOC."),
    ("Impairment", "Altération fonctionnelle", "Clinique", "Critère central de nombreux diagnostics : le retentissement sur la vie."),
    ("Implementation intention", "Intention de mise en œuvre", "Motivation", "Plan « si… alors » qui augmente fortement le passage à l'acte."),
    ("Impulsivity", "Impulsivité", "Personnalité", "Agir sans délibération ; plusieurs facettes distinctes en réalité."),
    ("Incentive", "Incitation, renforçateur", "Motivation", "Ne pas traduire par « incentive » ni par « motivation »."),
    ("Insight", "Prise de conscience, éclair de compréhension", "Cognition / Clinique", "En clinique : conscience du trouble ; en résolution de problème : illumination soudaine."),
    ("Internal consistency", "Cohérence interne", "Mesure", "Mesurée notamment par l'alpha de Cronbach."),
    ("Item", "Item, question", "Mesure", "Unité élémentaire d'un questionnaire ou d'un test."),
    ("Learned helplessness", "Impuissance apprise", "Motivation", "Traduction consacrée, bien que « résignation apprise » soit plus fidèle."),
    ("Likert scale", "Échelle de Likert", "Mesure", "Échelle d'accord graduée, typiquement en 5 ou 7 points."),
    ("Loss aversion", "Aversion à la perte", "Décision", "Une perte pèse psychologiquement environ deux fois plus qu'un gain équivalent."),
    ("Mastery", "Maîtrise", "Éducation", "<em>Mastery goal</em> : but de maîtrise, opposé au but de performance."),
    ("Mindfulness", "Pleine conscience", "Thérapies", "Attention intentionnelle au moment présent, sans jugement."),
    ("Mindset", "État d'esprit", "Éducation", "<em>Growth mindset</em> : état d'esprit de développement."),
    ("Mood", "Humeur", "Émotions", "Plus diffuse et plus durable qu'une émotion, et sans objet précis."),
    ("Nudge", "Coup de pouce, incitation douce", "Décision", "Modification de l'architecture du choix sans contrainte ni interdiction."),
    ("Openness", "Ouverture à l'expérience", "Personnalité", "Dimension du Big Five liée à la curiosité et à l'imagination."),
    ("Outcome", "Résultat, critère de jugement", "Méthodes", "<em>Primary outcome</em> : critère de jugement principal, fixé à l'avance."),
    ("Overconfidence", "Excès de confiance", "Décision", "Décalage entre la confiance déclarée et l'exactitude réelle."),
    ("Parenting", "Pratiques éducatives parentales", "Développement", "<em>Parenting style</em> : style éducatif (autoritaire, démocratique, permissif, négligent)."),
    ("Peer", "Pair", "Développement", "<em>Peer review</em> : évaluation par les pairs ; <em>peer pressure</em> : pression des pairs."),
    ("Performance", "Performance, exécution", "Général", "En psycholinguistique, s'oppose à la compétence au sens de Chomsky."),
    ("Perseveration", "Persévération", "Neuropsychologie", "Répétition d'une réponse devenue inadaptée ; signe frontal classique."),
    ("Placebo", "Placebo", "Méthodes", "L'effet placebo est un effet réel, mesurable, pas une absence d'effet."),
    ("Prejudice", "Préjugé", "Social", "Attitude ; la discrimination en est la traduction comportementale."),
    ("Primacy effect", "Effet de primauté", "Mémoire", "Meilleur rappel des premiers éléments d'une liste."),
    ("Priming", "Amorçage", "Cognition", "L'amorçage sémantique est solide ; l'amorçage comportemental l'est beaucoup moins."),
    ("Prospective memory", "Mémoire prospective", "Mémoire", "Se souvenir d'accomplir une action prévue — prendre son traitement, poster une lettre."),
    ("Prosocial behaviour", "Comportement prosocial", "Social", "Agir au bénéfice d'autrui, avec ou sans motivation altruiste."),
    ("Randomised controlled trial", "Essai contrôlé randomisé", "Méthodes", "Abrégé RCT en anglais, ECR en français."),
    ("Rapport", "Qualité du lien, mise en confiance", "Clinique", "Faux ami : ne signifie ni « rapport écrit » ni « relation » au sens large."),
    ("Recall", "Rappel", "Mémoire", "Restitution active, opposée à la reconnaissance (<em>recognition</em>)."),
    ("Recency effect", "Effet de récence", "Mémoire", "Meilleur rappel des derniers éléments d'une liste."),
    ("Rehearsal", "Répétition mentale", "Mémoire", "<em>Maintenance rehearsal</em> : répétition de maintien, peu efficace pour le long terme."),
    ("Reinforcement", "Renforcement", "Apprentissage", "Le renforcement négatif n'est pas une punition : il retire un élément désagréable."),
    ("Reliability", "Fidélité", "Mesure", "Faux ami redoutable : ne pas traduire par « fiabilité » en psychométrie."),
    ("Resilience", "Résilience", "Développement", "Capacité à maintenir ou retrouver un fonctionnement après l'adversité."),
    ("Retrieval", "Récupération", "Mémoire", "<em>Retrieval practice</em> : pratique de récupération, l'une des méthodes d'étude les plus efficaces."),
    ("Reward", "Récompense, renforçateur", "Motivation", "<em>Reward prediction error</em> : erreur de prédiction de la récompense."),
    ("Rumination", "Rumination", "Clinique", "Pensées répétitives centrées sur les causes et conséquences de la détresse."),
    ("Salience", "Saillance", "Attention", "Propriété d'un stimulus qui capte l'attention automatiquement."),
    ("Scaffolding", "Étayage", "Éducation", "Soutien temporaire ajusté, retiré à mesure que l'autonomie progresse."),
    ("Schema", "Schéma", "Cognition", "Structure de connaissances organisant la perception et la mémoire ; pluriel <em>schemata</em>."),
    ("Screening", "Dépistage", "Santé", "Repérage en population, distinct du diagnostic."),
    ("Self-efficacy", "Sentiment d'efficacité personnelle", "Motivation", "Concept de Bandura ; ne pas traduire par « auto-efficacité » en contexte académique français."),
    ("Self-esteem", "Estime de soi", "Personnalité", "Évaluation globale de sa propre valeur."),
    ("Self-report", "Auto-déclaration, mesure auto-rapportée", "Mesure", "Donnée fournie par la personne, avec les limites que cela implique."),
    ("Sensitivity", "Sensibilité", "Mesure", "Capacité d'un test à détecter les vrais positifs ; complément de la spécificité."),
    ("Set shifting", "Flexibilité mentale", "Cognition", "Capacité à changer de règle ou de critère en cours de tâche."),
    ("Severity", "Sévérité, gravité", "Clinique", "Dimension désormais spécifiée pour la plupart des diagnostics."),
    ("Social desirability", "Désirabilité sociale", "Mesure", "Tendance à se présenter sous un jour favorable."),
    ("Social loafing", "Paresse sociale", "Social", "Réduction de l'effort individuel quand la performance est collective."),
    ("Spacing effect", "Effet d'espacement", "Éducation", "Supériorité de l'étude répartie sur l'étude massée."),
    ("Stereotype threat", "Menace du stéréotype", "Social", "Effet répliqué mais de taille plus modeste que dans les publications initiales."),
    ("Stimulus", "Stimulus", "Général", "Pluriel <em>stimuli</em> en anglais comme en français savant."),
    ("Stress", "Stress", "Santé", "Terme emprunté à la physique par Selye ; distinguer stresseur, réponse et vécu."),
    ("Subjective well-being", "Bien-être subjectif", "Positive", "Satisfaction de vie, affects positifs, faible niveau d'affects négatifs."),
    ("Sunk cost", "Coût irrécupérable", "Décision", "Persister à cause de ce qui est déjà investi et non récupérable."),
    ("Survey", "Enquête par questionnaire", "Méthodes", "Faux ami : ne signifie ni « surveillance » ni « sondage » au sens strict."),
    ("Sustained attention", "Attention soutenue", "Attention", "Maintien de la vigilance dans la durée, distinct de l'attention sélective."),
    ("Theory of mind", "Théorie de l'esprit", "Développement", "Attribuer à autrui des états mentaux différents des siens."),
    ("Threshold", "Seuil", "Perception", "Seuil absolu : intensité minimale détectable ; seuil différentiel : plus petite différence perceptible."),
    ("Top-down", "Descendant, guidé par les connaissances", "Cognition", "Traitement piloté par les attentes et l'expérience."),
    ("Trait", "Trait", "Personnalité", "Disposition stable, opposée à l'état (<em>state</em>) qui est passager."),
    ("Trial", "Essai", "Méthodes", "Deux sens : un essai clinique, ou un essai individuel dans une tâche répétée."),
    ("Validity", "Validité", "Mesure", "Un instrument mesure-t-il ce qu'il prétend mesurer ?"),
    ("Vicarious learning", "Apprentissage vicariant", "Apprentissage", "Apprendre en observant les conséquences vécues par autrui."),
    ("Vigilance", "Vigilance", "Attention", "Maintien de la détection de signaux rares sur une longue durée."),
    ("Well-being", "Bien-être", "Positive", "Distinguer le versant hédonique (plaisir) et eudémonique (sens, accomplissement)."),
    ("Withdrawal", "Sevrage, retrait", "Addiction / Social", "Selon le contexte : syndrome de sevrage, ou retrait social."),
    ("Working memory", "Mémoire de travail", "Mémoire", "Espace de maintien et de manipulation temporaire de l'information."),
    ("Yerkes-Dodson law", "Loi de Yerkes-Dodson", "Motivation", "Relation en U inversé entre activation et performance."),
]

# Faux amis les plus coûteux, mis en avant sur la page.
FAUX_AMIS = [
    ("Actually", "En réalité, en fait", "et non « actuellement », qui se dit <em>currently</em>."),
    ("Affect (nom)", "Affect, tonalité émotionnelle", "et non « effet » ; <em>effect</em> est le nom, <em>affect</em> le verbe… sauf en psychologie où <em>affect</em> est aussi un nom technique."),
    ("Arousal", "Activation physiologique", "sans connotation sexuelle par défaut, contrairement à ce que suggère l'usage courant."),
    ("Compliance", "Observance thérapeutique", "et non « complaisance »."),
    ("Conscience", "Conscience morale", "alors que la conscience au sens psychologique se dit <em>consciousness</em> ou <em>awareness</em>."),
    ("Consistent", "Cohérent, constant", "et non « consistant » au sens d'épais ou de nourrissant."),
    ("Delay", "Délai, report", "mais <em>to delay</em> signifie retarder, pas « déléguer »."),
    ("Distress", "Détresse", "et non « stress » : le <em>distress</em> est le versant délétère du stress."),
    ("Evidence", "Données probantes, preuves", "et non « évidence » au sens de ce qui va de soi."),
    ("Eventually", "Finalement, à terme", "et non « éventuellement », qui se dit <em>possibly</em>."),
    ("Extensive", "Approfondi, vaste", "et non « extensif » au sens agricole ou économique."),
    ("Rapport", "Qualité de la relation établie", "et non « rapport » au sens de compte rendu (<em>report</em>)."),
    ("Relevant", "Pertinent", "et non « relevant de »."),
    ("Reliability", "Fidélité (psychométrie)", "et non « fiabilité » au sens général, qui induit un contresens technique."),
    ("Sensible", "Raisonnable, sensé", "alors que « sensible » en français se dit <em>sensitive</em>."),
    ("Support", "Soutien", "et non « supporter » au sens d'endurer, qui se dit <em>to endure</em> ou <em>to put up with</em>."),
    ("Sympathetic", "Compatissant, ou sympathique (système nerveux)", "et non « sympathique » au sens amical."),
    ("Trial", "Essai clinique, ou essai expérimental", "et non « procès » dans un article de psychologie expérimentale."),
]
