# -*- coding: utf-8 -*-
"""Panorama des tests et instruments psychométriques + chronologie de la discipline."""

# (id, nom, categorie, auteur_annee, mesure, passation, interpretation, limites)
TESTS = [
    ("wais", "WAIS-IV / WISC-V", "Intelligence", "David Wechsler, 1939 (révisions continues)",
     "Efficience intellectuelle globale et indices : compréhension verbale, raisonnement perceptif, mémoire de travail, vitesse de traitement.",
     "Individuelle, 1 h 30 à 2 h, administrée par un psychologue formé.",
     "QI moyen fixé à 100, écart-type 15 : 68 % de la population se situe entre 85 et 115. L'analyse des indices compte davantage que le score global, surtout en cas d'écarts importants.",
     "Sensible à la culture, à la langue, à la fatigue et à l'anxiété ; ne mesure ni la créativité, ni la motivation, ni les compétences sociales."),

    ("matrices-raven", "Matrices progressives de Raven", "Intelligence", "John C. Raven, 1938",
     "Raisonnement analogique non verbal, proche de l'intelligence fluide.",
     "Individuelle ou collective, 20 à 45 minutes, sans consigne verbale complexe.",
     "Considéré comme l'un des tests les moins dépendants de la culture et du langage, utile auprès de personnes non francophones.",
     "L'effet Flynn (hausse des scores au fil des générations) y est particulièrement marqué, imposant des réétalonnages réguliers."),

    ("nemi", "NEMI-3", "Intelligence", "Adaptation française, 2008",
     "Efficience intellectuelle de l'enfant de 4 à 12 ans, dans la lignée de Binet-Simon.",
     "Individuelle, environ 45 minutes.",
     "Outil francophone historique, utile en complément d'une WISC pour croiser les observations.",
     "Moins finement structuré en indices que la WISC-V ; peu utilisé seul aujourd'hui."),

    ("big-five", "NEO-PI-R / BFI (Big Five)", "Personnalité", "Costa & McCrae, 1985-1992",
     "Cinq grandes dimensions : ouverture, conscienciosité, extraversion, agréabilité, névrosisme (OCEAN).",
     "Auto-questionnaire, 60 à 240 items selon la version, 10 à 45 minutes.",
     "Modèle le mieux validé scientifiquement ; la conscienciosité prédit la réussite professionnelle et le névrosisme la vulnérabilité au stress.",
     "Auto-rapport sensible à la désirabilité sociale ; décrit des tendances moyennes, pas des comportements dans une situation précise."),

    ("mmpi", "MMPI-2 / MMPI-3", "Personnalité clinique", "Hathaway & McKinley, 1943",
     "Profil de personnalité et de psychopathologie via des échelles cliniques et de validité.",
     "Auto-questionnaire de 338 à 567 items, 60 à 90 minutes.",
     "Les échelles de validité détectent les réponses au hasard, la minimisation et l'exagération des symptômes — d'où son usage en expertise.",
     "Long, construit initialement sur un échantillon peu représentatif ; ne pose pas de diagnostic à lui seul."),

    ("16pf", "16PF", "Personnalité", "Raymond Cattell, 1949",
     "Seize facteurs primaires de personnalité et cinq facteurs globaux.",
     "Auto-questionnaire de 185 items, environ 35 à 50 minutes.",
     "Très utilisé en recrutement et en orientation professionnelle, avec un profil détaillé.",
     "Les 16 facteurs se recoupent partiellement ; le modèle à cinq facteurs lui est aujourd'hui préféré en recherche."),

    ("mbti", "MBTI", "Typologie", "Briggs & Myers, 1962, d'après Jung",
     "Classement en 16 types selon quatre dichotomies (E/I, S/N, T/F, J/P).",
     "Auto-questionnaire de 93 items, environ 20 minutes.",
     "Très populaire en entreprise pour faciliter le dialogue sur les préférences de fonctionnement.",
     "Faible validité scientifique : fidélité test-retest médiocre (jusqu'à 50 % de changement de type en quelques semaines), dichotomies artificielles alors que les traits sont continus. À ne pas utiliser pour une décision de sélection."),

    ("rorschach", "Test de Rorschach", "Projectif", "Hermann Rorschach, 1921",
     "Organisation de la personnalité, modes de traitement de l'information, dynamique affective.",
     "Individuelle, dix planches, 45 à 90 minutes avec l'enquête.",
     "Le système R-PAS et le système intégré d'Exner ont standardisé la cotation (localisation, déterminants, contenu, fréquence des réponses).",
     "Validité très inégale selon les indices ; certains sont solides, beaucoup ne le sont pas. Usage judiciaire particulièrement contesté."),

    ("tat", "TAT", "Projectif", "Murray & Morgan, 1935",
     "Thèmes conflictuels, relations objectales, besoins et pressions perçues.",
     "Individuelle, récits construits à partir de planches illustrées ambiguës.",
     "Analysé en France selon les procédés du discours (école de Shentoub), il éclaire le fonctionnement psychique plus qu'il ne classe.",
     "Cotation dépendante du clinicien ; faible standardisation ; à interpréter dans un faisceau d'indices."),

    ("beck-bdi", "Inventaire de dépression de Beck (BDI-II)", "Échelle clinique", "Aaron Beck, 1961 / 1996",
     "Intensité des symptômes dépressifs sur les deux dernières semaines.",
     "Auto-questionnaire de 21 items, 5 à 10 minutes.",
     "Seuils indicatifs : 0-13 minimal, 14-19 léger, 20-28 modéré, 29-63 sévère.",
     "Mesure une intensité, pas un diagnostic ; sensible aux symptômes somatiques d'origine médicale."),

    ("hamilton", "Échelle de Hamilton (HDRS)", "Échelle clinique", "Max Hamilton, 1960",
     "Sévérité de la dépression, évaluée par le clinicien.",
     "Hétéro-évaluation lors d'un entretien semi-structuré, 20 à 30 minutes.",
     "Référence historique des essais cliniques sur les antidépresseurs ; suit l'évolution sous traitement.",
     "Surpondère l'insomnie et les symptômes somatiques ; nécessite un évaluateur formé."),

    ("stai", "STAI (Spielberger)", "Échelle clinique", "Charles Spielberger, 1970",
     "Distingue l'anxiété-état (ici et maintenant) et l'anxiété-trait (disposition stable).",
     "Auto-questionnaire de 2 × 20 items, environ 10 minutes.",
     "Cette distinction est précieuse : une anxiété-état élevée avec un trait bas oriente vers une réaction situationnelle.",
     "Chevauchement important avec les échelles de dépression ; ne distingue pas les types de troubles anxieux."),

    ("hads", "HADS", "Échelle clinique", "Zigmond & Snaith, 1983",
     "Anxiété et dépression en milieu hospitalier non psychiatrique.",
     "Auto-questionnaire de 14 items, moins de 5 minutes.",
     "Conçue pour exclure les items somatiques, ce qui évite les faux positifs chez les patients physiquement malades.",
     "Outil de dépistage : un score élevé impose un entretien clinique, il ne le remplace pas."),

    ("epds", "EPDS", "Périnatalité", "Cox, Holden & Sagovsky, 1987",
     "Dépistage de la dépression du post-partum.",
     "Auto-questionnaire de 10 items, 5 minutes, en maternité ou en suivi.",
     "Un score ≥ 11 justifie une évaluation approfondie ; l'item 10 sur les idées suicidaires doit toujours être examiné.",
     "Outil de repérage, non diagnostique ; la honte peut conduire à minimiser les réponses."),

    ("mmse", "MMSE (Folstein)", "Neuropsychologie", "Folstein, 1975",
     "Dépistage global des troubles cognitifs : orientation, mémoire, attention, langage, praxies.",
     "Hétéro-évaluation, 10 à 15 minutes, score sur 30.",
     "Un score inférieur à 24 évoque une altération cognitive, à pondérer par le niveau d'éducation.",
     "Peu sensible aux troubles légers et aux atteintes dysexécutives ou frontales ; très influencé par la scolarité."),

    ("moca", "MoCA", "Neuropsychologie", "Nasreddine, 2005",
     "Dépistage des troubles cognitifs légers, avec une part exécutive plus importante que le MMSE.",
     "Hétéro-évaluation, 10 à 15 minutes, score sur 30.",
     "Seuil usuel de 26 ; un point est ajouté si le niveau d'études est inférieur à 12 ans.",
     "Effet plafond moindre mais fort effet de la culture et du niveau socio-éducatif."),

    ("bem", "Batterie BEM / figure de Rey", "Neuropsychologie", "Rey, 1941 ; Signoret, 1991",
     "Mémoire visuelle, planification, organisation perceptive.",
     "Individuelle : copie d'une figure complexe puis reproduction de mémoire.",
     "L'analyse du processus de copie (par blocs structurés ou par détails juxtaposés) est aussi informative que le score.",
     "Sensible aux troubles moteurs et visuels ; nécessite une cotation rigoureuse."),

    ("stroop-test", "Test de Stroop", "Neuropsychologie", "J. R. Stroop, 1935",
     "Inhibition, contrôle exécutif, flexibilité attentionnelle.",
     "Individuelle, 5 à 10 minutes, trois planches chronométrées.",
     "L'écart entre la planche d'interférence et les planches de base mesure le coût du contrôle inhibiteur.",
     "Sensible à l'âge, à la vitesse de lecture et au daltonisme ; un score isolé ne signe aucun diagnostic."),

    ("wcst", "Wisconsin Card Sorting Test", "Neuropsychologie", "Berg, 1948",
     "Flexibilité mentale, formation de concepts, sensibilité au feedback.",
     "Individuelle ou informatisée, 20 à 30 minutes.",
     "Les « erreurs persévératives » (continuer à appliquer une règle devenue caduque) sont l'indicateur clé d'une atteinte frontale.",
     "Tâche complexe mobilisant de nombreuses fonctions : un échec ne localise pas précisément une lésion."),

    ("adi-ados", "ADI-R et ADOS-2", "Développement", "Lord, Rutter et al., 1994-2012",
     "Évaluation standardisée du trouble du spectre de l'autisme.",
     "ADI-R : entretien avec les parents (1 h 30 à 3 h). ADOS-2 : observation standardisée avec la personne (40 à 60 min).",
     "Ce sont les outils de référence internationaux, toujours intégrés dans une évaluation pluridisciplinaire.",
     "Formation longue et certifiante requise ; sensibilité moindre chez les filles et les adultes qui camouflent leurs difficultés."),

    ("conners", "Échelles de Conners", "Développement", "Keith Conners, 1969-2008",
     "Symptômes du TDAH et troubles associés, évalués par les parents, l'enseignant et l'adolescent.",
     "Questionnaires de 25 à 110 items selon la version.",
     "La convergence entre les évaluateurs est essentielle, le TDAH devant se manifester dans au moins deux contextes.",
     "Sensible aux attentes de l'adulte évaluateur ; ne distingue pas toujours le TDAH d'une anxiété ou d'un trouble des apprentissages."),

    ("vineland", "Vineland-II", "Développement", "Sparrow, Balla & Cicchetti, 1984",
     "Comportements adaptatifs : communication, autonomie quotidienne, socialisation, motricité.",
     "Entretien semi-structuré avec un proche, 45 à 60 minutes.",
     "Indispensable pour évaluer le retentissement réel : deux personnes de même QI peuvent avoir une autonomie très différente.",
     "Repose sur le rapport d'un tiers, avec un risque de sur- ou sous-estimation."),

    ("aq-raads", "AQ et RAADS-R", "Dépistage", "Baron-Cohen, 2001 ; Ritvo, 2011",
     "Dépistage des traits autistiques chez l'adulte.",
     "Auto-questionnaires de 50 à 80 items, 15 à 30 minutes.",
     "Utiles comme point de départ d'une démarche diagnostique, notamment chez les adultes non repérés dans l'enfance.",
     "Ne posent jamais un diagnostic ; taux élevé de faux positifs chez les personnes anxieuses ou socialement isolées."),

    ("karasek", "Questionnaire de Karasek", "Psychologie du travail", "Robert Karasek, 1979",
     "Demande psychologique, latitude décisionnelle et soutien social au travail.",
     "Auto-questionnaire de 26 items, 10 minutes, souvent en enquête collective.",
     "Le « job strain » (forte demande + faible latitude) est associé à une augmentation significative du risque cardiovasculaire et dépressif.",
     "Mesure la perception subjective et s'interprète au niveau collectif, pas individuel."),

    ("mbi", "Maslach Burnout Inventory", "Psychologie du travail", "Christina Maslach, 1981",
     "Trois dimensions : épuisement émotionnel, dépersonnalisation, accomplissement personnel.",
     "Auto-questionnaire de 22 items, 10 minutes.",
     "Instrument de référence de la recherche sur le burn-out, décliné pour les métiers du soin, de l'éducation et les autres secteurs.",
     "Conçu pour la recherche, non pour établir un diagnostic individuel ; il n'existe pas de seuil clinique consensuel."),

    ("aai", "Entretien d'attachement adulte (AAI)", "Attachement", "George, Kaplan & Main, 1985",
     "État d'esprit actuel de l'adulte concernant ses expériences d'attachement.",
     "Entretien semi-structuré d'environ une heure, transcrit puis coté.",
     "Ce n'est pas le contenu des souvenirs qui est coté mais la cohérence du récit : classification autonome, détaché, préoccupé ou non résolu.",
     "Cotation exigeant une formation certifiante longue ; usage essentiellement en recherche."),

    ("echelles-qualite-vie", "SF-36 et WHOQOL", "Santé", "Ware, 1992 ; OMS, 1996",
     "Qualité de vie perçue : santé physique, psychologique, relations sociales, environnement.",
     "Auto-questionnaires de 26 à 36 items, 10 à 15 minutes.",
     "Permettent de suivre l'impact réel d'une maladie ou d'un traitement sur la vie quotidienne, au-delà des symptômes.",
     "Comparaisons interculturelles délicates ; la qualité de vie perçue se réajuste avec le temps (effet de réponse changeante)."),
]

# (annee, titre, description, categorie)
CHRONOLOGIE = [
    ("-400", "Hippocrate et les humeurs", "Hippocrate attribue les troubles mentaux à un déséquilibre des humeurs corporelles plutôt qu'aux dieux : première rupture avec l'explication surnaturelle.", "antiquite"),
    ("-350", "Aristote, De l'âme", "Premier traité systématique sur la perception, la mémoire, l'imagination et le sommeil. Il pose des questions encore débattues aujourd'hui.", "antiquite"),
    ("1025", "Avicenne, Le Canon de la médecine", "Description de troubles mentaux, de l'insomnie et de la mélancolie, avec des observations cliniques d'une grande finesse.", "antiquite"),
    ("1590", "Le mot « psychologie »", "Rudolf Goclenius popularise le terme dans un ouvrage latin ; il désigne alors l'étude philosophique de l'âme.", "fondations"),
    ("1637", "Descartes et le dualisme", "Le Discours de la méthode sépare l'âme pensante du corps machine — une question qui traverse toute la psychologie ultérieure.", "fondations"),
    ("1793", "Pinel libère les aliénés", "Philippe Pinel supprime les chaînes à Bicêtre et fonde le « traitement moral » : acte fondateur de la psychiatrie humaniste.", "fondations"),
    ("1848", "Le cas Phineas Gage", "Un accident révèle le rôle du cortex préfrontal dans la personnalité et le contrôle de soi.", "neurosciences"),
    ("1861", "L'aire de Broca", "Paul Broca localise la production du langage dans le lobe frontal gauche à partir du patient Leborgne, dit « Tan ».", "neurosciences"),
    ("1859", "L'Origine des espèces", "Darwin introduit l'idée d'adaptation, qui fera de la psychologie l'étude de fonctions utiles à la survie.", "fondations"),
    ("1872", "L'Expression des émotions", "Darwin décrit la continuité des expressions émotionnelles entre l'animal et l'humain.", "emotions"),
    ("1874", "Aire de Wernicke", "Carl Wernicke identifie la région de la compréhension du langage, complétant le modèle de Broca.", "neurosciences"),
    ("1879", "Le laboratoire de Leipzig", "Wundt fonde le premier laboratoire de psychologie expérimentale : acte de naissance officiel de la discipline scientifique.", "fondations"),
    ("1881", "Les Maladies de la mémoire", "Théodule Ribot formule la loi de régression de la mémoire et installe la psychologie scientifique en France.", "france"),
    ("1885", "La courbe de l'oubli", "Ebbinghaus mesure expérimentalement l'oubli et découvre l'effet d'espacement.", "apprentissage"),
    ("1889", "L'Automatisme psychologique", "Pierre Janet pose les bases de la théorie de la dissociation.", "france"),
    ("1890", "Principles of Psychology", "William James publie le traité qui formera des générations de psychologues américains.", "fondations"),
    ("1895", "Psychologie des foules", "Gustave Le Bon inaugure l'étude du comportement collectif.", "sociale"),
    ("1896", "Première clinique psychologique", "Lightner Witmer ouvre à Philadelphie la première consultation de psychologie appliquée à l'enfant.", "clinique"),
    ("1897", "Le Suicide de Durkheim", "Durkheim démontre les déterminants sociaux d'un acte réputé purement individuel.", "sociale"),
    ("1898", "Première expérience de psychologie sociale", "Triplett établit expérimentalement la facilitation sociale chez des cyclistes.", "sociale"),
    ("1900", "L'Interprétation des rêves", "Freud publie l'ouvrage fondateur de la psychanalyse.", "psychanalyse"),
    ("1904", "Adolescence", "G. Stanley Hall fait de l'adolescence une période psychologique distincte.", "developpement"),
    ("1905", "L'échelle Binet-Simon", "Naissance de la mesure de l'intelligence, conçue pour aider les élèves en difficulté.", "psychometrie"),
    ("1905", "Prix Nobel de Pavlov (1904)", "La physiologie de la digestion mène à la découverte du réflexe conditionnel.", "apprentissage"),
    ("1912", "La psychologie de la forme", "Wertheimer, Köhler et Koffka fondent la Gestalt : le tout est différent de la somme des parties.", "cognitive"),
    ("1913", "Le manifeste behavioriste", "Watson exclut la conscience du champ de la psychologie scientifique.", "apprentissage"),
    ("1920", "Le petit Albert", "Watson et Rayner démontrent le conditionnement d'une phobie chez un nourrisson.", "apprentissage"),
    ("1921", "Le test de Rorschach", "Publication du Psychodiagnostic, un an avant la mort de son auteur.", "psychometrie"),
    ("1921", "Types psychologiques", "Jung introduit introversion et extraversion, notions reprises par toute la psychologie de la personnalité.", "personnalite"),
    ("1924", "Les études Hawthorne", "La découverte accidentelle de l'effet de l'attention portée aux salariés fonde la psychologie du travail moderne.", "travail"),
    ("1927", "Effet Zeigarnik", "Bluma Zeigarnik montre que les tâches inachevées restent mieux en mémoire.", "cognitive"),
    ("1934", "Pensée et langage", "Vygotski, mort la même année, laisse une œuvre majeure sur le rôle du social dans le développement.", "developpement"),
    ("1935", "L'effet Stroop", "Une tâche simple devient le test de référence du contrôle exécutif.", "cognitive"),
    ("1936", "La naissance de l'intelligence", "Piaget décrit les stades du développement cognitif.", "developpement"),
    ("1938", "La boîte de Skinner", "Formalisation du conditionnement opérant et des programmes de renforcement.", "apprentissage"),
    ("1939", "L'échelle de Wechsler", "Wechsler crée le test d'intelligence pour adultes qui domine encore la pratique.", "psychometrie"),
    ("1943", "Le MMPI", "Premier grand inventaire de personnalité à visée clinique, avec échelles de validité.", "psychometrie"),
    ("1943", "La hiérarchie des besoins", "Maslow publie sa théorie de la motivation humaine.", "humaniste"),
    ("1949", "La règle de Hebb", "« Les neurones qui s'activent ensemble se lient ensemble » : fondement de la plasticité et des réseaux de neurones.", "neurosciences"),
    ("1951", "Le conformisme d'Asch", "Trois lignes suffisent à révéler le poids du groupe sur le jugement individuel.", "sociale"),
    ("1952", "Découverte des neuroleptiques", "La chlorpromazine transforme le pronostic de la schizophrénie et vide progressivement les asiles.", "clinique"),
    ("1953", "Le patient H.M.", "L'opération d'Henry Molaison révèle le rôle de l'hippocampe dans la formation des souvenirs.", "neurosciences"),
    ("1954", "La caverne des voleurs", "Sherif fabrique puis résout un conflit intergroupe dans un camp de vacances.", "sociale"),
    ("1956", "Le nombre magique sept", "Miller établit les limites de la mémoire immédiate et lance la révolution cognitive.", "cognitive"),
    ("1957", "La dissonance cognitive", "Festinger montre comment nos actes transforment nos croyances.", "sociale"),
    ("1958", "Les singes de Harlow", "Le réconfort tactile prime sur la nourriture dans l'attachement.", "developpement"),
    ("1959", "Chomsky contre Skinner", "La recension de Verbal Behavior fragilise durablement le behaviorisme.", "cognitive"),
    ("1960", "Center for Cognitive Studies", "Bruner et Miller institutionnalisent les sciences cognitives à Harvard.", "cognitive"),
    ("1961", "La poupée Bobo", "Bandura démontre l'apprentissage par observation.", "apprentissage"),
    ("1963", "L'obéissance de Milgram", "65 % des participants vont jusqu'au voltage maximal.", "sociale"),
    ("1967", "L'impuissance apprise", "Seligman propose un modèle expérimental de la dépression.", "clinique"),
    ("1968", "L'effet du témoin", "Darley et Latané expliquent la passivité collective face à l'urgence.", "sociale"),
    ("1969", "La situation étrange", "Ainsworth crée le protocole de référence des styles d'attachement.", "developpement"),
    ("1971", "La prison de Stanford", "L'expérience de Zimbardo, aujourd'hui très contestée, marque durablement la discipline.", "sociale"),
    ("1971", "Les groupes minimaux", "Tajfel montre qu'un critère trivial suffit à créer une discrimination intergroupe.", "sociale"),
    ("1972", "Le test du marshmallow", "Mischel étudie le report de gratification chez l'enfant.", "developpement"),
    ("1973", "L'étude de Rosenhan", "Huit pseudo-patients ébranlent la fiabilité du diagnostic psychiatrique.", "clinique"),
    ("1973", "Retrait de l'homosexualité du DSM", "L'APA cesse de considérer l'homosexualité comme un trouble mental.", "clinique"),
    ("1974", "Heuristiques et biais", "Tversky et Kahneman publient l'article fondateur de l'économie comportementale.", "cognitive"),
    ("1974", "La déformation du témoignage", "Loftus démontre l'influence des mots sur la mémoire des témoins.", "legale"),
    ("1974", "Mémoire de travail", "Baddeley et Hitch proposent un modèle à composantes multiples.", "cognitive"),
    ("1977", "Le sentiment d'efficacité personnelle", "Bandura formule un concept devenu central en motivation.", "motivation"),
    ("1979", "MBSR", "Kabat-Zinn introduit la pleine conscience dans un hôpital américain.", "therapies"),
    ("1979", "La thérapie cognitive de la dépression", "Beck publie le manuel qui installe les TCC.", "therapies"),
    ("1979", "Modèle écologique", "Bronfenbrenner replace le développement dans des systèmes emboîtés.", "developpement"),
    ("1980", "DSM-III", "Bascule vers des critères diagnostiques opérationnels et athéoriques.", "clinique"),
    ("1980", "Dimensions culturelles", "Hofstede publie la première grande comparaison interculturelle à grande échelle.", "interculturelle"),
    ("1983", "Les intelligences multiples", "Gardner conteste l'idée d'une intelligence unique.", "psychometrie"),
    ("1983", "Le test de Sally et Anne", "Naissance de l'étude expérimentale de la théorie de l'esprit.", "developpement"),
    ("1987", "EMDR", "Francine Shapiro développe une approche du trauma qui sera largement validée.", "therapies"),
    ("1990", "L'intelligence émotionnelle", "Salovey et Mayer formalisent le concept que Goleman popularisera en 1995.", "emotions"),
    ("1992", "Neurones miroirs", "L'équipe de Rizzolatti fait une découverte aussi célèbre que débattue.", "neurosciences"),
    ("1993", "La TCD", "Linehan publie le premier traitement validé du trouble borderline.", "therapies"),
    ("1994", "L'erreur de Descartes", "Damasio montre que l'émotion est nécessaire à la décision.", "emotions"),
    ("1998", "La psychologie positive", "Seligman lance le mouvement lors de sa présidence de l'APA.", "positive"),
    ("2005", "Imagerie cérébrale de masse", "L'IRM fonctionnelle devient un outil courant, avec ses promesses et ses excès interprétatifs.", "neurosciences"),
    ("2010", "Le biais WEIRD", "Henrich montre que la psychologie s'est construite sur des échantillons très atypiques.", "interculturelle"),
    ("2011", "Système 1 / Système 2", "Kahneman synthétise quarante ans de recherche pour le grand public.", "cognitive"),
    ("2013", "DSM-5", "Introduction du spectre autistique et de l'hyperphagie boulimique, abandon des axes.", "clinique"),
    ("2015", "La crise de la réplication", "Le Reproducibility Project ne reproduit que 36 % des résultats testés : la discipline engage sa réforme méthodologique.", "methodes"),
    ("2018", "CIM-11", "L'OMS reconnaît le TSPT complexe et le trouble du jeu vidéo.", "clinique"),
    ("2019", "Preregistration généralisée", "Les revues adoptent massivement l'enregistrement préalable des protocoles et les rapports enregistrés.", "methodes"),
    ("2020", "Santé mentale et pandémie", "La crise du Covid-19 provoque une hausse mondiale de l'anxiété et de la dépression, et accélère la téléconsultation.", "sante"),
]
