# -*- coding: utf-8 -*-
"""
Crédits des illustrations.

Chaque entrée : (fichier local, titre du fichier sur Wikimedia Commons,
licence, description). Les licences ont été relevées via l'API de Commons
et vérifiées une à une : toutes sont libres (domaine public, CC0, CC BY,
CC BY-SA). Les licences CC BY et CC BY-SA imposent de citer la source,
ce que fait la page `credits.html`.
"""

CREDITS = [
    ("courbe-oubli-ebbinghaus.svg", "ForgettingCurve.svg", "Domaine public", "Courbe de l'oubli d'Ebbinghaus"),
    ("illusion-muller-lyer.svg", "Müller-Lyer illusion.svg", "CC BY-SA 3.0", "Illusion de Müller-Lyer"),
    ("cube-necker.svg", "Necker cube.svg", "CC BY-SA 3.0", "Cube de Necker"),
    ("vase-rubin.svg", "Cup or faces paradox.svg", "CC BY-SA 3.0", "Vase de Rubin (figure et fond)"),
    ("triangle-kanizsa.svg", "Kanizsa triangle.svg", "CC BY-SA 3.0", "Triangle de Kanizsa"),
    ("illusion-ebbinghaus.svg", "Ebbinghaus Illusion.svg", "CC0", "Illusion d'Ebbinghaus (cercles de Titchener)"),
    ("neurone.svg", "Neuron Hand-tuned.svg", "CC BY-SA 3.0", "Structure d'un neurone"),
    ("neurone-complet-fr.svg", "Complete neuron cell diagram fr.svg", "Domaine public", "Anatomie du neurone, légendée en français"),
    ("synapse-chimique.jpg", "Chemical synapse schema cropped.jpg", "Domaine public", "La synapse chimique"),
    ("aires-brodmann.png", "Brodmann areas 3D.png", "Domaine public", "Les aires corticales de Brodmann"),
    ("homonculus-sensoriel.jpg", "1421 Sensory Homunculus.jpg", "CC BY 3.0", "Homoncule sensoriel de Penfield"),
    ("hippocampe.png", "Gray739-emphasizing-hippocampus.png", "Domaine public", "L'hippocampe"),
    ("systeme-limbique.png", "Blausen 0614 LimbicSystem.png", "CC BY 3.0", "Le système limbique"),
    ("corps-calleux.png", "Corpus callosum.png", "CC BY-SA 2.1 jp", "Le corps calleux"),
    ("cerveau-lobes-fr.svg", "Cerebrum lobes-FR.svg", "CC BY-SA 3.0", "Les lobes du cortex, légendés en français"),
    ("cerveau-lobes.png", "Lobes du cerveau humain.png", "Domaine public", "Lobes du cerveau humain"),
    ("cerveau-humain.svg", "Brain-diagram-pink-6289600.svg", "CC0", "Coupe du cerveau humain"),
    ("loi-yerkes-dodson.svg", "HebbianYerkesDodson.svg", "CC0", "Loi de Yerkes-Dodson"),
    ("roue-emotions-plutchik.svg", "Plutchik-wheel.svg", "Domaine public", "Roue des émotions de Plutchik"),
    ("pyramide-maslow.svg", "Pyramide des besoins de Maslow.svg", "CC BY-SA 4.0", "Pyramide des besoins de Maslow"),
    ("fenetre-johari.png", "Johari Window.PNG", "Domaine public", "Fenêtre de Johari"),
    ("conditionnement-pavlov.svg", "Pavlov's dog conditioning.svg", "CC BY-SA 4.0", "Schéma du conditionnement classique"),
    ("boite-skinner.png", "Skinner box scheme 01.png", "CC BY-SA 3.0", "Boîte de Skinner"),
    ("courbe-gauss.svg", "Normal Distribution PDF.svg", "Domaine public", "Distribution normale"),
    ("phrenologie.jpg", "PhrenologyPix.jpg", "Domaine public", "Planche de phrénologie"),
    ("rorschach-planche-1.jpg", "Normalized Rorschach blot 01.jpg", "Domaine public", "Planche I du test de Rorschach"),
    ("rorschach-planche-2.jpg", "Rorschach blot 02.jpg", "Domaine public", "Planche II du test de Rorschach"),
    ("phineas-gage.jpg", "Phineas Gage Cased Daguerreotype WilgusPhoto2008-12-19 Unretouched Color.jpg", "CC BY-SA 3.0", "Daguerréotype de Phineas Gage"),
    ("portrait-wundt.jpg", "Dora Arnd-Raschid - Portrait Wilhelm Wundt, 1898.png", "Domaine public", "Wilhelm Wundt"),
    ("portrait-james.jpg", "William James self-portrait.jpg", "Domaine public", "William James"),
    ("portrait-freud.jpg", "Sigmund Freud 1926.jpg", "Domaine public", "Sigmund Freud"),
    ("portrait-anna-freud.jpg", "Anna Freud 1957.jpg", "CC0", "Anna Freud"),
    ("portrait-jung.jpg", "Carl Gustav Jung portrait.jpg", "Domaine public", "Carl Gustav Jung"),
    ("portrait-adler.jpg", "Alfred Adler.jpg", "Domaine public", "Alfred Adler"),
    ("portrait-piaget.jpg", "Jean Piaget in Ann Arbor.png", "Domaine public", "Jean Piaget"),
    ("portrait-vygotski.jpg", "Lev Vygotsky 1896-1934.jpg", "CC BY-SA 3.0", "Lev Vygotski"),
    ("portrait-pavlov.jpg", "Françoise Foliot - Portrait du professeur Pavlov.jpg", "CC BY-SA 4.0", "Ivan Pavlov"),
    ("portrait-watson.jpg", "John Broadus Watson.JPG", "Domaine public", "John B. Watson"),
    ("portrait-thorndike.jpg", "PSM V80 D211 Edward Lee Thorndike.png", "Domaine public", "Edward Thorndike"),
    ("portrait-rogers.jpg", "Carl Rogers.jpg", "CC BY-SA 4.0", "Carl Rogers"),
    ("portrait-ebbinghaus.jpg", "Ebbinghaus2.jpg", "Domaine public", "Hermann Ebbinghaus"),
    ("portrait-fechner.jpg", "Gustav Fechner.jpg", "Domaine public", "Gustav Fechner"),
    ("portrait-helmholtz.jpg", "Hermann von Helmholtz.jpg", "Domaine public", "Hermann von Helmholtz"),
    ("portrait-galton.jpg", "Francis Galton 1850s.jpg", "Domaine public", "Francis Galton"),
    ("portrait-binet.jpg", "Alfred Binet.jpg", "Domaine public", "Alfred Binet"),
    ("portrait-pinel.jpg", "Philippe Pinel.jpg", "Domaine public", "Philippe Pinel"),
    ("portrait-broca.jpg", "Paul Broca 2.jpg", "Domaine public", "Paul Broca"),
    ("portrait-wernicke.jpg", "Carl Wernicke.png", "Domaine public", "Carl Wernicke"),
    ("portrait-charcot.jpg", "Charcot Jean-Martin Gallica Nadar.jpg", "Domaine public", "Jean-Martin Charcot"),
    ("portrait-janet.jpg", "Pierre Janet Marie Felix.jpg", "CC BY 4.0", "Pierre Janet"),
    ("portrait-ribot.jpg", "(Toulouse) Théodule Ribot vers 1880 par Ferdinand Mulnier - Paris musée d'Orsay.jpg", "Domaine public", "Théodule Ribot"),
    ("portrait-taine.jpg", "Portrait of Hippolyte Taine by Bonnat.jpg", "Domaine public", "Hippolyte Taine"),
    ("portrait-durkheim.jpg", "Portrait of Emile Durkheim in \"a collection of essays, with translations and a bibliography\".jpg", "Domaine public", "Émile Durkheim"),
    ("portrait-le-bon.jpg", "Gustave Le Bon.jpg", "Domaine public", "Gustave Le Bon"),
    ("portrait-lombroso.jpg", "Cesare Lombroso psychical researcher.png", "Domaine public", "Cesare Lombroso"),
    ("portrait-darwin.jpg", "Charles Robert Darwin by John Collier.jpg", "Domaine public", "Charles Darwin"),
    ("portrait-lorenz.jpg", "Konrad Lorenz.JPG", "CC BY-SA 3.0", "Konrad Lorenz"),
    ("portrait-koffka.jpg", "Kurt Koffka.jpg", "Domaine public", "Kurt Koffka"),
    ("portrait-kohler.jpg", "Wolfgang Köhler.jpg", "CC BY-SA 2.5", "Wolfgang Köhler"),
    ("portrait-hall.jpg", "Granville Stanley Hall.jpg", "Domaine public", "G. Stanley Hall"),
    ("portrait-titchener.jpg", "Edward B. Titchener.jpg", "Domaine public", "Edward Titchener"),
    ("golgi-pyramidal.jpg", "GolgiStainedPyramidalCell.jpg", "Domaine public", "Cellule pyramidale, coloration de Golgi"),
    ("cajal-hippocampe.jpg", "CajalHippocampus.jpeg", "Domaine public", "Hippocampe dessiné par Cajal"),
    ("portrait-cajal.jpg", "Santiago Ramón y Cajal (1852-1934) portrait (restored).jpg", "Domaine public", "Santiago Ramón y Cajal"),
    ("portrait-golgi.jpg", "Camillo Golgi.jpg", "Domaine public", "Camillo Golgi"),
    ("portrait-penfield.jpg", "Wilder Penfield.jpg", "Domaine public", "Wilder Penfield"),
    ("portrait-berger.jpg", "Hans Berger 1938.jpg", "Domaine public", "Hans Berger"),
    ("eeg-1020.jpg", "International 10-20 system for EEG-MCN.png", "CC BY-SA 3.0", "Système international 10-20 de l'EEG"),
    ("irm-sagittal.jpg", "MRI brain sagittal section.jpg", "CC BY-SA 3.0", "IRM sagittale du cerveau"),
    ("irm-axial.jpg", "MRI Brain ADC Axial (1).jpg", "CC BY-SA 4.0", "IRM axiale du cerveau"),
    ("dti-fibres.jpg", "DTI-sagittal-fibers.jpg", "CC BY 3.0", "Tractographie par tenseur de diffusion"),
    ("tms-bobine.jpg", "Transcranial magnetic stimulation.jpg", "CC BY-SA 3.0", "Bobine de stimulation magnétique transcrânienne"),
    ("vesale-cerveau.jpg", "The entire human brain and cerebellum, by Vesalius. Wellcome L0003677.jpg", "Domaine public", "Cerveau dans la Fabrica de Vésale"),
    ("gray-base.jpg", "Gray718.png", "Domaine public", "Base du cerveau, Gray's Anatomy"),
    ("gray-ventricules.jpg", "Gray734.png", "Domaine public", "Ventricules, Gray's Anatomy"),
    ("leborgne-cerveau.jpg", "Cerveau de Louis Victor Leborgne dit Tantan 1.jpg", "CC BY-SA 4.0", "Cerveau de Leborgne (Tan)"),
    ("cajal-cortex.png", "Cajal cortex drawings.png", "Domaine public", "Dessins de cortex par Cajal"),
    ("premier-eeg.png", "1st-eeg.png", "Domaine public", "Premier tracé EEG"),
    ("broca-wernicke.jpg", "1605 Brocas and Wernickes Areas-02.jpg", "CC BY 4.0", "Aires de Broca et de Wernicke"),
    ("eeg-enregistrement.jpg", "EEG recording.jpg", "CC BY-SA 4.0", "Enregistrement EEG"),
]

# Ouvrages du domaine public et bibliothèque d'origine.
SOURCES_LIVRES = [
    ("Internet Archive", "https://archive.org",
     "Numérisations de James, Taine, Le Bon, Durkheim, Ribot, Janet, Charcot et Lombroso."),
    ("Gallica — Bibliothèque nationale de France", "https://gallica.bnf.fr",
     "Fonds patrimonial français : ouvrages de psychologie et de médecine du XIXe siècle."),
    ("Project Gutenberg", "https://www.gutenberg.org",
     "Transcriptions HTML intégrales, notamment de Binet et de Le Bon."),
    ("Les Classiques des sciences sociales (UQAC)", "http://classiques.uqac.ca",
     "Éditions numériques françaises de Durkheim, Janet et Ribot."),
    ("Darwin Online", "http://darwin-online.org.uk",
     "Édition de référence de L'expression des émotions chez l'homme et les animaux."),
    ("Wikimedia Commons", "https://commons.wikimedia.org",
     "Ensemble des illustrations, portraits et schémas de ce guide."),
]
