# -*- coding: utf-8 -*-
"""Les grands modèles théoriques de la psychologie, expliqués et mis en perspective."""

# (id, nom, auteur, annee, domaine, idee, mecanisme, application, limite)
THEORIES = [
    ("conditionnement-classique", "Conditionnement classique", "Ivan Pavlov", "1897", "Apprentissage",
     "Un stimulus neutre qui annonce régulièrement un événement important finit par déclencher lui-même la réaction.",
     "Le cerveau détecte les régularités temporelles : si un signal précède fidèlement une conséquence, il devient un prédicteur. Le modèle de Rescorla-Wagner a précisé que l'apprentissage dépend de la <em>surprise</em> — on n'apprend que ce qui n'était pas déjà prévu.",
     "Traitement des phobies par exposition, compréhension des aversions alimentaires, des réactions de stress déclenchées par un lieu, ou du craving dans les addictions.",
     "Le modèle n'explique pas les apprentissages volontaires ni les comportements nouveaux. Il décrit des associations, pas des décisions."),

    ("conditionnement-operant", "Conditionnement opérant", "B. F. Skinner", "1938", "Apprentissage",
     "Un comportement se répète en fonction de ses conséquences : renforcé il augmente, puni ou ignoré il diminue.",
     "Quatre contingences : renforcement positif (on ajoute quelque chose d'agréable), renforcement négatif (on retire quelque chose de désagréable), punition positive, punition négative. Le <em>programme</em> de renforcement compte autant que le renforcement lui-même : les récompenses imprévisibles (ratio variable) produisent les comportements les plus résistants.",
     "Éducation, rééducation, gestion des comportements en institution, dressage animal — et, du côté sombre, conception des machines à sous et des applications à défilement infini.",
     "Ignore ce qui se passe entre le stimulus et la réponse. Les renforcements matériels peuvent aussi détruire la motivation intrinsèque (effet de surjustification)."),

    ("apprentissage-social", "Apprentissage social et auto-efficacité", "Albert Bandura", "1977", "Apprentissage",
     "On apprend massivement en observant les autres, sans avoir soi-même été récompensé ni puni.",
     "L'apprentissage vicariant suppose quatre étapes : attention au modèle, rétention en mémoire, reproduction motrice, motivation. Bandura y ajoute le sentiment d'<em>auto-efficacité</em> : la croyance en sa propre capacité à réussir une tâche, qui prédit l'effort fourni et la persistance face à l'échec.",
     "Formation par démonstration, mentorat, modèles positifs en prévention santé, entraînement à la prise de parole, rééducation après un échec scolaire.",
     "Le concept d'auto-efficacité est parfois utilisé de façon si large qu'il devient difficile à falsifier ; mesurer précisément l'influence d'un modèle reste délicat."),

    ("stades-piaget", "Stades du développement cognitif", "Jean Piaget", "1936", "Développement",
     "L'intelligence de l'enfant n'est pas une version réduite de celle de l'adulte : elle change de nature par paliers.",
     "Quatre stades — sensorimoteur (0-2 ans), préopératoire (2-7), opératoire concret (7-11), opératoire formel (11+) — franchis par assimilation (intégrer le nouveau dans ses schémas) et accommodation (modifier ses schémas pour accueillir le nouveau).",
     "Adapter les attentes scolaires à l'âge, comprendre pourquoi un enfant de 5 ans échoue aux tâches de conservation, concevoir des supports pédagogiques manipulables.",
     "Les âges sont surestimés : des versions simplifiées des épreuves montrent des compétences bien plus précoces. Les stades sont moins tranchés et plus dépendants du domaine que Piaget ne le pensait."),

    ("zone-proximale", "Zone proximale de développement", "Lev Vygotski", "1934", "Développement",
     "Ce que l'enfant sait faire aujourd'hui avec de l'aide, il saura le faire seul demain.",
     "Entre le niveau de développement actuel et le niveau potentiel s'ouvre une zone où l'apprentissage est possible grâce à l'étayage d'un adulte ou d'un pair plus avancé. Le langage, d'abord social, devient progressivement langage intérieur et outil de pensée.",
     "Pédagogie de l'étayage, tutorat entre élèves, différenciation, apprentissage coopératif, retrait progressif de l'aide (<em>fading</em>).",
     "La notion, restée programmatique à la mort précoce de Vygotski, n'est pas définie de façon opérationnelle : on ne sait pas mesurer objectivement la largeur de cette zone."),

    ("attachement", "Théorie de l'attachement", "John Bowlby & Mary Ainsworth", "1969", "Développement",
     "Le besoin de proximité avec une figure protectrice est un besoin primaire, aussi fondamental que la faim.",
     "La figure d'attachement joue deux rôles : base de sécurité pour explorer, havre de réconfort en cas de détresse. La qualité des réponses de l'adulte construit des « modèles internes opérants » — des attentes implicites sur la disponibilité d'autrui, observables dès 12 mois dans la Situation étrange.",
     "Soutien à la parentalité, accueil en crèche, compréhension des difficultés relationnelles à l'âge adulte, prise en charge en protection de l'enfance.",
     "Les styles d'attachement ne sont ni figés ni déterministes : la stabilité entre l'enfance et l'âge adulte est modérée. Les catégories varient selon les cultures et les pratiques éducatives."),

    ("psychosocial-erikson", "Les huit âges de la vie", "Erik Erikson", "1950", "Développement",
     "Le développement ne s'arrête pas à l'adolescence : chaque âge de la vie pose une tension propre à résoudre.",
     "Huit crises successives, de la confiance contre la méfiance du nourrisson à l'intégrité contre le désespoir du grand âge, en passant par l'identité contre la confusion des rôles à l'adolescence. Chaque résolution réussie ajoute une force (espoir, volonté, fidélité, amour, sollicitude, sagesse).",
     "Cadre de lecture des transitions de vie : adolescence, parentalité, crise du milieu de vie, retraite, fin de vie. Très utilisé en gérontologie et en accompagnement.",
     "Modèle descriptif et culturellement situé (Amérique du Nord du milieu du XXe siècle), difficile à tester expérimentalement."),

    ("memoire-atkinson", "Modèle modal de la mémoire", "Richard Atkinson & Richard Shiffrin", "1968", "Cognition",
     "La mémoire n'est pas un réservoir unique mais une chaîne de systèmes aux propriétés différentes.",
     "Trois magasins : registre sensoriel (quelques centaines de millisecondes), mémoire à court terme (durée et capacité limitées), mémoire à long terme (capacité pratiquement illimitée). Le passage de l'un à l'autre dépend de l'attention puis du traitement.",
     "Comprendre pourquoi une information entendue disparaît si elle n'est pas traitée, structurer un cours, expliquer les effets de primauté et de récence.",
     "Trop linéaire : le simple maintien d'une information ne suffit pas à la mémoriser. C'est la profondeur du traitement qui compte, et la mémoire de travail s'est révélée bien plus qu'un magasin passif."),

    ("memoire-travail", "Mémoire de travail", "Alan Baddeley & Graham Hitch", "1974", "Cognition",
     "Le court terme n'est pas un simple stockage : c'est un espace de travail actif où l'on manipule l'information.",
     "Un administrateur central pilote l'attention et coordonne deux systèmes esclaves : la boucle phonologique (matériel verbal) et le calepin visuo-spatial (images et positions). Un tampon épisodique, ajouté en 2000, relie ces informations à la mémoire à long terme.",
     "Expliquer les difficultés de calcul mental, la charge cognitive en classe, l'impact du bruit sur le travail, les troubles de l'apprentissage et les effets du vieillissement.",
     "Les frontières entre les composants restent débattues ; d'autres modèles décrivent plutôt la mémoire de travail comme l'activation focalisée d'une partie de la mémoire à long terme."),

    ("niveaux-traitement", "Niveaux de traitement", "Fergus Craik & Robert Lockhart", "1972", "Cognition",
     "On ne retient pas ce qu'on répète, on retient ce qu'on a traité en profondeur.",
     "Un traitement superficiel (la forme du mot, sa sonorité) laisse une trace fragile ; un traitement sémantique (le sens, le lien avec soi, l'élaboration) laisse une trace durable. L'effet d'auto-référence — rapporter l'information à soi — est l'un des plus puissants.",
     "Méthodes d'étude efficaces : reformuler, expliquer à quelqu'un, relier à des exemples personnels plutôt que surligner et relire.",
     "La « profondeur » est difficile à définir sans circularité : on la mesure par ce qu'elle produit. La nature de la tâche de restitution compte aussi (principe de spécificité de l'encodage)."),

    ("charge-cognitive", "Théorie de la charge cognitive", "John Sweller", "1988", "Éducation",
     "Apprendre échoue quand on dépasse les limites de la mémoire de travail, pas quand on manque d'intelligence.",
     "Trois charges se cumulent : intrinsèque (complexité propre du contenu), extrinsèque (imposée par une présentation maladroite), essentielle (celle qui construit réellement les schémas). L'objectif pédagogique est de réduire la charge extrinsèque pour libérer des ressources.",
     "Conception de supports : éviter de dédoubler la même information en texte et en voix, intégrer les légendes dans les schémas, donner des exemples résolus avant les exercices, segmenter les vidéos.",
     "Mesurer la charge cognitive reste indirect (questionnaires, temps de réaction secondaire). Certaines prédictions s'inversent chez les apprenants experts (effet de renversement de l'expertise)."),

    ("dissonance-cognitive", "Dissonance cognitive", "Leon Festinger", "1957", "Social",
     "Quand nos actes contredisent nos idées, ce sont souvent nos idées qui plient.",
     "L'incohérence entre deux cognitions produit un inconfort que l'on réduit par le chemin le plus économique : changer d'avis, minimiser l'enjeu, ajouter une justification. L'effet est maximal quand l'acte a été posé librement, publiquement et sans forte récompense externe.",
     "Comprendre la persistance des croyances après démenti, l'engagement militant, la rationalisation des achats coûteux, les techniques de manipulation par engagement (pied-dans-la-porte).",
     "La théorie explique beaucoup après coup et prédit moins bien à l'avance. Des interprétations concurrentes (théorie de l'auto-perception de Bem) rendent compte d'une partie des mêmes résultats."),

    ("attribution", "Théorie de l'attribution", "Fritz Heider, Harold Kelley, Bernard Weiner", "1958-1985", "Social",
     "Nous sommes des détectives de causes : expliquer les comportements est une activité mentale permanente.",
     "On attribue un comportement à la personne (cause interne) ou à la situation (cause externe), selon trois informations : le consensus, la distinctivité et la constance. Weiner ajoute deux dimensions décisives pour la motivation : la stabilité et la contrôlabilité de la cause.",
     "Comprendre l'échec scolaire (« je suis nul » contre « je n'ai pas assez travaillé cette fois »), l'entretien d'évaluation, les conflits de couple, la stigmatisation des personnes au chômage.",
     "Le fameux « biais fondamental d'attribution » est nettement plus faible dans les cultures collectivistes : ce n'est pas une loi universelle du raisonnement."),

    ("identite-sociale", "Identité sociale", "Henri Tajfel & John Turner", "1979", "Social",
     "Une partie de ce que nous sommes vient des groupes auxquels nous appartenons — et cela suffit à créer des préjugés.",
     "Trois processus : catégorisation (classer le monde en groupes), identification (s'y inclure), comparaison (chercher une supériorité de son groupe pour nourrir son estime de soi). Les expériences de groupes minimaux montrent qu'une division totalement arbitraire déclenche déjà du favoritisme.",
     "Analyser les rivalités d'équipes, les conflits intercommunautaires, la cohésion en entreprise, les stratégies de réduction des préjugés (buts supraordonnés, identité commune).",
     "Le modèle explique le favoritisme envers son groupe mieux que l'hostilité active envers l'autre, qui demande d'autres ingrédients (menace réelle, idéologie, autorisation sociale)."),

    ("comportement-planifie", "Comportement planifié", "Icek Ajzen", "1991", "Social / Santé",
     "L'intention d'agir dépend de trois choses, et l'intention ne suffit pas toujours à passer à l'acte.",
     "L'attitude envers le comportement, les normes subjectives (ce que les proches approuvent) et le contrôle perçu déterminent l'intention. Le contrôle perçu influence aussi directement le comportement lorsqu'il reflète des contraintes réelles.",
     "Campagnes de prévention (tabac, vaccination, sécurité routière), marketing social, conception d'interventions en santé publique.",
     "Le fossé intention-comportement reste large : beaucoup d'intentions ne se réalisent jamais. Les modèles récents ajoutent les habitudes, les émotions et les plans d'action concrets (<em>implementation intentions</em>)."),

    ("big-five", "Modèle en cinq facteurs", "Paul Costa & Robert McCrae", "1987", "Personnalité",
     "La personnalité normale se résume assez bien à cinq grandes dimensions continues.",
     "Ouverture, Conscienciosité, Extraversion, Agréabilité, Névrosisme — dimensions obtenues par analyse factorielle du vocabulaire décrivant les personnes, retrouvées dans des dizaines de langues. Chacune se décompose en facettes plus fines.",
     "Sélection professionnelle (la conscienciosité prédit modestement mais régulièrement la performance), orientation, recherche en santé, compréhension des différences individuelles.",
     "Descriptif plutôt qu'explicatif : le modèle dit <em>quoi</em>, pas <em>pourquoi</em>. Il ignore le contexte et néglige les traits sombres ; les corrélations avec les résultats de vie sont réelles mais faibles individuellement."),

    ("hierarchie-maslow", "Hiérarchie des besoins", "Abraham Maslow", "1943", "Motivation",
     "Les besoins humains s'organiseraient en niveaux, des plus vitaux aux plus personnels.",
     "Besoins physiologiques, de sécurité, d'appartenance, d'estime, puis d'accomplissement de soi. Maslow lui-même n'a jamais dessiné de pyramide : la figure a été ajoutée par des consultants en management dans les années 1960.",
     "Grille de lecture intuitive en management, en travail social, en marketing — utile pour rappeler qu'on ne se forme pas correctement quand on a froid ou peur.",
     "La hiérarchie stricte est empiriquement fausse : des personnes en grande précarité créent, aiment et s'accomplissent. Le modèle n'a jamais été validé sérieusement, ce qui n'a pas nui à sa popularité."),

    ("autodetermination", "Théorie de l'autodétermination", "Edward Deci & Richard Ryan", "1985", "Motivation",
     "La motivation durable vient de trois besoins psychologiques, pas des récompenses.",
     "Autonomie (choisir), compétence (progresser), affiliation (compter pour quelqu'un). Quand ils sont satisfaits, la motivation devient intrinsèque ou bien intégrée ; quand on les contraint par des récompenses ou des menaces, la motivation se dégrade — c'est l'effet de surjustification.",
     "Management, pédagogie, santé, sport, conception d'applications : proposer des choix, rendre les progrès visibles, créer de l'appartenance plutôt qu'empiler les primes et les points.",
     "La frontière entre soutien de l'autonomie et laisser-faire est ténue ; l'effet délétère des récompenses dépend fortement du type de tâche et de la manière dont elles sont présentées."),

    ("flow", "Théorie du flow", "Mihály Csíkszentmihályi", "1975", "Motivation",
     "L'état optimal d'engagement survient quand la difficulté rencontre exactement le niveau de compétence.",
     "Trop facile : ennui. Trop difficile : anxiété. Dans le couloir étroit entre les deux, avec un but clair et un retour immédiat, la conscience de soi s'efface et le temps se déforme.",
     "Conception pédagogique et de jeux vidéo, design d'exercices progressifs, organisation du travail par blocs de concentration, pratique musicale et sportive.",
     "L'état est mesuré presque exclusivement par auto-déclaration rétrospective ; la relation causale entre flow et performance est difficile à démêler."),

    ("mindset", "Théories implicites de l'intelligence", "Carol Dweck", "2006", "Éducation",
     "Croire que l'intelligence peut se développer change la façon d'affronter l'échec.",
     "Un état d'esprit « fixe » traite l'erreur comme un verdict sur sa valeur ; un état d'esprit « de développement » la traite comme une information. Le second favorise la persévérance et la recherche de défis.",
     "Retours pédagogiques centrés sur la stratégie et l'effort plutôt que sur le talent, réduction de la peur de l'erreur, accompagnement des élèves en difficulté.",
     "Les méta-analyses récentes montrent des effets réels mais bien plus modestes que la version popularisée ; les interventions brèves marchent surtout chez les élèves fragiles, et mal implantées elles ne font rien."),

    ("appraisal-lazarus", "Modèle transactionnel du stress", "Richard Lazarus & Susan Folkman", "1984", "Émotions / Santé",
     "Le stress n'est pas dans l'événement : il naît de l'évaluation qu'on en fait.",
     "Évaluation primaire : est-ce une menace, un défi, une perte ? Évaluation secondaire : ai-je les ressources pour y faire face ? Le coping qui suit est centré sur le problème (agir) ou sur l'émotion (réguler son ressenti) — aucun n'est supérieur dans l'absolu, tout dépend de la contrôlabilité.",
     "Gestion du stress professionnel, préparation aux examens, accompagnement de la maladie chronique, thérapies cognitives.",
     "Les évaluations sont reconstruites après coup par les participants, ce qui rend la causalité difficile à établir. Les réponses physiologiques précèdent parfois l'évaluation consciente."),

    ("james-lange", "Théories des émotions", "William James, Walter Cannon, Stanley Schachter", "1884-1962", "Émotions",
     "Le débat fondateur : le corps précède-t-il le sentiment, ou l'inverse ?",
     "James-Lange : nous avons peur <em>parce que</em> nous tremblons. Cannon-Bard : corps et sentiment surviennent en parallèle. Schachter-Singer : l'émotion est une activation physiologique diffuse à laquelle on colle une étiquette cognitive fournie par le contexte.",
     "Comprendre pourquoi agir sur le corps (respiration lente, cohérence cardiaque, posture) modifie réellement le ressenti, et pourquoi le même emballement cardiaque peut se lire comme peur ou comme désir.",
     "Aucune des trois versions ne suffit seule. Les théories contemporaines (émotion construite, Barrett) proposent que l'émotion soit une catégorisation prédictive apprise, sans signature corporelle unique."),

    ("roue-plutchik", "Modèle des émotions de base", "Paul Ekman, Robert Plutchik", "1972-1980", "Émotions",
     "Un petit nombre d'émotions seraient universelles, les autres en étant des mélanges ou des nuances.",
     "Ekman identifie six expressions faciales reconnues dans des cultures très éloignées : joie, tristesse, colère, peur, dégoût, surprise. Plutchik en propose huit disposées en roue, combinables par paires (joie + confiance = amour).",
     "Analyse des expressions, formation à la communication non verbale, conception d'interfaces, travail sur le vocabulaire émotionnel chez l'enfant.",
     "L'universalité est contestée : les études utilisaient des choix forcés parmi quelques étiquettes. En condition libre, la reconnaissance chute fortement, et le contexte pèse davantage que le visage."),

    ("modele-beck", "Modèle cognitif de la dépression", "Aaron Beck", "1967", "Clinique",
     "Ce ne sont pas les événements qui nous abattent, mais la façon dont nous nous les racontons.",
     "Trois niveaux : les pensées automatiques (immédiates, crédibles), les distorsions cognitives (généralisation, filtre négatif, catastrophisme), et les schémas profonds formés tôt. La triade dépressive porte sur soi, le monde et l'avenir.",
     "Thérapie cognitive de la dépression et de l'anxiété : identifier les pensées automatiques, les tester comme des hypothèses, construire des alternatives réalistes.",
     "La direction de la causalité reste discutée : les distorsions sont peut-être autant une conséquence de l'humeur qu'une cause. Le modèle rend mal compte des dépressions à forte composante biologique ou contextuelle."),

    ("abc-ellis", "Modèle ABC", "Albert Ellis", "1955", "Clinique",
     "Entre l'événement et la réaction s'intercale toujours une croyance, que l'on peut examiner.",
     "A (événement activateur) → B (croyance, souvent une exigence rigide : « je dois », « il faut absolument ») → C (conséquence émotionnelle). La thérapie ajoute D (discussion de la croyance) et E (effet d'une croyance plus souple).",
     "Outil d'auto-observation accessible, utilisé en thérapie, en coaching, en gestion de la colère et de l'anxiété de performance.",
     "Séduisant par sa simplicité mais parfois appliqué de façon normative, comme si toute détresse relevait d'une pensée irrationnelle — ce qui peut invalider des souffrances légitimes."),

    ("diathese-stress", "Modèle vulnérabilité-stress", "Paul Meehl, Joseph Zubin", "1962-1977", "Clinique",
     "Un trouble apparaît quand une vulnérabilité préexistante rencontre un environnement suffisamment éprouvant.",
     "La vulnérabilité (génétique, neurodéveloppementale, psychologique) fixe un seuil ; les facteurs de stress (deuil, précarité, consommation, isolement) font franchir ce seuil. Deux personnes exposées au même événement n'ont donc pas le même risque.",
     "Cadre dominant en psychopathologie : il explique pourquoi la prévention agit à la fois sur les facteurs de risque et sur les facteurs de protection.",
     "Souvent invoqué de façon vague, sans mesurer réellement la vulnérabilité. La distinction entre vulnérabilité et stress s'estompe quand l'environnement précoce modifie lui-même la biologie."),

    ("biopsychosocial", "Modèle biopsychosocial", "George Engel", "1977", "Santé",
     "La santé ne se comprend qu'en croisant le biologique, le psychologique et le social.",
     "Engel critique le modèle strictement biomédical : une même lésion ne produit ni la même douleur, ni le même handicap, ni le même pronostic selon les croyances, l'humeur, le soutien social et les conditions de vie de la personne.",
     "Prise en charge de la douleur chronique, de la fibromyalgie, du diabète, de l'obésité ; travail en équipe pluriprofessionnelle ; éducation thérapeutique du patient.",
     "Sa force est aussi sa faiblesse : tout peut y entrer, ce qui rend le modèle difficile à réfuter et parfois peu opérationnel dans l'organisation concrète des soins."),

    ("porte-douleur", "Théorie du portillon de la douleur", "Ronald Melzack & Patrick Wall", "1965", "Santé / Neuro",
     "La douleur n'est pas un signal qui remonte passivement : la moelle épinière filtre ce qui passe.",
     "Les fibres de gros calibre (toucher, pression) peuvent fermer le « portillon » médullaire et bloquer partiellement les messages nociceptifs. Des voies descendantes venues du cerveau modulent aussi ce filtre selon l'attention, l'émotion et l'attente.",
     "Explique pourquoi frotter une zone douloureuse soulage, fonde la neurostimulation transcutanée (TENS) et l'usage de l'hypnose ou de la distraction en soins douloureux.",
     "Les détails anatomiques du modèle initial ont été révisés ; Melzack l'a lui-même élargi avec la théorie de la neuromatrice pour rendre compte des douleurs fantômes."),

    ("hebb", "Plasticité hebbienne", "Donald Hebb", "1949", "Neurosciences",
     "Des neurones qui s'activent ensemble renforcent leur liaison.",
     "L'activation répétée et simultanée de deux neurones augmente l'efficacité de leur synapse — mécanisme observé plus tard sous le nom de potentialisation à long terme dans l'hippocampe. Le corollaire est vrai aussi : ce qui n'est plus activé s'affaiblit.",
     "Base biologique de l'apprentissage et de la mémoire, principe inspirateur des réseaux de neurones artificiels, fondement de la rééducation après lésion.",
     "Le slogan simplifie : la synchronie ne suffit pas, l'ordre temporel compte (plasticité dépendante du timing), et des mécanismes homéostatiques évitent l'emballement."),

    ("lateralisation", "Spécialisation hémisphérique", "Roger Sperry & Michael Gazzaniga", "1968", "Neurosciences",
     "Les deux hémisphères ne traitent pas l'information de la même façon — sans pour autant définir deux types de personnes.",
     "Les patients au corps calleux sectionné révèlent une dominance gauche pour le langage articulé et droite pour certains traitements spatiaux et prosodiques. L'hémisphère gauche fabrique aussitôt des explications aux actes déclenchés à droite : l'« interprète ».",
     "Neuropsychologie clinique, évaluation préchirurgicale de l'épilepsie, compréhension de l'aphasie et de la négligence spatiale.",
     "Le mythe du « cerveau gauche rationnel / cerveau droit créatif » est faux : toute tâche complexe mobilise les deux hémisphères en permanence, reliés par 200 millions de fibres."),

    ("neurones-miroirs", "Neurones miroirs", "Giacomo Rizzolatti et al.", "1992", "Neurosciences",
     "Certains neurones s'activent aussi bien quand on agit que quand on voit quelqu'un d'autre agir.",
     "Découverts dans le cortex prémoteur du macaque, ils suggèrent une simulation motrice interne de l'action observée, qui faciliterait sa compréhension immédiate.",
     "Pistes sur l'imitation, l'apprentissage moteur par observation, la rééducation par thérapie miroir après accident vasculaire cérébral.",
     "Très surinterprétés : on leur a attribué l'empathie, le langage, l'autisme et la culture. Les preuves directes chez l'humain sont indirectes et la « théorie du miroir brisé » de l'autisme n'est pas soutenue."),

    ("double-processus", "Systèmes 1 et 2", "Daniel Kahneman & Amos Tversky", "1974-2011", "Cognition",
     "Deux modes de pensée cohabitent : un mode rapide et intuitif, un mode lent et contrôlé.",
     "Le système 1 est automatique, associatif, toujours actif et producteur d'heuristiques efficaces mais faillibles ; le système 2 est coûteux, séquentiel, paresseux, et endosse souvent les conclusions du premier au lieu de les vérifier.",
     "Économie comportementale, conception de politiques publiques (<em>nudges</em>), décisions médicales, formation au raisonnement critique, ergonomie des interfaces.",
     "Métaphore pédagogique plus qu'architecture cérébrale : il n'existe pas deux systèmes localisables. Plusieurs effets d'amorçage cités dans la littérature grand public n'ont pas résisté à la réplication."),

    ("perspective-gestalt", "Lois de la Gestalt", "Max Wertheimer, Kurt Koffka, Wolfgang Köhler", "1912", "Perception",
     "Le tout perçu est autre chose que la somme de ses parties.",
     "Le système visuel organise spontanément le champ selon des principes : proximité, similitude, continuité, clôture, destin commun, figure-fond. Ces regroupements précèdent l'identification consciente des objets.",
     "Design graphique et interfaces, lisibilité des schémas, mise en page pédagogique, compréhension des illusions visuelles.",
     "Les lois décrivent remarquablement bien les phénomènes mais expliquent peu leurs mécanismes ; elles entrent parfois en conflit sans règle d'arbitrage claire."),

    ("perception-gregory", "Perception comme inférence", "Hermann von Helmholtz, Richard Gregory", "1867-1970", "Perception",
     "Percevoir, c'est formuler la meilleure hypothèse sur ce qui a produit nos sensations.",
     "Les données sensorielles sont ambiguës et incomplètes ; le cerveau les complète par des inférences inconscientes fondées sur l'expérience passée. Les illusions sont alors des hypothèses raisonnables appliquées à une situation piégée.",
     "Fondement des modèles contemporains de codage prédictif, explication des illusions, conception de stimuli en réalité virtuelle.",
     "Opposée à l'approche écologique de Gibson, pour qui l'information disponible dans l'environnement est bien plus riche qu'on ne le suppose et ne nécessite pas tant d'inférences."),

    ("affordance-gibson", "Théorie écologique des affordances", "James J. Gibson", "1979", "Perception",
     "On ne perçoit pas des formes abstraites, on perçoit directement ce que l'environnement permet de faire.",
     "Une poignée « offre » d'être saisie, un sol plat « offre » d'être parcouru. L'information est directement contenue dans le flux optique produit par le mouvement de l'observateur : pas besoin de représentation intermédiaire.",
     "Ergonomie et design d'objets, conception d'interfaces intuitives, robotique, analyse du geste sportif, aménagement des espaces.",
     "La notion de perception « directe » rend mal compte des situations d'ambiguïté et des illusions ; le débat avec les approches inférentielles n'est pas tranché."),

    ("traitement-parallele", "Modèles connexionnistes", "David Rumelhart & James McClelland", "1986", "Cognition",
     "La cognition émergerait de l'activation parallèle d'un grand nombre d'unités simples.",
     "Plutôt que des règles symboliques, un réseau d'unités reliées par des poids ajustables. La connaissance réside dans les poids, distribuée dans tout le réseau : il n'y a pas de « case » où serait stocké un mot.",
     "Modélisation de la lecture, de l'acquisition du passé des verbes, des troubles neuropsychologiques par lésion simulée ; ancêtre direct de l'apprentissage profond actuel.",
     "Difficulté à rendre compte de la compositionnalité et de la généralisation systématique du langage — la critique de Fodor et Pylyshyn reste largement d'actualité."),

    ("grammaire-universelle", "Grammaire universelle", "Noam Chomsky", "1965", "Langage",
     "L'enfant acquiert le langage trop vite et trop bien pour n'apprendre que par imitation.",
     "L'argument de la pauvreté du stimulus postule une dotation innée : un ensemble de principes communs à toutes les langues, avec des paramètres fixés par l'exposition. La compétence (le savoir implicite) se distingue de la performance (l'usage réel).",
     "A refondé la linguistique moderne, orienté la recherche sur l'acquisition, inspiré les premières approches formelles du traitement automatique des langues.",
     "Les approches par l'usage (Tomasello) montrent que les enfants apprennent à partir de constructions concrètes et d'énormes quantités de données ; la pauvreté du stimulus est aujourd'hui fortement contestée."),

    ("usage-tomasello", "Acquisition du langage par l'usage", "Michael Tomasello", "2003", "Langage",
     "Le langage s'acquiert grâce à l'attention conjointe et à la lecture des intentions d'autrui.",
     "L'enfant part de « constructions » entières entendues en contexte, puis les schématise progressivement. Deux capacités sociales sont décisives : suivre le regard de l'autre et comprendre qu'il veut communiquer quelque chose.",
     "Éducation précoce, intervention en orthophonie, importance de la qualité des interactions plutôt que du seul volume de mots entendus.",
     "Rend moins bien compte de certaines régularités syntaxiques complexes acquises sans exemples suffisants ; le débat avec le camp générativiste reste ouvert."),

    ("sapir-whorf", "Relativité linguistique", "Edward Sapir & Benjamin Lee Whorf", "1940", "Langage / Culture",
     "La langue que l'on parle influencerait la manière dont on perçoit et catégorise le monde.",
     "La version forte (le langage détermine la pensée) est abandonnée. La version faible, soutenue par des données, dit que la langue oriente l'attention : les langues qui grammaticalisent une distinction rendent cette distinction plus saillante et plus rapide à traiter.",
     "Perception des couleurs, repérage spatial (langues à repères absolus), genre grammatical, formulation des questions en sondage, traduction et interculturalité.",
     "Beaucoup d'exemples célèbres sont des légendes (les prétendus innombrables mots inuits pour la neige). Les effets réels existent mais sont fins et souvent limités aux tâches verbales."),

    ("dimensions-hofstede", "Dimensions culturelles", "Geert Hofstede", "1980", "Interculturel",
     "Les cultures nationales se distinguent sur un petit nombre de dimensions mesurables.",
     "Distance hiérarchique, individualisme-collectivisme, masculinité-féminité, évitement de l'incertitude, orientation à long terme, indulgence. Les scores proviennent d'enquêtes initialement menées auprès de salariés d'une même multinationale.",
     "Management international, négociation, conception de formations, adaptation de produits et d'interfaces, compréhension des malentendus de communication.",
     "Réduire un pays à un score masque une énorme variabilité interne et fige des différences dans le temps. Le risque de stéréotype est réel si on l'applique à un individu."),

    ("weird", "Critique des échantillons WEIRD", "Joseph Henrich, Steven Heine, Ara Norenzayan", "2010", "Méthodologie",
     "La psychologie a largement décrit une population très particulière tout en croyant décrire l'humain.",
     "La grande majorité des participants proviennent de sociétés occidentales, éduquées, industrialisées, riches et démocratiques (<em>Western, Educated, Industrialized, Rich, Democratic</em>) — souvent des étudiants de première année. Sur de nombreuses mesures, ces populations sont des cas extrêmes plutôt que représentatifs.",
     "Impose de préciser sur qui portent les conclusions, de multiplier les réplications interculturelles et de se méfier des affirmations sur la « nature humaine ».",
     "Le constat est plus facile à établir qu'à corriger : mener des études hors de ces populations coûte cher et pose ses propres problèmes méthodologiques."),

    ("crise-replication", "Crise de la réplication", "Brian Nosek et le consortium Open Science", "2015", "Méthodologie",
     "Une part importante des résultats publiés ne se reproduit pas lorsqu'on refait l'expérience.",
     "Sur cent études de psychologie répliquées à grande échelle, environ un tiers à un peu plus retrouvent un effet significatif, et les tailles d'effet sont en moyenne divisées par deux. Causes identifiées : petits échantillons, flexibilité dans l'analyse, biais de publication en faveur du positif.",
     "A transformé les pratiques : préenregistrement des hypothèses, partage des données, réplications directes multi-laboratoires, revues acceptant les résultats nuls.",
     "Ne signifie pas que la psychologie est fausse, mais que la certitude publiée était surestimée. D'autres disciplines connaissent des taux comparables lorsqu'on les examine."),

    ("evolution-selection", "Psychologie évolutionniste", "Leda Cosmides & John Tooby", "1992", "Évolution",
     "L'esprit contiendrait des mécanismes façonnés par la sélection naturelle pour résoudre des problèmes récurrents.",
     "Plutôt qu'un processeur généraliste, un ensemble de modules spécialisés : détection des tricheurs, choix du partenaire, peur des prédateurs, dégoût face aux agents pathogènes. Ces mécanismes seraient adaptés à l'environnement ancestral, pas nécessairement au monde moderne.",
     "Éclaire les préférences alimentaires, certaines peurs disproportionnées, la jalousie, le choix du partenaire, le décalage entre nos réflexes et l'environnement contemporain.",
     "Risque d'« histoires adaptatives » impossibles à tester rétrospectivement. Les critiques (Gould, Lewontin) rappellent que tout trait n'est pas une adaptation : certains sont des sous-produits."),

    ("triarchique", "Théorie triarchique de l'intelligence", "Robert Sternberg", "1985", "Intelligence",
     "Être intelligent ne se réduit pas à réussir des tests scolaires.",
     "Trois composantes : analytique (analyser, comparer, évaluer), créative (produire du nouveau face à l'inédit), pratique (s'adapter à son environnement réel, « intelligence de la rue »). Les tests classiques ne mesurent bien que la première.",
     "Évaluation élargie en éducation, sélection universitaire alternative, valorisation de compétences invisibles à l'école.",
     "Les mesures des composantes créative et pratique sont moins fiables et corrèlent finalement beaucoup avec l'analytique, ce qui nourrit le soupçon qu'elles ne sont pas si indépendantes."),

    ("cattell-horn-carroll", "Modèle CHC de l'intelligence", "Raymond Cattell, John Horn, John Carroll", "1993", "Intelligence",
     "L'intelligence s'organise en trois strates, du facteur général aux aptitudes très spécifiques.",
     "Au sommet, le facteur g ; en dessous, une dizaine d'aptitudes larges dont l'intelligence fluide (raisonner sur du nouveau) et l'intelligence cristallisée (connaissances accumulées) ; enfin, des dizaines d'aptitudes étroites. La fluide décline avec l'âge, la cristallisée se maintient longtemps.",
     "Charpente théorique des échelles de Wechsler et de la plupart des tests actuels ; guide l'interprétation des profils en bilan psychologique.",
     "Modèle statistique issu d'analyses factorielles : il décrit la structure des corrélations entre tests, sans dire ce que g est biologiquement, ni ce qu'il doit à l'environnement."),

    ("intelligences-multiples", "Intelligences multiples", "Howard Gardner", "1983", "Intelligence",
     "Il existerait plusieurs intelligences relativement indépendantes plutôt qu'une aptitude générale.",
     "Gardner propose huit formes : linguistique, logico-mathématique, spatiale, musicale, corporelle-kinesthésique, interpersonnelle, intrapersonnelle, naturaliste, sélectionnées selon des critères comme la dissociation après lésion cérébrale.",
     "A légitimé la diversité des talents à l'école et la variété des supports pédagogiques ; très populaire chez les enseignants.",
     "Peu de soutien empirique : les « intelligences » corrèlent entre elles, et la théorie a été détournée en « styles d'apprentissage », dont l'inefficacité pédagogique est aujourd'hui bien documentée."),

    ("styles-apprentissage-mythe", "Styles d'apprentissage : la théorie réfutée", "Neil Fleming et ses successeurs", "1987", "Éducation",
     "L'idée séduisante que chacun apprendrait mieux dans sa modalité préférée ne résiste pas aux tests.",
     "Le modèle VAK/VARK classe les apprenants en visuels, auditifs, kinesthésiques. L'hypothèse testable est celle de l'« appariement » : enseigner dans la modalité préférée devrait améliorer les résultats. Les expériences contrôlées ne trouvent pas cet effet.",
     "Cas d'école pour apprendre à distinguer une préférence déclarée d'une efficacité mesurée — et pour comprendre comment un neuromythe se propage malgré les démentis.",
     "La préférence existe bien, c'est son effet sur l'apprentissage qui est nul. Ce qui compte réellement, c'est l'adéquation entre la modalité et la <em>nature du contenu</em> : on apprend la géographie avec des cartes, la prononciation avec du son."),

    ("effet-test", "Effet de test et pratique de récupération", "Henry Roediger & Jeffrey Karpicke", "2006", "Éducation",
     "Se tester n'est pas seulement évaluer l'apprentissage : c'est le principal moteur de l'apprentissage.",
     "Récupérer activement une information en mémoire renforce sa trace bien davantage que la relire. L'effet grandit avec le délai : à une semaine, les groupes qui se sont testés écrasent ceux qui ont relu, alors qu'ils se sentaient moins sûrs d'eux.",
     "Flashcards, quiz d'entraînement, questions en fin de chapitre, examens blancs fréquents et sans enjeu, auto-explication sans notes.",
     "Nécessite un retour correctif : se tester en fixant une erreur est contre-productif. L'effet est plus faible pour des contenus très complexes mal compris au départ."),

    ("pratique-espacee", "Pratique espacée", "Hermann Ebbinghaus, puis Harry Bahrick", "1885-1993", "Éducation",
     "Le même temps d'étude produit beaucoup plus de mémoire s'il est réparti que s'il est massé.",
     "L'oubli partiel entre deux sessions rend la récupération suivante plus coûteuse — et c'est précisément cette difficulté qui consolide. L'intervalle optimal augmente avec le délai visé : réviser quelques jours avant pour une semaine, quelques semaines avant pour un an.",
     "Planification des révisions, logiciels de répétition espacée, formation continue, apprentissage des langues et du vocabulaire médical.",
     "Contre-intuitif : l'apprentissage massé donne une impression de maîtrise supérieure sur le moment, ce qui explique sa popularité persistante malgré des résultats durablement inférieurs."),

    ("elaboration-vraisemblance", "Modèle de vraisemblance d'élaboration", "Richard Petty & John Cacioppo", "1986", "Persuasion",
     "Un message convainc par deux routes très différentes selon l'attention qu'on lui accorde.",
     "Route centrale : la personne motivée et capable examine les arguments ; le changement d'attitude est durable et résistant. Route périphérique : elle s'appuie sur des indices superficiels (attrait de la source, nombre d'arguments, musique) ; le changement est fragile.",
     "Publicité, communication de santé publique, plaidoyer, conception de campagnes selon l'implication du public visé.",
     "La frontière entre les deux routes est poreuse ; la « motivation à traiter » est souvent mesurée après coup, ce qui affaiblit le pouvoir prédictif du modèle."),

    ("nudge", "Architecture du choix", "Richard Thaler & Cass Sunstein", "2008", "Décision",
     "Modifier la présentation des options change les décisions sans rien interdire.",
     "Les options par défaut, l'ordre de présentation, la saillance et les normes sociales explicites orientent puissamment les choix, parce que le système 1 s'appuie sur le contexte. Le don d'organes en opt-out contre opt-in en est l'exemple le plus spectaculaire.",
     "Politiques publiques (épargne retraite automatique, tri des déchets), santé (placement des aliments à la cantine), écologie, administration en ligne.",
     "Effets souvent plus modestes en pratique qu'annoncés, et certains travaux fondateurs sur l'amorçage n'ont pas tenu. Question éthique centrale : qui décide du « bon » défaut ?"),

    ("perspective-temporelle", "Perspective temporelle", "Philip Zimbardo & John Boyd", "1999", "Personnalité",
     "Chacun privilégie un rapport au temps qui colore ses décisions quotidiennes.",
     "Cinq orientations : passé positif, passé négatif, présent hédoniste, présent fataliste, futur. Un profil équilibré — passé positif élevé, futur modéré, présent hédoniste modéré — est associé au meilleur bien-être.",
     "Prévention des conduites à risque chez les adolescents, accompagnement de la procrastination, épargne et santé, thérapie de la perspective temporelle après un traumatisme.",
     "Instrument auto-déclaratif, sensible à l'humeur du moment ; la causalité entre orientation temporelle et comportements reste largement corrélationnelle."),

    ("impuissance-apprise", "Impuissance apprise et théorie de l'espoir", "Martin Seligman & Steven Maier", "1967-2016", "Motivation / Clinique",
     "L'exposition répétée à une situation incontrôlable peut éteindre toute tentative d'agir.",
     "Le constat initial : des animaux soumis à des chocs inévitables cessent d'essayer de fuir, même quand la fuite devient possible. Cinquante ans plus tard, Maier et Seligman inversent l'interprétation : la passivité est la réponse par défaut ; c'est le <em>contrôle</em> qui s'apprend, en activant les circuits préfrontaux qui inhibent cette réaction.",
     "Compréhension de la dépression, de la démotivation scolaire et du désengagement au travail ; interventions qui restaurent des expériences concrètes de contrôle.",
     "Les premières expériences posaient de sérieux problèmes éthiques. La généralisation de l'animal à des situations sociales humaines complexes demande beaucoup de prudence."),

    ("modele-demandes-ressources", "Modèle exigences-ressources au travail", "Arnold Bakker & Evangelia Demerouti", "2007", "Travail",
     "L'épuisement et l'engagement professionnels suivent deux chemins distincts.",
     "Les exigences (charge, pression temporelle, conflits) usent l'énergie et mènent à l'épuisement ; les ressources (autonomie, soutien, reconnaissance, sens) nourrissent la motivation et l'engagement, et amortissent l'effet des exigences.",
     "Diagnostic des risques psychosociaux, prévention du burn-out, conception des postes, politiques de qualité de vie au travail.",
     "Les mesures reposent presque toujours sur des questionnaires remplis par les salariés eux-mêmes, au même moment : la causalité est difficile à établir sans suivi longitudinal."),

    ("karasek", "Modèle demande-latitude", "Robert Karasek", "1979", "Travail / Santé",
     "Ce n'est pas la charge de travail seule qui rend malade, c'est la charge sans marge de manœuvre.",
     "Le croisement d'une forte demande psychologique et d'une faible latitude décisionnelle définit le <em>job strain</em>, associé à un risque cardiovasculaire et dépressif accru. Johnson y ajoute une troisième dimension : le soutien social.",
     "Épidémiologie professionnelle, évaluation des risques psychosociaux, aménagement de postes, argumentaire pour l'autonomie au travail.",
     "Le questionnaire capture mal certaines formes contemporaines de travail (indépendance précaire, travail émotionnel, plateformes). Les effets, robustes, restent de taille modérée."),

    ("leadership-transformationnel", "Leadership transformationnel", "Bernard Bass", "1985", "Travail",
     "Certains responsables obtiennent l'adhésion par le sens plutôt que par l'échange donnant-donnant.",
     "Quatre leviers : influence idéalisée (exemplarité), motivation inspirante (vision claire), stimulation intellectuelle (encourager la remise en question), considération individualisée (attention à chacun). Le style transactionnel, à l'inverse, repose sur les récompenses contingentes.",
     "Formation des managers, conduite du changement, engagement des équipes, secteur associatif et hospitalier.",
     "Difficile à distinguer du charisme perçu ; les évaluations proviennent souvent des subordonnés eux-mêmes, avec un risque de circularité (on juge inspirant celui dont l'équipe va bien)."),

    ("conservation-ressources", "Conservation des ressources", "Stevan Hobfoll", "1989", "Stress",
     "Le stress naît de la menace, de la perte ou de l'échec à reconstituer ses ressources.",
     "Les ressources (temps, énergie, argent, estime, relations) s'accumulent ou se perdent en spirales : une perte en entraîne d'autres, tandis que ceux qui disposent de réserves sont mieux armés pour en gagner encore.",
     "Compréhension du burn-out, de l'effet cumulatif de la précarité, du stress post-traumatique collectif après une catastrophe, du soutien aux aidants.",
     "Notion de « ressource » très extensive, ce qui complique la mesure ; les spirales sont plus faciles à raconter qu'à démontrer sur données longitudinales."),

    ("deuil-kubler-ross", "Les cinq étapes du deuil", "Elisabeth Kübler-Ross", "1969", "Clinique",
     "Un modèle immensément célèbre — et largement mal utilisé.",
     "Déni, colère, marchandage, dépression, acceptation. Le modèle a été construit à partir d'entretiens avec des personnes en fin de vie, non avec des personnes endeuillées, et Kübler-Ross n'a jamais affirmé que ces étapes se succédaient dans l'ordre.",
     "A eu le mérite historique immense de faire parler de la mort et d'humaniser l'accompagnement en fin de vie.",
     "Les données sur le deuil réel ne retrouvent pas cette séquence : la trajectoire la plus fréquente est la résilience. Imposer des « étapes » à une personne endeuillée peut ajouter de la culpabilité à la peine."),

    ("modele-processus-dual-deuil", "Modèle du double processus du deuil", "Margaret Stroebe & Henk Schut", "1999", "Clinique",
     "On ne fait pas son deuil en avançant tout droit : on oscille entre deux orientations.",
     "Une orientation vers la perte (pleurer, se souvenir, souffrir) et une orientation vers la restauration (reprendre des activités, réorganiser sa vie). Le va-et-vient entre les deux, y compris les moments de répit, est le mécanisme adaptatif lui-même.",
     "Accompagnement du deuil, soutien aux endeuillés, formation des bénévoles, distinction entre deuil normal et deuil prolongé pathologique.",
     "Moins connu du grand public que le modèle en cinq étapes, alors qu'il est bien mieux soutenu empiriquement. L'oscillation reste difficile à mesurer objectivement."),

    ("transtheorique", "Modèle transthéorique du changement", "James Prochaska & Carlo DiClemente", "1983", "Santé",
     "Changer une habitude passe par des stades, et la rechute en fait partie.",
     "Précontemplation, contemplation, préparation, action, maintien — avec des rechutes fréquentes qui ramènent à un stade antérieur sans annuler les acquis. À chaque stade correspondent des interventions différentes.",
     "Sevrage tabagique, addictologie, activité physique, entretien motivationnel, éducation thérapeutique.",
     "Les stades sont peut-être une catégorisation artificielle d'un continuum ; les essais contrôlés d'interventions adaptées au stade donnent des résultats mitigés."),

    ("motivationnel", "Entretien motivationnel", "William Miller & Stephen Rollnick", "1983", "Thérapies",
     "On ne convainc pas quelqu'un de changer : on l'aide à formuler ses propres raisons de le faire.",
     "L'ambivalence est normale. L'intervenant évite le « réflexe correcteur » (argumenter, avertir), pratique l'écoute réflective, fait émerger et renforce le discours-changement de la personne, et respecte son autonomie.",
     "Addictions, observance thérapeutique, travail social, santé publique, entretiens professionnels difficiles.",
     "Demande une formation et une supervision réelles : appliqué comme une technique de persuasion déguisée, il perd tout son effet et devient manipulatoire."),

    ("acceptation-engagement", "Flexibilité psychologique", "Steven Hayes", "1999", "Thérapies",
     "Plutôt que de combattre ses pensées douloureuses, apprendre à agir malgré elles.",
     "Six processus articulés : acceptation, défusion cognitive (voir la pensée comme une pensée), contact avec le moment présent, soi-comme-contexte, clarification des valeurs, action engagée. La lutte contre les contenus mentaux est vue comme une part du problème.",
     "Douleur chronique, anxiété, dépression, souffrance au travail, maladies chroniques ; troisième vague des thérapies comportementales.",
     "Les données d'efficacité sont solides mais rarement supérieures à celles des thérapies cognitivo-comportementales classiques ; les mécanismes théoriques spécifiques restent discutés."),

    ("centree-personne", "Approche centrée sur la personne", "Carl Rogers", "1951", "Thérapies",
     "La relation elle-même est thérapeutique, à trois conditions.",
     "Congruence (le thérapeute est authentique), regard positif inconditionnel (il accueille sans juger), empathie (il comprend le cadre de référence interne de la personne). Rogers postule une tendance actualisante : chacun porte en soi les ressources de son évolution.",
     "A transformé la posture d'écoute bien au-delà de la psychothérapie : relation d'aide, travail social, éducation, management, formation à l'entretien.",
     "Les trois conditions se révèlent nécessaires mais pas toujours suffisantes ; sur certains troubles (TOC, phobies spécifiques), les approches structurées obtiennent de meilleurs résultats."),

    ("facteurs-communs", "Facteurs communs en psychothérapie", "Saul Rosenzweig, puis Bruce Wampold", "1936-2001", "Thérapies",
     "Ce qui fait l'efficacité d'une thérapie tient moins à sa marque qu'à ce que toutes partagent.",
     "Alliance thérapeutique, attentes du patient, compétence et engagement du praticien, cadre rassurant et explication cohérente des difficultés expliquent une part importante de la variance des résultats — c'est le « verdict de l'oiseau Dodo » : tout le monde a gagné.",
     "Formation des thérapeutes centrée sur l'alliance, mesure régulière du ressenti du patient (<em>feedback-informed treatment</em>), choix éclairé d'une approche.",
     "Ne signifie pas que toutes les approches se valent pour tous les troubles : des techniques spécifiques gardent une supériorité nette dans plusieurs indications précises."),

    ("neuromatrice", "Théorie de la neuromatrice", "Ronald Melzack", "1990", "Neurosciences / Santé",
     "La douleur est produite par le cerveau, même en l'absence totale de signal périphérique.",
     "Un réseau distribué génère une « neurosignature » du corps. La douleur du membre fantôme, chez des personnes amputées, montre qu'un corps peut être douloureusement ressenti sans exister physiquement.",
     "Prise en charge des douleurs neuropathiques et fantômes, thérapie miroir, éducation à la neurophysiologie de la douleur, lutte contre le discours « c'est dans la tête » (au sens de « ce n'est pas réel »).",
     "Modèle conceptuel de haut niveau, difficile à tester directement ; la localisation précise de la neuromatrice reste hypothétique."),

    ("codage-predictif", "Codage prédictif", "Karl Friston et al.", "2005", "Neurosciences",
     "Le cerveau est une machine à prédire qui ne traite vraiment que ses erreurs.",
     "Des modèles internes envoient en permanence des prédictions vers les aires sensorielles ; seul l'écart entre prédiction et signal reçu (l'erreur de prédiction) remonte et met à jour le modèle. Le poids donné à l'erreur dépend de sa précision estimée.",
     "Cadre unificateur pour la perception, l'illusion, l'apprentissage, l'action, et pour des hypothèses sur les hallucinations, l'autisme ou la dépression.",
     "Extrêmement général : sa formulation mathématique la plus ambitieuse (principe d'énergie libre) est critiquée comme difficilement falsifiable en l'état."),

    ("theorie-esprit", "Théorie de l'esprit", "David Premack & Guy Woodruff, puis Simon Baron-Cohen", "1978-1985", "Développement / Social",
     "Comprendre qu'autrui a des croyances différentes des siennes, et parfois fausses.",
     "L'épreuve des fausses croyances (tâche de Sally et Anne) est réussie vers 4 ans : l'enfant comprend qu'un personnage cherchera son objet là où il l'a laissé, et non là où il se trouve réellement. Des versions non verbales suggèrent des précurseurs bien plus précoces.",
     "Compréhension de certaines difficultés sociales dans l'autisme, éducation à l'empathie, analyse du mensonge, de l'ironie et de la négociation.",
     "L'hypothèse d'un déficit spécifique dans l'autisme est aujourd'hui nuancée : les difficultés sont bidirectionnelles (problème de « double empathie ») et varient énormément selon les personnes."),

    ("soi-marche", "Soi et estime de soi", "William James, Morris Rosenberg, Mark Leary", "1890-1995", "Personnalité",
     "L'estime de soi ressemble moins à un carburant qu'à une jauge.",
     "James la définit comme le rapport entre succès et prétentions. Leary propose la théorie du sociomètre : l'estime de soi mesurerait en continu notre valeur relationnelle perçue — notre risque d'exclusion — plutôt qu'elle ne causerait la réussite.",
     "Fait basculer les interventions : plutôt que de « gonfler » l'estime de soi par des compliments, travailler les compétences réelles, les liens sociaux et l'autocompassion.",
     "Les programmes scolaires visant directement l'estime de soi n'améliorent pas les résultats ; une estime très élevée et instable est même associée à l'agressivité défensive."),

    ("autocompassion", "Autocompassion", "Kristin Neff", "2003", "Positive",
     "Se traiter soi-même avec la bienveillance qu'on offrirait à un ami.",
     "Trois composantes : bienveillance envers soi plutôt qu'autocritique, sentiment d'humanité commune plutôt qu'isolement, pleine conscience plutôt que sur-identification aux pensées douloureuses.",
     "Programmes de réduction du stress, prévention du burn-out chez les soignants, accompagnement des troubles alimentaires, travail sur le perfectionnisme.",
     "Le risque de confusion avec la complaisance est souvent soulevé ; les données montrent l'inverse (elle favorise la responsabilité), mais les mesures restent auto-déclaratives."),

    ("broaden-build", "Élargir et construire", "Barbara Fredrickson", "1998", "Positive",
     "Les émotions positives ne sont pas un simple confort : elles élargissent le répertoire d'action.",
     "Là où la peur rétrécit l'attention pour fuir, la joie, l'intérêt ou la gratitude élargissent le champ perceptif et cognitif, ce qui permet de construire durablement des ressources (compétences, liens, résilience).",
     "Psychologie positive appliquée, conception d'interventions de gratitude, climat d'équipe, prévention des rechutes dépressives.",
     "Le fameux « ratio de positivité » de 3 pour 1 s'est révélé mathématiquement infondé et a été rétracté ; le cœur de la théorie, lui, reste soutenu."),

    ("resilience", "Résilience", "Emmy Werner, Boris Cyrulnik", "1971-1999", "Développement",
     "Après un traumatisme, la trajectoire la plus fréquente n'est pas l'effondrement durable.",
     "L'étude longitudinale de Kauai suit des enfants à haut risque pendant quarante ans : un tiers évolue favorablement. Les facteurs protecteurs ne sont pas héroïques : au moins un adulte fiable, un tempérament sociable, des compétences scolaires, un sentiment de sens.",
     "Protection de l'enfance, éducation en milieu défavorisé, accompagnement après catastrophe, prévention en santé mentale.",
     "Le terme a été popularisé jusqu'à devenir une injonction (« sois résilient »), qui peut culpabiliser ceux qui souffrent et masquer la responsabilité des conditions sociales."),

    ("scripts-sociaux", "Schémas et scripts", "Roger Schank & Robert Abelson", "1977", "Cognition sociale",
     "Nous naviguons dans le monde social grâce à des scénarios pré-appris.",
     "Un script est une séquence typique d'événements associée à une situation (aller au restaurant, prendre le train). Il permet de combler les informations manquantes et d'anticiper — au prix de faux souvenirs conformes au script plutôt qu'à la scène réelle.",
     "Compréhension de texte, témoignage oculaire, intégration des nouveaux arrivants dans une organisation, conception d'interfaces conversationnelles.",
     "Rend mal compte de la flexibilité réelle des situations ; les frontières entre schéma, script et stéréotype restent floues."),

    ("memoire-reconstructive", "Mémoire reconstructive", "Frederic Bartlett, Elizabeth Loftus", "1932-1974", "Mémoire",
     "Se souvenir n'est pas relire un enregistrement : c'est reconstruire, donc déformer.",
     "Bartlett montre que le rappel d'un récit étranger se déforme vers les schémas culturels du lecteur. Loftus démontre qu'une question suggestive suffit à modifier un souvenir, et qu'on peut implanter des souvenirs d'événements jamais vécus.",
     "Réforme des auditions judiciaires et des parades d'identification, prudence sur les « souvenirs retrouvés », éducation aux limites du témoignage.",
     "Le fait que la mémoire soit malléable ne signifie pas qu'elle soit globalement peu fiable : dans les conditions ordinaires, elle reste raisonnablement exacte sur l'essentiel."),
]
