# -*- coding: utf-8 -*-
"""Encyclopédie des expériences célèbres de la psychologie."""

# (id, titre, chercheur, annee, categorie, resume, protocole, resultat, portee, critique)
EXPERIENCES = [
    ("chiens-pavlov", "Les chiens de Pavlov", "Ivan Pavlov", "1897", "03-cognitive",
     "L'expérience fondatrice du conditionnement classique.",
     "Pavlov fait précéder systématiquement la distribution de nourriture à des chiens par un signal sonore (métronome, cloche), tout en mesurant précisément leur salivation à l'aide d'une fistule.",
     "Après plusieurs associations, le signal sonore seul déclenche la salivation : un stimulus neutre est devenu un stimulus conditionnel.",
     "Ce mécanisme explique une grande part de nos réactions émotionnelles automatiques : phobies, aversions alimentaires, réactions de stress à un lieu ou un son particulier.",
     "Le modèle a longtemps été présenté comme purement mécanique ; on sait aujourd'hui que l'animal apprend surtout une relation de prédiction entre événements (modèle de Rescorla-Wagner)."),

    ("petit-albert", "Le petit Albert", "John Watson & Rosalie Rayner", "1920", "09-psychopathologie",
     "La démonstration qu'une phobie peut être apprise par conditionnement.",
     "Un bébé de 11 mois, initialement à l'aise avec un rat blanc, est exposé au rat accompagné d'un bruit violent (barre métallique frappée) à plusieurs reprises.",
     "L'enfant développe une peur du rat, qui se généralise à d'autres objets blancs et poilus (lapin, fourrure, barbe de Père Noël).",
     "Base théorique des thérapies comportementales des phobies : si une peur s'apprend, elle peut se désapprendre (exposition, contre-conditionnement).",
     "Expérience aujourd'hui inacceptable sur le plan éthique (aucun consentement éclairé, aucune procédure d'extinction). Ses résultats n'ont jamais été répliqués proprement."),

    ("boite-skinner", "La boîte de Skinner", "B.F. Skinner", "1938", "13-education",
     "La mise en évidence expérimentale du conditionnement opérant.",
     "Un rat placé dans une cage instrumentée découvre qu'en appuyant sur un levier, il obtient une boulette de nourriture. Skinner fait varier les programmes de renforcement (continu, à intervalle fixe, à ratio variable).",
     "Le comportement augmente selon les conséquences reçues. Les renforcements imprévisibles (ratio variable) produisent les comportements les plus résistants à l'extinction.",
     "Fondement des programmes d'apprentissage, des systèmes de récompense en éducation… et du modèle économique des jeux de hasard et des applications à défilement infini.",
     "Réduit l'apprentissage à ses conséquences observables, en négligeant les processus mentaux internes (motivation, compréhension, sens)."),

    ("poupee-bobo", "La poupée Bobo", "Albert Bandura", "1961", "13-education",
     "Les enfants apprennent l'agressivité en observant des modèles.",
     "Des enfants observent un adulte frapper une poupée gonflable Bobo, ou au contraire jouer calmement. Ils sont ensuite laissés seuls avec le même jouet.",
     "Les enfants exposés au modèle agressif reproduisent les gestes observés, parfois en les enrichissant, sans avoir été récompensés pour cela.",
     "Naissance de la théorie de l'apprentissage social : on apprend par observation, ce qui alimente le débat sur l'influence des contenus violents chez l'enfant.",
     "La poupée Bobo est conçue pour être frappée : la situation encourage peut-être artificiellement l'imitation de l'agression."),

    ("conformite-asch", "Le conformisme d'Asch", "Solomon Asch", "1951", "04-sociale",
     "La pression du groupe peut nous faire nier l'évidence perceptive.",
     "Un participant naïf doit dire laquelle de trois lignes a la même longueur qu'une ligne de référence, après avoir entendu 7 complices donner tous la même réponse manifestement fausse.",
     "37 % des réponses suivent le groupe ; 75 % des participants se conforment au moins une fois. Un seul allié dissident suffit à faire chuter massivement la conformité.",
     "Comprendre la dynamique des groupes, la pensée de groupe en entreprise, la difficulté d'exprimer un avis minoritaire.",
     "Réalisée majoritairement sur des étudiants masculins américains des années 1950 ; les taux varient fortement selon les cultures et les époques."),

    ("obeissance-milgram", "L'obéissance à l'autorité", "Stanley Milgram", "1963", "04-sociale",
     "Des personnes ordinaires peuvent infliger une souffrance grave sur ordre.",
     "Le participant, dans le rôle d'« enseignant », doit administrer des chocs électriques croissants (jusqu'à 450 V) à un « apprenant » (complice) qui simule douleur puis silence, sous l'injonction d'un expérimentateur.",
     "65 % des participants vont jusqu'au voltage maximal, malgré un stress visible et intense.",
     "Éclaire les mécanismes d'obéissance destructrice : diffusion de la responsabilité vers l'autorité, engagement progressif, légitimité perçue de l'institution.",
     "Débat éthique majeur (détresse infligée aux participants) et critiques méthodologiques : certains participants doutaient de la réalité des chocs ; les archives montrent des pressions plus insistantes que décrites."),

    ("prison-stanford", "La prison de Stanford", "Philip Zimbardo", "1971", "04-sociale",
     "Des étudiants ordinaires endossent brutalement des rôles de gardien et de prisonnier.",
     "24 étudiants volontaires sont répartis au hasard comme gardiens ou prisonniers dans une prison simulée au sous-sol de l'université, prévue pour 14 jours.",
     "L'expérience est interrompue au bout de 6 jours : humiliations, comportements sadiques de certains gardiens, effondrement psychologique de plusieurs prisonniers.",
     "Popularise l'idée que la situation et les rôles sociaux pèsent au moins autant que la personnalité dans les comportements abusifs.",
     "Fortement remise en cause depuis : consignes explicites données aux gardiens, sélection de volontaires prédisposés, absence de groupe contrôle, un seul essai non réplicable. À considérer comme une démonstration, pas comme une preuve scientifique."),

    ("effet-temoin", "L'effet du témoin", "John Darley & Bibb Latané", "1968", "04-sociale",
     "Plus il y a de témoins, moins on intervient.",
     "Des participants entendent quelqu'un simuler une crise d'épilepsie via un interphone, en croyant être seul témoin, ou l'un de 2, 3 ou 6 témoins.",
     "85 % interviennent quand ils se croient seuls, contre 31 % lorsqu'ils pensent que 5 autres personnes entendent aussi.",
     "Explique la passivité collective dans l'espace public et fonde les formations aux premiers secours : désigner nommément une personne (« vous, en bleu, appelez le 15 »).",
     "Le récit fondateur du meurtre de Kitty Genovese (« 38 témoins passifs ») a été largement exagéré par la presse de l'époque."),

    ("robbers-cave", "La caverne des voleurs", "Muzafer Sherif", "1954", "04-sociale",
     "Comment créer, puis résoudre, un conflit intergroupe.",
     "Dans un camp de vacances, 22 garçons sont séparés en deux groupes, mis en compétition, puis confrontés à des objectifs nécessitant leur coopération (réparer la canalisation d'eau du camp).",
     "La compétition fabrique rapidement hostilité et stéréotypes ; seuls les « buts supraordonnés » nécessitant une coopération réelle réduisent le conflit.",
     "Base des interventions de réduction des préjugés : le simple contact ne suffit pas, il faut une interdépendance coopérative.",
     "Les archives révèlent que les chercheurs ont activement attisé certaines tensions, et qu'une première tentative d'expérience avait échoué."),

    ("gorille-invisible", "Le gorille invisible", "Daniel Simons & Christopher Chabris", "1999", "03-cognitive",
     "L'attention sélective nous rend aveugles à l'inattendu.",
     "Les participants comptent les passes de ballon d'une équipe dans une vidéo. Au milieu, une personne déguisée en gorille traverse la scène, s'arrête et se frappe la poitrine.",
     "Environ 50 % des participants ne voient pas le gorille — et refusent souvent de croire qu'il était là.",
     "Conséquences directes sur la sécurité routière, l'aviation, la médecine (erreurs de diagnostic par « cécité attentionnelle »).",
     "Ne signifie pas que nous sommes « aveugles » en général : l'effet dépend fortement de la charge de la tâche principale."),

    ("faux-souvenirs", "L'implantation de faux souvenirs", "Elizabeth Loftus", "1974-1995", "03-cognitive",
     "La mémoire peut être modifiée, voire fabriquée, après les faits.",
     "Après avoir vu un accident filmé, des participants sont interrogés avec des verbes différents (« heurtées » vs « percutées »). Dans une autre étude, on suggère à des adultes un faux souvenir d'enfance (s'être perdu dans un centre commercial).",
     "Le choix des mots modifie les estimations de vitesse et fait apparaître de faux détails (verre brisé inexistant). Environ 25 % des participants « se souviennent » de l'événement fabriqué.",
     "Bouleverse la valeur du témoignage judiciaire et alimente le débat sur les souvenirs « retrouvés » en thérapie.",
     "Ne prouve pas que tous les souvenirs traumatiques rapportés sont faux : il s'agit de démontrer la malléabilité de la mémoire, pas d'invalider les témoignages en bloc."),

    ("miller-sept", "Le nombre magique 7 ± 2", "George Miller", "1956", "03-cognitive",
     "La capacité limitée de la mémoire à court terme.",
     "Synthèse d'expériences de rappel immédiat de chiffres, lettres ou mots présentés en série.",
     "La mémoire immédiate retient environ 7 ± 2 unités d'information, mais ces unités peuvent être regroupées (chunking) pour augmenter la quantité retenue.",
     "Explique le format des numéros de téléphone, des codes, et l'intérêt de découper l'information en blocs signifiants pour apprendre.",
     "Les estimations modernes sont plus basses (≈ 4 unités pour la mémoire de travail pure, selon Cowan) et dépendent du matériel utilisé."),

    ("ebbinghaus-oubli", "La courbe de l'oubli", "Hermann Ebbinghaus", "1885", "13-education",
     "La mesure expérimentale de la vitesse d'oubli.",
     "Ebbinghaus apprend par cœur des milliers de syllabes sans signification (ZUC, DAX) puis mesure sur lui-même ce qu'il en reste après 20 minutes, 1 heure, 1 jour, 1 semaine.",
     "L'oubli est très rapide au début puis se stabilise ; chaque révision espacée aplatit la courbe et prolonge la rétention.",
     "Fondement scientifique de la répétition espacée, utilisée aujourd'hui par tous les logiciels de flashcards (Anki, SuperMemo).",
     "Réalisée sur un seul sujet (lui-même) et avec du matériel dépourvu de sens, donc peu représentatif de l'apprentissage réel de contenus signifiants."),

    ("guimauve", "Le test du marshmallow", "Walter Mischel", "1972", "05-developpement",
     "La capacité à différer une gratification chez l'enfant.",
     "Un enfant de 4 ans est laissé seul avec un marshmallow : s'il attend une quinzaine de minutes sans le manger, il en recevra deux.",
     "Les enfants qui attendent utilisent des stratégies (détourner le regard, chanter, se distraire). Les premiers suivis suggéraient de meilleurs résultats scolaires ultérieurs.",
     "A popularisé l'importance de l'autorégulation et des stratégies attentionnelles dans la réussite.",
     "Les réplications à grande échelle (2018) montrent que l'effet est bien plus faible qu'annoncé et s'explique largement par le milieu socio-économique et la fiabilité perçue de l'adulte."),

    ("situation-etrange", "La situation étrange", "Mary Ainsworth", "1969", "05-developpement",
     "La mesure standardisée des styles d'attachement.",
     "Un enfant de 12-18 mois traverse 8 épisodes de 3 minutes : séparations et retrouvailles avec sa figure d'attachement, en présence d'une inconnue.",
     "Quatre profils se dégagent : sûr (≈65 %), évitant, anxieux-ambivalent, et plus tard désorganisé. C'est la réaction aux retrouvailles qui est la plus informative.",
     "Outil de référence en psychologie du développement et en protection de l'enfance ; base des travaux sur l'attachement adulte.",
     "Protocole conçu dans un contexte culturel occidental : les proportions de chaque style varient selon les pratiques éducatives des cultures étudiées."),

    ("harlow-singes", "Les singes de Harlow", "Harry Harlow", "1958", "05-developpement",
     "Le besoin de réconfort prime sur le besoin alimentaire.",
     "De jeunes macaques sont placés avec deux « mères » artificielles : une en fil de fer qui distribue du lait, une recouverte de tissu doux sans nourriture.",
     "Les petits passent l'essentiel de leur temps agrippés à la mère en tissu et ne vont vers l'autre que pour se nourrir ; ils s'y réfugient en cas de peur.",
     "Réfute la théorie selon laquelle l'attachement n'est qu'un apprentissage lié à la nourriture ; soutient les travaux de Bowlby sur le besoin primaire de contact.",
     "Expérimentations extrêmement cruelles (isolement social prolongé), aujourd'hui interdites ; elles ont paradoxalement nourri le mouvement de protection animale."),

    ("piaget-conservation", "Les épreuves de conservation", "Jean Piaget", "1940s", "05-developpement",
     "La logique de l'enfant change qualitativement avec l'âge.",
     "On verse le contenu d'un verre large dans un verre étroit et haut devant l'enfant, puis on lui demande s'il y a la même quantité de liquide.",
     "Avant ~7 ans, l'enfant affirme qu'il y en a plus dans le verre haut : il se centre sur une seule dimension. Après, il maîtrise la réversibilité et la conservation.",
     "Structure toute la pédagogie du premier degré : adapter les apprentissages au niveau de raisonnement réel de l'enfant.",
     "Piaget a sous-estimé les compétences précoces : avec des consignes simplifiées, des enfants plus jeunes réussissent des versions allégées de ces épreuves."),

    ("fausses-croyances", "Le test de Sally et Anne", "Wimmer & Perner / Baron-Cohen", "1983-1985", "05-developpement",
     "L'émergence de la théorie de l'esprit.",
     "Sally range une bille dans un panier puis sort ; Anne la déplace dans une boîte. On demande à l'enfant où Sally cherchera sa bille en revenant.",
     "Vers 4 ans, l'enfant répond correctement « dans le panier » : il comprend que Sally a une croyance fausse, différente de la réalité qu'il connaît.",
     "Outil central pour étudier le développement social et certaines particularités de la cognition sociale dans l'autisme.",
     "Réussir ou échouer au test dépend aussi du langage et de la mémoire de travail ; il ne mesure pas à lui seul « l'empathie »."),

    ("split-brain", "Les patients au cerveau divisé", "Roger Sperry & Michael Gazzaniga", "1960s", "08-neurosciences",
     "Deux hémisphères, deux modes de traitement.",
     "Chez des patients épileptiques dont le corps calleux a été sectionné, on présente des images uniquement à un hémisphère (champ visuel gauche ou droit).",
     "L'hémisphère gauche (dominant pour le langage) peut nommer ce qu'il voit ; le droit, non, mais la main gauche peut désigner l'objet. Le cerveau invente ensuite des justifications cohérentes.",
     "Prix Nobel 1981. Démontre la spécialisation hémisphérique et l'existence d'un « interprète » qui rationalise nos actes a posteriori.",
     "A nourri le mythe populaire du « cerveau gauche rationnel / cerveau droit créatif », très exagéré : les deux hémisphères coopèrent en permanence."),

    ("phineas-gage", "Le cas Phineas Gage", "John Harlow", "1848", "08-neurosciences",
     "Le lobe frontal et la personnalité.",
     "Une barre à mine traverse le crâne de ce contremaître de chemin de fer, détruisant une partie de son cortex préfrontal. Il survit et récupère ses fonctions motrices et son langage.",
     "Sa personnalité change profondément : impulsivité, difficultés à planifier, comportement social désinhibé selon les rapports de l'époque.",
     "Premier grand argument clinique reliant le cortex préfrontal au contrôle de soi, à la planification et au comportement social.",
     "Les descriptions ont été embellies au fil du temps ; des travaux récents montrent qu'il s'est en partie réadapté et a occupé un emploi stable de cocher."),

    ("patient-hm", "Le patient H.M.", "Brenda Milner", "1957", "08-neurosciences",
     "La dissociation entre mémoire explicite et implicite.",
     "Après l'ablation bilatérale de ses hippocampes pour traiter une épilepsie sévère, Henry Molaison est suivi pendant des décennies.",
     "Il ne peut plus former de nouveaux souvenirs conscients, mais progresse d'un jour à l'autre à des tâches motrices (dessin en miroir) sans se souvenir de les avoir pratiquées.",
     "Prouve que la mémoire n'est pas un système unique : la mémoire procédurale est indépendante de la mémoire déclarative et de l'hippocampe.",
     "Cas unique : les généralisations à partir d'un seul patient demandent prudence, même si elles ont été largement confirmées depuis."),

    ("neurones-miroir", "La découverte des neurones miroirs", "Giacomo Rizzolatti", "1992", "08-neurosciences",
     "Des neurones qui s'activent aussi quand on observe autrui.",
     "En enregistrant l'activité de neurones prémoteurs chez le macaque, l'équipe constate que certains déchargent aussi bien quand l'animal saisit un objet que lorsqu'il voit un humain le faire.",
     "Ces neurones codent l'action indépendamment de qui l'exécute, suggérant un mécanisme de compréhension directe des gestes d'autrui.",
     "A inspiré des hypothèses sur l'imitation, l'empathie et l'apprentissage social.",
     "Les extrapolations à l'empathie, au langage ou à l'autisme sont très spéculatives et contestées : l'existence d'un vrai « système miroir » humain reste débattue."),

    ("impuissance-apprise", "L'impuissance apprise", "Martin Seligman & Steven Maier", "1967", "11-positive",
     "Quand l'absence de contrôle produit la passivité.",
     "Des chiens exposés à des chocs inévitables cessent ensuite de tenter d'échapper à des chocs pourtant évitables, contrairement à ceux qui avaient pu les contrôler.",
     "L'expérience du non-contrôle, et non la douleur elle-même, produit la passivité et les symptômes dépressifs.",
     "Modèle influent de la dépression et point de départ, par renversement, de la psychologie positive et de l'optimisme appris.",
     "Réinterprétée par ses auteurs eux-mêmes en 2016 : la passivité serait la réaction par défaut du cerveau, et c'est le contrôle qui s'apprend, pas l'impuissance."),

    ("effet-placebo", "L'effet placebo en chirurgie", "Bruce Moseley", "2002", "14-sante",
     "Une opération simulée aussi efficace que la vraie.",
     "180 patients souffrant d'arthrose du genou sont répartis au hasard entre chirurgie arthroscopique réelle et chirurgie simulée (incisions cutanées seules, sous anesthésie).",
     "Les deux groupes rapportent une réduction de douleur équivalente pendant deux ans.",
     "Démontre la puissance des attentes et du rituel de soin ; a fait évoluer les recommandations sur cette intervention.",
     "L'effet placebo agit surtout sur les symptômes subjectifs (douleur, fatigue) ; il ne guérit pas une infection ou une tumeur."),

    ("hofling-infirmieres", "L'expérience de Hofling", "Charles Hofling", "1966", "04-sociale",
     "L'obéissance en milieu professionnel réel.",
     "Un faux médecin téléphone à des infirmières et leur demande d'administrer une dose manifestement excessive d'un médicament inconnu, en violation du protocole.",
     "21 infirmières sur 22 s'exécutent, alors que la quasi-totalité de leurs collègues interrogées affirmaient qu'elles refuseraient.",
     "Montre l'écart entre ce que nous croyons que nous ferions et ce que nous faisons réellement face à une autorité hiérarchique.",
     "Contexte hospitalier des années 1960, très hiérarchisé ; les protocoles de sécurité modernes (double validation) visent précisément ce risque."),

    ("rosenhan", "L'étude de Rosenhan", "David Rosenhan", "1973", "09-psychopathologie",
     "La fragilité du diagnostic psychiatrique.",
     "Huit pseudo-patients en bonne santé se présentent à l'hôpital en rapportant une hallucination auditive unique, puis se comportent normalement.",
     "Tous sont hospitalisés (en moyenne 19 jours) ; leurs comportements ordinaires sont réinterprétés à la lumière du diagnostic posé.",
     "A accéléré la refonte des critères diagnostiques (DSM-III, 1980) vers des définitions opérationnelles et vérifiables.",
     "Une enquête de 2019 (Susannah Cahalan) a mis en doute la véracité de plusieurs données rapportées par Rosenhan."),

    ("beck-triade", "La thérapie cognitive de la dépression", "Aaron Beck", "1977", "10-therapies",
     "Premier essai contrôlé comparant psychothérapie et médicament.",
     "Des patients dépressifs sont répartis au hasard entre thérapie cognitive et traitement par antidépresseur tricyclique.",
     "La thérapie cognitive obtient des résultats au moins équivalents, avec moins de rechutes au suivi.",
     "Installe la TCC comme traitement de première intention de la dépression et de l'anxiété dans les recommandations internationales.",
     "Les premiers essais étaient de petite taille ; les méta-analyses récentes confirment l'efficacité mais avec des tailles d'effet plus modestes qu'initialement annoncées."),

    ("effet-hawthorne", "Les études Hawthorne", "Elton Mayo", "1924-1932", "12-travail",
     "L'attention portée aux travailleurs modifie leur performance.",
     "Dans une usine de Western Electric, on fait varier l'éclairage et les conditions de travail d'un groupe d'ouvrières en mesurant leur productivité.",
     "La productivité augmente quelles que soient les modifications — y compris en revenant aux conditions initiales.",
     "Naissance du mouvement des relations humaines : la reconnaissance et la dynamique de groupe comptent autant que les conditions matérielles.",
     "Les réanalyses des données brutes montrent des effets bien plus faibles et confondus avec d'autres facteurs (paie aux pièces, remplacement d'ouvrières)."),

    ("pygmalion", "L'effet Pygmalion", "Robert Rosenthal & Lenore Jacobson", "1968", "13-education",
     "Les attentes de l'enseignant influencent les résultats des élèves.",
     "On annonce à des enseignants que certains élèves, désignés au hasard, vont connaître une forte progression selon un test (fictif) de potentiel.",
     "Ces élèves progressent davantage que les autres à la fin de l'année, en particulier dans les petites classes.",
     "Sensibilise au poids des attentes et des étiquettes en éducation, en management et en santé.",
     "Effet réel mais modeste et inconstant selon les réplications ; l'étude originale a été critiquée pour ses instruments de mesure."),

    ("stroop", "L'effet Stroop", "John Ridley Stroop", "1935", "03-cognitive",
     "L'interférence entre lecture automatique et dénomination.",
     "Le participant doit nommer la couleur de l'encre de mots écrits, quand le mot lui-même désigne une autre couleur (le mot « ROUGE » écrit en bleu).",
     "Le temps de réponse augmente nettement et les erreurs se multiplient : la lecture, automatisée, interfère avec la tâche demandée.",
     "Test de référence du contrôle exécutif et de l'inhibition, utilisé en neuropsychologie clinique et en recherche.",
     "Tâche sensible à de nombreux facteurs (âge, fatigue, langue, daltonisme), ce qui complique l'interprétation d'un score isolé."),

    ("kitty-dissonance", "La dissonance cognitive", "Leon Festinger & James Carlsmith", "1959", "04-sociale",
     "Quand nos actes transforment nos opinions.",
     "Après une tâche volontairement ennuyeuse, on paie les participants 1 $ ou 20 $ pour affirmer à un inconnu qu'elle était intéressante.",
     "Ceux payés 1 $ finissent par juger la tâche réellement plus plaisante : sans justification externe suffisante, ils ajustent leur opinion à leur comportement.",
     "Explique l'engagement, la justification de l'effort, la rationalisation des choix difficiles, y compris en marketing et en politique.",
     "La théorie a été reformulée de multiples fois ; toutes les situations d'incohérence ne produisent pas de dissonance."),

    ("bystander-fumee", "La salle enfumée", "Latané & Darley", "1968", "04-sociale",
     "L'ignorance pluraliste face au danger.",
     "De la fumée s'infiltre dans une salle d'attente où le participant est seul, ou accompagné de complices impassibles.",
     "Seul, 75 % signalent la fumée ; entouré de complices passifs, seulement 10 % le font.",
     "Montre que nous lisons l'urgence dans la réaction des autres : si personne ne bouge, nous concluons qu'il n'y a pas de danger.",
     "Situation de laboratoire : l'ambiguïté réelle du danger joue un rôle majeur dans l'ampleur de l'effet."),

    ("false-consensus", "Le faux consensus", "Lee Ross", "1977", "04-sociale",
     "Nous surestimons le nombre de gens qui pensent comme nous.",
     "On demande à des étudiants s'ils accepteraient de porter un panneau publicitaire sur le campus, puis d'estimer le pourcentage de leurs pairs qui accepteraient.",
     "Chaque groupe estime que la majorité ferait le même choix que lui, quelle que soit sa décision.",
     "Éclaire les bulles d'opinion, les erreurs de sondage informel et les malentendus dans les débats publics.",
     "L'effet varie selon la nature du jugement : il est plus fort pour les opinions que pour les faits vérifiables."),

    ("ancrage-kahneman", "L'effet d'ancrage", "Amos Tversky & Daniel Kahneman", "1974", "03-cognitive",
     "Un nombre arbitraire influence nos estimations.",
     "Une roue de loterie truquée s'arrête sur 10 ou 65 devant les participants, à qui l'on demande ensuite le pourcentage de pays africains à l'ONU.",
     "Les estimations moyennes suivent l'ancre : 25 % après un 10, 45 % après un 65, alors que le nombre est manifestement sans rapport.",
     "Pilier de l'économie comportementale (prix barrés, négociation salariale, première offre en négociation). Prix Nobel d'économie 2002 pour Kahneman.",
     "Certaines réplications à grande échelle trouvent des effets plus faibles ; l'ancrage reste néanmoins l'un des biais les plus robustes."),

    ("cadrage", "L'effet de cadrage", "Tversky & Kahneman", "1981", "03-cognitive",
     "La formulation d'un choix en change l'issue.",
     "Face à une épidémie hypothétique, on présente les mêmes options en termes de vies sauvées ou de morts évitées (« problème de la maladie asiatique »).",
     "Formulé en gains, le public choisit l'option sûre ; formulé en pertes, il prend le risque — alors que les probabilités sont identiques.",
     "Fondamental en santé publique, en communication du risque et en politiques publiques (« nudges »).",
     "L'ampleur de l'effet dépend de l'expertise du décideur et du temps de réflexion disponible."),

    ("marshmallow-social", "La falaise visuelle", "Eleanor Gibson & Richard Walk", "1960", "05-developpement",
     "La perception de la profondeur chez le nourrisson.",
     "Un bébé qui rampe est placé sur une plaque de verre surplombant un vide apparent, sa mère l'appelant de l'autre côté.",
     "La plupart des bébés de 6-14 mois refusent de traverser le « vide », même encouragés : la perception de la profondeur est très précoce.",
     "Montre que certaines compétences perceptives sont présentes très tôt et guidées par les signaux émotionnels du parent (référencement social).",
     "Les bébés testés savent déjà ramper : on ne peut pas conclure que cette perception est innée plutôt qu'apprise par l'expérience motrice."),

    ("capgras-experiences", "Les expériences de privation sensorielle", "Donald Hebb", "1951", "08-neurosciences",
     "Le cerveau a besoin de stimulation pour fonctionner normalement.",
     "Des étudiants volontaires sont payés pour ne rien faire dans une pièce insonorisée, avec lunettes translucides et manchons limitant le toucher.",
     "Après quelques heures : troubles de la concentration, hallucinations, désorientation ; la plupart abandonnent en moins de 3 jours malgré la rémunération.",
     "A éclairé les effets de l'isolement carcéral, de la monotonie extrême et l'importance de la stimulation sensorielle.",
     "Ces travaux ont malheureusement inspiré des techniques d'interrogatoire coercitives, ce qui pose une question éthique majeure sur leur héritage."),

    ("attribution-jones", "L'erreur fondamentale d'attribution", "Edward Jones & Victor Harris", "1967", "04-sociale",
     "Nous surestimons les causes personnelles au détriment de la situation.",
     "Des participants lisent un texte pro- ou anti-Castro, en sachant explicitement que l'auteur n'avait pas le choix de la position défendue.",
     "Ils attribuent malgré tout l'opinion exprimée aux convictions réelles de l'auteur.",
     "Explique de nombreux jugements injustes : attribuer un échec scolaire à la « paresse » plutôt qu'aux conditions de vie, par exemple.",
     "Moins marquée dans les cultures collectivistes, qui accordent davantage de poids au contexte : le biais n'est pas universel."),

    ("zajonc-exposition", "L'effet de simple exposition", "Robert Zajonc", "1968", "04-sociale",
     "Plus on voit quelque chose, plus on l'apprécie.",
     "Des participants voient des idéogrammes chinois, des visages ou des mots inventés un nombre variable de fois, puis évaluent leur agrément.",
     "Les stimuli les plus souvent vus sont jugés plus agréables, même lorsque les participants ne se souviennent pas les avoir vus.",
     "Fondement psychologique de la publicité par répétition et de la familiarité des marques ou des visages politiques.",
     "L'effet s'inverse au-delà d'un certain seuil de répétition (lassitude) et ne fonctionne pas si l'impression initiale est franchement négative."),

    ("cocktail-party", "L'effet cocktail party", "Colin Cherry", "1953", "03-cognitive",
     "Le filtrage attentionnel de l'information auditive.",
     "On diffuse deux messages différents dans chaque oreille du participant, qui doit répéter à voix haute celui d'une seule oreille (écoute dichotique).",
     "Le message ignoré n'est pas mémorisé, mais certaines informations saillantes le traversent — notamment le prénom du participant.",
     "Modèle de référence de l'attention sélective, avec des applications en ergonomie sonore et en conception d'alarmes.",
     "A donné lieu à un long débat entre filtres « précoces » et « tardifs » ; la réponse actuelle est que le filtrage est flexible selon la charge cognitive."),

    ("mcgurk", "L'effet McGurk", "Harry McGurk & John MacDonald", "1976", "03-cognitive",
     "La vision modifie ce que nous entendons.",
     "On présente le son « ba » synchronisé sur une vidéo de lèvres articulant « ga ».",
     "La plupart des personnes perçoivent une troisième syllabe (« da ») : le cerveau fusionne les informations auditives et visuelles.",
     "Démontre que la perception est multisensorielle par nature, avec des applications en lecture labiale, doublage et interfaces vocales.",
     "L'effet varie fortement selon les langues, l'âge et les individus ; certains ne le perçoivent pas du tout."),

    ("loftus-témoignage", "Les mots qui déforment le souvenir", "Elizabeth Loftus & John Palmer", "1974", "15-legale",
     "L'influence des questions sur la mémoire du témoin.",
     "Après une vidéo d'accident, on demande à quelle vitesse les voitures roulaient quand elles se sont « touchées », « heurtées » ou « fracassées ».",
     "Les estimations de vitesse augmentent avec l'intensité du verbe, et une semaine plus tard, les participants du groupe « fracassées » se souviennent d'un verre brisé inexistant.",
     "A conduit à réformer les protocoles d'audition des témoins et des enfants victimes (questions ouvertes, non suggestives).",
     "Effet démontré en laboratoire : la mémoire d'un événement réellement vécu et traumatisant peut obéir à des dynamiques différentes."),

    ("tajfel-groupes", "Les groupes minimaux", "Henri Tajfel", "1971", "04-sociale",
     "Il suffit de presque rien pour créer un « eux » et un « nous ».",
     "Des participants sont répartis en deux groupes sur un critère trivial (préférence pour un peintre, tirage au sort), sans aucune interaction ni enjeu réel.",
     "Ils attribuent systématiquement plus de ressources aux membres de leur propre groupe, quitte à réduire le gain absolu de leur camp.",
     "Fondement de la théorie de l'identité sociale, qui éclaire le sport, la politique, le nationalisme et les rivalités d'entreprise.",
     "Certaines réanalyses soulignent que les participants cherchent aussi à respecter ce qu'ils croient être la norme attendue par l'expérimentateur."),

    ("flow-csik", "L'échantillonnage de l'expérience", "Mihaly Csikszentmihalyi", "1975", "11-positive",
     "Capturer le bien-être dans la vie quotidienne.",
     "Des participants portent un bipeur qui sonne à des moments aléatoires de la journée ; ils notent alors leur activité, leur humeur et leur niveau de concentration.",
     "Les moments les plus satisfaisants ne sont pas les moments de repos, mais ceux où défi et compétence s'équilibrent — l'état de flow.",
     "Méthode devenue standard pour étudier l'expérience subjective en conditions réelles (aujourd'hui via smartphone).",
     "Dépend de l'auto-rapport, sensible à la désirabilité sociale et au fait que répondre interrompt l'expérience mesurée."),

    ("darwin-emotions-exp", "L'enquête photographique sur les émotions", "Charles Darwin", "1872", "07-emotions",
     "Une des premières études interculturelles des expressions.",
     "Darwin envoie un questionnaire à des correspondants sur tous les continents et montre des photographies d'expressions (dont celles de Duchenne de Boulogne) à des observateurs.",
     "Les mêmes expressions sont reconnues à travers des cultures très différentes, ce qui soutient l'hypothèse d'une origine évolutive commune.",
     "Ancêtre direct des travaux d'Ekman sur l'universalité des émotions de base et des systèmes automatiques de reconnaissance faciale.",
     "Méthodologie peu contrôlée pour les standards actuels (questions suggestives, échantillons de convenance)."),

    ("binet-simon", "La première échelle d'intelligence", "Alfred Binet & Théodore Simon", "1905", "06-personnalite",
     "Mesurer le développement intellectuel pour aider les élèves en difficulté.",
     "Binet et Simon construisent une série de 30 tâches de difficulté croissante (suivre une lumière du regard, définir des mots, raisonner) étalonnées par âge.",
     "L'échelle permet de situer l'« âge mental » d'un enfant par rapport à son âge réel, afin d'orienter vers un soutien adapté.",
     "Acte de naissance de la psychométrie moderne ; le QI en dérive directement (Stern, puis Wechsler).",
     "Binet lui-même refusait l'idée d'une intelligence fixe et héréditaire — interprétation abusive qui s'est ensuite imposée, notamment aux États-Unis."),

    ("broca-tan", "Le patient Tan (Leborgne)", "Paul Broca", "1861", "27-science-psychologique",
     "Première localisation anatomique d'une fonction mentale.",
     "Leborgne, dit « Tan », ne peut plus articuler qu'une syllabe depuis des années. Broca attend l'autopsie et examine le cerveau.",
     "Une lésion du pied de la troisième circonvolution frontale gauche correspond à la perte de la parole articulée, les autres fonctions étant relativement préservées.",
     "Fonde la neuropsychologie du langage et l'idée moderne de localisation — à relier à la fiche Langage.",
     "Un cas unique ne suffit pas ; la « zone de Broca » est aujourd'hui un nœud dans un réseau, pas un centre isolé."),

    ("wernicke-aphasie", "L'aphasie de Wernicke", "Carl Wernicke", "1874", "27-science-psychologique",
     "Un langage fluide peut être vide de sens.",
     "Wernicke décrit des patients qui parlent avec un débit normal, parfois logorrhéique, sans comprendre et sans produire de phrases cohérentes.",
     "La lésion siège plutôt dans le temporal postérieur gauche : un second pôle du langage, distinct de Broca.",
     "Le modèle Broca–Wernicke–Lichtheim structure encore l'enseignement, précisé ensuite par Geschwind et l'imagerie.",
     "Les frontières exactes varient ; beaucoup d'aphasies mixtes ne rentrent pas dans la dichotomie scolaire."),

    ("fritsch-hitzig", "L'excitation du cortex moteur", "Gustav Fritsch & Eduard Hitzig", "1870", "27-science-psychologique",
     "Un courant faible fait bouger le corps opposé.",
     "Sur le cortex d'un chien, les deux médecins appliquent une stimulation électrique localisée et observent les mouvements controlatéraux.",
     "Le cortex moteur existe et est organisé. La stimulation devient un instrument de cartographie.",
     "Ouvre la voie à Ferrier, puis à Penfield. Relie physiologie et psychologie de l'action.",
     "Expérience animale du XIXe siècle, sans les standards éthiques actuels ; les cartes précises viendront plus tard."),

    ("penfield-homoncule", "L'homoncule de Penfield", "Wilder Penfield", "1937-1957", "27-science-psychologique",
     "La carte corticale du corps n'est pas à l'échelle du corps.",
     "Pendant des chirurgies d'épilepsie à Montréal, le patient reste éveillé. Penfield stimule le cortex et note le mouvement ou la sensation rapportée.",
     "Mains, lèvres et langue occupent une surface démesurée ; le tronc est minuscule. Parfois un souvenir ou une aura apparaît.",
     "Image durable de la somatotopie. Voir aussi la galerie de la zone de découverte.",
     "Les cartes varient d'un individu à l'autre et se réorganisent après amputation : l'homoncule n'est pas un destin."),

    ("berger-eeg", "Le premier électroencéphalogramme humain", "Hans Berger", "1924-1929", "27-science-psychologique",
     "L'activité électrique du cerveau devient visible sans ouvrir le crâne.",
     "Berger enregistre le scalp de son fils, puis de patients, à la recherche d'une « énergie psychique » mesurable.",
     "Des ondes régulières (rythme alpha) apparaissent les yeux fermés et s'atténuent à l'ouverture. L'EEG est né.",
     "Outil quotidien de l'épilepsie, du sommeil et des potentiels évoqués (P300, N400, MMN).",
     "D'abord moqué, puis surexploité : un tracé ne « lit » pas les pensées."),

    ("hubel-wiesel-colonnes", "Les colonnes d'orientation", "David Hubel & Torsten Wiesel", "1959-1962", "27-science-psychologique",
     "Un neurone du cortex visuel a une orientation préférée.",
     "Une microélectrode dans le cortex visuel d'un chat ; on projette des barres de différentes orientations.",
     "Chaque cellule décharge pour une orientation, et les voisines s'organisent en colonnes. Nobel 1981 (avec Sperry).",
     "La perception n'est pas une photo : elle est déjà une statistique de traits.",
     "Réalisée sur l'animal. La généralisation à toute la vision humaine demande les travaux ultérieurs sur V2, V4, MT."),

    ("libet-intention", "Le potentiel de préparation et l'intention", "Benjamin Libet", "1983", "27-science-psychologique",
     "L'activité cérébrale précède le moment où l'on croit décider.",
     "Le participant note, sur une horloge rapide, l'instant où il « décide » de fléchir le poignet, pendant que l'EEG enregistre le potentiel de Bereitschaft.",
     "Le potentiel précède d'environ 350 ms le moment conscient rapporté.",
     "Interdit le mythe d'un moi transparent et immédiat. Alimente le débat sur le libre arbitre.",
     "La mesure du « moment conscient » est fragile ; Libet lui-même laissait un droit de veto. Voir les débats du site."),

    ("blindsight", "La vision aveugle", "Lawrence Weiskrantz", "1974", "27-science-psychologique",
     "On peut orienter une action vers un objet « non vu ». ",
     "Des patients avec lésion du cortex visuel primaire disent ne rien voir dans une partie du champ. On leur demande de deviner ou de pointer.",
     "Leurs réponses dépassent le hasard. Une voie visuelle extra-striée a survécu à la conscience.",
     "Soutient l'idée de deux voies (quoi / comment) et limite l'équation « vision = conscience ».",
     "Phénomène rare, variable, qui ne se confond pas avec la cécité corticale complète."),

    ("kandel-aplysia", "La mémoire de la limace de mer", "Eric Kandel", "1960s-2000", "27-science-psychologique",
     "L'apprentissage change des synapses que l'on peut compter.",
     "Chez Aplysia, on habite, sensibilise ou conditionne le réflexe de retrait du siphon, tout en enregistrant les synapses.",
     "L'habitude diminue la transmission ; la sensibilisation et le conditionnement la renforcent, jusqu'à de nouvelles connexions.",
     "Nobel 2000. Relie psychologie de l'apprentissage et biologie de la synapse (Hebb devenu mesurable).",
     "Une limace n'est pas un humain : le principe se généralise, pas le circuit exact."),

    ("okeefe-cellules-lieu", "Les cellules de lieu", "John O'Keefe", "1971", "27-science-psychologique",
     "Un neurone de l'hippocampe s'allume à un endroit de l'espace.",
     "Chez le rat qui explore un labyrinthe, on enregistre des cellules qui ne déchargent que dans une zone précise.",
     "L'hippocampe contient une carte spatiale. Plus tard, les Moser décrivent les cellules de grille. Nobel 2014.",
     "Relie H.M. (mémoire) et navigation. La mémoire autobiographique a une géométrie.",
     "D'abord démontré chez le rongeur ; les homologues humains sont étudiés en épilepsie implantée."),

    ("raichle-reseau-defaut", "Le réseau du mode par défaut", "Marcus Raichle", "2001", "27-science-psychologique",
     "Le cerveau au repos n'est pas éteint.",
     "En IRMf, un ensemble de régions (précunéus, cingulaire postérieur, préfrontal médian) s'active quand la tâche s'arrête.",
     "Ce réseau soutient rumination, souvenir, projection, théorie de l'esprit — le travail intérieur.",
     "Change la lecture des « contrôles au repos » et relie neurosciences et clinique de la rumination.",
     "« Au repos » n'est pas un état unique ; le réseau se décompose en sous-systèmes."),

    ("damasio-iowa-gambling", "Le Iowa Gambling Task", "Antoine Bechara & Antonio Damasio", "1994", "27-science-psychologique",
     "Sans marqueurs corporels, on décide plus mal.",
     "Quatre paquets de cartes, gains et pertes inégaux. On mesure aussi la conductance de la peau avant les choix conscients.",
     "Les sujets sains évitent les paquets toxiques avant de pouvoir l'expliquer. Les lésions ventromédianes, non.",
     "L'émotion n'est pas l'ennemie de la raison. Relie frontal, décision et fiche Émotions.",
     "Tâche de laboratoire : la vie réelle a plus de dimensions que quatre paquets."),

    ("rubber-hand", "L'illusion de la main en caoutchouc", "Matthew Botvinick & Jonathan Cohen", "1998", "27-science-psychologique",
     "Le schéma corporel est une hypothèse, pas une donnée.",
     "On caresse une main factice en même temps que la main cachée du participant, puis on demande où est « ma » main.",
     "La localisation se décale vers le leurre. Le cerveau a adopté la main étrangère.",
     "Éclaire membres fantômes, réalité virtuelle, et la plasticité du corps vécu.",
     "L'effet varie fortement ; ce n'est pas une preuve que « le moi n'existe pas »."),

    ("two-streams-goodale", "Les deux voies visuelles", "Melvyn Goodale & David Milner", "1992", "27-science-psychologique",
     "Voir un objet et s'en saisir ne passent pas par le même chemin.",
     "La patiente D.F., atteinte visuelle, ne reconnaît pas la forme d'une fente mais oriente correctement la main pour y poster une carte.",
     "Voie ventrale (« quoi ») et voie dorsale (« comment »). La conscience visuelle n'est pas l'action visuelle.",
     "Cadre encore central, à relier au blindsight et à la fiche Cognitive.",
     "Les deux voies communiquent ; la séparation n'est pas étanche."),

    ("wada-test", "Le test de Wada", "Juhn Atsushi Wada", "1949", "27-science-psychologique",
     "Endormir un hémisphère pour savoir où habite le langage.",
     "On injecte un barbiturique dans une carotide. Pendant quelques minutes, un hémisphère est anesthésié ; on teste langage et mémoire.",
     "Chez la plupart des droitiers, le langage s'effondre à gauche. Le test guide la chirurgie d'épilepsie.",
     "Technique clinique réelle, pas une métaphore. Complète Broca sans attendre l'autopsie.",
     "Invasif, remplacé parfois par l'IRMf de langage, qui n'a pas la même valeur causale."),

    ("p300", "Le potentiel P300", "Samuel Sutton", "1965", "27-science-psychologique",
     "Une onde électrique marque la surprise pertinente.",
     "Dans une tâche oddball, un stimulus rare et à détecter évoque une positivité autour de 300 ms (P3).",
     "L'amplitude et la latence suivent l'attention et la décision. Base de certains épelleurs cerveau-machine.",
     "Montre qu'on peut extraire une intention sans parole, dans des conditions très contrôlées.",
     "N'est pas un détecteur de mensonge fiable, malgré des tentatives commerciales."),

    ("n400", "L'onde N400", "Marta Kutas & Steven Hillyard", "1980", "27-science-psychologique",
     "Le cerveau détecte un mot qui ne va pas, avant qu'on le commente.",
     "On lit une phrase dont le dernier mot est inattendu (« je prends le café avec du ciment »). L'EEG montre une négativité vers 400 ms.",
     "L'onde suit la surprenante sémantique, même si le mot est grammaticalement correct.",
     "Outil majeur de la psycholinguistique, à relier à la fiche Langage.",
     "C'est un marqueur, pas une définition de « la compréhension »."),

    ("mismatch-negativity", "La négativité de discordance (MMN)", "Risto Näätänen", "1978", "27-science-psychologique",
     "Même sans faire attention, l'oreille détecte l'écart.",
     "Une série de sons identiques est interrompue par un son déviant, pendant que le participant lit ou ignore.",
     "Une négativité automatique apparaît. Le cerveau compare en continu à une prédiction.",
     "Soutient le modèle prédictif. Utilisée en recherche sur le coma et le développement.",
     "Interprétation clinique individuelle encore prudente."),

    ("lashley-masse", "La loi d'action de masse", "Karl Lashley", "1929", "27-science-psychologique",
     "Après des lésions corticales, Lashley conclut que la mémoire est partout.",
     "Des rats apprennent un labyrinthe ; on ôte des portions variables de cortex et on reteste.",
     "Le déficit suit surtout la quantité de tissu retiré, pas un lieu unique. Lashley parle d'équiponentialité.",
     "Utile contre le localisme naïf. Faux dans sa forme extrême : toutes les régions ne se valent pas.",
     "Les travaux suivants (Milner, O'Keefe, imagerie) ont réintroduit des lieux — dans des réseaux."),

    ("flourens-ablations", "Les ablations de Flourens", "Pierre Flourens", "1824", "27-science-psychologique",
     "Enlever un morceau de cerveau et voir ce qui reste.",
     "Flourens détruit chez l'oiseau des portions de cervelet, de bulbe ou d'hémisphères, et décrit les déficits.",
     "Le cervelet coordonne, le bulbe maintient la vie, les hémisphères « l'intelligence » — mais il nie les localisations fines de Gall.",
     "Méthode fondatrice, et frein temporaire à la localisation. Le débat Gall / Flourens structure le siècle.",
     "Espèces, anesthésie, précisions : les conclusions étaient trop globales."),

    ("merzenich-plasticite", "La carte qui se déplace", "Michael Merzenich", "1980s", "27-science-psychologique",
     "Le cortex somatosensoriel se réorganise selon l'usage.",
     "Chez le singe, on ampute ou on entraîne un doigt, puis on recartographie le cortex.",
     "La zone du doigt disparu est envahie par les voisines ; l'entraînement agrandit la représentation.",
     "Base de la rééducation intensive et de la thérapie contrainte. La plasticité a un mode d'emploi : la répétition.",
     "Ne justifie aucun programme « reprogrammez votre cerveau en 7 jours »."),

    ("ramachandran-miroir", "La boîte à miroir", "Vilayanur Ramachandran", "1990s", "27-science-psychologique",
     "Tromper le cerveau pour soulager un membre fantôme.",
     "Le patient regarde le membre sain dans un miroir, à la place du membre amputé, et le « bouge ».",
     "Chez certains, la douleur fantôme diminue : le conflit visuo-moteur se dénoue.",
     "Exemple frappant de ce qu'on peut faire d'une illusion (cf. main en caoutchouc) en clinique.",
     "Efficacité inégale selon les essais ; ce n'est pas un remède universel."),

    ("tms-pascual", "Cartographier sans ouvrir", "Álvaro Pascual-Leone et al.", "1990s", "27-science-psychologique",
     "Une impulsion magnétique perturbe une région depuis le scalp.",
     "Une bobine délivre un champ bref ; le cortex moteur fait bouger un doigt, le cortex du langage interrompt un mot.",
     "On obtient une causalité temporaire, réversible, utilisable en recherche et, en protocoles encadrés, en clinique.",
     "Complète l'IRMf (corrélation) par une perturbation. Usage dépressif répétitif sous conditions.",
     "Un casque grand public « d'amélioration cognitive » n'est pas de la TMS clinique."),

    ("dbs-benabid", "La stimulation cérébrale profonde", "Alim-Louis Benabid", "1987-1990s", "27-science-psychologique",
     "Des électrodes dans les noyaux gris pour calmer un tremblement.",
     "À Grenoble, on implante et on stimule à haute fréquence le noyau sous-thalamique ou le VIM chez des patients parkinsoniens.",
     "Le tremblement et la rigidité chutent, de façon réglable et réversible — contrairement aux lésions définitives.",
     "Exemple français majeur de ce qu'on peut faire du savoir sur les circuits. Indications élargies ensuite, toujours encadrées.",
     "Chirurgie lourde, effets secondaires possibles (humeur, parole). Pas une « télécommande du soi »."),

    ("optogenetique", "Allumer un neurone avec la lumière", "Karl Deisseroth, Edward Boyden", "2005", "27-science-psychologique",
     "Une opsine, une fibre optique, une population précise.",
     "On exprime une protéine sensible à la lumière dans des neurones ciblés, puis on les active ou inhibe à la milliseconde.",
     "On peut relier un type cellulaire à un comportement chez l'animal avec une précision inédite.",
     "A redessiné la causalité en neurosciences de circuit. Reste essentiellement préclinique.",
     "Ne se traduit pas en casque lumineux pour humain dans un salon."),

    ("soon-haynes", "Décoder une intention avant le rapport", "Chun Siong Soon, John-Dylan Haynes", "2008", "27-science-psychologique",
     "L'IRMf prévoit un peu mieux que le hasard quel bouton sera pressé.",
     "Le participant choisit à son rythme gauche ou droite. Un classifieur entraîné sur l'activité préfrontale et pariétale anticipe le choix plusieurs secondes avant.",
     "L'information de l'action future est présente tôt, à un niveau encore peu conscient.",
     "Prolonge Libet avec l'imagerie. Relance le débat, n'y met pas fin.",
     "Précision limitée, tâche triviale, pas une lecture de la vie morale."),

    ("patient-sm", "La patiente S.M. et l'amygdale", "Ralph Adolphs, Daniel Tranel, Antonio Damasio", "1994-2010", "27-science-psychologique",
     "Sans amygdale, la peur extérieure s'émousse.",
     "S.M., atteinte d'une maladie d'Urbach-Wiethe, a les amygdales détruites. On lui montre des visages, des scènes, des serpents.",
     "Elle reconnaît mal la peur sur les visages et s'approche de stimuli que d'autres fuient, tout en ayant d'autres émotions.",
     "Dissociation précieuse, à relier à la fiche Émotions — sans réduire quelqu'un à une structure.",
     "Un cas. La peur interne (suffocation) peut rester. L'amygdale n'est pas « l'organe de la peur » unique."),

    ("heminegligence", "La négligence spatiale unilatérale", "Description classique, travaux de Bisiach & Luzzatti", "1978", "27-science-psychologique",
     "On peut « oublier » la moitié du monde sans être aveugle.",
     "Après une lésion pariétale droite, le patient mange la moitié de l'assiette, dessine une maison sans côté gauche, décrit une place en omettant un flanc.",
     "Bisiach demande d'imaginer la place du Dôme de Milan : le côté omis change quand on inverse le point de vue mental.",
     "Ce n'est pas un trou dans l'œil, c'est un trou dans l'espace représenté. Relie attention, espace, conscience.",
     "Tableau variable, souvent associé à l'anosognosie : le patient nie le déficit."),

    ("change-blindness", "La cécité au changement", "Ronald Rensink, Daniel Simons", "1997", "27-science-psychologique",
     "Un détail énorme peut changer sous les yeux sans être vu.",
     "Deux images alternent avec un bref masque ; un élément important a été modifié.",
     "La détection est très lente. On n'encode pas toute la scène, seulement ce que l'attention a choisi.",
     "Complète le gorille invisible. Conséquences en sécurité, radiologie, témoignage.",
     "Ne signifie pas que « nous ne voyons rien » : la tâche et le masque pèsent lourd."),
]
