# -*- coding: utf-8 -*-
"""PSYCLOPÉDIA — Pensées du jour, rappels et métadonnées des planches.

Les citations longues d'auteurs encore protégés sont évitées : on privilégie
des pensées rédigées pour le site, des paraphrases attribuées « d'après »,
et de courtes formules du domaine public.
"""

# Créneaux horaires (Europe/Paris) où une pensée peut être proposée.
SLOTS = [
    ("matin", "08:30", "Pensée du matin"),
    ("midi", "12:15", "Citation de midi"),
    ("apres-midi", "16:00", "Pause de réflexion"),
    ("soir", "20:30", "Retour du soir"),
]

# Minutes avant un cours pour les rappels (du plus tôt au plus tard).
COURS_OFFSETS = [
    (60, "Dans une heure"),
    (15, "Dans quinze minutes"),
    (0, "C'est l'heure"),
]

# (id, kind, slot_pref, texte, attribution, href_rel_ebook_or_abs, plate_id, keywords)
PENSEES = [
    ("p-flux", "citation", "matin",
     "La conscience n'est pas un théâtre avec des objets posés : c'est un courant. On n'y entre pas deux fois de la même façon.",
     "D'après William James", "references/auteurs.html#james", "hero-conscience",
     "conscience flux james"),
    ("p-habitude", "prompt", "matin",
     "Quelle habitude de ce matin a décidé à ta place ? Nomme-la, puis choisis-en une seule à faire volontairement.",
     "Psyclopédia", "pratique.html", "cat-06-personnalite",
     "habitude volonté"),
    ("p-attention", "citation", "apres-midi",
     "L'attention n'augmente pas ce qui est là : elle choisit ce qui existera pour toi dans la minute qui vient.",
     "Psyclopédia", "categories/03-cognitive.html", "hero-attention",
     "attention cognitive"),
    ("p-memoire", "prompt", "soir",
     "Sans relire tes notes : qu'est-ce que tu peux encore raconter du dernier cours, en trois phrases ?",
     "Psyclopédia", "apprendre.html", "hero-memoire",
     "memoire recuperation"),
    ("p-wundt", "citation", "midi",
     "La psychologie commence quand on cesse de commenter l'âme et qu'on mesure une expérience immédiate.",
     "D'après Wilhelm Wundt", "references/auteurs.html#wundt", "cat-01-fondamentaux",
     "wundt laboratoire"),
    ("p-piaget", "citation", "matin",
     "L'intelligence n'est pas un stock de réponses. C'est ce que l'esprit invente quand il ne sait pas encore.",
     "D'après Jean Piaget", "references/auteurs.html#piaget", "cat-05-developpement",
     "piaget intelligence"),
    ("p-vygotski", "citation", "midi",
     "Ce que tu fais aujourd'hui avec une aide bien placée, tu le feras seul demain. Cherche cette zone, pas la facilité.",
     "D'après Lev Vygotski", "references/auteurs.html#vygotski", "cat-13-education",
     "vygotski zpd"),
    ("p-emotion", "prompt", "apres-midi",
     "Nomme l'émotion présente en un mot précis — pas « mal », pas « bizarre ». Le vocabulaire change déjà ce que le corps raconte.",
     "Psyclopédia", "categories/07-emotions.html", "hero-emotion",
     "emotion labelling"),
    ("p-biais", "citation", "midi",
     "Un biais n'est pas une insulte. C'est une économie de l'esprit : utile hier, à vérifier aujourd'hui.",
     "Psyclopédia", "references/biais.html", "cat-03-cognitive",
     "biais jugement"),
    ("p-ribot", "citation", "matin",
     "On n'observe pas la mémoire comme on observerait une chose : on observe ce qu'elle laisse revenir, et ce qu'elle retient.",
     "D'après Théodule Ribot", "references/auteurs.html#ribot", "hero-memoire",
     "ribot memoire"),
    ("p-binet", "citation", "apres-midi",
     "Une mesure de l'esprit n'est pas l'esprit. C'est une coupe, à une heure, dans une tâche.",
     "D'après Alfred Binet", "references/tests.html", "cat-19-psychometrie",
     "binet mesure"),
    ("p-pavlov", "citation", "midi",
     "Le chien de Pavlov n'illustre pas la stupidité : il illustre que l'attente elle-même devient un stimulus.",
     "D'après Ivan Pavlov", "references/experiences.html", "cat-12-travail",
     "pavlov conditionnement"),
    ("p-sociale", "prompt", "apres-midi",
     "Dans le dernier groupe où tu t'es tu : était-ce de la prudence, ou de la conformité ? Les deux existent.",
     "Psyclopédia", "categories/04-sociale.html", "cat-04-sociale",
     "conformite asch"),
    ("p-sommeil", "prompt", "soir",
     "Le cerveau ne révise pas mieux en forçant. Il révise en dormant. Coupe l'écran vingt minutes plus tôt que d'habitude.",
     "Psyclopédia", "pratique.html", "cat-14-sante",
     "sommeil consolidation"),
    ("p-methode", "citation", "matin",
     "Une anecdote convainc. Une série d'anecdotes persuade. Seule une comparaison contrôlée commence à prouver.",
     "Psyclopédia", "methodes.html", "cat-01-fondamentaux",
     "methode preuve"),
    ("p-replication", "citation", "midi",
     "Un résultat célèbre n'est pas un résultat établi. Demande toujours s'il a été répliqué — et par qui.",
     "Psyclopédia", "references/debats.html", "cat-19-psychometrie",
     "replication crise"),
    ("p-attachement", "citation", "soir",
     "Une base sûre n'empêche pas d'explorer. C'est ce qui rend l'exploration possible.",
     "D'après John Bowlby", "references/auteurs.html#bowlby", "cat-05-developpement",
     "attachement bowlby"),
    ("p-rogers", "citation", "matin",
     "Écouter n'est pas attendre son tour pour parler. C'est faire de la place à une expérience qui n'est pas la tienne.",
     "D'après Carl Rogers", "references/auteurs.html#rogers", "cat-10-therapies",
     "rogers ecoute"),
    ("p-stress", "prompt", "apres-midi",
     "Le trac et l'excitation partagent le même corps. Réétiqueter « je me prépare » change parfois la suite — pas toujours, assez pour essayer.",
     "Psyclopédia", "categories/07-emotions.html", "hero-emotion",
     "stress reevaluation"),
    ("p-ecrans", "prompt", "soir",
     "Combien de fois as-tu déverrouillé le téléphone depuis le déjeuner ? Devine d'abord, vérifie ensuite. L'écart est déjà une donnée.",
     "Psyclopédia", "categories/22-numerique.html", "cat-22-numerique",
     "ecrans attention"),
    ("p-decision", "citation", "midi",
     "On décide rarement avec toutes les cartes. On décide avec un récit, puis on cherche les cartes qui le confirment.",
     "Psyclopédia", "references/biais.html", "cat-21-consommation",
     "decision confirmation"),
    ("p-langage", "citation", "matin",
     "Le mot que tu choisis pour un état n'est pas un étiquette collée après coup : il oriente ce que tu vas en faire.",
     "Psyclopédia", "categories/18-langage.html", "cat-18-langage",
     "langage emotion"),
    ("p-mythe", "citation", "apres-midi",
     "Nous n'utilisons pas dix pour cent du cerveau. Nous utilisons, à chaque instant, beaucoup moins que ce que la formule promet — et beaucoup plus que ce qu'elle laisse croire.",
     "Psyclopédia", "references/mythes.html", "cat-08-neurosciences",
     "neuromythe cerveau"),
    ("p-travail", "prompt", "matin",
     "Avant d'ouvrir la boîte mail : une seule tâche de trente minutes qui ferait de cette journée une journée utile.",
     "Psyclopédia", "categories/12-travail.html", "cat-12-travail",
     "attention travail"),
    ("p-clinique", "citation", "soir",
     "Comprendre un trouble n'est pas le posséder. Une fiche n'est pas un diagnostic — et le site ne s'y substitue jamais.",
     "Psyclopédia", "aide.html", "cat-09-psychopathologie",
     "clinique prudence"),
    ("p-histoire", "citation", "midi",
     "Chaque école de psychologie est née d'une objection. Lire l'histoire, c'est lire des disputes qui ont duré.",
     "Psyclopédia", "references/courants.html", "cat-02-histoire",
     "histoire courants"),
    ("p-espace", "prompt", "apres-midi",
     "Lève-toi. Trois minutes sans écran. Note une seule chose que tu as vue et que tu aurais manquée assis.",
     "Psyclopédia", "categories/25-environnementale.html", "cat-25-environnementale",
     "attention environnement"),
    ("p-age", "citation", "soir",
     "Le vieillissement n'est pas une soustraction uniforme. Certaines fonctions baissent, d'autres se réorganisent — et l'expérience compte.",
     "Psyclopédia", "categories/24-vieillissement.html", "cat-24-vieillissement",
     "vieillissement"),
    ("p-sport", "prompt", "matin",
     "Le corps n'est pas le véhicule de l'esprit. Aujourd'hui, quelle sensation physique précède ta meilleure concentration ?",
     "Psyclopédia", "categories/20-sport.html", "cat-20-sport",
     "corps sport"),
    ("p-politique", "citation", "midi",
     "On ne vote pas seulement des programmes : on vote des identités. Le savoir de cela n'annule pas le vote, il l'éclaire.",
     "Psyclopédia", "categories/26-politique.html", "cat-26-politique",
     "politique identite"),
    ("p-interculturel", "prompt", "apres-midi",
     "Quelle norme de ta culture te paraît « naturelle » — et le resterait-elle à cent kilomètres d'ici ?",
     "Psyclopédia", "categories/17-interculturelle.html", "cat-17-interculturelle",
     "culture norme"),
    ("p-comparee", "citation", "matin",
     "Observer un autre animal n'est pas le déguiser en humain. C'est accepter qu'il y a plusieurs solutions à un même problème de vie.",
     "Psyclopédia", "categories/16-comparee.html", "cat-16-comparee",
     "comparee evolution"),
    ("p-positive", "citation", "soir",
     "La psychologie positive n'est pas l'injonction d'être heureux. C'est l'étude de ce qui aide à tenir — sans nier ce qui fait mal.",
     "Psyclopédia", "categories/11-positive.html", "cat-11-positive",
     "positive prudence"),
    ("p-cours", "prompt", "matin",
     "Le prochain cours de 50 minutes : une question que tu veux lui poser avant d'appuyer sur lecture. Écris-la.",
     "Psyclopédia", "emploi-du-temps.html", "hero-frontispice",
     "cours preparation"),
    ("p-revision", "prompt", "soir",
     "Deux cartes de révision, pas vingt. La constance bat le marathon — c'est l'un des résultats les plus stables de l'apprentissage.",
     "Psyclopédia", "revision.html", "hero-memoire",
     "revision espacee"),
    ("p-descartes", "citation", "matin",
     "Ce n'est pas assez d'avoir l'esprit bon, le principal est de l'appliquer bien.",
     "René Descartes, Discours de la méthode", "references/chronologie.html", "cat-01-fondamentaux",
     "descartes methode"),
    ("p-pascal", "citation", "soir",
     "L'homme n'est qu'un roseau, le plus faible de la nature ; mais c'est un roseau pensant.",
     "Blaise Pascal, Pensées", "categories/08-neurosciences.html", "hero-conscience",
     "pascal pensee"),
    ("p-montaigne", "citation", "midi",
     "La plus grande chose du monde, c'est de savoir être à soi.",
     "Michel de Montaigne, Essais", "categories/06-personnalite.html", "hero-personnalite",
     "montaigne soi"),
    ("p-quiz", "prompt", "apres-midi",
     "Une question de quiz ratée vaut mieux qu'une page relue en diagonale. L'erreur annotée reste.",
     "Psyclopédia", "quiz/index.html", "cat-13-education",
     "quiz recuperation"),
    ("p-laboratoire", "prompt", "midi",
     "Va faire deux minutes de Stroop. Ensuite seulement, relis ce que le test est censé mesurer. L'ordre inverse gâche la démonstration.",
     "Psyclopédia", "laboratoire.html", "cat-03-cognitive",
     "laboratoire stroop"),
]

# Planches statiques (fichiers déjà présents) — collection de référence + planches créées.
# file est relatif à la racine du dépôt.
PLATES_STATIQUES = [
    {"id": "col-frontispice", "fig": "I", "title": "Frontispice — science de la représentation",
     "file": "assets-ebook/plates/collection/frontispice.png", "paper": "cream",
     "kind": "collection", "meaning": "L'esprit figuré comme un système d'axes : ce que l'on peut représenter, on peut commencer à l'étudier.",
     "cats": ["01-fondamentaux"], "origin": "collection"},
    {"id": "col-cardioide", "fig": "3", "title": "Courbe d'attention",
     "file": "assets-ebook/plates/collection/fig-03-cardioide.png", "paper": "blue",
     "kind": "collection", "meaning": "Une forme unique sur une grille polaire : l'attention isole un contour dans un champ de possibles.",
     "cats": ["03-cognitive"], "origin": "collection"},
    {"id": "col-polar", "fig": "19", "title": "Champ émotionnel",
     "file": "assets-ebook/plates/collection/fig-19-polar.png", "paper": "red",
     "kind": "collection", "meaning": "L'émotion comme un cercle de forces : intensité, direction, secteurs encore vides.",
     "cats": ["07-emotions"], "origin": "collection"},
    {"id": "col-ovales", "fig": "2", "title": "Couches de la mémoire",
     "file": "assets-ebook/plates/collection/fig-02-ovales.png", "paper": "cream",
     "kind": "collection", "meaning": "Des enveloppes emboîtées : ce qui est répété s'épaissit, ce qui n'est pas rappelé s'efface.",
     "cats": ["03-cognitive", "05-developpement"], "origin": "collection"},
    {"id": "col-tulipe", "fig": "12", "title": "Forme individuelle",
     "file": "assets-ebook/plates/collection/fig-12-tulipe.png", "paper": "peach",
     "kind": "collection", "meaning": "Une surface fermée, irrégulière, unique : la personnalité n'est pas une moyenne, c'est une géométrie.",
     "cats": ["06-personnalite"], "origin": "collection"},
    {"id": "col-vecteur", "fig": "17", "title": "Axe de la conscience",
     "file": "assets-ebook/plates/collection/fig-17-vecteur.png", "paper": "cream",
     "kind": "collection", "meaning": "Deux régimes superposés — pointe et volume — comme le foyer attentif et le fond de l'expérience.",
     "cats": ["08-neurosciences", "01-fondamentaux"], "origin": "collection"},
    {"id": "hero-frontispice", "fig": "A", "title": "Planche de représentation",
     "file": "assets-ebook/plates/hero/plate_frontispice_site.png", "paper": "cream",
     "kind": "hero", "meaning": "Frontispice du cabinet : représenter, ce n'est pas copier l'esprit, c'est lui donner un axe.",
     "cats": ["01-fondamentaux"], "origin": "created"},
    {"id": "hero-attention", "fig": "11", "title": "Rose de l'attention",
     "file": "assets-ebook/plates/hero/plate_attention_polaire.png", "paper": "blue",
     "kind": "hero", "meaning": "L'attention dessine une cardioïde dans le champ : tout le reste reste en pointillés.",
     "cats": ["03-cognitive"], "origin": "created"},
    {"id": "hero-emotion", "fig": "21", "title": "Roue des affects",
     "file": "assets-ebook/plates/hero/plate_emotion_rouge.png", "paper": "red",
     "kind": "hero", "meaning": "Un cercle incomplet : toute émotion a des secteurs encore sans nom.",
     "cats": ["07-emotions"], "origin": "created"},
    {"id": "hero-memoire", "fig": "7", "title": "Enveloppes mnémoniques",
     "file": "assets-ebook/plates/hero/plate_memoire_ovales.png", "paper": "cream",
     "kind": "hero", "meaning": "Se souvenir, c'est épaissir une enveloppe. Oublier, c'est la laisser poreuse.",
     "cats": ["03-cognitive", "13-education"], "origin": "created"},
    {"id": "hero-personnalite", "fig": "14", "title": "Solide de la personne",
     "file": "assets-ebook/plates/hero/plate_personnalite_tulipe.png", "paper": "peach",
     "kind": "hero", "meaning": "Trois lobes, une ombre intérieure : le caractère a un relief, pas seulement un score.",
     "cats": ["06-personnalite"], "origin": "created"},
    {"id": "hero-conscience", "fig": "23", "title": "Vecteur et volume",
     "file": "assets-ebook/plates/hero/plate_conscience_vecteur.png", "paper": "cream",
     "kind": "hero", "meaning": "Le foyer conscient (pointe) repose sur un volume d'habitudes et de traces.",
     "cats": ["08-neurosciences"], "origin": "created"},
]

# Une planche SVG par catégorie (générée par build_plates.py).
# figure : nom du traceur ; paper : cream|blue|red|peach|sage
PLATES_CATEGORIES = [
    ("01-fondamentaux", "axis_diamond", "cream", "L'objet de la psychologie"),
    ("02-histoire", "stacked_vector", "cream", "Couches de l'histoire"),
    ("03-cognitive", "polar_cardioid", "blue", "Contour de l'attention"),
    ("04-sociale", "polar_wheel", "blue", "Champ du groupe"),
    ("05-developpement", "nested_ovals", "cream", "Enveloppes de l'âge"),
    ("06-personnalite", "tulip_form", "peach", "Relief du caractère"),
    ("07-emotions", "polar_wheel", "red", "Rose des affects"),
    ("08-neurosciences", "axis_diamond", "sage", "Axe du système nerveux"),
    ("09-psychopathologie", "rose_curve", "red", "Forme brisée"),
    ("10-therapies", "vesica", "cream", "Rencontre thérapeutique"),
    ("11-positive", "tulip_form", "peach", "Élan"),
    ("12-travail", "radiating_field", "cream", "Forces de la tâche"),
    ("13-education", "nested_ovals", "blue", "Cercles d'apprentissage"),
    ("14-sante", "vesica", "peach", "Corps et récit"),
    ("15-legale", "stacked_vector", "cream", "Jugement et preuve"),
    ("16-comparee", "rose_curve", "sage", "Autres solutions du vivant"),
    ("17-interculturelle", "polar_wheel", "peach", "Normes en rotation"),
    ("18-langage", "spiral", "cream", "Bobine du discours"),
    ("19-psychometrie", "polar_wheel", "cream", "Cadran de la mesure"),
    ("20-sport", "radiating_field", "peach", "Activation"),
    ("21-consommation", "tulip_form", "red", "Désir et choix"),
    ("22-numerique", "spiral", "blue", "Boucle de l'écran"),
    ("23-evolutionniste", "nested_ovals", "sage", "Strates adaptées"),
    ("24-vieillissement", "nested_ovals", "cream", "Réorganisation"),
    ("25-environnementale", "rose_curve", "sage", "Lieu et conduite"),
    ("26-politique", "radiating_field", "cream", "Identités en champ"),
]
