# -*- coding: utf-8 -*-
"""Extension du dictionnaire : 250 notions supplémentaires (terme, définition, catégorie liée)."""

GLOSSAIRE_PLUS = [
    # --- Méthodes, épistémologie ---
    ("Aléatorisation", "Répartition au hasard des participants entre les conditions d'une expérience ; seule procédure permettant de conclure à une causalité.", "01-fondamentaux"),
    ("Double aveugle", "Protocole dans lequel ni le participant ni l'expérimentateur ne savent qui reçoit le traitement actif, afin de neutraliser les attentes.", "01-fondamentaux"),
    ("Variable confondue", "Facteur non contrôlé qui varie en même temps que la variable étudiée et peut expliquer le résultat à sa place.", "01-fondamentaux"),
    ("Taille d'effet", "Mesure de l'ampleur d'un phénomène, indépendante de la taille de l'échantillon ; bien plus informative que la seule significativité.", "01-fondamentaux"),
    ("Méta-analyse", "Synthèse statistique de nombreuses études portant sur une même question, qui augmente la précision de l'estimation.", "01-fondamentaux"),
    ("Préenregistrement", "Dépôt public des hypothèses et du plan d'analyse avant le recueil des données, pour empêcher le p-hacking.", "01-fondamentaux"),
    ("P-hacking", "Multiplication d'analyses non déclarées jusqu'à obtenir un résultat statistiquement significatif.", "01-fondamentaux"),
    ("HARKing", "Présenter après coup une hypothèse formulée à partir des résultats comme si elle avait été posée au départ.", "01-fondamentaux"),
    ("Biais de publication", "Tendance des revues à publier les résultats positifs, ce qui déforme la littérature disponible.", "01-fondamentaux"),
    ("Puissance statistique", "Probabilité de détecter un effet réellement présent ; faible quand l'échantillon est trop petit.", "01-fondamentaux"),
    ("Étude longitudinale", "Suivi des mêmes personnes sur une longue période, permettant d'observer des trajectoires individuelles.", "01-fondamentaux"),
    ("Étude transversale", "Comparaison de groupes différents à un même moment ; économique mais confond âge et génération.", "01-fondamentaux"),
    ("Effet de cohorte", "Différence entre générations attribuée à tort au vieillissement dans les études transversales.", "24-vieillissement"),
    ("Validité écologique", "Degré auquel les résultats obtenus en laboratoire se transposent aux situations réelles.", "01-fondamentaux"),
    ("Effet expérimentateur", "Influence involontaire des attentes du chercheur sur le comportement des participants.", "01-fondamentaux"),
    ("Désirabilité sociale", "Tendance à répondre conformément à ce qui est socialement valorisé plutôt que sincèrement.", "01-fondamentaux"),
    ("Falsifiabilité", "Critère de Popper : une théorie scientifique doit pouvoir être réfutée par une observation possible.", "01-fondamentaux"),
    ("Opérationnalisation", "Traduction d'un concept abstrait en une mesure concrète et reproductible.", "19-psychometrie"),
    ("Réplication directe", "Reproduction d'une étude avec le même protocole pour vérifier la solidité du résultat.", "01-fondamentaux"),
    ("Consentement éclairé", "Accord donné après information complète sur le déroulement, les risques et le droit de retrait.", "01-fondamentaux"),

    # --- Cognition ---
    ("Mémoire de travail", "Système actif de maintien et de manipulation temporaire d'informations, de capacité très limitée.", "03-cognitive"),
    ("Boucle phonologique", "Composante de la mémoire de travail qui maintient l'information verbale par répétition intérieure.", "03-cognitive"),
    ("Calepin visuo-spatial", "Composante de la mémoire de travail dédiée aux images mentales et aux relations spatiales.", "03-cognitive"),
    ("Administrateur central", "Composante attentionnelle qui coordonne les autres sous-systèmes de la mémoire de travail.", "03-cognitive"),
    ("Buffer épisodique", "Espace d'intégration reliant mémoire de travail et mémoire à long terme en épisodes cohérents.", "03-cognitive"),
    ("Chunking", "Regroupement d'éléments en unités signifiantes pour augmenter la quantité d'information retenue.", "03-cognitive"),
    ("Mémoire déclarative", "Mémoire des faits et des événements, accessible consciemment et verbalisable.", "03-cognitive"),
    ("Mémoire procédurale", "Mémoire des savoir-faire automatisés, accessible sans conscience explicite.", "03-cognitive"),
    ("Mémoire épisodique", "Souvenirs d'événements personnellement vécus, situés dans un temps et un lieu.", "03-cognitive"),
    ("Mémoire sémantique", "Connaissances générales sur le monde, détachées du contexte de leur acquisition.", "03-cognitive"),
    ("Mémoire prospective", "Capacité à se souvenir d'une action à accomplir dans le futur.", "03-cognitive"),
    ("Consolidation", "Stabilisation progressive d'un souvenir après son encodage, largement dépendante du sommeil.", "03-cognitive"),
    ("Reconsolidation", "Fragilisation temporaire d'un souvenir lors de son rappel, qui permet sa modification.", "03-cognitive"),
    ("Encodage", "Transformation d'une information perçue en trace mnésique exploitable.", "03-cognitive"),
    ("Indice de récupération", "Élément de contexte facilitant l'accès à un souvenir stocké.", "03-cognitive"),
    ("Spécificité d'encodage", "Principe de Tulving : on se souvient mieux dans un contexte proche de celui de l'apprentissage.", "03-cognitive"),
    ("Interférence proactive", "Perturbation d'un nouvel apprentissage par des connaissances antérieures.", "03-cognitive"),
    ("Interférence rétroactive", "Perturbation d'un souvenir ancien par un apprentissage plus récent.", "03-cognitive"),
    ("Amnésie antérograde", "Incapacité à former de nouveaux souvenirs après une lésion.", "08-neurosciences"),
    ("Amnésie rétrograde", "Perte de souvenirs formés avant une lésion ou un traumatisme.", "08-neurosciences"),
    ("Bosse de réminiscence", "Surabondance de souvenirs autobiographiques datant de l'adolescence et du début de l'âge adulte.", "24-vieillissement"),
    ("Attention soutenue", "Capacité à maintenir la concentration sur une durée prolongée.", "03-cognitive"),
    ("Attention sélective", "Filtrage de l'information pertinente au détriment des distracteurs.", "03-cognitive"),
    ("Attention exécutive", "Résolution des conflits attentionnels et inhibition des réponses automatiques.", "03-cognitive"),
    ("Cécité au changement", "Incapacité à détecter une modification importante d'une scène visuelle entre deux instants.", "03-cognitive"),
    ("Charge cognitive", "Quantité de ressources mentales mobilisées par une tâche à un instant donné.", "13-education"),
    ("Automatisation", "Passage d'un traitement contrôlé et coûteux à un traitement rapide et sans effort.", "03-cognitive"),
    ("Fonctions exécutives", "Ensemble de processus de contrôle : inhibition, flexibilité, mise à jour, planification.", "03-cognitive"),
    ("Inhibition cognitive", "Capacité à supprimer une réponse dominante ou une information non pertinente.", "03-cognitive"),
    ("Flexibilité mentale", "Aptitude à changer de règle, de stratégie ou de point de vue.", "03-cognitive"),
    ("Heuristique", "Raccourci mental économique, efficace en général mais générateur d'erreurs systématiques.", "03-cognitive"),
    ("Système 1", "Mode de pensée rapide, automatique, intuitif et sans effort.", "03-cognitive"),
    ("Système 2", "Mode de pensée lent, contrôlé, analytique et coûteux en ressources.", "03-cognitive"),
    ("Métacognition", "Connaissance et régulation de ses propres processus mentaux.", "13-education"),
    ("Difficulté désirable", "Condition qui ralentit l'apprentissage immédiat mais améliore la rétention à long terme.", "13-education"),
    ("Effet de supériorité de l'image", "Meilleure mémorisation des images que des mots correspondants.", "13-education"),
    ("Priming sémantique", "Facilitation du traitement d'un mot par la présentation préalable d'un mot lié par le sens.", "03-cognitive"),
    ("Gestalt", "Courant selon lequel la perception organise le champ en formes globales irréductibles à leurs parties.", "03-cognitive"),
    ("Constance perceptive", "Stabilité perçue d'un objet malgré les variations d'éclairage, de distance ou d'angle.", "03-cognitive"),
    ("Traitement descendant", "Influence des connaissances et des attentes sur la perception d'un stimulus.", "03-cognitive"),
    ("Traitement ascendant", "Analyse perceptive guidée uniquement par les caractéristiques physiques du stimulus.", "03-cognitive"),
    ("Seuil absolu", "Intensité minimale d'un stimulus détectable dans la moitié des essais.", "03-cognitive"),
    ("Loi de Weber-Fechner", "La plus petite différence perceptible est proportionnelle à l'intensité du stimulus de départ.", "03-cognitive"),
    ("Détection du signal", "Théorie distinguant la sensibilité perceptive du critère de décision adopté par l'observateur.", "03-cognitive"),
    ("Synesthésie", "Association automatique et stable entre deux modalités sensorielles, comme voir des couleurs en entendant des sons.", "03-cognitive"),
    ("Aphantasie", "Absence ou quasi-absence d'imagerie mentale visuelle volontaire.", "03-cognitive"),

    # --- Social ---
    ("Identité sociale", "Part de l'image de soi dérivée de l'appartenance à des groupes.", "04-sociale"),
    ("Catégorisation sociale", "Classement automatique des personnes en groupes, base des stéréotypes.", "04-sociale"),
    ("Homogénéité de l'exogroupe", "Perception selon laquelle les membres de l'autre groupe se ressemblent tous.", "04-sociale"),
    ("Stéréotype", "Croyance généralisée sur les caractéristiques des membres d'un groupe.", "04-sociale"),
    ("Préjugé", "Attitude affective, généralement négative, envers un groupe et ses membres.", "04-sociale"),
    ("Discrimination", "Comportement défavorable envers une personne en raison de son appartenance groupale.", "04-sociale"),
    ("Hypothèse du contact", "Sous quatre conditions, le contact intergroupe réduit durablement les préjugés.", "04-sociale"),
    ("Ignorance pluraliste", "Situation où chacun désapprouve une norme en privé tout en croyant être le seul.", "04-sociale"),
    ("Norme descriptive", "Perception de ce que font réellement les autres ; puissant levier de changement.", "04-sociale"),
    ("Norme injonctive", "Perception de ce qui est approuvé ou attendu socialement.", "04-sociale"),
    ("Facilitation sociale", "Amélioration de la performance sur des tâches simples en présence d'autrui.", "04-sociale"),
    ("Paresse sociale", "Réduction de l'effort individuel lorsque la performance est collective et non identifiable.", "04-sociale"),
    ("Polarisation de groupe", "Radicalisation des positions moyennes d'un groupe après discussion entre semblables.", "04-sociale"),
    ("Pensée de groupe", "Recherche d'unanimité qui empêche l'examen réaliste des alternatives.", "04-sociale"),
    ("Désindividuation", "Perte du sentiment d'identité personnelle dans une foule ou sous anonymat.", "04-sociale"),
    ("Réactance", "Résistance déclenchée par une menace perçue sur sa liberté de choix.", "04-sociale"),
    ("Pied dans la porte", "Technique consistant à obtenir un petit accord pour en obtenir un plus grand ensuite.", "04-sociale"),
    ("Porte au nez", "Technique consistant à formuler une demande excessive puis la demande réellement visée.", "04-sociale"),
    ("Amorçage tactique", "Obtenir un accord puis révéler des conditions moins favorables que celles annoncées.", "21-consommation"),
    ("Théorie de l'engagement", "Nos actes librement consentis nous lient et orientent nos attitudes ultérieures.", "04-sociale"),
    ("Attribution causale", "Explication que nous donnons aux causes d'un comportement, interne ou externe.", "04-sociale"),
    ("Locus de contrôle", "Croyance selon laquelle les événements dépendent principalement de soi ou de facteurs externes.", "04-sociale"),
    ("Comparaison sociale", "Évaluation de soi par référence à autrui, vers le haut ou vers le bas.", "04-sociale"),
    ("Menace du stéréotype", "Dégradation de performance provoquée par la crainte de confirmer un stéréotype négatif.", "04-sociale"),
    ("Effet Pygmalion", "Amélioration de la performance induite par des attentes positives d'autrui.", "13-education"),
    ("Effet Golem", "Dégradation de la performance induite par des attentes négatives d'autrui.", "13-education"),
    ("Altruisme", "Comportement bénéfique à autrui, coûteux pour soi et sans contrepartie attendue.", "04-sociale"),
    ("Empathie", "Capacité à ressentir et comprendre l'état émotionnel d'autrui tout en le distinguant du sien.", "07-emotions"),
    ("Compassion", "Sentiment d'être touché par la souffrance d'autrui, associé au désir de la soulager.", "07-emotions"),
    ("Théorie de l'esprit", "Capacité à attribuer à autrui des états mentaux différents des siens.", "05-developpement"),

    # --- Développement ---
    ("Assimilation", "Intégration d'une information nouvelle dans un schéma mental existant.", "05-developpement"),
    ("Accommodation", "Modification d'un schéma mental pour intégrer une information qui n'y entre pas.", "05-developpement"),
    ("Équilibration", "Processus d'ajustement entre assimilation et accommodation, moteur du développement chez Piaget.", "05-developpement"),
    ("Zone proximale de développement", "Écart entre ce que l'enfant réussit seul et ce qu'il réussit avec l'aide d'un adulte.", "05-developpement"),
    ("Étayage", "Soutien temporaire de l'adulte sur la partie de la tâche que l'enfant ne maîtrise pas encore.", "13-education"),
    ("Permanence de l'objet", "Compréhension qu'un objet continue d'exister lorsqu'il disparaît du champ perceptif.", "05-developpement"),
    ("Égocentrisme enfantin", "Difficulté à adopter un point de vue différent du sien, au sens cognitif et non moral.", "05-developpement"),
    ("Période sensible", "Fenêtre développementale durant laquelle un apprentissage se fait avec une facilité particulière.", "05-developpement"),
    ("Empreinte", "Attachement irréversible formé très précocement envers le premier objet mouvant perçu.", "16-comparee"),
    ("Base de sécurité", "Figure d'attachement depuis laquelle l'enfant explore le monde et vers laquelle il revient.", "05-developpement"),
    ("Modèle interne opérant", "Représentation intériorisée de soi et des autres construite à partir des expériences d'attachement.", "05-developpement"),
    ("Attachement désorganisé", "Style marqué par des comportements contradictoires, souvent lié à une figure à la fois source de peur et de réconfort.", "05-developpement"),
    ("Référencement social", "Consultation du visage de l'adulte par le bébé pour évaluer une situation ambiguë.", "05-developpement"),
    ("Attention conjointe", "Partage d'un même objet d'attention avec autrui, socle du développement du langage.", "18-langage"),
    ("Style parental démocratique", "Combinaison d'exigences claires et de chaleur affective, associée aux meilleurs résultats.", "05-developpement"),
    ("Crise d'identité", "Période de questionnement sur soi, centrale au stade adolescent selon Erikson.", "05-developpement"),
    ("Générativité", "Besoin adulte de transmettre et de contribuer aux générations suivantes (Erikson).", "05-developpement"),
    ("Théorie des stades d'Erikson", "Huit crises psychosociales jalonnant la vie, de la confiance de base à l'intégrité.", "05-developpement"),
    ("Dilemme de Heinz", "Situation morale utilisée par Kohlberg pour analyser le raisonnement éthique.", "05-developpement"),
    ("Éthique du care", "Approche morale centrée sur la relation et la responsabilité, proposée par Gilligan.", "05-developpement"),

    # --- Émotions et motivation ---
    ("Valence", "Caractère agréable ou désagréable d'une expérience émotionnelle.", "07-emotions"),
    ("Activation (arousal)", "Niveau d'éveil physiologique accompagnant un état émotionnel.", "07-emotions"),
    ("Réévaluation cognitive", "Réinterprétation d'une situation pour en modifier l'impact émotionnel.", "07-emotions"),
    ("Suppression expressive", "Inhibition de l'expression d'une émotion ressentie, stratégie coûteuse et peu efficace.", "07-emotions"),
    ("Étiquetage affectif", "Fait de nommer son émotion, ce qui réduit l'activation de l'amygdale.", "07-emotions"),
    ("Granularité émotionnelle", "Finesse avec laquelle une personne distingue et nomme ses états émotionnels.", "07-emotions"),
    ("Alexithymie", "Difficulté à identifier et à décrire ses propres émotions.", "07-emotions"),
    ("Émotion de base", "Émotion supposée universelle et innée, comme la peur, la colère ou le dégoût.", "07-emotions"),
    ("Émotion sociale", "Émotion impliquant la conscience du regard d'autrui, comme la honte, la fierté ou la culpabilité.", "07-emotions"),
    ("Contagion émotionnelle", "Transmission automatique des états affectifs entre personnes en interaction.", "04-sociale"),
    ("Marqueur somatique", "Signal corporel associé à une expérience passée, orientant rapidement la décision.", "08-neurosciences"),
    ("Catharsis", "Idée, invalidée, selon laquelle exprimer une émotion violente la ferait diminuer.", "07-emotions"),
    ("Motivation intrinsèque", "Motivation issue du plaisir et de l'intérêt inhérents à l'activité elle-même.", "07-emotions"),
    ("Motivation extrinsèque", "Motivation reposant sur une récompense ou une sanction extérieure à l'activité.", "07-emotions"),
    ("Effet de surjustification", "Baisse de motivation intrinsèque provoquée par l'ajout d'une récompense externe.", "20-sport"),
    ("Autodétermination", "Théorie fondée sur trois besoins : autonomie, compétence et affiliation.", "07-emotions"),
    ("Sentiment d'efficacité personnelle", "Croyance en sa capacité à réussir une tâche donnée (Bandura).", "07-emotions"),
    ("But de maîtrise", "Objectif orienté vers la progression et la compréhension plutôt que vers la comparaison.", "13-education"),
    ("But de performance", "Objectif orienté vers la démonstration de sa compétence face aux autres.", "13-education"),
    ("Flow", "État d'absorption complète dans une activité où défi et compétence s'équilibrent.", "11-positive"),

    # --- Neurosciences ---
    ("Neurone", "Cellule excitable du système nerveux transmettant l'information par signaux électrochimiques.", "08-neurosciences"),
    ("Synapse", "Zone de contact fonctionnel entre deux neurones où l'information est transmise chimiquement.", "08-neurosciences"),
    ("Potentiel d'action", "Impulsion électrique se propageant le long de l'axone selon la loi du tout ou rien.", "08-neurosciences"),
    ("Myéline", "Gaine lipidique isolant l'axone et accélérant fortement la conduction nerveuse.", "08-neurosciences"),
    ("Neurotransmetteur", "Molécule libérée dans la synapse pour transmettre un signal au neurone suivant.", "08-neurosciences"),
    ("Plasticité synaptique", "Modification durable de l'efficacité des connexions selon leur activité.", "08-neurosciences"),
    ("Potentialisation à long terme", "Renforcement durable d'une synapse après stimulation répétée, base cellulaire de la mémoire.", "08-neurosciences"),
    ("Règle de Hebb", "Les neurones qui s'activent ensemble renforcent leur connexion.", "08-neurosciences"),
    ("Élagage synaptique", "Élimination des connexions peu utilisées, massive à l'adolescence.", "05-developpement"),
    ("Amygdale", "Structure limbique centrale dans la détection de la menace et le conditionnement de la peur.", "08-neurosciences"),
    ("Hippocampe", "Structure indispensable à la formation des souvenirs déclaratifs et à la navigation spatiale.", "08-neurosciences"),
    ("Cortex préfrontal", "Région du contrôle exécutif, de la planification et de la régulation du comportement social.", "08-neurosciences"),
    ("Système limbique", "Ensemble de structures impliquées dans l'émotion, la motivation et la mémoire.", "08-neurosciences"),
    ("Ganglions de la base", "Noyaux profonds impliqués dans l'apprentissage des habitudes et le contrôle moteur.", "08-neurosciences"),
    ("Cervelet", "Structure coordonnant le mouvement fin, l'équilibre et certains apprentissages procéduraux.", "08-neurosciences"),
    ("Corps calleux", "Faisceau de fibres reliant les deux hémisphères cérébraux.", "08-neurosciences"),
    ("Thalamus", "Relais sensoriel majeur redistribuant l'information vers le cortex.", "08-neurosciences"),
    ("Hypothalamus", "Centre de régulation des fonctions vitales : faim, soif, température, rythmes, hormones.", "08-neurosciences"),
    ("Axe HHS", "Axe hypothalamo-hypophyso-surrénalien, circuit hormonal central de la réponse au stress.", "14-sante"),
    ("Cortisol", "Hormone du stress dont l'élévation chronique a des effets délétères sur la santé.", "14-sante"),
    ("Signal BOLD", "Mesure indirecte de l'activité cérébrale en IRMf, fondée sur l'oxygénation sanguine.", "08-neurosciences"),
    ("EEG", "Enregistrement de l'activité électrique cérébrale, à excellente résolution temporelle.", "08-neurosciences"),
    ("Stimulation magnétique transcrânienne", "Technique perturbant ou stimulant temporairement une région corticale, utilisée en recherche et en thérapeutique.", "08-neurosciences"),
    ("Système glymphatique", "Réseau d'élimination des déchets cérébraux, particulièrement actif pendant le sommeil profond.", "08-neurosciences"),
    ("Rythme circadien", "Cycle biologique d'environ 24 heures régulant sommeil, température et hormones.", "08-neurosciences"),
    ("Sommeil paradoxal", "Phase de sommeil associée aux rêves narratifs, à l'atonie musculaire et à la consolidation émotionnelle.", "08-neurosciences"),
    ("Chronotype", "Préférence individuelle pour le matin ou le soir, en partie déterminée biologiquement.", "08-neurosciences"),
    ("Dette de sommeil", "Accumulation d'un déficit de sommeil aux effets cognitifs mesurables et sous-estimés.", "14-sante"),
    ("Membre fantôme", "Sensation persistante d'un membre amputé, illustrant la plasticité et la construction cérébrale du corps.", "08-neurosciences"),
    ("Neuroplasticité", "Capacité du système nerveux à se réorganiser structurellement et fonctionnellement.", "08-neurosciences"),

    # --- Clinique, psychopathologie ---
    ("DSM", "Manuel diagnostique et statistique américain des troubles mentaux, fondé sur des critères opérationnels.", "09-psychopathologie"),
    ("CIM", "Classification internationale des maladies de l'OMS, référence officielle du codage médical.", "09-psychopathologie"),
    ("Comorbidité", "Présence simultanée de plusieurs troubles chez une même personne.", "09-psychopathologie"),
    ("Prévalence", "Proportion de personnes présentant un trouble dans une population à un moment donné.", "09-psychopathologie"),
    ("Incidence", "Nombre de nouveaux cas apparaissant dans une population sur une période donnée.", "14-sante"),
    ("Vulnérabilité-stress", "Modèle expliquant l'apparition d'un trouble par l'interaction entre prédisposition et facteurs de stress.", "09-psychopathologie"),
    ("Facteur transdiagnostique", "Mécanisme commun à plusieurs troubles, comme la rumination ou l'évitement expérientiel.", "09-psychopathologie"),
    ("Rumination", "Pensée répétitive centrée sur les causes et conséquences de son mal-être, facteur de maintien de la dépression.", "09-psychopathologie"),
    ("Évitement expérientiel", "Refus de ressentir certaines émotions ou sensations, qui les amplifie à long terme.", "10-therapies"),
    ("Anhédonie", "Perte de la capacité à éprouver du plaisir, symptôme central de la dépression.", "09-psychopathologie"),
    ("Dissociation", "Rupture de l'intégration normale entre conscience, mémoire, identité et perception.", "09-psychopathologie"),
    ("Dépersonnalisation", "Sentiment d'être détaché de soi-même, comme un observateur extérieur.", "09-psychopathologie"),
    ("Déréalisation", "Sentiment d'irréalité ou d'étrangeté du monde environnant.", "09-psychopathologie"),
    ("Flashback", "Reviviscence intrusive et sensorielle d'un souvenir traumatique vécue au présent.", "09-psychopathologie"),
    ("Hypervigilance", "État d'alerte permanent avec surveillance excessive de l'environnement.", "09-psychopathologie"),
    ("Compulsion", "Acte répétitif réalisé pour neutraliser l'angoisse provoquée par une obsession.", "09-psychopathologie"),
    ("Obsession", "Pensée, image ou impulsion intrusive, involontaire et anxiogène.", "09-psychopathologie"),
    ("Hallucination", "Perception sans objet extérieur, vécue comme réelle par la personne.", "09-psychopathologie"),
    ("Idée délirante", "Conviction inébranlable, non partagée culturellement et résistante aux preuves contraires.", "09-psychopathologie"),
    ("Symptômes négatifs", "Retrait, émoussement affectif et perte d'initiative, fréquents dans la schizophrénie.", "09-psychopathologie"),
    ("Insight", "Conscience qu'a la personne de son trouble et de son besoin de soin.", "09-psychopathologie"),
    ("Prodrome", "Phase de signes précoces précédant l'installation complète d'un trouble.", "09-psychopathologie"),
    ("Rechute", "Réapparition des symptômes après une période d'amélioration.", "10-therapies"),
    ("Rétablissement", "Processus de reconstruction d'une vie satisfaisante, avec ou sans symptômes résiduels.", "09-psychopathologie"),
    ("Stigmatisation intériorisée", "Adoption par la personne concernée des préjugés négatifs visant son trouble.", "09-psychopathologie"),
    ("Plan de sécurité", "Document personnalisé listant signaux d'alerte, stratégies et contacts en cas de crise suicidaire.", "09-psychopathologie"),
    ("Idéation suicidaire", "Pensées relatives à la mort ou au suicide, d'intensité variable.", "09-psychopathologie"),
    ("Syndrome de renutrition", "Complication métabolique grave lors de la reprise alimentaire après dénutrition sévère.", "09-psychopathologie"),
    ("Catastrophisation", "Amplification mentale de la menace et sentiment d'impuissance, prédicteur de chronicisation de la douleur.", "14-sante"),
    ("Kinésiophobie", "Peur du mouvement après une douleur, qui entretient l'incapacité.", "14-sante"),

    # --- Thérapies ---
    ("Alliance thérapeutique", "Qualité du lien et accord sur les objectifs et les tâches ; meilleur prédicteur du résultat.", "10-therapies"),
    ("Facteurs communs", "Ingrédients partagés par toutes les psychothérapies efficaces, indépendamment de la technique.", "10-therapies"),
    ("Restructuration cognitive", "Identification et modification des pensées automatiques dysfonctionnelles.", "10-therapies"),
    ("Exposition graduée", "Confrontation progressive et répétée au stimulus redouté, sans évitement.", "10-therapies"),
    ("Prévention de la réponse", "Fait de s'abstenir du rituel après exposition au déclencheur ; traitement de référence du TOC.", "10-therapies"),
    ("Exposition intéroceptive", "Reproduction volontaire des sensations corporelles redoutées, utilisée dans le trouble panique.", "10-therapies"),
    ("Habituation", "Diminution naturelle de la réaction émotionnelle lors d'une exposition prolongée.", "10-therapies"),
    ("Activation comportementale", "Réintroduction planifiée d'activités gratifiantes, très efficace contre la dépression.", "10-therapies"),
    ("Schéma précoce inadapté", "Croyance profonde sur soi et les autres, formée dans l'enfance et réactivée à l'âge adulte.", "10-therapies"),
    ("Mentalisation", "Capacité à comprendre son comportement et celui d'autrui en termes d'états mentaux.", "10-therapies"),
    ("Transfert", "Report sur le thérapeute d'affects et d'attentes issus de relations antérieures.", "10-therapies"),
    ("Contre-transfert", "Réactions émotionnelles du thérapeute envers son patient, utilisées comme outil clinique.", "10-therapies"),
    ("Association libre", "Consigne de dire tout ce qui vient à l'esprit, sans sélection ni censure.", "10-therapies"),
    ("Mécanisme de défense", "Procédé psychique inconscient protégeant du conflit et de l'angoisse.", "10-therapies"),
    ("Entretien motivationnel", "Approche collaborative explorant l'ambivalence pour susciter le changement sans confrontation.", "10-therapies"),
    ("Psychoéducation", "Transmission structurée d'informations sur le trouble et sa gestion au patient et à ses proches.", "10-therapies"),
    ("Pleine conscience", "Attention intentionnelle portée au moment présent, sans jugement.", "10-therapies"),
    ("MBCT", "Thérapie cognitive fondée sur la pleine conscience, recommandée en prévention de la rechute dépressive.", "10-therapies"),
    ("ACT", "Thérapie d'acceptation et d'engagement, centrée sur la flexibilité psychologique et les valeurs.", "10-therapies"),
    ("TCD", "Thérapie comportementale dialectique, référence pour le trouble borderline.", "10-therapies"),
    ("EMDR", "Approche de retraitement des souvenirs traumatiques par stimulation bilatérale.", "10-therapies"),
    ("TCC-I", "Thérapie cognitivo-comportementale de l'insomnie, traitement de première intention.", "10-therapies"),
    ("Restriction du temps de sommeil", "Technique de la TCC-I consistant à réduire le temps passé au lit pour consolider le sommeil.", "10-therapies"),
    ("Feedback-informed treatment", "Évaluation régulière des symptômes et de l'alliance pour ajuster la thérapie en cours.", "10-therapies"),
    ("Verdict du Dodo", "Constat d'efficacité globalement comparable entre psychothérapies différentes.", "10-therapies"),

    # --- Travail, éducation, santé ---
    ("Job strain", "Combinaison de forte demande et de faible latitude décisionnelle, très délétère pour la santé.", "12-travail"),
    ("Latitude décisionnelle", "Marge d'autonomie et possibilité d'utiliser ses compétences dans son travail.", "12-travail"),
    ("Justice organisationnelle", "Perception d'équité des résultats, des procédures et des relations au travail.", "12-travail"),
    ("Job crafting", "Remodelage actif par le salarié de ses tâches, relations et perception de son travail.", "12-travail"),
    ("Technostress", "Tension liée à la sollicitation permanente par les outils numériques professionnels.", "22-numerique"),
    ("Présentéisme", "Fait d'être présent au travail sans être en état d'être efficace, souvent plus coûteux que l'absence.", "12-travail"),
    ("Entretien structuré", "Entretien de recrutement à questions et cotation standardisées, bien plus prédictif que l'entretien libre.", "12-travail"),
    ("Assessment center", "Dispositif d'évaluation multi-exercices utilisé pour la sélection et le développement professionnel.", "12-travail"),
    ("Leadership transformationnel", "Style fondé sur la vision, la stimulation intellectuelle et la considération individuelle.", "12-travail"),
    ("Sécurité psychologique", "Climat d'équipe où l'on peut exprimer une erreur ou un désaccord sans crainte ; premier facteur de performance collective identifié chez Google.", "12-travail"),
    ("Pratique de récupération", "Fait de se tester activement, technique d'apprentissage la plus efficace.", "13-education"),
    ("Répétition espacée", "Révisions réparties dans le temps à intervalles croissants.", "13-education"),
    ("Entrelacement", "Alternance de types de problèmes au sein d'une même session d'apprentissage.", "13-education"),
    ("Exemple résolu", "Problème entièrement corrigé étudié par un débutant, plus efficace que la résolution autonome.", "13-education"),
    ("Effet de renversement de l'expertise", "Une méthode efficace pour les novices peut devenir contre-productive pour les experts.", "13-education"),
    ("Effet de modalité", "Meilleure compréhension d'une image accompagnée d'un commentaire oral plutôt qu'écrit.", "13-education"),
    ("Neuromythe", "Croyance erronée sur le cerveau largement répandue dans le monde éducatif.", "13-education"),
    ("Évaluation formative", "Évaluation destinée à réguler l'apprentissage en cours, sans enjeu de notation.", "13-education"),
    ("COM-B", "Modèle du changement de comportement : Capacité, Opportunité, Motivation.", "14-sante"),
    ("Intention de mise en œuvre", "Plan précis « si… alors » qui double la probabilité de passage à l'acte.", "14-sante"),
    ("Contraste mental", "Technique consistant à imaginer l'objectif puis l'obstacle, puis à planifier la réponse.", "14-sante"),
    ("Observance", "Degré de suivi effectif d'un traitement prescrit.", "14-sante"),
    ("Décision médicale partagée", "Processus associant patient et soignant dans le choix thérapeutique.", "14-sante"),
    ("Littératie en santé", "Capacité à trouver, comprendre et utiliser l'information de santé.", "14-sante"),
    ("Effet nocebo", "Apparition de symptômes désagréables induits par l'attente négative.", "14-sante"),

    # --- Légale, comparée, interculturelle, numérique ---
    ("Suggestibilité", "Tendance à intégrer des informations suggérées dans son propre souvenir.", "15-legale"),
    ("Focalisation sur l'arme", "Concentration de l'attention sur l'arme au détriment du visage de l'agresseur.", "15-legale"),
    ("Effet d'autre origine ethnique", "Moindre précision d'identification des visages d'un groupe ethnique peu familier.", "15-legale"),
    ("Faux aveu", "Reconnaissance d'un crime non commis, souvent liée à des techniques d'interrogatoire coercitives.", "15-legale"),
    ("Méthode PEACE", "Technique d'audition non accusatoire centrée sur le recueil d'informations.", "15-legale"),
    ("Jugement professionnel structuré", "Évaluation du risque combinant grille validée et analyse clinique.", "15-legale"),
    ("Taux de base", "Fréquence d'un phénomène dans la population, souvent négligée dans les jugements de probabilité.", "15-legale"),
    ("Éthologie", "Étude du comportement animal dans son milieu naturel et dans une perspective évolutive.", "16-comparee"),
    ("Canon de Morgan", "Principe de parcimonie : ne pas invoquer un processus mental élevé si un plus simple suffit.", "16-comparee"),
    ("Anthropomorphisme", "Attribution d'états mentaux humains à un animal sans justification empirique.", "16-comparee"),
    ("Anthropodéni", "Refus par principe de toute continuité mentale entre humains et animaux.", "16-comparee"),
    ("Enrichissement environnemental", "Aménagement offrant des possibilités de comportements naturels en captivité.", "16-comparee"),
    ("Biais de jugement animal", "Interprétation optimiste ou pessimiste d'un signal ambigu, indicateur d'état émotionnel.", "16-comparee"),
    ("Questions de Tinbergen", "Quatre niveaux d'explication d'un comportement : cause, développement, fonction, évolution.", "16-comparee"),
    ("WEIRD", "Acronyme désignant les populations occidentales, éduquées, industrialisées, riches et démocratiques.", "17-interculturelle"),
    ("Acculturation", "Processus d'adaptation psychologique et culturelle au contact d'une autre culture.", "17-interculturelle"),
    ("Soi interdépendant", "Conception de soi définie par les relations et les rôles plutôt que par des attributs individuels.", "17-interculturelle"),
    ("Culture à contexte fort", "Culture où l'essentiel du message passe par l'implicite et la relation.", "17-interculturelle"),
    ("Idiome culturel de détresse", "Manière culturellement façonnée d'exprimer une souffrance psychique.", "17-interculturelle"),
    ("Validation transculturelle", "Procédure garantissant qu'un test conserve son sens et ses propriétés dans une autre culture.", "19-psychometrie"),
    ("Grammaire universelle", "Hypothèse chomskyenne d'un socle grammatical inné commun à toutes les langues.", "18-langage"),
    ("Conscience phonologique", "Capacité à percevoir et manipuler les unités sonores de la langue, clé de l'apprentissage de la lecture.", "18-langage"),
    ("Recyclage neuronal", "Réutilisation d'un circuit cérébral évolué pour une compétence culturelle récente comme la lecture.", "18-langage"),
    ("Code-switching", "Alternance entre deux langues dans un même échange, signe de maîtrise et non de confusion.", "18-langage"),
    ("Relativité linguistique", "Hypothèse selon laquelle la langue oriente certains aspects de la pensée.", "18-langage"),
    ("Aphasie", "Trouble acquis du langage consécutif à une lésion cérébrale.", "18-langage"),
    ("Économie de l'attention", "Modèle économique reposant sur la captation et la revente du temps d'attention.", "22-numerique"),
    ("Défilement infini", "Interface supprimant tout point d'arrêt naturel pour prolonger la session.", "22-numerique"),
    ("Dark pattern", "Conception d'interface délibérément trompeuse orientant l'utilisateur contre son intérêt.", "22-numerique"),
    ("FOMO", "Peur de manquer quelque chose, moteur de consultation compulsive des réseaux sociaux.", "22-numerique"),
    ("Effet Google", "Modification de la stratégie mnésique : retenir où trouver l'information plutôt que l'information.", "22-numerique"),
    ("Désinhibition en ligne", "Relâchement des freins sociaux favorisé par l'anonymat et l'invisibilité.", "22-numerique"),
    ("Prebunking", "Exposition préalable aux techniques de manipulation pour immuniser contre la désinformation.", "26-politique"),
    ("Vérité illusoire", "Effet par lequel une affirmation répétée paraît plus vraie.", "26-politique"),
    ("Raisonnement motivé", "Évaluation asymétrique des preuves selon qu'elles confirment ou contredisent nos préférences.", "26-politique"),
    ("Polarisation affective", "Hostilité croissante envers le camp adverse, distincte de l'écart idéologique.", "26-politique"),
    ("Fondements moraux", "Ensemble d'intuitions morales de base dont la pondération varie selon les orientations politiques.", "26-politique"),
    ("Deep canvassing", "Conversation longue et non jugeante fondée sur le récit personnel, efficace pour faire évoluer des attitudes.", "26-politique"),
    ("Illusion de profondeur explicative", "Surestimation de sa compréhension d'un mécanisme, révélée en tentant de l'expliquer.", "26-politique"),
    ("Localisation cérébrale", "Principe selon lequel une fonction mentale s'appuie sur des territoires et des réseaux identifiables, sans se réduire à une bosse.", "27-science-psychologique"),
    ("Dissociation", "Profil où une capacité survit et une autre disparaît, prouvant qu'elles ne sont pas le même système.", "27-science-psychologique"),
    ("Homoncule", "Carte corticale du corps, déformée selon la précision sensorielle ou motrice plutôt que selon la taille réelle.", "27-science-psychologique"),
    ("Signal BOLD", "Mesure indirecte utilisée en IRMf, fondée sur l'oxygénation du sang, décalée de plusieurs secondes.", "27-science-psychologique"),
    ("Potentiel évoqué", "Déflexion EEG moyenne déclenchée par un événement (P300, N400, MMN).", "27-science-psychologique"),
    ("P300", "Onde positive vers 300 ms liée à la détection d'un événement rare et pertinent.", "27-science-psychologique"),
    ("N400", "Onde négative vers 400 ms marquant un mot sémantiquement inattendu.", "27-science-psychologique"),
    ("MMN", "Négativité de discordance : détection automatique d'un écart dans une série, même hors attention.", "27-science-psychologique"),
    ("Réseau du mode par défaut", "Ensemble de régions actives au « repos » : rumination, souvenir, projection.", "27-science-psychologique"),
    ("Connectome", "Carte des connexions structurelles ou fonctionnelles d'un cerveau.", "27-science-psychologique"),
    ("Tractographie", "Reconstruction des faisceaux de substance blanche à partir de la diffusion de l'eau (DTI).", "27-science-psychologique"),
    ("TMS", "Impulsion magnétique transcranienne qui perturbe ou facilite temporairement une région corticale.", "27-science-psychologique"),
    ("DBS", "Stimulation cérébrale profonde par électrodes implantées, notamment dans la maladie de Parkinson.", "27-science-psychologique"),
    ("Optogénétique", "Activation ou inhibition de neurones ciblés par la lumière, après expression d'opsines.", "27-science-psychologique"),
    ("Test de Wada", "Anesthésie temporaire d'un hémisphère pour localiser langage et mémoire avant chirurgie.", "27-science-psychologique"),
    ("Blindsight", "Capacité à orienter une action vers un stimulus « non vu » après lésion du cortex visuel primaire.", "27-science-psychologique"),
    ("Négligence spatiale", "Oubli d'un côté de l'espace après lésion pariétale, sans cécité correspondante.", "27-science-psychologique"),
    ("Marqueur somatique", "Signal corporel associé à une expérience passée, qui oriente la décision avant l'explication.", "27-science-psychologique"),
    ("Doctrine du neurone", "Thèse de Cajal : le système nerveux est fait de cellules distinctes communiquant par synapses, non d'un filet continu.", "27-science-psychologique"),
    ("Équiponentialité", "Idée, trop extrême chez Lashley, selon laquelle toute région corticale pourrait assumer n'importe quelle fonction.", "27-science-psychologique"),
    ("Phrénologie", "Doctrine fausse de Gall : lire le caractère dans les bosses du crâne.", "27-science-psychologique"),
    ("Décalage évolutif", "Inadéquation entre des mécanismes adaptés au passé et l'environnement actuel.", "23-evolutionniste"),
    ("Gestion des erreurs", "Théorie expliquant certains biais par l'asymétrie des coûts entre deux types d'erreur.", "23-evolutionniste"),
    ("Sélection de parentèle", "Mécanisme expliquant l'altruisme envers les apparentés par le partage de gènes.", "23-evolutionniste"),
    ("Altruisme réciproque", "Coopération entre non-apparentés fondée sur l'attente d'un retour différé.", "23-evolutionniste"),
    ("Nombre de Dunbar", "Estimation d'environ 150 relations sociales stables qu'un humain peut entretenir.", "23-evolutionniste"),
    ("Savoir biologiquement primaire", "Compétence acquise spontanément par exposition, comme parler ou marcher.", "23-evolutionniste"),
    ("Sophisme naturaliste", "Erreur consistant à déduire ce qui doit être de ce qui est.", "23-evolutionniste"),
    ("Réserve cognitive", "Capital de connexions et de stratégies retardant l'expression clinique d'une atteinte cérébrale.", "24-vieillissement"),
    ("Effet de positivité", "Tendance des personnes âgées à mieux retenir les informations positives.", "24-vieillissement"),
    ("Sélectivité socio-émotionnelle", "Recentrage sur les relations significatives quand l'horizon temporel perçu se raccourcit.", "24-vieillissement"),
    ("Âgisme", "Discrimination fondée sur l'âge, la plus socialement tolérée.", "24-vieillissement"),
    ("Elderspeak", "Langage infantilisant adressé aux personnes âgées, délétère pour l'estime de soi.", "24-vieillissement"),
    ("Trouble neurocognitif majeur", "Terme actuel remplaçant « démence » : atteinte cognitive retentissant sur l'autonomie.", "24-vieillissement"),
    ("Restauration de l'attention", "Théorie expliquant l'effet réparateur des environnements naturels sur l'attention dirigée.", "25-environnementale"),
    ("Design biophilique", "Conception intégrant des éléments naturels dans les espaces bâtis.", "25-environnementale"),
    ("Éco-anxiété", "Inquiétude persistante liée aux menaces environnementales, réponse adaptée et non trouble mental.", "25-environnementale"),
    ("Tragédie des communs", "Dilemme social où l'intérêt individuel épuise une ressource collective.", "25-environnementale"),
    ("Effet rebond", "Absorption des gains d'efficacité par une hausse de la consommation.", "25-environnementale"),
    ("Prospect-refuge", "Préférence pour les lieux offrant à la fois une vue dégagée et un adossement protecteur.", "25-environnementale"),
    ("Distance psychologique", "Éloignement perçu d'un événement dans le temps, l'espace ou la probabilité, qui réduit la mobilisation.", "25-environnementale"),
    ("Zone de performance optimale", "Plage d'activation individuelle associée aux meilleures performances.", "20-sport"),
    ("Choking", "Effondrement de la performance sous pression, lié à la reprise du contrôle conscient.", "20-sport"),
    ("Routine pré-performance", "Séquence d'actions stable réalisée avant l'exécution pour stabiliser l'attention.", "20-sport"),
    ("Imagerie motrice", "Répétition mentale d'un geste activant partiellement les mêmes réseaux que son exécution.", "20-sport"),
    ("Objectif de processus", "But portant sur l'exécution elle-même, entièrement sous contrôle de la personne.", "20-sport"),
    ("Architecture du choix", "Manière dont la présentation des options oriente les décisions sans les contraindre.", "21-consommation"),
    ("Option par défaut", "Choix appliqué en l'absence de décision active ; levier comportemental le plus puissant.", "21-consommation"),
    ("Effet leurre", "Ajout d'une option peu attractive qui oriente le choix vers une option ciblée.", "21-consommation"),
    ("Douleur de payer", "Désagrément psychologique du paiement, atténué par les moyens dématérialisés.", "21-consommation"),
    ("Neuromarketing", "Application des méthodes de neurosciences à l'étude des comportements d'achat, aux résultats limités.", "21-consommation"),
    ("Congruence de l'image de soi", "Préférence pour les marques correspondant à l'image que l'on a ou souhaite projeter.", "21-consommation"),
    ("Titre de psychologue", "Titre protégé en France : licence plus master de psychologie avec stage et mémoire, puis inscription au répertoire. La licence seule ne suffit pas.", "01-fondamentaux"),
    ("PsyEN", "Psychologue de l'Éducation nationale, recruté sur concours, qui intervient auprès des élèves — notamment via le CIO.", "13-education"),
    ("Attendus Parcoursup", "Compétences signalées par une formation (ici la L1 psychologie) : démarche scientifique, rédaction, autonomie — aucune spécialité n'est obligatoire.", "01-fondamentaux"),
    ("Mineure de L1", "Seconde discipline parfois proposée au semestre 1 (sciences cognitives, sociologie, anthropologie ou sciences de l'éducation) avant de confirmer la majeure.", "01-fondamentaux"),
    ("Cadre clinique", "Lieu, durée, confidentialité et règles qui rendent possible un entretien : sans cadre, pas de clinique.", "09-psychopathologie"),
    ("Variable indépendante", "Facteur que l'expérimentateur fait varier pour observer son effet sur la variable dépendante.", "01-fondamentaux"),
    ("Variable dépendante", "Mesure observée (score, temps, choix) dont on attend qu'elle change si la variable indépendante a un effet.", "01-fondamentaux"),
    ("Étayage", "Aide ajustée, puis retirée, qui permet à l'enfant de réussir dans sa zone proximale de développement.", "05-developpement"),
    ("Norme descriptive", "Ce que les gens font réellement, souvent plus influent qu'une consigne morale (norme injonctive).", "04-sociale"),
    ("Grand oral", "Épreuve de Terminale : question, plan, sources et échange — le même geste qu'un compte rendu d'expérience en L1.", "01-fondamentaux"),
]
