# -*- coding: utf-8 -*-
"""Psychologie appliquée : ce que la recherche permet réellement de faire au quotidien.

Chaque fiche part d'une situation concrète, rappelle ce que disent les données,
propose un protocole en étapes, puis signale le piège classique. Rien ici ne
remplace un accompagnement professionnel en cas de souffrance.
"""

# (id, titre, famille, situation, recherche, etapes, piege)
PRATIQUES = [
    ("apprendre-efficacement", "Apprendre pour retenir durablement", "Apprendre",
     "Vous relisez vos cours plusieurs fois, vous avez l'impression de savoir, et le jour de l'examen tout s'effondre.",
     "La relecture produit une <strong>illusion de maîtrise</strong> : la familiarité du texte est prise pour de la connaissance. Les deux techniques les mieux établies sont la pratique de récupération (se tester) et l'espacement. Dans l'étude classique de Roediger et Karpicke, les étudiants qui se testaient se sentaient moins sûrs d'eux que ceux qui relisaient, et retenaient pourtant nettement plus une semaine après.",
     ["Lisez une première fois pour comprendre, sans surligner.",
      "Fermez le document et écrivez tout ce dont vous vous souvenez, de mémoire.",
      "Rouvrez et corrigez en rouge : les trous que vous découvrez sont exactement votre programme de révision.",
      "Reprenez ce point à J+1, J+3, J+7, J+21 — l'oubli partiel entre deux sessions est ce qui consolide.",
      "Alternez les sujets au sein d'une même session (pratique entrelacée) plutôt que de traiter un chapitre en bloc."],
     "Confondre effort ressenti et efficacité. Les méthodes qui donnent une impression de fluidité sont presque toujours les moins efficaces ; les « difficultés désirables » sont désagréables sur le moment et payantes au long cours."),

    ("procrastination", "Sortir de la procrastination", "Organisation",
     "Vous savez ce que vous avez à faire, vous voulez le faire, et vous faites autre chose.",
     "La procrastination n'est pas un problème de gestion du temps mais de <strong>régulation des émotions</strong> : on fuit l'inconfort associé à la tâche (ennui, peur de mal faire, ambiguïté). Les travaux de Tim Pychyl et Fuschia Sirois montrent que l'autocompassion après un épisode de procrastination réduit la procrastination suivante, alors que l'autocritique l'aggrave.",
     ["Nommez l'émotion évitée : « cette tâche m'angoisse », « je ne sais pas par où commencer ».",
      "Réduisez la première marche jusqu'à l'absurde : ouvrir le document et écrire une phrase.",
      "Formulez un plan « si… alors » précis : « si je m'assieds à mon bureau à 9 h, alors j'ouvre le dossier X ».",
      "Rendez le démarrage automatique par le lieu et l'heure plutôt que par la motivation.",
      "Après un épisode raté, passez à autre chose sans autoflagellation : c'est ce qui réduit la récidive."],
     "Attendre d'avoir envie. La motivation suit l'action bien plus souvent qu'elle ne la précède : c'est le mouvement qui crée l'élan, pas l'inverse."),

    ("habitudes", "Installer une habitude durable", "Organisation",
     "Vos bonnes résolutions tiennent trois semaines puis s'évaporent.",
     "Une habitude est un comportement déclenché automatiquement par un contexte. L'étude de Phillippa Lally donne une médiane de <strong>66 jours</strong> pour atteindre l'automatisme, avec une variabilité énorme (18 à 254 jours selon les personnes et les comportements). Fait rassurant : rater un jour n'a pas compromis la formation de l'habitude.",
     ["Choisissez un déclencheur existant et stable : après le café du matin, en sortant du travail.",
      "Réduisez la version minimale à quelque chose d'impossible à rater (deux minutes).",
      "Préparez l'environnement la veille : tenue de sport visible, téléphone hors de la chambre.",
      "Suivez la régularité, pas la performance : cochez les jours où vous avez fait, même la version minimale.",
      "Après un jour manqué, appliquez la règle « jamais deux fois de suite »."],
     "Viser trop grand au démarrage. L'ambition initiale est la première cause d'abandon : une habitude minuscule maintenue bat une habitude ambitieuse abandonnée."),

    ("sommeil", "Retrouver un sommeil de qualité", "Santé",
     "Vous vous couchez tôt, vous tournez pendant une heure, et vous êtes épuisé au réveil.",
     "Le traitement de référence de l'insomnie chronique n'est pas médicamenteux : c'est la <strong>thérapie cognitivo-comportementale de l'insomnie (TCC-I)</strong>, recommandée en première intention par les sociétés savantes, avec des effets supérieurs aux somnifères à moyen terme et sans accoutumance. Son ingrédient le plus efficace est contre-intuitif : la restriction de temps passé au lit.",
     ["Fixez une heure de lever constante, sept jours sur sept, même après une mauvaise nuit.",
      "Ne restez pas au lit éveillé plus de vingt minutes : levez-vous, faites une activité calme en lumière tamisée, revenez quand le sommeil vient.",
      "Réservez le lit au sommeil : ni travail, ni écran, ni rumination.",
      "Exposez-vous à la lumière du jour le matin : c'est le principal synchroniseur de l'horloge biologique.",
      "Décalez les préoccupations : un « créneau souci » de quinze minutes en début de soirée, carnet à l'appui."],
     "Compenser par des grasses matinées et des siestes longues. Cela réduit la pression de sommeil et entretient le cercle vicieux. En cas d'insomnie durable, de somnolence diurne marquée ou de ronflement avec pauses respiratoires, consultez : ce peut être une apnée du sommeil."),

    ("stress-aigu", "Réguler un pic de stress", "Émotions",
     "Avant une prise de parole ou un entretien, le cœur s'emballe et la voix tremble.",
     "Le système nerveux autonome répond aux signaux corporels avant les raisonnements. Une <strong>expiration plus longue que l'inspiration</strong> active le frein parasympathique en quelques dizaines de secondes. Par ailleurs, Jeremy Jamieson a montré que réinterpréter l'activation comme une préparation à l'action (« mon corps se met en ordre de marche ») améliore les performances par rapport à la consigne « calmez-vous ».",
     ["Respirez en allongeant l'expiration : quatre temps à l'inspiration, six à huit à l'expiration, pendant deux minutes.",
      "Relâchez consciemment la mâchoire, les épaules et les mains.",
      "Reformulez : « je suis stressé » devient « je suis activé, mon corps se prépare ».",
      "Ancrez l'attention dans le concret : trois choses visibles, trois sons, trois sensations.",
      "Préparez vos trente premières secondes par cœur : c'est le moment où le trac est maximal."],
     "Chercher à supprimer complètement l'activation. Un niveau modéré d'activation améliore la performance (loi de Yerkes-Dodson) ; l'objectif est de la ramener dans la zone utile, pas de l'éteindre."),

    ("rumination", "Interrompre une rumination", "Émotions",
     "La même pensée tourne en boucle depuis une heure et rien n'avance.",
     "La rumination se distingue de la réflexion par son <strong>orientation</strong> : elle porte sur les causes et les conséquences (« pourquoi moi ? »), pas sur l'action (« que puis-je faire ? »). Les travaux de Susan Nolen-Hoeksema en font un facteur de risque majeur de dépression, et ils expliquent une part de la surreprésentation féminine dans les troubles dépressifs.",
     ["Repérez le basculement : si vous tournez depuis plus de dix minutes sans avancer, c'est de la rumination.",
      "Changez la question : « pourquoi » devient « quelle est la prochaine action concrète ? ».",
      "Si aucune action n'est possible, changez de modalité : marche, mouvement, contact avec quelqu'un.",
      "Notez la préoccupation par écrit et fixez-lui un rendez-vous ultérieur plutôt que de la chasser.",
      "Prenez de la distance en passant à la troisième personne : « pourquoi est-ce que Marie se sent ainsi ? »"],
     "Tenter de ne pas y penser. La suppression volontaire d'une pensée augmente sa fréquence (effet de l'ours blanc de Wegner) : la voie efficace est la réorientation, pas l'interdiction."),

    ("anxiete-anticipation", "Calmer l'anxiété d'anticipation", "Émotions",
     "Vous redoutez un événement dans trois semaines et vous le vivez cent fois d'avance.",
     "L'anxiété est une réponse à une menace <strong>projetée</strong>. Le mécanisme central est l'évitement : chaque évitement soulage à court terme et renforce la peur à long terme. C'est pourquoi l'exposition graduée constitue le traitement le mieux validé des troubles anxieux.",
     ["Écrivez le scénario redouté jusqu'au bout, en détail — la vague vous fait plus peur que la précision.",
      "Estimez la probabilité réelle, puis cherchez ce qui s'est passé les fois précédentes.",
      "Préparez un plan pour le pire cas raisonnable : savoir quoi faire désamorce une grande part de la peur.",
      "Exposez-vous progressivement aux situations évitées, en commençant par les plus accessibles.",
      "Limitez les demandes de réassurance : elles fonctionnent comme un évitement déguisé."],
     "Utiliser la préparation comme un évitement. Préparer indéfiniment sans jamais affronter entretient l'anxiété. Si elle est envahissante et dure depuis des mois, un accompagnement en TCC est indiqué."),

    ("communication-conflit", "Aborder un conflit sans l'aggraver", "Relations",
     "Une discussion difficile à avoir avec un proche ou un collègue, et la crainte que ça dégénère.",
     "Les travaux de John Gottman sur des milliers de couples identifient quatre comportements associés à la rupture : critique de la personne, mépris, attitude défensive, retrait. Le mépris est le meilleur prédicteur isolé. À l'inverse, la manière dont une discussion <strong>démarre</strong> prédit fortement la manière dont elle finit.",
     ["Choisissez le moment : jamais à chaud, jamais fatigué, jamais devant témoin.",
      "Ouvrez par un fait observable, pas par un jugement : « hier tu es rentré à 21 h sans prévenir ».",
      "Exprimez l'effet sur vous plutôt que le défaut de l'autre : « je me suis inquiété » plutôt que « tu es irrespectueux ».",
      "Formulez une demande concrète, unique et négociable.",
      "Reformulez ce que l'autre a dit avant de répondre : c'est le geste qui fait le plus baisser la tension."],
     "Empiler les griefs (« et d'ailleurs, l'an dernier… »). Une discussion, un sujet. Le cumul transforme un désaccord réparable en procès global de la personne."),

    ("ecoute-active", "Écouter vraiment quelqu'un", "Relations",
     "Un proche traverse une épreuve et vous ne savez pas quoi dire.",
     "Les trois conditions décrites par Carl Rogers — authenticité, regard positif inconditionnel, empathie — restent le socle le mieux documenté de la relation d'aide. Contre-intuitivement, les <strong>conseils non sollicités</strong> réduisent le sentiment d'être compris, même lorsqu'ils sont pertinents.",
     ["Commencez par demander : « tu veux que je t'écoute ou que je t'aide à trouver des solutions ? »",
      "Laissez les silences : c'est souvent après un silence que l'essentiel arrive.",
      "Reformulez le contenu et l'émotion : « si je comprends bien, tu te sens coincé entre les deux ».",
      "Évitez les minimisations bienveillantes (« ça va aller », « d'autres vivent pire »).",
      "Proposez une aide concrète et datée plutôt qu'un « dis-moi si tu as besoin »."],
     "Raconter votre propre expérience similaire. L'intention est bonne, l'effet ramène l'attention sur vous et interrompt le récit de l'autre."),

    ("feedback", "Donner un retour critique constructif", "Travail",
     "Vous devez signaler un problème de travail sans démolir la personne.",
     "Un retour est efficace quand il porte sur la <strong>tâche et la stratégie</strong>, pas sur la personne. La synthèse de Kluger et DeNisi réserve une surprise : environ un tiers des retours détériorent la performance, principalement lorsqu'ils visent le soi (« tu es désorganisé ») plutôt que le processus.",
     ["Annoncez l'intention : « je veux qu'on améliore ce point, pas te faire un procès ».",
      "Décrivez un comportement observable et daté, avec son effet concret.",
      "Demandez le point de vue de la personne avant de proposer quoi que ce soit.",
      "Formulez une attente précise et vérifiable pour la suite.",
      "Fixez un point de suivi : sans suivi, un retour n'est qu'un reproche."],
     "Le « sandwich » compliment-critique-compliment. Il est tellement connu que chacun attend la critique dès la première phrase agréable, ce qui dévalue les compliments et brouille le message."),

    ("decision-difficile", "Prendre une décision importante", "Décision",
     "Deux options, des mois d'hésitation, et le sentiment de tourner en rond.",
     "Nos décisions sont dégradées par l'excès de confiance, le biais de confirmation et l'attachement aux coûts déjà engagés. Deux outils simples ont fait leurs preuves : le <strong>pré-mortem</strong> de Gary Klein et la <strong>règle 10/10/10</strong>, qui obligent à changer de point de vue temporel.",
     ["Écrivez la décision et les critères qui comptent vraiment, avant de comparer les options.",
      "Faites un pré-mortem : « nous sommes dans un an, c'est un échec — que s'est-il passé ? ».",
      "Cherchez activement l'information qui vous donnerait tort.",
      "Appliquez la règle 10/10/10 : qu'en penserai-je dans dix minutes, dix mois, dix ans ?",
      "Si les options restent équivalentes après analyse sérieuse, choisissez et engagez-vous : l'indécision a elle-même un coût."],
     "Laisser le coût irrécupérable décider (« j'ai déjà investi trois ans »). Ce qui est dépensé l'est de toute façon ; seule compte la meilleure suite possible à partir d'aujourd'hui."),

    ("negociation", "Préparer une négociation", "Travail",
     "Demande d'augmentation, achat important, répartition de tâches.",
     "L'<strong>ancrage</strong> est l'effet le mieux documenté du domaine : le premier chiffre énoncé oriente durablement l'issue, même lorsque les participants savent qu'il est arbitraire. La préparation de votre solution de repli (la meilleure option en cas d'échec) détermine votre marge réelle bien plus que vos talents oratoires.",
     ["Identifiez votre solution de repli et votre seuil de rupture avant l'entretien.",
      "Renseignez-vous sur les repères objectifs : grilles, prix de marché, précédents.",
      "Ancrez en premier quand vous disposez d'une information fiable, et justifiez votre chiffre.",
      "Élargissez au-delà du seul montant : délais, formation, jours de télétravail, périmètre.",
      "Laissez le silence après une proposition — c'est souvent l'autre qui le comble."],
     "Confondre fermeté sur le fond et dureté relationnelle. Les négociateurs les plus efficaces sont exigeants sur les intérêts et coopératifs sur la relation."),

    ("motivation-long-terme", "Tenir un objectif dans la durée", "Motivation",
     "L'enthousiasme du début retombe et l'objectif s'éloigne.",
     "La théorie de l'autodétermination identifie trois besoins dont la satisfaction soutient la motivation : <strong>autonomie, compétence, affiliation</strong>. Les objectifs purement externes (regard des autres, récompense) s'essoufflent plus vite que ceux reliés à des valeurs personnelles.",
     ["Reliez l'objectif à une valeur : pourquoi cela compte pour vous, indépendamment du regard d'autrui.",
      "Découpez en jalons atteignables : le sentiment de progression est le carburant principal.",
      "Rendez les progrès visibles (graphique, carnet, série de jours).",
      "Associez quelqu'un : engagement public ou partenaire de pratique.",
      "Planifiez les obstacles à l'avance avec des plans « si… alors »."],
     "Se fier à la motivation pour agir. Construisez plutôt un système (créneaux, environnement, engagement social) qui fonctionne les jours sans envie."),

    ("perfectionnisme", "Desserrer le perfectionnisme", "Émotions",
     "Rien n'est jamais assez bien, vous repoussez la remise, vous vous épuisez.",
     "La recherche distingue le perfectionnisme de <strong>standards élevés</strong>, plutôt bénéfique, du perfectionnisme de <strong>préoccupation</strong> (peur de l'erreur, doute permanent, autocritique), associé à l'anxiété, la dépression et l'épuisement. Les deux se ressemblent en apparence et n'ont pas les mêmes effets.",
     ["Distinguez les tâches qui méritent l'excellence de celles qui exigent seulement d'être faites.",
      "Fixez un budget-temps à l'avance et livrez à échéance, quel que soit l'état.",
      "Pratiquez l'imperfection délibérée sur des enjeux faibles pour tester vos prédictions catastrophiques.",
      "Remplacez l'autocritique par ce que vous diriez à un ami dans la même situation.",
      "Mesurez le coût réel du surtravail : heures, sommeil, relations."],
     "Croire que le perfectionnisme est la cause de vos réussites. Le plus souvent, on réussit malgré lui et à un coût élevé, en confondant exigence et peur."),

    ("estime-soi", "Travailler son rapport à soi", "Émotions",
     "Un discours intérieur dur, une sensibilité forte à la critique.",
     "Les programmes visant à « augmenter l'estime de soi » par des compliments n'améliorent ni les résultats ni le bien-être. Les données soutiennent en revanche l'<strong>autocompassion</strong> (Kristin Neff) et la construction de compétences réelles. La théorie du sociomètre suggère que l'estime de soi mesure notre valeur relationnelle perçue plutôt qu'elle ne la crée.",
     ["Repérez votre discours intérieur en situation d'échec, en le notant mot pour mot.",
      "Testez-le : parleriez-vous ainsi à un ami ? Que lui diriez-vous à la place ?",
      "Remplacez « je suis nul » par une description de situation et une action possible.",
      "Accumulez des expériences de compétence réelles, même petites et mesurables.",
      "Investissez les liens : l'appartenance nourrit l'estime de soi plus sûrement que les affirmations positives."],
     "Les affirmations positives auxquelles on ne croit pas. Les travaux de Joanne Wood montrent qu'elles dégradent l'humeur des personnes à faible estime de soi, en soulignant l'écart avec le vécu."),

    ("deuil-accompagner", "Accompagner une personne endeuillée", "Relations",
     "Un proche vient de perdre quelqu'un et vous craignez de mal faire.",
     "La trajectoire la plus fréquente après un deuil est la <strong>résilience</strong>, pas l'effondrement durable. Le modèle du double processus de Stroebe et Schut décrit une oscillation normale entre confrontation à la perte et retour à la vie courante : les moments de répit ne sont pas de l'indifférence.",
     ["Soyez présent sans exiger de mots : la présence physique compte plus que les formules.",
      "Nommez la personne disparue : l'éviter isole davantage l'endeuillé.",
      "Proposez une aide concrète et précise plutôt qu'un « appelle-moi si besoin ».",
      "Tenez dans la durée : l'entourage s'éclipse souvent après quelques semaines, au moment où le soutien manque le plus.",
      "Ne fixez aucun calendrier : « il faudrait tourner la page » ajoute de la culpabilité à la peine."],
     "Imposer les « cinq étapes du deuil ». Ce modèle n'a pas été validé pour le deuil et transforme un vécu singulier en norme à respecter. En cas de détresse intense persistant au-delà d'un an avec blocage majeur, une orientation professionnelle est utile."),

    ("parler-enfant-emotions", "Aider un enfant avec ses émotions", "Parentalité",
     "Colères, peurs, chagrins : vous ne savez pas quand consoler et quand cadrer.",
     "La régulation émotionnelle se construit d'abord à deux : l'adulte régule l'enfant avant que celui-ci ne puisse le faire seul. Les travaux sur le <strong>coaching émotionnel</strong> (Gottman, Denham) montrent que les parents qui accueillent l'émotion tout en tenant le cadre comportemental ont des enfants mieux régulés socialement.",
     ["Validez l'émotion sans valider le comportement : « tu es très en colère, et on ne tape pas ».",
      "Mettez des mots : le vocabulaire émotionnel est un outil de régulation.",
      "Attendez la fin de la crise pour raisonner : pendant, le cerveau n'est pas disponible pour les arguments.",
      "Reprenez à froid, brièvement, avec une alternative concrète pour la prochaine fois.",
      "Repérez les déclencheurs récurrents : faim, fatigue, transition, surcharge sensorielle."],
     "Le chantage affectif (« tu me fais de la peine ») et les punitions disproportionnées. Ils obtiennent l'obéissance immédiate et enseignent la dissimulation plutôt que la régulation."),

    ("ecrans-enfants", "Encadrer les écrans en famille", "Parentalité",
     "Les négociations quotidiennes autour du temps d'écran.",
     "Les effets moyens du temps d'écran sur le bien-être sont <strong>faibles</strong> dans les grandes bases de données. Ce qui compte davantage : le contenu, le moment (soir et nuit), ce que l'écran remplace (sommeil, sport, interactions), et l'usage familial. Les recommandations sérieuses portent sur ces dimensions plutôt que sur un compteur d'heures.",
     ["Protégez d'abord le sommeil : pas d'écran dans la chambre, arrêt une heure avant le coucher.",
      "Préservez les trois piliers : sommeil, activité physique, temps relationnel hors écran.",
      "Regardez ensemble et parlez du contenu, surtout avant l'adolescence.",
      "Fixez des règles claires, stables et appliquées aussi aux adultes.",
      "Discutez des mécanismes de captation (défilement infini, notifications) : comprendre aide à reprendre la main."],
     "Faire de l'écran l'unique variable. Un adolescent qui va mal utilise souvent plus son téléphone <em>parce qu'</em>il va mal : supprimer l'écran sans traiter la cause déplace le problème."),

    ("prise-parole", "Parler en public sans se laisser paralyser", "Travail",
     "La perspective de parler devant un groupe déclenche une anxiété disproportionnée.",
     "Le public surestime largement sa perception de votre nervosité : c'est l'<strong>illusion de transparence</strong>. Par ailleurs, se dire « je suis enthousiaste » plutôt que « calme-toi » améliore les performances mesurées en prise de parole (travaux d'Alison Wood Brooks).",
     ["Répétez à voix haute et debout, pas seulement dans votre tête.",
      "Apprenez par cœur les trente premières secondes et la conclusion.",
      "Arrivez tôt, occupez l'espace, parlez à quelques personnes avant : le groupe devient des visages.",
      "Reformulez l'activation en enthousiasme plutôt que de chercher à l'éteindre.",
      "Fixez trois points d'appui dans le public et regardez-les à tour de rôle."],
     "Chercher la perfection du texte. Le public retient la structure et l'énergie, pas la formulation exacte. Une hésitation assumée passe mieux qu'une récitation figée."),

    ("entretien-embauche", "Réussir un entretien de recrutement", "Travail",
     "Vous préparez un entretien et ne savez pas sur quoi porter l'effort.",
     "Les méta-analyses de Schmidt et Hunter classent l'<strong>entretien structuré</strong> parmi les meilleurs prédicteurs de la performance professionnelle, loin devant l'entretien libre, la graphologie (nulle) ou l'ancienneté. Les questions comportementales (« racontez une fois où… ») prédisent mieux que les questions hypothétiques.",
     ["Préparez six à huit situations vécues au format STAR : situation, tâche, action, résultat chiffré.",
      "Reliez chaque compétence de l'annonce à une situation concrète.",
      "Préparez une réponse honnête sur une difficulté réelle et ce que vous en avez tiré.",
      "Renseignez-vous sur l'organisation et préparez trois questions de fond.",
      "Entraînez-vous à voix haute avec quelqu'un : la formulation orale se travaille."],
     "Les réponses prêtes à l'emploi trouvées en ligne. Elles sont immédiatement reconnues et signalent surtout que vous n'avez pas réfléchi à votre propre parcours."),

    ("reunion-efficace", "Animer une réunion utile", "Travail",
     "Des réunions longues, nombreuses, dont rien ne sort.",
     "La <strong>pensée de groupe</strong> (Janis) et la production bloquée en brainstorming collectif sont deux effets bien établis : les groupes produisent moins d'idées et moins originales qu'un même nombre de personnes travaillant d'abord séparément. L'ordre de parole compte : le premier avis exprimé, surtout s'il vient d'un responsable, ancre toute la discussion.",
     ["Envoyez le document à lire avant ; ne lisez pas en séance.",
      "Faites écrire les idées individuellement avant toute discussion collective.",
      "Faites parler du plus junior au plus senior pour limiter l'ancrage hiérarchique.",
      "Désignez explicitement quelqu'un chargé de porter la contradiction.",
      "Terminez par : qui fait quoi, pour quand — écrit et visible de tous."],
     "Confondre consensus et accord. Un silence n'est pas une adhésion : c'est souvent le signe qu'exprimer un désaccord coûte trop cher dans ce groupe."),

    ("teletravail", "Tenir la distance en télétravail", "Travail",
     "Les journées s'étirent, les frontières s'effacent, l'isolement s'installe.",
     "Le modèle exigences-ressources prédit ce qui se joue à distance : l'autonomie augmente (ressource) mais le soutien social et la reconnaissance diminuent (ressources perdues), tandis que la <strong>disponibilité permanente</strong> devient une exigence supplémentaire.",
     ["Créez des frontières physiques et temporelles : un lieu dédié, des horaires annoncés.",
      "Ritualisez le début et la fin de journée (une marche fait un excellent trajet symbolique).",
      "Provoquez du contact informel : les échanges spontanés ne surviennent pas d'eux-mêmes à distance.",
      "Rendez votre travail visible : à distance, ce qui n'est pas dit n'existe pas.",
      "Coupez les notifications en dehors des plages convenues."],
     "Compenser l'invisibilité par une hyper-disponibilité. C'est le chemin le plus direct vers l'épuisement, et cela n'améliore pas la perception de votre contribution."),

    ("burnout-reperer", "Repérer un épuisement professionnel", "Travail",
     "Fatigue qui ne passe plus avec le repos, cynisme, sentiment d'inefficacité.",
     "Le burn-out se définit par trois dimensions (Maslach) : <strong>épuisement</strong>, <strong>cynisme</strong> et <strong>perte d'accomplissement</strong>. Ce n'est pas un diagnostic psychiatrique mais un phénomène lié au travail, reconnu comme tel par l'OMS. Les facteurs organisationnels — charge, autonomie, reconnaissance, équité, valeurs — pèsent davantage que la « fragilité » individuelle.",
     ["Repérez les signaux : réveils nocturnes, irritabilité, désengagement, erreurs inhabituelles.",
      "Notez sur deux semaines vos horaires réels et votre état à la fin de chaque journée.",
      "Identifiez la ressource manquante : est-ce la charge, l'autonomie, la reconnaissance, ou le sens ?",
      "Parlez-en à un médecin du travail ou à votre médecin traitant — l'arrêt précoce évite les formes longues.",
      "Ne reprenez pas à l'identique : sans changement organisationnel, la rechute est la règle."],
     "Traiter le problème comme un défaut personnel de résistance. Les interventions individuelles (relaxation, gestion du temps) ont des effets réels mais modestes si l'organisation du travail reste inchangée."),

    ("motivation-eleves", "Soutenir la motivation d'un élève", "Éducation",
     "Un enfant ou un adolescent qui « ne veut plus rien faire ».",
     "Le désengagement scolaire est presque toujours une <strong>protection</strong> : ne pas essayer permet d'éviter d'échouer en ayant essayé. Les attributions comptent (Weiner) : attribuer l'échec à une cause stable et incontrôlable (« je suis nul en maths ») éteint l'effort ; l'attribuer à une stratégie modifiable le relance.",
     ["Cherchez la peur derrière le refus avant de chercher la paresse.",
      "Fractionnez jusqu'à une première réussite possible, même minuscule.",
      "Commentez la stratégie et le progrès, pas le talent ni la note.",
      "Redonnez du choix là où c'est possible : ordre, support, format.",
      "Rendez le progrès visible dans le temps (comparer à soi-même, pas aux autres)."],
     "Multiplier les récompenses matérielles. Elles fonctionnent à court terme et dégradent la motivation intrinsèque quand elles sont retirées (effet de surjustification)."),

    ("devoirs", "Organiser le travail scolaire à la maison", "Éducation",
     "Les devoirs durent des heures et se terminent en conflit.",
     "Le bénéfice des devoirs sur les apprentissages est faible à l'école primaire et croît avec l'âge (synthèses de Harris Cooper). Ce qui fait la différence n'est pas la durée mais la <strong>méthode</strong> : se tester plutôt que relire, espacer plutôt que masser.",
     ["Fixez un créneau et un lieu stables, téléphone hors de portée.",
      "Commencez par cinq minutes de récupération sur la leçon précédente.",
      "Travaillez par blocs courts avec pauses réelles (et sans écran pendant la pause).",
      "Faites expliquer la leçon à voix haute plutôt que la relire.",
      "Arrêtez à l'heure convenue : au-delà, le rendement s'effondre et le conflit commence."],
     "Faire à la place de l'enfant quand la fatigue monte. Cela résout la soirée et supprime précisément l'effort qui produit l'apprentissage."),

    ("lecture-critique-info", "Évaluer une information santé ou psy", "Esprit critique",
     "Un article annonce qu'une étude « prouve » quelque chose de spectaculaire.",
     "Entre l'article scientifique et le titre de presse, l'information traverse plusieurs filtres qui amplifient systématiquement les effets. Les <strong>communiqués de presse universitaires</strong> sont responsables d'une grande part des exagérations causales, avant même le travail journalistique.",
     ["Remontez à l'étude d'origine : qui, combien, comment ?",
      "Vérifiez le type de plan : corrélationnel ou expérimental ? Humains ou souris ?",
      "Cherchez la taille d'effet, pas seulement la significativité.",
      "Demandez-vous si le résultat a été répliqué indépendamment.",
      "Méfiez-vous des verbes causaux dans les titres et du conflit d'intérêts en fin d'article."],
     "Rejeter en bloc toute la science parce que certains résultats sont faux. Le doute méthodique s'applique aussi au doute : la solution n'est pas de ne plus rien croire, mais de hiérarchiser la qualité des preuves."),

    ("manipulation-reperer", "Repérer une tentative de manipulation", "Esprit critique",
     "Une sollicitation commerciale, militante ou relationnelle qui vous met mal à l'aise.",
     "Les techniques d'influence documentées par Robert Cialdini reposent sur six leviers : <strong>réciprocité, engagement, preuve sociale, autorité, sympathie, rareté</strong>. Elles fonctionnent d'autant mieux qu'elles sont invisibles et que la décision est prise rapidement.",
     ["Repérez l'urgence artificielle : « offre valable aujourd'hui seulement ».",
      "Repérez le cadeau initial qui crée une dette (échantillon, service rendu, invitation).",
      "Repérez l'escalade d'engagement : un petit accord anodin qui en appelle un plus grand.",
      "Imposez un délai : « je vous réponds demain » désamorce la plupart des techniques.",
      "Vérifiez les sources d'autorité invoquées, qui sont souvent approximatives ou inventées."],
     "Se croire immunisé. Le « point aveugle des biais » fait que chacun s'estime moins influençable que la moyenne — ce qui est précisément ce qui rend vulnérable."),

    ("temoignage-fiable", "Recueillir un témoignage sans le déformer", "Esprit critique",
     "Vous devez interroger quelqu'un sur ce qu'il a vu ou vécu.",
     "Les travaux d'Elizabeth Loftus ont établi que la <strong>formulation de la question modifie le souvenir</strong> : demander à quelle vitesse les voitures se sont « percutées » plutôt que « touchées » augmente la vitesse estimée et fait apparaître des débris de verre inexistants. L'entretien cognitif, développé par Fisher et Geiselman, augmente sensiblement la quantité d'informations exactes.",
     ["Commencez par un récit libre et complet, sans jamais interrompre.",
      "Posez ensuite des questions ouvertes : « que s'est-il passé ensuite ? ».",
      "N'introduisez jamais d'information nouvelle dans votre question.",
      "Demandez de restituer dans un autre ordre ou d'un autre point de vue.",
      "Notez le niveau de certitude au moment du premier récit : il se gonfle ensuite avec les répétitions."],
     "Confondre confiance et exactitude. La corrélation entre l'assurance d'un témoin et la justesse de son souvenir est faible, surtout après qu'il a répété son récit."),

    ("premiers-secours-psy", "Réagir face à une personne en détresse", "Urgence",
     "Quelqu'un exprime un désespoir profond ou évoque le suicide.",
     "Contrairement à une croyance tenace, <strong>parler du suicide n'induit pas le passage à l'acte</strong> : les données montrent l'inverse, la question ouverte soulage et ouvre un espace. Les programmes de secourisme en santé mentale reposent sur ce constat.",
     ["Posez la question directement et calmement : « est-ce que tu penses à te suicider ? ».",
      "Écoutez sans minimiser, sans argumenter, sans promettre le secret.",
      "Restez présent et éloignez les moyens accessibles si c'est possible.",
      "Orientez concrètement : accompagner l'appel vaut mieux que donner un numéro.",
      "En France : 3114 (prévention du suicide, gratuit, 24 h/24), 15 en cas d'urgence vitale."],
     "Promettre le secret. C'est la seule promesse à ne pas faire : la sécurité de la personne prime, et le lui dire d'emblée évite un sentiment de trahison ensuite."),

    ("aidant", "Tenir dans la durée quand on est aidant", "Santé",
     "Vous accompagnez un proche malade, âgé ou en situation de handicap.",
     "Le modèle de conservation des ressources décrit ce qui se produit : une <strong>spirale de pertes</strong> (temps, sommeil, revenus, vie sociale) dont il devient de plus en plus difficile de sortir. Les aidants présentent un risque accru de dépression, de troubles du sommeil et de problèmes somatiques.",
     ["Acceptez une aide concrète dès le début, avant l'épuisement.",
      "Renseignez-vous sur les dispositifs existants : répit, accueil de jour, aides financières.",
      "Protégez au moins un créneau hebdomadaire entièrement à vous, non négociable.",
      "Rejoignez un groupe d'aidants : l'isolement est le principal facteur aggravant.",
      "Surveillez vos propres signaux (sommeil, irritabilité, renoncement aux soins) comme vous surveillez ceux du proche."],
     "Attendre d'être à bout pour demander de l'aide. Le sentiment de culpabilité (« c'est à moi de le faire ») est le principal obstacle, et il n'aide ni l'aidant ni la personne aidée."),

    ("douleur-chronique", "Vivre avec une douleur persistante", "Santé",
     "Une douleur installée depuis des mois, sans solution médicale simple.",
     "La théorie du portillon puis la neuromatrice ont établi que la douleur est <strong>produite</strong> par le cerveau, modulée par l'attention, l'émotion et l'attente — ce qui ne la rend ni imaginaire ni moins réelle. L'éducation à la neurophysiologie de la douleur réduit mesurablement l'incapacité.",
     ["Comprendre le mécanisme : douleur ne signifie pas nécessairement lésion en cours.",
      "Reprendre l'activité progressivement selon un quota horaire, pas selon la douleur du jour.",
      "Éviter le cycle suractivité-effondrement en fractionnant les efforts.",
      "Travailler le sommeil : la privation abaisse directement le seuil douloureux.",
      "Se faire accompagner : TCC, hypnose et ACT ont des données d'efficacité sur l'incapacité et la qualité de vie."],
     "Le repos complet prolongé. Sauf phase aiguë, il aggrave le déconditionnement, la peur du mouvement et finalement la douleur elle-même."),

    ("activite-physique", "Utiliser l'activité physique comme levier", "Santé",
     "Vous avez entendu que le sport aide le moral, sans savoir ce qui est vrai.",
     "Les méta-analyses montrent un effet réel de l'exercice sur les symptômes dépressifs et anxieux, d'une ampleur comparable à d'autres interventions de première intention pour les formes légères à modérées. Les essais souffrent toutefois de limites méthodologiques (impossible d'être en aveugle), et l'effet est <strong>plus net en prévention</strong> qu'en traitement des formes sévères.",
     ["Visez la régularité avant l'intensité : trois séances courtes valent mieux qu'une longue.",
      "Choisissez une activité que vous n'avez pas à vous forcer à aimer.",
      "Ancrez-la dans un horaire fixe et un contexte social si possible.",
      "Comptez les sorties, pas les performances, les premières semaines.",
      "Marcher dehors cumule exercice, lumière et souvent lien social."],
     "En faire une injonction supplémentaire auprès de personnes déjà en difficulté. « Fais du sport » adressé à quelqu'un de gravement déprimé revient à lui demander d'utiliser la capacité que la maladie a précisément détruite."),

    ("addiction-reduire", "Réduire une consommation problématique", "Santé",
     "Alcool, tabac, cannabis, jeux, écrans : l'usage a pris trop de place.",
     "Le modèle transthéorique rappelle que le changement passe par des stades et que la <strong>rechute fait partie du processus</strong>, pas de l'échec. L'entretien motivationnel obtient de meilleurs résultats que la confrontation, qui augmente la résistance.",
     ["Mesurez d'abord sans rien changer, pendant une semaine, honnêtement.",
      "Listez vous-même les avantages et inconvénients : la balance doit venir de vous.",
      "Identifiez les déclencheurs (lieu, heure, personne, émotion) et modifiez l'environnement.",
      "Fixez un objectif précis et daté, en réduction ou en arrêt selon la substance.",
      "Préparez la rechute à l'avance : que ferez-vous le lendemain d'un écart ?"],
     "Attendre la « volonté ». Pour l'alcool et certaines substances, l'arrêt brutal sans accompagnement médical peut être dangereux : un sevrage se prépare avec un professionnel."),

    ("argent-decisions", "Décider avec son argent sans se piéger", "Décision",
     "Achats impulsifs, abonnements oubliés, épargne qui ne démarre jamais.",
     "L'aversion à la perte, la comptabilité mentale et le poids des <strong>options par défaut</strong> expliquent une grande part des comportements financiers. Le programme « Save More Tomorrow » de Thaler et Benartzi a fait exploser les taux d'épargne simplement en la rendant automatique et progressive.",
     ["Automatisez l'épargne le jour du salaire : ce qui n'est pas vu n'est pas dépensé.",
      "Instaurez un délai de 48 h pour tout achat non essentiel au-dessus d'un seuil.",
      "Passez en revue les prélèvements récurrents une fois par an.",
      "Comparez en coût annuel plutôt qu'en mensualité : « 9,99 € par mois » se lit 120 € par an.",
      "Ignorez ce que vous avez déjà dépensé dans une décision future."],
     "Compter sur la discipline mensuelle. Les systèmes automatiques battent la volonté sur la durée, parce qu'ils ne dépendent pas de votre état du moment."),

    ("solitude", "Rompre l'isolement social", "Relations",
     "Peu de contacts, l'impression que créer des liens est devenu difficile.",
     "La solitude subjective est associée à un risque accru de mortalité comparable à d'autres grands facteurs de risque (travaux de Holt-Lunstad). Le mécanisme identifié par John Cacioppo est un cercle vicieux : l'isolement met en <strong>hypervigilance sociale</strong>, on interprète les signaux neutres comme des rejets, on se retire davantage.",
     ["Visez la régularité plutôt que la nouveauté : les liens naissent de la répétition (activité hebdomadaire, même lieu).",
      "Privilégiez les contextes à but partagé (bénévolat, sport, chorale) plutôt que les rencontres pour rencontrer.",
      "Relancez les liens dormants : reprendre contact est beaucoup plus efficace que repartir de zéro.",
      "Testez vos interprétations : un message sans réponse a mille explications.",
      "Prenez l'initiative de proposer, en acceptant un taux de refus normal."],
     "Attendre d'aller mieux pour recréer du lien. La solitude prolongée dégrade elle-même la perception sociale : c'est en agissant, même à petite dose, que le cercle s'inverse."),

    ("changement-avis", "Faire changer un avis sans braquer", "Social",
     "Un proche soutient une idée que vous jugez fausse et dangereuse.",
     "L'argumentation frontale déclenche souvent un renforcement défensif. Les données soutiennent en revanche l'<strong>écoute profonde</strong> (<em>deep canvassing</em>) : des conversations non jugeantes centrées sur des expériences personnelles produisent des changements d'attitude durables, mesurés jusqu'à des mois plus tard.",
     ["Commencez par écouter réellement et faire préciser la position.",
      "Demandez à la personne d'expliquer le mécanisme en détail : l'illusion de profondeur explicative fait le travail.",
      "Partagez une expérience vécue plutôt qu'une statistique.",
      "Séparez la personne de l'idée : personne ne renonce à une opinion en même temps qu'à sa dignité.",
      "Laissez du temps : on ne change pas d'avis devant témoin, mais souvent plusieurs jours après."],
     "Le déluge de faits. Corriger une croyance identitaire par l'accumulation de preuves produit souvent l'effet inverse, surtout en public où le coût social de céder est maximal."),

    ("transition-vie", "Traverser une transition de vie", "Développement",
     "Déménagement, séparation, perte d'emploi, retraite, naissance.",
     "Toute transition combine une perte et une reconstruction, même quand elle est choisie. Les données sur l'<strong>adaptation hédonique</strong> montrent que le bien-être revient largement à son niveau antérieur après la plupart des événements — avec des exceptions notables : le chômage prolongé et le veuvage laissent des traces durables.",
     ["Nommez ce qui se termine, y compris dans une transition heureuse.",
      "Maintenez trois repères stables (sommeil, une activité, un lien) pendant que le reste bouge.",
      "Accordez-vous un délai avant les grandes décisions irréversibles.",
      "Cherchez les autres qui ont vécu la même transition : le récit d'autrui restructure le vôtre.",
      "Anticipez le creux du milieu : l'énergie du départ retombe avant que le nouveau cadre ne tienne."],
     "Exiger de soi une adaptation rapide. La plupart des transitions demandent plusieurs mois, et se comparer à quelqu'un qui « a rebondi tout de suite » n'a aucun sens statistique."),

    ("vieillir-cognition", "Entretenir ses capacités en vieillissant", "Vieillissement",
     "Trous de mémoire, peur du déclin, offres de « gym cérébrale ».",
     "L'intelligence fluide décline progressivement, l'intelligence cristallisée se maintient longtemps. Les programmes commerciaux d'entraînement cérébral améliorent surtout… les tâches entraînées, avec un <strong>transfert très limité</strong> au quotidien. Ce qui dispose des meilleures données : activité physique, contrôle des facteurs de risque vasculaires, engagement social, correction auditive.",
     ["Bougez régulièrement : c'est l'intervention la mieux soutenue sur la cognition du grand âge.",
      "Surveillez tension, diabète, cholestérol, tabac : le cerveau vieillit avec les vaisseaux.",
      "Faites corriger une perte auditive : elle est l'un des facteurs de risque modifiables les plus importants.",
      "Maintenez des activités intellectuelles nouvelles et socialement engageantes.",
      "Consultez si les oublis gênent les gestes du quotidien, plutôt que de consulter des tests en ligne."],
     "Confondre oubli bénin et pathologie. Oublier un nom est banal à tout âge ; oublier comment on utilise un objet familier ou se perdre sur un trajet connu ne l'est pas et justifie un avis médical."),

    ("choisir-psy", "Choisir un psy et savoir si ça marche", "Thérapies",
     "Vous voulez consulter et vous ne savez pas vers qui vous tourner.",
     "En France, le titre de <strong>psychologue</strong> est protégé et suppose un master ; le <strong>psychiatre</strong> est médecin et peut prescrire ; le titre de <strong>psychothérapeute</strong> est réglementé depuis 2010. « Psychanalyste » et « coach » ne sont protégés par aucun cadre légal. Le meilleur prédicteur de résultat est la qualité de l'alliance, mesurable dès les premières séances.",
     ["Vérifiez le titre et l'inscription au registre ADELI ou à l'Ordre selon la profession.",
      "Demandez dès le premier contact : quelle approche, quelle durée envisagée, quels objectifs ?",
      "Évaluez après trois à quatre séances : vous sentez-vous compris et respecté ?",
      "Renseignez-vous sur les dispositifs remboursés (Mon soutien psy, centres médico-psychologiques).",
      "Il est légitime de changer de praticien : ce n'est ni un échec ni une trahison."],
     "Rester des années sans évaluer. Une thérapie doit produire des changements perceptibles ; en l'absence totale de mouvement après plusieurs mois, le sujet mérite d'être posé explicitement, avec le praticien."),

    ("attention-concentration", "Récupérer sa capacité de concentration", "Cognition",
     "Impossible de rester quinze minutes sur une tâche sans vérifier son téléphone.",
     "Le coût des interruptions est largement sous-estimé : après une interruption, le retour à la tâche initiale prend plusieurs minutes, et la simple <strong>présence visible</strong> d'un smartphone réduit les ressources attentionnelles disponibles, même éteint. Le « multitâche » cognitif n'existe pas : c'est une alternance coûteuse.",
     ["Sortez le téléphone de la pièce, pas seulement de la table.",
      "Travaillez par blocs de 25 à 50 minutes avec un objectif écrit avant de commencer.",
      "Regroupez les vérifications de messagerie en deux ou trois créneaux fixes.",
      "Notez les distractions qui surgissent sur un papier au lieu d'y céder.",
      "Prenez de vraies pauses sans écran : le réseau du mode par défaut a besoin de temps mort."],
     "Croire qu'on peut s'habituer aux interruptions. On s'habitue à l'inconfort de l'interruption, pas à son coût cognitif, qui reste entier."),

    ("creativite", "Débloquer sa créativité", "Cognition",
     "Vous tournez en rond sur un problème depuis des jours.",
     "L'incubation — mettre le problème de côté — améliore la résolution dans les méta-analyses, particulièrement pour les problèmes créatifs. Le mécanisme probable est l'affaiblissement des fausses pistes dominantes. La <strong>fixation fonctionnelle</strong> (Duncker) explique pourquoi on ne voit pas les usages alternatifs d'un objet familier.",
     ["Chargez le problème à fond, puis interrompez volontairement : marche, douche, sommeil.",
      "Changez la formulation du problème : reformuler est souvent plus productif que chercher davantage.",
      "Générez délibérément de mauvaises idées : cela casse la fixation.",
      "Exposez-vous à des domaines éloignés : la plupart des idées neuves sont des analogies importées.",
      "Notez immédiatement : les idées d'incubation s'évaporent en quelques minutes."],
     "Le brainstorming collectif spontané. Les groupes produisent moins d'idées que les mêmes personnes travaillant d'abord seules : il faut écrire individuellement, puis mettre en commun."),
]
