# -*- coding: utf-8 -*-
"""Les grandes controverses de la psychologie, présentées de façon contradictoire.

Chaque dossier expose la question, les deux positions dans leur meilleure version,
puis l'état actuel des connaissances — sans faire semblant qu'il existe toujours
une réponse tranchée.
"""

# (id, titre, famille, question, pos_a_titre, pos_a, pos_b_titre, pos_b, etat)
DEBATS = [
    ("inne-acquis", "Inné ou acquis ?", "Fondements",
     "Nos aptitudes et nos traits viennent-ils de nos gènes ou de notre environnement ?",
     "La part héréditaire est massive",
     "Les études de jumeaux et d'adoption convergent : l'héritabilité de l'intelligence mesurée est estimée entre 50 et 70 % à l'âge adulte, celle des grands traits de personnalité autour de 40 à 50 %. Des jumeaux séparés à la naissance se ressemblent bien plus que des frères adoptifs élevés ensemble. Nier cette composante par crainte de ses usages politiques revient à renoncer à comprendre.",
     "L'environnement façonne tout, y compris l'expression des gènes",
     "L'héritabilité est une statistique de population dans un environnement donné, jamais une propriété d'un individu. Là où les conditions de vie sont très inégales, l'héritabilité du QI s'effondre : les gènes ne s'expriment que si l'environnement le permet. L'effet Flynn — un gain de près de trois points de QI par décennie pendant le XXe siècle — ne peut être génétique : les gènes n'évoluent pas en trente ans.",
     "La question est aujourd'hui considérée comme mal posée. Rien n'est « purement » inné ou acquis : les gènes fixent des sensibilités à l'environnement, et l'environnement modifie l'expression des gènes (épigénétique). Une formulation plus productive : <em>quels</em> environnements permettent à <em>quelles</em> dispositions de se développer, et comment agir dessus ?"),

    ("qi-intelligence", "Le QI mesure-t-il l'intelligence ?", "Intelligence",
     "Un score chiffré peut-il rendre compte de l'intelligence humaine ?",
     "C'est la mesure la mieux validée de la psychologie",
     "Le QI prédit, mieux que n'importe quel autre indicateur psychologique, la réussite scolaire, la performance professionnelle moyenne et même certains indicateurs de santé. Le facteur g — la corrélation positive entre toutes les épreuves cognitives — est l'un des résultats les plus robustes et les plus répliqués de la discipline, depuis Spearman en 1904.",
     "Il mesure une compétence culturellement située, pas une essence",
     "Les tests évaluent surtout des aptitudes valorisées par l'école occidentale. Ils ignorent la créativité, la compétence sociale, la sagesse pratique, la persévérance. Le QI dépend fortement de la scolarisation, de la nutrition et du milieu ; l'effet Flynn montre qu'il bouge avec la société. Historiquement, ces tests ont servi à justifier des politiques eugénistes et discriminatoires.",
     "Les deux positions sont largement compatibles : le QI est une mesure valide et utile d'un ensemble restreint d'aptitudes cognitives, et non la mesure de la valeur ou du potentiel d'une personne. La communauté scientifique s'accorde sur sa valeur prédictive au niveau des groupes et sur sa prudence d'usage au niveau individuel."),

    ("psychanalyse-science", "La psychanalyse est-elle une science ?", "Épistémologie",
     "Peut-on ranger la théorie freudienne parmi les savoirs scientifiques ?",
     "Non, et c'est un problème",
     "Karl Popper en fait son contre-exemple canonique : une théorie qui explique aussi bien un comportement que son contraire n'est pas falsifiable. Les concepts centraux (refoulement, pulsion de mort) n'ont pas reçu de confirmation expérimentale. Les études d'efficacité des psychothérapies placent régulièrement les approches structurées devant la cure classique pour la plupart des troubles ciblés.",
     "Elle relève d'une autre forme de savoir",
     "La psychanalyse a introduit des idées devenues massivement consensuelles : l'existence de processus mentaux non conscients, l'importance des expériences précoces, la valeur du transfert dans toute relation d'aide, l'idée que le symptôme peut avoir un sens. Sa méthode est celle de l'étude de cas approfondie, comme en anthropologie ou en histoire — un autre régime de preuve, pas une absence de rigueur.",
     "Le consensus académique international considère la psychanalyse comme une tradition herméneutique et clinique, non comme une science expérimentale. Sa place dans l'enseignement de la psychologie a fortement reculé dans le monde anglophone, tandis qu'elle reste plus présente en France. Les psychothérapies psychodynamiques brèves, elles, disposent de données d'efficacité réelles sur plusieurs indications."),

    ("efficacite-therapies", "Toutes les psychothérapies se valent-elles ?", "Clinique",
     "L'approche choisie change-t-elle réellement le résultat ?",
     "Oui : certaines techniques sont supérieures pour certains troubles",
     "Pour les troubles anxieux, les TOC, les phobies spécifiques ou le stress post-traumatique, l'exposition graduée et les protocoles cognitivo-comportementaux obtiennent des résultats nettement supérieurs aux approches non structurées, avec des tailles d'effet importantes et répliquées. Il serait absurde de proposer autre chose en première intention.",
     "Non : ce sont les facteurs communs qui font l'essentiel",
     "Le « verdict de l'oiseau Dodo » désigne le constat que les approches bien conduites obtiennent des résultats comparables sur les troubles courants. L'alliance thérapeutique, les attentes du patient et la compétence du praticien expliquent une part de la variance supérieure à celle attribuable à la technique elle-même. La variabilité entre thérapeutes d'une même école dépasse souvent la variabilité entre écoles.",
     "Synthèse actuelle : les facteurs communs constituent le socle indispensable, et des techniques spécifiques ajoutent un gain réel sur des indications précises. Autrement dit, ni « tout se vaut », ni « seule ma méthode fonctionne ». Le meilleur prédicteur pratique reste la qualité du lien et la mesure régulière des progrès."),

    ("ecrans-jeunes", "Les écrans nuisent-ils à la santé mentale des jeunes ?", "Numérique",
     "L'augmentation des troubles anxio-dépressifs chez les adolescents est-elle causée par les réseaux sociaux ?",
     "Oui, le calendrier et les mécanismes concordent",
     "La dégradation de la santé mentale adolescente commence autour de 2012, au moment de la généralisation du smartphone et des réseaux sociaux, dans plusieurs pays simultanément, et touche davantage les filles. Les mécanismes plausibles ne manquent pas : comparaison sociale permanente, cyberharcèlement, privation de sommeil, réduction des interactions en face à face.",
     "Non, les effets mesurés sont minuscules",
     "Les analyses sur de très grands ensembles de données trouvent des associations de l'ordre de r = 0,04 — comparables à l'effet de manger des pommes de terre. La corrélation peut s'expliquer en sens inverse : les adolescents qui vont mal utilisent davantage leur téléphone. L'histoire des paniques morales (roman, radio, bande dessinée, télévision, jeu vidéo) invite à la prudence.",
     "Le débat est actif et non tranché. Les points d'accord : l'effet moyen est faible, mais il est probablement bien plus fort pour certains usages (réseaux à comparaison sociale intense, usage nocturne) et certains profils vulnérables. Les données expérimentales et longitudinales manquent encore, et les chercheurs n'ont pas accès aux données des plateformes."),

    ("jeux-violents", "Les jeux vidéo violents rendent-ils agressifs ?", "Numérique",
     "Jouer à des jeux violents augmente-t-il l'agressivité réelle ?",
     "Oui, à court terme et de façon mesurable",
     "Des dizaines d'expériences montrent une augmentation des pensées et affects hostiles et des comportements agressifs en laboratoire immédiatement après le jeu. Le modèle général de l'agression explique ce résultat par l'amorçage de schémas hostiles et la désensibilisation progressive.",
     "Non, et les mesures de laboratoire ne valent rien",
     "L'agressivité est mesurée par des procédés douteux (volume de bruit infligé, dose de sauce piquante attribuée) dont le lien avec la violence réelle n'est pas établi. À l'échelle des populations, la diffusion massive des jeux vidéo s'est accompagnée d'une <em>baisse</em> de la criminalité violente juvénile. Les méta-analyses corrigées du biais de publication font largement fondre l'effet.",
     "La controverse a été vive et parfois âpre entre équipes. La position majoritaire aujourd'hui : effet à court terme réel mais faible sur des mesures de laboratoire, absence de preuve d'un effet sur la violence grave. Plusieurs sociétés savantes ont révisé leurs communiqués pour distinguer « agressivité » et « violence »."),

    ("difference-sexes", "Existe-t-il des différences cognitives entre les sexes ?", "Différences individuelles",
     "Les différences observées sont-elles biologiques, sociales, ou artefactuelles ?",
     "Des différences existent et sont documentées",
     "On observe de façon répliquée un avantage masculin moyen en rotation mentale d'objets en trois dimensions et un avantage féminin moyen en fluence verbale et en reconnaissance des émotions. Les écarts de variance sont également documentés. Ignorer ces données au nom d'un idéal égalitaire n'est pas une position scientifique.",
     "Les écarts sont faibles, mobiles et largement construits",
     "La quasi-totalité de ces différences correspond à des tailles d'effet petites, avec des distributions qui se recouvrent à plus de 85 % : connaître le sexe d'une personne ne permet pratiquement pas de prédire sa performance. Surtout, les écarts varient énormément selon les pays et se réduisent avec l'égalité de genre. La menace du stéréotype suffit à les créer ou à les effacer en laboratoire.",
     "L'hypothèse des « similarités de genre » de Janet Hyde résume bien l'état des données : sur la grande majorité des variables psychologiques, hommes et femmes se ressemblent davantage qu'ils ne diffèrent. Les écarts réels sont réels, petits, et jamais un motif valable de décision individuelle."),

    ("libre-arbitre", "Le libre arbitre existe-t-il ?", "Fondements",
     "Nos décisions sont-elles réellement libres ou entièrement déterminées ?",
     "Les données neuroscientifiques pointent vers le déterminisme",
     "Les expériences de Benjamin Libet montrent un potentiel de préparation cérébral quelques centaines de millisecondes avant que la personne rapporte avoir décidé. Des travaux ultérieurs en IRM prédisent certains choix binaires plusieurs secondes à l'avance. L'hémisphère gauche fabrique après coup des justifications à des actes qu'il n'a pas initiés.",
     "Ces expériences ne portent pas sur ce qui nous importe",
     "Bouger un doigt à un moment arbitraire n'a rien à voir avec choisir un métier, rompre une relation ou résister à une tentation. La méthode de datation de l'intention consciente est elle-même contestée, et des réanalyses interprètent le potentiel de préparation comme du bruit neuronal fluctuant. Le compatibilisme philosophique définit la liberté comme agir selon ses propres raisons, ce qu'aucune donnée n'infirme.",
     "Question philosophique que la psychologie éclaire sans la trancher. Un résultat plus directement utile : croire au libre arbitre influence les comportements. Induire expérimentalement une croyance déterministe augmente légèrement la tricherie et diminue la persévérance — un effet lui-même à confirmer à grande échelle."),

    ("diagnostic-psychiatrique", "Les diagnostics psychiatriques sont-ils valides ?", "Clinique",
     "Les catégories du DSM découpent-elles des entités réelles ?",
     "Ce sont des conventions utiles mais artificielles",
     "Les frontières entre catégories sont poreuses, la comorbidité est la règle, deux personnes peuvent recevoir le même diagnostic sans partager un seul symptôme, et aucun marqueur biologique ne valide une catégorie. L'élargissement des critères successifs a multiplié les diagnostics sans que la santé mentale des populations s'améliore.",
     "Sans catégories, il n'y a ni recherche, ni soin, ni droits",
     "Un langage commun permet de communiquer entre professionnels, d'accumuler des connaissances, de comparer des traitements, d'ouvrir des droits et des remboursements. Les critères opérationnels du DSM-III ont massivement amélioré la fiabilité inter-juges, qui était catastrophique auparavant. Un diagnostic imparfait vaut mieux qu'un jugement clinique purement intuitif.",
     "La recherche s'oriente vers des approches dimensionnelles (modèle HiTOP, cadre RDoC) qui décrivent des continuums plutôt que des boîtes. En pratique clinique, les catégories restent l'outil de travail, avec une conscience accrue de leur statut d'outil — et non de description de la nature."),

    ("medicaments-antidepresseurs", "Les antidépresseurs sont-ils efficaces ?", "Clinique",
     "Leur bénéfice dépasse-t-il celui du placebo ?",
     "L'effet réel est modeste et concentré sur les formes sévères",
     "Les analyses incluant les essais non publiés montrent un écart avec le placebo faible en moyenne, en deçà du seuil de pertinence clinique pour les dépressions légères à modérées. Une part importante de l'amélioration observée relève du placebo, de l'évolution spontanée et de la régression vers la moyenne.",
     "Ils sont efficaces, et le doute public coûte des vies",
     "La plus vaste méta-analyse en réseau, portant sur 522 essais et plus de 116 000 participants, conclut que tous les antidépresseurs étudiés font mieux que le placebo dans la dépression caractérisée de l'adulte. Dans les formes sévères, le bénéfice est net. Décourager un traitement chez une personne gravement déprimée n'est pas une position neutre.",
     "Consensus opérationnel : bénéfice modeste mais réel, croissant avec la sévérité ; en première intention, la psychothérapie est recommandée pour les formes légères, et l'association médicament + psychothérapie donne les meilleurs résultats sur les formes sévères. Le sujet reste politiquement et commercialement chargé, ce qui pollue le débat scientifique."),

    ("neurosciences-reduction", "Les neurosciences vont-elles absorber la psychologie ?", "Épistémologie",
     "Expliquer le cerveau suffira-t-il à expliquer le comportement ?",
     "À terme, oui : tout état mental est un état cérébral",
     "L'imagerie, l'optogénétique et la modélisation progressent à une vitesse considérable. Les concepts psychologiques flous sont progressivement remplacés par des mécanismes identifiés. Une science mature réduit ses niveaux d'explication supérieurs, comme la chimie s'est adossée à la physique.",
     "Non : le niveau psychologique est irréductible",
     "Connaître les transistors n'explique pas un traitement de texte. Un même comportement peut reposer sur des substrats différents, et une même activation cérébrale accompagner des états mentaux différents — c'est le problème de l'inférence inverse. Les phénomènes sociaux, culturels et développementaux ne se lisent pas dans un voxel.",
     "La position dominante est un « non-réductionnisme pragmatique » : les niveaux d'analyse se contraignent mutuellement sans se remplacer. La « neuromanie » des années 2000 — une image cérébrale rendant n'importe quelle explication plus crédible aux yeux du public — a d'ailleurs été documentée expérimentalement comme un biais."),

    ("amorcage-social", "L'amorçage social existe-t-il vraiment ?", "Méthodologie",
     "Des indices subtils peuvent-ils modifier nos comportements complexes à notre insu ?",
     "Des dizaines d'études l'ont montré",
     "Les travaux fondateurs rapportaient que lire des mots associés à la vieillesse ralentit la marche, que tenir une boisson chaude rend plus chaleureux dans son jugement d'autrui, que voir un drapeau modifie les intentions de vote. Le cadre théorique est cohérent avec ce qu'on sait de l'activation associative en mémoire.",
     "Ces effets ne se répliquent pas",
     "Les réplications directes, à grands échantillons et en double aveugle, échouent régulièrement à retrouver ces résultats. Les études d'origine portaient souvent sur trente participants, avec des degrés de liberté considérables dans l'analyse. Daniel Kahneman lui-même a adressé une lettre publique appelant le domaine à mettre de l'ordre.",
     "C'est le champ le plus durement touché par la crise de la réplication. L'amorçage sémantique classique (reconnaître plus vite « infirmière » après « médecin ») reste solide ; l'amorçage comportemental à distance est aujourd'hui considéré comme non établi. Un cas d'école de la différence entre un effet réel et un effet publié."),

    ("autisme-spectre", "Faut-il parler d'un déficit ou d'une différence ?", "Neurodéveloppement",
     "Comment décrire l'autisme sans le réduire ni le nier ?",
     "Le modèle médical décrit un trouble avec des besoins de soin",
     "L'autisme s'accompagne fréquemment de difficultés majeures : absence de langage chez une partie des personnes, déficience intellectuelle associée, troubles sensoriels invalidants, comorbidités psychiatriques et espérance de vie réduite. Nier la dimension de handicap prive les personnes les plus affectées d'accompagnement et de droits.",
     "Le modèle de la neurodiversité décrit une variation humaine",
     "Beaucoup de difficultés attribuées à la personne relèvent d'un environnement inadapté (bruit, lumière, normes sociales implicites, injonction au contact visuel). La théorie de la « double empathie » montre que l'incompréhension est réciproque : les personnes autistes se comprennent très bien entre elles. Les interventions visant à faire « paraître normal » sont associées à une détresse accrue et à l'épuisement du masquage.",
     "Les deux lectures coexistent et le débat est porté en grande partie par les personnes concernées elles-mêmes. Une position de synthèse répandue : reconnaître le handicap et les besoins de soutien, tout en visant l'adaptation de l'environnement plutôt que la normalisation de la personne."),

    ("hypnose", "L'hypnose est-elle un état de conscience particulier ?", "États de conscience",
     "Existe-t-il un « état hypnotique » distinct de l'éveil ordinaire ?",
     "Oui, un état dissociatif identifiable",
     "Des modifications de connectivité cérébrale sont observées en imagerie chez les personnes hautement suggestibles. L'analgésie hypnotique est suffisamment robuste pour permettre des interventions chirurgicales avec une sédation réduite, et son efficacité sur la douleur procédurale est documentée par des essais contrôlés.",
     "Non, c'est une réponse sociale à des attentes",
     "Les théories socio-cognitives expliquent les phénomènes hypnotiques par la suggestion, l'imagination active, l'adhésion au rôle et les attentes — sans postuler d'état spécial. Des participants non hypnotisés à qui l'on demande simplement de se comporter comme s'ils l'étaient produisent des résultats souvent indiscernables.",
     "Le débat sur la nature de l'hypnose n'est pas clos, mais son utilité clinique est largement admise : douleur aiguë et chronique, syndrome de l'intestin irritable, anxiété préopératoire. En revanche, son usage pour « retrouver des souvenirs » est fermement déconseillé, car elle augmente la confiance dans le souvenir sans en augmenter l'exactitude."),

    ("souvenirs-retrouves", "Peut-on retrouver des souvenirs refoulés ?", "Mémoire",
     "Les souvenirs traumatiques oubliés puis remémorés en thérapie sont-ils fiables ?",
     "Le refoulement existe et les victimes doivent être crues",
     "Des cas documentés de personnes ayant perdu puis recouvré le souvenir d'abus réels existent. Douter systématiquement de ces récits revient à ajouter une injustice à une violence déjà subie, dans un domaine où la parole des victimes a été historiquement disqualifiée.",
     "La mémoire est reconstructive et hautement suggestible",
     "Les travaux d'Elizabeth Loftus ont montré qu'il est possible d'implanter des souvenirs détaillés et émotionnellement intenses d'événements jamais survenus, chez une proportion non négligeable de participants. Les techniques dites de récupération (hypnose, imagerie guidée, interprétation de rêves) sont précisément celles qui produisent ces faux souvenirs en laboratoire.",
     "La « guerre des souvenirs » des années 1990 a laissé un consensus prudent : les souvenirs recouvrés spontanément et hors contexte suggestif sont plus fiables que ceux émergeant après des techniques de récupération. Les sociétés savantes déconseillent ces techniques. Surtout : la véracité d'un souvenir ne peut jamais s'établir sur le seul sentiment de certitude de la personne, aussi sincère soit-il."),

    ("bonheur-argent", "L'argent fait-il le bonheur ?", "Bien-être",
     "Le revenu influence-t-il durablement la satisfaction de vie ?",
     "Au-delà d'un seuil, non",
     "Les travaux de Kahneman et Deaton avaient identifié un plafonnement du bien-être émotionnel quotidien autour d'un revenu confortable. L'adaptation hédonique fait que les gains de revenu produisent une satisfaction qui s'érode. Le paradoxe d'Easterlin observe que les pays se sont enrichis sans que le bonheur déclaré suive.",
     "Oui, et l'effet ne plafonne pas",
     "Les données de Matthew Killingsworth, recueillies en temps réel sur des dizaines de milliers de personnes, ne trouvent pas de plateau : le bien-être continue de croître avec le revenu, de façon logarithmique. Une analyse conjointe des deux équipes a conclu que le plateau ne concernait qu'une minorité malheureuse pour d'autres raisons.",
     "Consensus adverse résolu par collaboration — un bel exemple de « désaccord adversarial » productif. La relation est logarithmique : doubler son revenu produit un gain à peu près constant, ce qui signifie qu'un même euro compte infiniment plus pour une personne pauvre. Comparaison sociale et sécurité matérielle pèsent plus que le montant absolu."),

    ("crise-milieu-vie", "La crise du milieu de vie existe-t-elle ?", "Développement",
     "La quarantaine est-elle un moment de bouleversement inévitable ?",
     "Un creux réel se mesure",
     "Les grandes enquêtes internationales retrouvent régulièrement une courbe du bien-être en forme de U, avec un minimum entre 45 et 55 ans, observée dans des dizaines de pays et même, selon certains travaux, chez les grands singes. Le cumul des responsabilités professionnelles, parentales et filiales à cette période est objectivement maximal.",
     "C'est un artefact statistique et culturel",
     "La courbe en U disparaît dans plusieurs analyses lorsqu'on suit les mêmes personnes dans le temps plutôt que de comparer des générations différentes. Le terme de « crise » vient d'un article de 1965 sans données solides, et le scénario stéréotypé (voiture de sport, rupture) n'est vécu que par une petite minorité.",
     "Un léger fléchissement du bien-être en milieu de vie est probable, la « crise » spectaculaire est un mythe culturel. La plupart des transitions de cette période sont progressives, et une majorité de personnes déclarent une satisfaction qui remonte ensuite jusqu'à un âge avancé."),

    ("evolution-psy", "La psychologie évolutionniste explique-t-elle nos comportements ?", "Épistémologie",
     "Peut-on remonter d'un comportement actuel à une pression de sélection ancestrale ?",
     "Oui : l'esprit a une histoire naturelle",
     "L'anatomie est façonnée par l'évolution ; il serait étrange que le cerveau y échappe. Certaines prédictions se vérifient : peurs préparées pour les serpents et les hauteurs plutôt que pour les prises électriques, préférences alimentaires, réponses de dégoût face aux signaux de contamination, investissement parental différencié.",
     "Non : ce sont des récits rétrospectifs invérifiables",
     "La critique des « spandrels » de Gould et Lewontin rappelle que tout trait n'est pas une adaptation : certains sont des sous-produits. Comme les comportements ne fossilisent pas, on ne peut pas tester l'histoire proposée. Le risque est de naturaliser des arrangements sociaux contemporains en les projetant sur la préhistoire.",
     "Le champ a gagné en rigueur : prédictions préenregistrées, comparaisons interculturelles, modélisation. Les hypothèses testables et effectivement testées sont prises au sérieux ; les explications post hoc d'un comportement contemporain particulier restent largement considérées comme de la spéculation."),

    ("hypothese-serotonine", "La dépression est-elle un déséquilibre chimique ?", "Clinique",
     "L'explication par le manque de sérotonine tient-elle ?",
     "Cette explication n'est pas soutenue",
     "Une revue-parapluie publiée en 2022 conclut qu'il n'existe pas de preuve convaincante d'un lien entre concentration de sérotonine et dépression. L'hypothèse est née d'un raisonnement à rebours : les médicaments agissant sur la sérotonine soulagent, donc la dépression viendrait de la sérotonine — comme si le mal de tête venait d'un manque de paracétamol.",
     "Abandonner ce discours a un coût",
     "Le modèle biologique a contribué à déstigmatiser la dépression en la sortant du registre moral (« fais un effort »). Le fait que le mécanisme précis soit inconnu n'implique pas qu'il n'existe aucune base biologique : héritabilité, altérations neuro-inflammatoires et modifications de la plasticité hippocampique sont documentées.",
     "La formule « déséquilibre chimique » est aujourd'hui considérée comme une simplification abusive, y compris par beaucoup de psychiatres qui l'utilisaient en consultation. Le modèle dominant est vulnérabilité-stress, multifactoriel. Point important : cela ne signifie pas que les traitements ne fonctionnent pas — un médicament peut être efficace sans que son mécanisme soit compris."),

    ("intervention-precoce", "Faut-il dépister largement en santé mentale ?", "Santé publique",
     "Le dépistage systématique améliore-t-il la santé mentale des populations ?",
     "Oui, repérer tôt évite la chronicisation",
     "Plus une difficulté est prise en charge tôt, meilleur est le pronostic — c'est établi pour la psychose débutante, les troubles des apprentissages et la dépression du post-partum. Le dépistage réduit aussi les inégalités d'accès : sans lui, seuls les mieux informés consultent.",
     "Attention à la médicalisation du mal-être ordinaire",
     "Un dépistage de masse dans une population où la prévalence est faible produit surtout des faux positifs, avec leur cortège d'étiquetage, d'anxiété et de traitements inutiles. Les programmes scolaires de « pleine conscience » à grande échelle n'ont pas démontré de bénéfice, et certains ont même produit des effets négatifs chez les adolescents les plus vulnérables.",
     "Le compromis actuel privilégie le dépistage ciblé sur les populations à risque plutôt qu'universel, associé à une offre de soin réellement disponible — dépister sans pouvoir orienter ne fait qu'ajouter de l'inquiétude. La question de fond reste politique : agir sur les conditions de vie ou sur les individus ?"),
]
